<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Variable Selection | Applied Regression with R</title>
  <meta name="description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Variable Selection | Applied Regression with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Variable Selection | Applied Regression with R" />
  
  <meta name="twitter:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

<meta name="author" content="Darrin Speegle" />


<meta name="date" content="2022-01-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
<link rel="prev" href="regression-predictive-models.html"/>
<link rel="next" href="non-linear-regression-models.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Regression With R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="classicaltheory.html"><a href="classicaltheory.html"><i class="fa fa-check"></i><b>2</b> Classical Theory of Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="classicaltheory.html"><a href="classicaltheory.html#review"><i class="fa fa-check"></i><b>2.1</b> Review</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-means-and-standard-deviations"><i class="fa fa-check"></i><b>2.1.1</b> Estimating Means and standard deviations</a></li>
<li class="chapter" data-level="2.1.2" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-the-density-of-an-rv"><i class="fa fa-check"></i><b>2.1.2</b> Estimating the density of an rv</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-overview"><i class="fa fa-check"></i><b>2.2</b> Linear Regression Overview</a></li>
<li class="chapter" data-level="2.3" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-with-no-intercept"><i class="fa fa-check"></i><b>2.3</b> Linear Regression with no intercept</a></li>
<li class="chapter" data-level="2.4" data-path="classicaltheory.html"><a href="classicaltheory.html#the-full-model"><i class="fa fa-check"></i><b>2.4</b> The full model</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="classicaltheory.html"><a href="classicaltheory.html#hypothesis-test-interlude"><i class="fa fa-check"></i><b>2.4.1</b> Hypothesis Test Interlude</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="classicaltheory.html"><a href="classicaltheory.html#using-different-loss-functions"><i class="fa fa-check"></i><b>2.5</b> Using different loss functions</a></li>
<li class="chapter" data-level="" data-path="classicaltheory.html"><a href="classicaltheory.html#vignette-a-dplyr-primer"><i class="fa fa-check"></i>Vignette: A dplyr primer</a></li>
<li class="chapter" data-level="2.6" data-path="classicaltheory.html"><a href="classicaltheory.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#anova"><i class="fa fa-check"></i><b>3.0.1</b> Aside on multiple R squared and ANOVA</a></li>
<li class="chapter" data-level="3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-variable-selection-anova"><i class="fa fa-check"></i><b>3.1</b> More Variable Selection: ANOVA</a></li>
<li class="chapter" data-level="3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#predictions"><i class="fa fa-check"></i><b>3.2</b> Predictions</a></li>
<li class="chapter" data-level="3.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercises-1"><i class="fa fa-check"></i><b>3.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html"><i class="fa fa-check"></i><b>4</b> Intro to Predictive Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#comparing-two-models"><i class="fa fa-check"></i><b>4.1</b> Comparing Two Models</a></li>
<li class="chapter" data-level="4.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#simulations-of-expected-mse"><i class="fa fa-check"></i><b>4.2</b> Simulations of Expected MSE</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-and-bias-variance-tradeoff"><i class="fa fa-check"></i><b>4.2.1</b> Estimating MSE and Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="4.2.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-for-new-predictors-uniformly-sampled"><i class="fa fa-check"></i><b>4.2.2</b> Estimating MSE for new predictors uniformly sampled</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>4.3</b> Bias Variance Trade-off</a></li>
<li class="chapter" data-level="4.4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#exercises-2"><i class="fa fa-check"></i><b>4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html"><i class="fa fa-check"></i><b>5</b> Regression Predictive Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#preprocessing"><i class="fa fa-check"></i><b>5.1</b> Preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#missing-data"><i class="fa fa-check"></i><b>5.2</b> Missing Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#predicting-when-a-level-is-missing-from-the-training-set"><i class="fa fa-check"></i><b>5.2.1</b> Predicting when a level is missing from the training set</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#correlated-predictors"><i class="fa fa-check"></i><b>5.3</b> Correlated Predictors</a></li>
<li class="chapter" data-level="5.4" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#aside-on-pca"><i class="fa fa-check"></i><b>5.4</b> Aside on PCA</a></li>
<li class="chapter" data-level="5.5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#johnson-lindenstrauss-dimension-reduction"><i class="fa fa-check"></i><b>5.5</b> Johnson-Lindenstrauss Dimension Reduction</a></li>
<li class="chapter" data-level="5.6" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#exercises-3"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variable-selection.html"><a href="variable-selection.html"><i class="fa fa-check"></i><b>6</b> Variable Selection</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variable-selection.html"><a href="variable-selection.html#partial-least-squares"><i class="fa fa-check"></i><b>6.1</b> Partial Least Squares</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="variable-selection.html"><a href="variable-selection.html#optional-pls-stuff"><i class="fa fa-check"></i><b>6.1.1</b> Optional PLS Stuff</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variable-selection.html"><a href="variable-selection.html#ridgelasso-and-elastic-net"><i class="fa fa-check"></i><b>6.2</b> Ridge/Lasso and Elastic Net</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="variable-selection.html"><a href="variable-selection.html#ridge-regression"><i class="fa fa-check"></i><b>6.2.1</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.2.2" data-path="variable-selection.html"><a href="variable-selection.html#lasso"><i class="fa fa-check"></i><b>6.2.2</b> LASSO</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variable-selection.html"><a href="variable-selection.html#step-aic"><i class="fa fa-check"></i><b>6.3</b> Step AIC</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="variable-selection.html"><a href="variable-selection.html#doing-lgocv-with-preprocessing"><i class="fa fa-check"></i><b>6.3.1</b> Doing LGOCV with preprocessing</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variable-selection.html"><a href="variable-selection.html#interactions"><i class="fa fa-check"></i><b>6.4</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html"><i class="fa fa-check"></i><b>7</b> Non-Linear Regression Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#support-vector-regression"><i class="fa fa-check"></i><b>7.1</b> Support Vector Regression</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#plot-twist"><i class="fa fa-check"></i><b>7.1.1</b> PLOT TWIST</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>7.2</b> K Nearest Neighbors</a></li>
<li class="chapter" data-level="7.3" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#exercises-4"><i class="fa fa-check"></i><b>7.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tree-regression-models.html"><a href="tree-regression-models.html"><i class="fa fa-check"></i><b>8</b> Tree Regression Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="tree-regression-models.html"><a href="tree-regression-models.html#basic-regression-trees"><i class="fa fa-check"></i><b>8.1</b> Basic Regression Trees</a></li>
<li class="chapter" data-level="8.2" data-path="tree-regression-models.html"><a href="tree-regression-models.html#regression-model-trees"><i class="fa fa-check"></i><b>8.2</b> Regression Model Trees</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="tree-regression-models.html"><a href="tree-regression-models.html#choosing-variable-to-split"><i class="fa fa-check"></i><b>8.2.1</b> Choosing Variable to Split</a></li>
<li class="chapter" data-level="8.2.2" data-path="tree-regression-models.html"><a href="tree-regression-models.html#choosing-split-value"><i class="fa fa-check"></i><b>8.2.2</b> Choosing Split Value</a></li>
<li class="chapter" data-level="8.2.3" data-path="tree-regression-models.html"><a href="tree-regression-models.html#predicting-values-smoothing"><i class="fa fa-check"></i><b>8.2.3</b> Predicting values (Smoothing)</a></li>
<li class="chapter" data-level="8.2.4" data-path="tree-regression-models.html"><a href="tree-regression-models.html#using-r-functions"><i class="fa fa-check"></i><b>8.2.4</b> Using R functions</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="tree-regression-models.html"><a href="tree-regression-models.html#bagging"><i class="fa fa-check"></i><b>8.3</b> Bagging</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>9</b> Solutions</a>
<ul>
<li class="chapter" data-level="9.1" data-path="solutions.html"><a href="solutions.html#chapter-2-solutions"><i class="fa fa-check"></i><b>9.1</b> Chapter 2 Solutions</a></li>
<li class="chapter" data-level="9.2" data-path="solutions.html"><a href="solutions.html#chapter-3-solutions"><i class="fa fa-check"></i><b>9.2</b> Chapter 3 Solutions</a></li>
<li class="chapter" data-level="9.3" data-path="solutions.html"><a href="solutions.html#chapter-5"><i class="fa fa-check"></i><b>9.3</b> Chapter 5</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Regression with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="variable-selection" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Variable Selection</h1>
<p>We have already seen times when we have more predictors than optimal for predicting the response. We discussed an <em>ad hoc</em> method of variable selection using <span class="math inline">\(p\)</span>-values, which can be useful for explanatory model building. We also looked at projecting the predictors onto a smaller subspace using PCA, which works about as well as projecting randomly onto subspaces in many cases.</p>
<p>The issue with PCA regression is that the choice of directions of maximal variance may have nothing to do with the response. It **could* be that the predictive value of the predictors is in a direction that has small variance relative to other directions, in which case it would be hidden in one of the later components. For this reason, we will want to consider the relationship of the components in the predictors with the response. That is the idea behind partial least squares.</p>
<p>In the next section, we will consider ridge and lasso regression. These methods attempt to minimize an error function that also includes the magnitudes of the coefficients. The thought is that if a predictor doesn’t have much predictive power, then the penalty associated with the coefficient will force the coefficient to be zero, which is the same as eliminating it from the model.</p>
<p>Next, we will talk about the Akaike Information Criterion, which is a classical way of variable selection that also performs well in predictive models.</p>
<p>Finally, we will take a <strong>long</strong> overdue detour and talk about interactions. Interactions really belonged in the classical theory section, but are also useful for predictive modeling. We will discuss their use both in explanatory model building and predictive model building.</p>
<div id="partial-least-squares" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Partial Least Squares</h2>
<p>As mentioned above, partial least squares first finds the direction in the predictor space that has maximum covariance with the response. Let’s do that using simulations so that we can understand what is going on. Our data is also simulated data.</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="variable-selection.html#cb480-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2162020</span>)</span>
<span id="cb480-2"><a href="variable-selection.html#cb480-2" aria-hidden="true" tabindex="-1"></a>Sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(<span class="dv">9</span>), <span class="at">nrow =</span> <span class="dv">3</span>)</span>
<span id="cb480-3"><a href="variable-selection.html#cb480-3" aria-hidden="true" tabindex="-1"></a>Sigma <span class="ot">&lt;-</span> Sigma <span class="sc">%*%</span> <span class="fu">t</span>(Sigma)</span>
<span id="cb480-4"><a href="variable-selection.html#cb480-4" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="dv">500</span>, <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">Sigma =</span> Sigma))</span>
<span id="cb480-5"><a href="variable-selection.html#cb480-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dd) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;x&quot;</span>, <span class="st">&quot;y&quot;</span>, <span class="st">&quot;z&quot;</span>)</span>
<span id="cb480-6"><a href="variable-selection.html#cb480-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dd)</span></code></pre></div>
<pre><code>##            x          y          z
## x  1.0000000  0.3970130 -0.4702539
## y  0.3970130  1.0000000 -0.9928534
## z -0.4702539 -0.9928534  1.0000000</code></pre>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="variable-selection.html#cb482-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">mutate</span>(dd, <span class="at">response =</span> <span class="dv">2</span> <span class="sc">*</span> (x <span class="sc">+</span> <span class="dv">4</span> <span class="sc">*</span>y) <span class="sc">+</span> .<span class="dv">25</span> <span class="sc">*</span> (x <span class="sc">+</span> <span class="dv">6</span><span class="sc">*</span>y <span class="sc">+</span> z) <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">500</span>, <span class="dv">0</span>, <span class="dv">7</span>))</span>
<span id="cb482-2"><a href="variable-selection.html#cb482-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(response <span class="sc">~</span>., <span class="at">data =</span> dd))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = response ~ ., data = dd)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -20.1504  -4.6839  -0.2462   4.6686  19.8194 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -0.1148     0.3203  -0.358 0.720159    
## x             2.3100     0.6733   3.431 0.000652 ***
## y            12.5728     3.1097   4.043 6.11e-05 ***
## z             4.3116     3.9722   1.085 0.278256    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.147 on 496 degrees of freedom
## Multiple R-squared:  0.7119, Adjusted R-squared:  0.7101 
## F-statistic: 408.5 on 3 and 496 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We begin by centering and scaling the predictors.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="variable-selection.html#cb484-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> dd <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">x =</span> <span class="fu">scale</span>(x),</span>
<span id="cb484-2"><a href="variable-selection.html#cb484-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="fu">scale</span>(y),</span>
<span id="cb484-3"><a href="variable-selection.html#cb484-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">z =</span> <span class="fu">scale</span>(z))</span></code></pre></div>
<p>Next, as in the case of PCA, we randomly select values in the unit sphere of <span class="math inline">\(R^3\)</span>, and we compute the covariance of the projection of the data onto that direction with the response. We will keep track of the largest and that will be our rough estimate for the PLS component 1. We begin with some helper functions, which are the inner product of two vectors and the norm of a vector.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="variable-selection.html#cb485-1" aria-hidden="true" tabindex="-1"></a>ip <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y) {</span>
<span id="cb485-2"><a href="variable-selection.html#cb485-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(x <span class="sc">*</span> y)</span>
<span id="cb485-3"><a href="variable-selection.html#cb485-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb485-4"><a href="variable-selection.html#cb485-4" aria-hidden="true" tabindex="-1"></a>mynorm <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb485-5"><a href="variable-selection.html#cb485-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb485-6"><a href="variable-selection.html#cb485-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Next, we see how to take a random sample from the sphere, project the data onto that direction, and compute the covariance with the response.</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="variable-selection.html#cb486-1" aria-hidden="true" tabindex="-1"></a>rvec <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">3</span>)</span>
<span id="cb486-2"><a href="variable-selection.html#cb486-2" aria-hidden="true" tabindex="-1"></a>rvec <span class="ot">&lt;-</span> rvec<span class="sc">/</span><span class="fu">mynorm</span>(rvec)</span>
<span id="cb486-3"><a href="variable-selection.html#cb486-3" aria-hidden="true" tabindex="-1"></a>dd_p <span class="ot">&lt;-</span> <span class="fu">apply</span>(dd[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">ip</span>(x, rvec))</span>
<span id="cb486-4"><a href="variable-selection.html#cb486-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(dd_p, dd<span class="sc">$</span>response)</span></code></pre></div>
<pre><code>## [1] 0.3228743</code></pre>
<p>Now, we do this 1000 times, and keep track of the largest component. This time, instead of taking random points on the sphere, we jitter the current best a bit and if it improves things, then we move in that direction.</p>
<div class="sourceCode" id="cb488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb488-1"><a href="variable-selection.html#cb488-1" aria-hidden="true" tabindex="-1"></a>largest_cov <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">cov</span>(dd_p, dd<span class="sc">$</span>response))</span>
<span id="cb488-2"><a href="variable-selection.html#cb488-2" aria-hidden="true" tabindex="-1"></a>largest_direction <span class="ot">&lt;-</span> rvec</span>
<span id="cb488-3"><a href="variable-selection.html#cb488-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) {</span>
<span id="cb488-4"><a href="variable-selection.html#cb488-4" aria-hidden="true" tabindex="-1"></a>  rvec <span class="ot">&lt;-</span> largest_direction</span>
<span id="cb488-5"><a href="variable-selection.html#cb488-5" aria-hidden="true" tabindex="-1"></a>  rvec <span class="ot">&lt;-</span> rvec <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">3</span>, <span class="dv">0</span>, .<span class="dv">2</span>)</span>
<span id="cb488-6"><a href="variable-selection.html#cb488-6" aria-hidden="true" tabindex="-1"></a>  rvec <span class="ot">&lt;-</span> rvec<span class="sc">/</span><span class="fu">mynorm</span>(rvec)</span>
<span id="cb488-7"><a href="variable-selection.html#cb488-7" aria-hidden="true" tabindex="-1"></a>  dd_p <span class="ot">&lt;-</span> <span class="fu">apply</span>(dd[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">ip</span>(x, rvec))</span>
<span id="cb488-8"><a href="variable-selection.html#cb488-8" aria-hidden="true" tabindex="-1"></a>  curr_cov <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">cov</span>(dd_p, dd<span class="sc">$</span>response))</span>
<span id="cb488-9"><a href="variable-selection.html#cb488-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(curr_cov <span class="sc">&gt;</span> largest_cov) {</span>
<span id="cb488-10"><a href="variable-selection.html#cb488-10" aria-hidden="true" tabindex="-1"></a>    largest_cov <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">cov</span>(dd_p, dd<span class="sc">$</span>response))</span>
<span id="cb488-11"><a href="variable-selection.html#cb488-11" aria-hidden="true" tabindex="-1"></a>    largest_direction <span class="ot">&lt;-</span> rvec</span>
<span id="cb488-12"><a href="variable-selection.html#cb488-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(largest_direction)</span>
<span id="cb488-13"><a href="variable-selection.html#cb488-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb488-14"><a href="variable-selection.html#cb488-14" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1]  0.96147443 -0.27409769  0.02091332
## [1] 0.999462344 0.031434892 0.009320402
## [1]  0.9638841  0.1690204 -0.2058142
## [1]  0.9480203  0.2729168 -0.1636276
## [1]  0.8904580  0.3637548 -0.2734355
## [1]  0.8022974  0.5139944 -0.3035270
## [1]  0.6743569  0.7131305 -0.1915402
## [1]  0.4528270  0.7976425 -0.3983895
## [1]  0.3159840  0.8273111 -0.4644465
## [1]  0.2028455  0.6537100 -0.7290521
## [1]  0.4530832  0.6443218 -0.6160885
## [1]  0.3844822  0.5933179 -0.7072109
## [1]  0.3637054  0.6369490 -0.6797164
## [1]  0.3161830  0.6750865 -0.6665482
## [1]  0.3338814  0.6594096 -0.6735742
## [1]  0.3326478  0.6691214 -0.6645464</code></pre>
<p>According to this, our estimate for the first PLS component is 0.333, 0.669, -0.665. This is the direction of the data that has the largest covariance with the response. Let’s check it against the first component found using the <code>plsr</code> function in the <code>pls</code> package.</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="variable-selection.html#cb490-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pls)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;pls&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:caret&#39;:
## 
##     R2</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     loadings</code></pre>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="variable-selection.html#cb494-1" aria-hidden="true" tabindex="-1"></a>plsmod <span class="ot">&lt;-</span> <span class="fu">plsr</span>(response <span class="sc">~</span> x <span class="sc">+</span> y <span class="sc">+</span> z, <span class="at">data =</span> dd)</span>
<span id="cb494-2"><a href="variable-selection.html#cb494-2" aria-hidden="true" tabindex="-1"></a><span class="fu">loadings</span>(plsmod)</span></code></pre></div>
<pre><code>## 
## Loadings:
##   Comp 1 Comp 2 Comp 3
## x  0.401 -0.942  0.100
## y  0.645  0.281  0.678
## z -0.655 -0.186  0.728
## 
##                Comp 1 Comp 2 Comp 3
## SS loadings     1.006  1.002  1.000
## Proportion Var  0.335  0.334  0.333
## Cumulative Var  0.335  0.669  1.002</code></pre>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="variable-selection.html#cb496-1" aria-hidden="true" tabindex="-1"></a>plsmod<span class="sc">$</span>projection</span></code></pre></div>
<pre><code>##       Comp 1     Comp 2     Comp 3
## x  0.3306078 -0.9135712 0.06426708
## y  0.6676654  0.3579067 0.69202962
## z -0.6670243 -0.2072125 0.72009477</code></pre>
<p>We see that the first component that <code>plsr</code> got in the <code>projection</code> is <span class="math inline">\((0.331, 0.668, -0.6667)\)</span>, which is pretty close to what we got. We confirm that the covariance for that vector is slightly better than the one we got via our crude technique.</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="variable-selection.html#cb498-1" aria-hidden="true" tabindex="-1"></a>rvec <span class="ot">&lt;-</span> plsmod<span class="sc">$</span>projection[,<span class="dv">1</span>]</span>
<span id="cb498-2"><a href="variable-selection.html#cb498-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mynorm</span>(rvec)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="variable-selection.html#cb500-1" aria-hidden="true" tabindex="-1"></a>dd_p <span class="ot">&lt;-</span> <span class="fu">apply</span>(dd[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">ip</span>(x, rvec))</span>
<span id="cb500-2"><a href="variable-selection.html#cb500-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(dd_p, dd<span class="sc">$</span>response)</span></code></pre></div>
<pre><code>## [1] 16.67199</code></pre>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="variable-selection.html#cb502-1" aria-hidden="true" tabindex="-1"></a>largest_cov</span></code></pre></div>
<pre><code>## [1] 16.67189</code></pre>
<p>Now, in PCA to get the second component, we looked at all directions perpendicular to the first component and found the one with maximum variance. In PLS, we no longer force the second component to be orthogonal to the first component. That’s one difference. But, we do want it to pick up different information than the first component. How do we accomplish that?</p>
<p>A first idea might be to find the direction that has the highest covariance with the <strong>residuals</strong> of the response after predicting on the directions chosen so far. That is pretty close to what happens, but doesn’t work exactly. In partial least squares, we first <strong>deflate</strong> the predictor matrix by subtracting out <span class="math inline">\(d d^T M\)</span>, where <span class="math inline">\(d\)</span> is the first direction, <span class="math inline">\(d^T\)</span> is the transpose of <span class="math inline">\(d\)</span>, and <span class="math inline">\(M\)</span> is the original matrix. Then, we find the direction of maximum covariance between the residuals of the first model and this new matrix. I include the details below, but this section is <strong>OPTIONAL</strong>.</p>
<div id="optional-pls-stuff" class="section level3" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Optional PLS Stuff</h3>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="variable-selection.html#cb504-1" aria-hidden="true" tabindex="-1"></a>first_vec <span class="ot">&lt;-</span> largest_direction</span>
<span id="cb504-2"><a href="variable-selection.html#cb504-2" aria-hidden="true" tabindex="-1"></a>dd<span class="sc">$</span>direction_1 <span class="ot">&lt;-</span> <span class="fu">apply</span>(dd[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">ip</span>(x, first_vec))</span>
<span id="cb504-3"><a href="variable-selection.html#cb504-3" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(response <span class="sc">~</span> direction_1, <span class="at">data =</span> dd)</span>
<span id="cb504-4"><a href="variable-selection.html#cb504-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb504-5"><a href="variable-selection.html#cb504-5" aria-hidden="true" tabindex="-1"></a>pvec <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb504-6"><a href="variable-selection.html#cb504-6" aria-hidden="true" tabindex="-1"></a><span class="co">#first_vec</span></span>
<span id="cb504-7"><a href="variable-selection.html#cb504-7" aria-hidden="true" tabindex="-1"></a><span class="co">#dd$direction_1 &lt;- apply(dd[,1:3], 1, function(x) ip(x, first_vec))</span></span>
<span id="cb504-8"><a href="variable-selection.html#cb504-8" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(dd[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb504-9"><a href="variable-selection.html#cb504-9" aria-hidden="true" tabindex="-1"></a>new_dat <span class="ot">&lt;-</span> E <span class="sc">-</span> dd<span class="sc">$</span>direction_1<span class="sc">%*%</span> <span class="fu">t</span>(dd<span class="sc">$</span>direction_1) <span class="sc">%*%</span> E <span class="sc">/</span>(<span class="fu">mynorm</span>(dd<span class="sc">$</span>direction_1)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb504-10"><a href="variable-selection.html#cb504-10" aria-hidden="true" tabindex="-1"></a>projections <span class="ot">&lt;-</span> <span class="fu">apply</span>(new_dat, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">ip</span>(x, pvec))</span>
<span id="cb504-11"><a href="variable-selection.html#cb504-11" aria-hidden="true" tabindex="-1"></a>best_cov <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">cov</span>(m1<span class="sc">$</span>residuals, projections))</span>
<span id="cb504-12"><a href="variable-selection.html#cb504-12" aria-hidden="true" tabindex="-1"></a>best_dir <span class="ot">&lt;-</span> pvec</span>
<span id="cb504-13"><a href="variable-selection.html#cb504-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) {</span>
<span id="cb504-14"><a href="variable-selection.html#cb504-14" aria-hidden="true" tabindex="-1"></a>  pvec <span class="ot">&lt;-</span> best_dir <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">3</span>,<span class="dv">0</span>,.<span class="dv">02</span>)</span>
<span id="cb504-15"><a href="variable-selection.html#cb504-15" aria-hidden="true" tabindex="-1"></a>  pvec <span class="ot">&lt;-</span> pvec<span class="sc">/</span><span class="fu">mynorm</span>(pvec)</span>
<span id="cb504-16"><a href="variable-selection.html#cb504-16" aria-hidden="true" tabindex="-1"></a>  projections <span class="ot">&lt;-</span> <span class="fu">apply</span>(new_dat, <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">ip</span>(x, pvec))</span>
<span id="cb504-17"><a href="variable-selection.html#cb504-17" aria-hidden="true" tabindex="-1"></a>  covv <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">cov</span>(m1<span class="sc">$</span>residuals, projections))</span>
<span id="cb504-18"><a href="variable-selection.html#cb504-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(covv <span class="sc">&gt;</span> best_cov) {</span>
<span id="cb504-19"><a href="variable-selection.html#cb504-19" aria-hidden="true" tabindex="-1"></a>    best_cov <span class="ot">&lt;-</span> covv</span>
<span id="cb504-20"><a href="variable-selection.html#cb504-20" aria-hidden="true" tabindex="-1"></a>    best_dir <span class="ot">&lt;-</span> pvec</span>
<span id="cb504-21"><a href="variable-selection.html#cb504-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(pvec)</span>
<span id="cb504-22"><a href="variable-selection.html#cb504-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb504-23"><a href="variable-selection.html#cb504-23" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1]  0.999848603 -0.016853769  0.004326839
## [1]  0.99898323 -0.04016527  0.02047567
## [1]  0.99817648 -0.03972204  0.04545186
## [1]  0.99821353 -0.04789278  0.03572155
## [1]  0.99796648 -0.06057936  0.01982518
## [1]  0.99677991 -0.05339694  0.05982115
## [1]  0.99623029 -0.05875939  0.06381645
## [1]  0.99568104 -0.06083110  0.07013451
## [1]  0.99511372 -0.07517205  0.06401446
## [1]  0.99411839 -0.07987067  0.07313892
## [1]  0.99375252 -0.09170947  0.06360266
## [1]  0.9914283 -0.1040483  0.0790188
## [1]  0.9878531 -0.1181481  0.1009324
## [1]  0.9855875 -0.1333311  0.1041156
## [1]  0.98504862 -0.14953909  0.08554107
## [1]  0.98397083 -0.16392295  0.07021871
## [1]  0.97769795 -0.20250526  0.05566264
## [1]  0.96729806 -0.23685566  0.09074065
## [1]  0.9657439 -0.2268927  0.1259303
## [1]  0.9587509 -0.2588302  0.1174887
## [1]  0.9531252 -0.2650923  0.1458709
## [1]  0.9407376 -0.3087545  0.1402978
## [1]  0.9360941 -0.3106349  0.1650268
## [1]  0.9354886 -0.3148256  0.1604551
## [1]  0.9389629 -0.3034146  0.1621362
## [1]  0.9374347 -0.3112765  0.1559589
## [1]  0.9379053 -0.3070694  0.1613752
## [1]  0.9378402 -0.3082186  0.1595527
## [1]  0.9378103 -0.3092016  0.1578172</code></pre>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="variable-selection.html#cb506-1" aria-hidden="true" tabindex="-1"></a>best_dir</span></code></pre></div>
<pre><code>## [1]  0.9378103 -0.3092016  0.1578172</code></pre>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="variable-selection.html#cb508-1" aria-hidden="true" tabindex="-1"></a>plsmod<span class="sc">$</span>loading.weights</span></code></pre></div>
<pre><code>## 
## Loadings:
##   Comp 1 Comp 2 Comp 3
## x  0.331 -0.938  0.100
## y  0.668  0.308  0.678
## z -0.667 -0.157  0.728
## 
##                Comp 1 Comp 2 Comp 3
## SS loadings     1.000  1.000  1.000
## Proportion Var  0.333  0.333  0.333
## Cumulative Var  0.333  0.667  1.000</code></pre>
<p>As we can see, we have recovered the <em>loading weights</em>, which map the <strong>deflated</strong> predictors onto the scores. Continuing in this fashion, we could find all of the loading weights, use them to compute the scores, and then compute the loadings via</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="variable-selection.html#cb510-1" aria-hidden="true" tabindex="-1"></a>corpcor<span class="sc">::</span><span class="fu">pseudoinverse</span>(<span class="fu">as.matrix</span>(dd[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])) <span class="sc">%*%</span> plsmod<span class="sc">$</span>scores</span></code></pre></div>
<pre><code>##          Comp 1     Comp 2     Comp 3
## [1,]  0.3306078 -0.9135712 0.06426708
## [2,]  0.6676654  0.3579067 0.69202962
## [3,] -0.6670243 -0.2072125 0.72009477</code></pre>
<p>And this would give us our projection, which we could use to transform the original (or new) data into the basis spanned by the partial least squares representation. The trickiest part about this whole thing is understanding why we deflate the data each time we get a new component in our partial least squares. Let’s leave that for another time, shall we?</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="variable-selection.html#cb512-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.matrix</span>(dd[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]) <span class="sc">%*%</span> plsmod<span class="sc">$</span>projection <span class="sc">%&gt;%</span> </span>
<span id="cb512-2"><a href="variable-selection.html#cb512-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##          Comp 1     Comp 2      Comp 3
## [1,] -1.4064660 -0.4825527  0.05256135
## [2,] -0.6267724 -0.7521577  0.04244780
## [3,]  0.2123543 -1.7215781  0.04869281
## [4,]  0.3974183  0.8213185 -0.11928340
## [5,] -1.9513938  2.2888549 -0.06070022
## [6,]  0.3300496 -0.9384224  0.03141818</code></pre>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="variable-selection.html#cb514-1" aria-hidden="true" tabindex="-1"></a>plsmod<span class="sc">$</span>scores[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span></code></pre></div>
<pre><code>##       Comp 1     Comp 2      Comp 3
## 1 -1.4064660 -0.4825527  0.05256135
## 2 -0.6267724 -0.7521577  0.04244780
## 3  0.2123543 -1.7215781  0.04869281
## 4  0.3974183  0.8213185 -0.11928340
## 5 -1.9513938  2.2888549 -0.06070022
## 6  0.3300496 -0.9384224  0.03141818</code></pre>
</div>
</div>
<div id="ridgelasso-and-elastic-net" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Ridge/Lasso and Elastic Net</h2>
<p>PCR and partial least squares regression both have the goal of reducing the number of predictor variables by replacing the given predictors with a smaller set of linear combinations of the predictors. This has the advantage of finding directions in the data that are aligned with either the signal of the data or the response, but has as a disadvantage that it can be hard to interpret the new predictors. The techniques of this section work directly with the predictors, and lead to models that tend to be more easily interpretable.</p>
<div id="ridge-regression" class="section level3" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Ridge Regression</h3>
<p>We start with <strong>ridge regression</strong>. The basic idea is that minimizing SSE has no penalty at all on having arbitrarily large coefficients. If we add a penalty related to the size of the coefficients, then minimizing this new cost function will keep the coefficients relatively small. Ideally, it would force some of them to be either zero, or close enough to zero that we could round to zero and remove that variable from the model that we are building.</p>
<p>Some more details. Suppose our model is</p>
<p><span class="math display">\[
y = \beta_0 + \sum_{p = 1}^P \beta_p x_p + \epsilon
\]</span></p>
<p>Recall that the SSE based on data is
<span class="math display">\[
SSE = \sum_{i = 1}^n\bigl(y_i - \hat y_i\bigr)^2
\]</span>
where <span class="math inline">\(\hat y_i\)</span> is the estimate of the response <span class="math inline">\(y\)</span>. In ridge regression, we add a penalty based on the size of the coefficients <span class="math inline">\(\beta_p\)</span>:</p>
<p><span class="math display">\[
SSE_{L^2} = \sum_{i = 1}^n \bigl(y_i - \hat y_i\bigr)^2 + \lambda \sum_{p = 1}^P \beta_p^2
\]</span>
Note that there is also a tuning parameter <span class="math inline">\(\lambda\)</span> in the SSE. Depending on the scales of the predictors and the responses, as well as the relationship between the response and predictor, different <span class="math inline">\(\lambda\)</span> will need to be chosen.</p>
<p>Let’s see how this works with a simple simulated example. It is suggested to center and scale our predictors before using ridge regression. We begin with an OLS model.</p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="variable-selection.html#cb516-1" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(<span class="dv">9</span>), <span class="at">nrow =</span> <span class="dv">3</span>)</span>
<span id="cb516-2"><a href="variable-selection.html#cb516-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">t</span>(sigma) <span class="sc">%*%</span> sigma</span>
<span id="cb516-3"><a href="variable-selection.html#cb516-3" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="dv">500</span>, <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">Sigma =</span> sigma)</span>
<span id="cb516-4"><a href="variable-selection.html#cb516-4" aria-hidden="true" tabindex="-1"></a>response <span class="ot">&lt;-</span> dd[,<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> dd[,<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">500</span>,<span class="dv">0</span>,<span class="dv">3</span>)</span>
<span id="cb516-5"><a href="variable-selection.html#cb516-5" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">scale</span>(dd)</span>
<span id="cb516-6"><a href="variable-selection.html#cb516-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(response <span class="sc">~</span> dd) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = response ~ dd)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.636 -1.907  0.143  1.976  8.883 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.04982    0.13183   0.378   0.7057    
## dd1          1.49658    0.13493  11.091   &lt;2e-16 ***
## dd2          4.57711    0.24714  18.521   &lt;2e-16 ***
## dd3          0.47260    0.24475   1.931   0.0541 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.948 on 496 degrees of freedom
## Multiple R-squared:  0.7214, Adjusted R-squared:  0.7197 
## F-statistic: 428.2 on 3 and 496 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now, let’s choose <span class="math inline">\(\lambda = 1\)</span> and minimize the <span class="math inline">\(SSE_{L^2}\)</span> cost function.</p>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="variable-selection.html#cb518-1" aria-hidden="true" tabindex="-1"></a>ssel2 <span class="ot">&lt;-</span> <span class="cf">function</span>(dd, response, beta_0, beta, <span class="at">lambda =</span> <span class="dv">1</span>) {</span>
<span id="cb518-2"><a href="variable-selection.html#cb518-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((dd <span class="sc">%*%</span> beta <span class="sc">+</span> beta_0 <span class="sc">-</span> response)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> lambda <span class="sc">*</span> <span class="fu">sum</span>(beta<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb518-3"><a href="variable-selection.html#cb518-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb518-4"><a href="variable-selection.html#cb518-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ssel2</span>(dd, response, <span class="dv">0</span>, <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>))</span></code></pre></div>
<pre><code>## [1] 12370.04</code></pre>
<p>Now, if we want to minimize this, we use the <code>optim</code> function. First, we define the cost function just in terms of the variables that we are trying to minimize.</p>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb520-1"><a href="variable-selection.html#cb520-1" aria-hidden="true" tabindex="-1"></a>sse_for_optim <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) {</span>
<span id="cb520-2"><a href="variable-selection.html#cb520-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ssel2</span>(dd, response, beta[<span class="dv">1</span>], beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>])</span>
<span id="cb520-3"><a href="variable-selection.html#cb520-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb520-4"><a href="variable-selection.html#cb520-4" aria-hidden="true" tabindex="-1"></a><span class="fu">optim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">fn =</span> sse_for_optim)</span></code></pre></div>
<pre><code>## $par
## [1] 0.04953374 1.49598584 4.54315591 0.44305891
## 
## $value
## [1] 4333.199
## 
## $counts
## function gradient 
##      269       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="variable-selection.html#cb522-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(response <span class="sc">~</span> dd)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = response ~ dd)
## 
## Coefficients:
## (Intercept)          dd1          dd2          dd3  
##     0.04982      1.49658      4.57711      0.47260</code></pre>
<p>We see that regularizing with <span class="math inline">\(\lambda = 1\)</span> had little impact on the result! Since the actual minimum SSE is about 4000, and the coefficients are about 1, that makes sense. In order to get them on the same scale, we would need to have <span class="math inline">\(\lambda = 1000\)</span> or so. Let’s try again with <span class="math inline">\(\lambda = 1000\)</span> just to see. Before we do this, you should think about whether larger <span class="math inline">\(\lambda\)</span> will be associated with coefficients that are closer to what we get with OLS, or further.</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="variable-selection.html#cb524-1" aria-hidden="true" tabindex="-1"></a>sse_for_optim <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) {</span>
<span id="cb524-2"><a href="variable-selection.html#cb524-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ssel2</span>(dd, response, beta[<span class="dv">1</span>], beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">lambda =</span> <span class="dv">1000</span>)</span>
<span id="cb524-3"><a href="variable-selection.html#cb524-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb524-4"><a href="variable-selection.html#cb524-4" aria-hidden="true" tabindex="-1"></a><span class="fu">optim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">fn =</span> sse_for_optim)</span></code></pre></div>
<pre><code>## $par
## [1]  0.04975632  0.66185128  1.21633033 -0.82730013
## 
## $value
## [1] 10477.42
## 
## $counts
## function gradient 
##      245       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="variable-selection.html#cb526-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(response <span class="sc">~</span> dd)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = response ~ dd)
## 
## Coefficients:
## (Intercept)          dd1          dd2          dd3  
##     0.04982      1.49658      4.57711      0.47260</code></pre>
<p>Still not a huge difference, but note that the large coefficients are now closer to the same size. If we do ridge regression with highly correlated predictors, it is often the case that the coefficients associated with the highly correlated predictors end up being about the same size. That is, ridge regression tends to spread out the weight of that direction across all of the predictors.</p>
<p>There are several R packages that implement ridge regression. One that gives the same answer as the algorithm described in the book is <code>ridge</code>.</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="variable-selection.html#cb528-1" aria-hidden="true" tabindex="-1"></a>ridge<span class="sc">::</span><span class="fu">linearRidge</span>(response <span class="sc">~</span> dd, <span class="at">lambda =</span> <span class="dv">1000</span>, <span class="at">scaling =</span> <span class="st">&quot;scale&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## ridge::linearRidge(formula = response ~ dd, lambda = 1000, scaling = &quot;scale&quot;)
## 
## (Intercept)         dd1         dd2         dd3 
##  0.04981915  0.66178400  1.21647445 -0.82711643</code></pre>
<p>However, as we saw above, it can be tricky to find the right <span class="math inline">\(\lambda\)</span>, so other packages do more scaling and trickery, which means that their answers have twists from the algorithm that we described above. Here is the technique suggested by the book.</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="variable-selection.html#cb530-1" aria-hidden="true" tabindex="-1"></a>emod <span class="ot">&lt;-</span> elasticnet<span class="sc">::</span><span class="fu">enet</span>(<span class="at">x =</span> dd, <span class="at">y =</span> response, <span class="at">lambda =</span> <span class="dv">1000</span>)</span>
<span id="cb530-2"><a href="variable-selection.html#cb530-2" aria-hidden="true" tabindex="-1"></a>enetCoef<span class="ot">&lt;-</span> <span class="fu">predict</span>(emod, <span class="at">newx =</span> dd,</span>
<span id="cb530-3"><a href="variable-selection.html#cb530-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">s =</span> <span class="dv">1</span>, </span>
<span id="cb530-4"><a href="variable-selection.html#cb530-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mode =</span> <span class="st">&quot;fraction&quot;</span>,</span>
<span id="cb530-5"><a href="variable-selection.html#cb530-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">type =</span> <span class="st">&quot;coefficients&quot;</span>)</span>
<span id="cb530-6"><a href="variable-selection.html#cb530-6" aria-hidden="true" tabindex="-1"></a>enetCoef</span></code></pre></div>
<pre><code>## $s
## [1] 1
## 
## $fraction
## 0 
## 1 
## 
## $mode
## [1] &quot;fraction&quot;
## 
## $coefficients
## [1]  2.363010  4.483117 -3.606031</code></pre>
<p>As long as the method is internally consistent with how it penalizes, it doesn’t matter so much whether it matches the exact definition we gave; it’s more of a frustration than a problem. As before, in any real problem, we will use cross validation to decide which <span class="math inline">\(\lambda\)</span> to pick. We could again use <code>train</code>, as below:</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="variable-selection.html#cb532-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb532-2"><a href="variable-selection.html#cb532-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;tecator&quot;</span>)</span>
<span id="cb532-3"><a href="variable-selection.html#cb532-3" aria-hidden="true" tabindex="-1"></a><span class="fu">train</span>(<span class="at">x =</span> <span class="fu">as.data.frame</span>(absorp),</span>
<span id="cb532-4"><a href="variable-selection.html#cb532-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> endpoints[,<span class="dv">1</span>],</span>
<span id="cb532-5"><a href="variable-selection.html#cb532-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">method =</span> <span class="st">&quot;ridge&quot;</span>)</span></code></pre></div>
<pre><code>## Ridge Regression 
## 
## 215 samples
## 100 predictors
## 
## No pre-processing
## Resampling: Bootstrapped (25 reps) 
## Summary of sample sizes: 215, 215, 215, 215, 215, 215, ... 
## Resampling results across tuning parameters:
## 
##   lambda  RMSE      Rsquared   MAE     
##   0e+00   4.572167  0.8326010  2.369945
##   1e-04   2.628113  0.9345484  2.086432
##   1e-01   4.054888  0.8547589  3.255681
## 
## RMSE was used to select the optimal model using the smallest value.
## The final value used for the model was lambda = 1e-04.</code></pre>
<p>But we can get some better information more easily out of the dedicated package <code>glmnet</code>. Let’s see how to do it. I am following <a href="https://daviddalpiaz.github.io/r4sl/regularization.html">this book</a> which has tons of interesting things!</p>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="variable-selection.html#cb534-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 4.1-1</code></pre>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="variable-selection.html#cb539-1" aria-hidden="true" tabindex="-1"></a>fit_ridge <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(<span class="at">x =</span> absorp, <span class="at">y =</span> endpoints[,<span class="dv">1</span>], <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb539-2"><a href="variable-selection.html#cb539-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_ridge, <span class="at">label =</span> T, <span class="at">xvar =</span> <span class="st">&quot;lambda&quot;</span>)</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Here, we can see that as <span class="math inline">\(\lambda\)</span> gets bigger the coefficients of the variables are forced to be smaller and smaller, until eventually they are essentially zero.</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="variable-selection.html#cb540-1" aria-hidden="true" tabindex="-1"></a>fit_ridge_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(absorp, endpoints[,<span class="dv">1</span>], <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb540-2"><a href="variable-selection.html#cb540-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_ridge_cv)</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>The first vertical dotted line is where the smallest MSE is, and the second line is where the MSE is one standard error away from the smallest. In this case, <strong>larger</strong> <span class="math inline">\(\lambda\)</span> corresponds to <strong>simpler</strong> models, or at least, models that have been more regularized.</p>
<p>The function <code>glmnet</code> returns the models associated with each of those two <span class="math inline">\(\lambda\)</span>’s for further investigation and use. We can see the coefficients used in the model:</p>
<div class="sourceCode" id="cb541"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb541-1"><a href="variable-selection.html#cb541-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">coef</span>(fit_ridge_cv, <span class="at">s =</span> <span class="st">&quot;lambda.min&quot;</span>), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span>
<span id="cb541-2"><a href="variable-selection.html#cb541-2" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">coef</span>(fit_ridge_cv, <span class="at">s =</span> <span class="st">&quot;lambda.1se&quot;</span>), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>We see that there isn’t a big difference in the coefficients for the two models! If we wanted to predict values, we could use <code>predict</code>.</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb542-1"><a href="variable-selection.html#cb542-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit_ridge_cv, <span class="at">newx =</span> absorp[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,], <span class="at">s =</span> <span class="st">&quot;lambda.min&quot;</span>)</span></code></pre></div>
<pre><code>##             1
## [1,] 63.72555
## [2,] 51.59263</code></pre>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="variable-selection.html#cb544-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit_ridge_cv, <span class="at">newx =</span> absorp[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,], <span class="at">s =</span> <span class="st">&quot;lambda.1se&quot;</span>)</span></code></pre></div>
<pre><code>##             1
## [1,] 63.64588
## [2,] 51.86430</code></pre>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="variable-selection.html#cb546-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(fit_ridge_cv, <span class="at">newx =</span> absorp, <span class="at">s =</span> <span class="st">&quot;lambda.min&quot;</span>) <span class="sc">-</span> <span class="fu">predict</span>(fit_ridge_cv, <span class="at">newx =</span> absorp), <span class="at">ylab =</span> <span class="st">&quot;Moisture&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Difference in Predictions of Moisture Content&quot;</span>)</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Ridge regression is a regularization technique. The point is that if there are highly correlated variables and we resample, we are likely to get similar results using ridge regression with a similar penalty. Let’s check that out. We will need to come up with a covariance matrix that produces highly correlated predictors.</p>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="variable-selection.html#cb547-1" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">runif</span>(<span class="dv">16</span>, .<span class="dv">9</span>, <span class="fl">1.1</span>), <span class="at">nrow =</span> <span class="dv">4</span>)</span>
<span id="cb547-2"><a href="variable-selection.html#cb547-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> sigma <span class="sc">%*%</span> <span class="fu">t</span>(sigma)</span>
<span id="cb547-3"><a href="variable-selection.html#cb547-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="dv">500</span>, <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">Sigma =</span> sigma)</span>
<span id="cb547-4"><a href="variable-selection.html#cb547-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df)</span></code></pre></div>
<pre><code>##           [,1]      [,2]      [,3]      [,4]
## [1,] 1.0000000 0.9996242 0.9926460 0.9982551
## [2,] 0.9996242 1.0000000 0.9936326 0.9984568
## [3,] 0.9926460 0.9936326 1.0000000 0.9978345
## [4,] 0.9982551 0.9984568 0.9978345 1.0000000</code></pre>
<div class="sourceCode" id="cb549"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb549-1"><a href="variable-selection.html#cb549-1" aria-hidden="true" tabindex="-1"></a>response <span class="ot">&lt;-</span> df[,<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> df[,<span class="dv">2</span>] <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> df[,<span class="dv">3</span>] <span class="sc">+</span> <span class="dv">4</span> <span class="sc">*</span> df[,<span class="dv">4</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">500</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb549-2"><a href="variable-selection.html#cb549-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(response <span class="sc">~</span> df)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = response ~ df)
## 
## Coefficients:
## (Intercept)          df1          df2          df3          df4  
##     0.01814      3.01538      4.20074      5.49045     -2.62774</code></pre>
<p>You should check that if you run the above code multiple times, you get quite different answers for the regression coefficients. Now, let’s do ridge regression.</p>
<div class="sourceCode" id="cb551"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb551-1"><a href="variable-selection.html#cb551-1" aria-hidden="true" tabindex="-1"></a>ridge_model <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> df, <span class="at">y =</span> response, <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb551-2"><a href="variable-selection.html#cb551-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coefficients</span>(ridge_model)</span></code></pre></div>
<pre><code>## 5 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                       1
## (Intercept) -0.01171997
## V1           2.41032173
## V2           2.33671157
## V3           2.48730344
## V4           2.39171129</code></pre>
<p>The ridge-regression model typically gives a model of about <span class="math inline">\(t = 2.5 x_1 + 2.5 x_2 + 2.5 x_3 + 2.5 x_4\)</span>, which is about <span class="math inline">\(y = 10 x_i\)</span> for any of the predictors <span class="math inline">\(x_i\)</span>.</p>
</div>
<div id="lasso" class="section level3" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> LASSO</h3>
<p>Unlike ridge regression, the LASSO is more of a variable selection technique. If we are trying to force the non-important or redundant predictors’ coefficients to be zero, we would want to use the so-called <span class="math inline">\(L_0\)</span> norm as a penalty:</p>
<p><span class="math display">\[
SSE_{L_0} = \sum\bigl(\hat y_i - y_i\bigr)^2 + \lambda\bigl| \{p: \beta_p \not= 0\}\bigr|
\]</span></p>
<p>However, this is a hard problem to solve when there are lots of variables! It essentially involves computing the SSE for each subset of predictors and seeing which one is the smallest. If we had 100 predictors, like in <code>tecator</code>, that would mean <span class="math inline">\(2^{100} \approx 1,267,561,000,000,000,000,000,000,000,000\)</span> subsets. That’s gonna take some time, and even if we could do it, what if we found a data set that had 1000 predictors? I don’t have that kind of time. Instead, we solve the <strong>convex relaxation</strong> of the problem, which is to minimize</p>
<p><span class="math display">\[
SSE_{L_1} = \sum\bigl(\hat y_i - y_i\bigr)^2 + \lambda \sum_{i = 1}^P |\beta_i|
\]</span></p>
<p>Again, we don’t typically penalize the intercept, though we could if that made sense for the problem you were working on. Let’s see how it works when we have the same four highly correlated synthetic data as we had in the last section.</p>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="variable-selection.html#cb553-1" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">runif</span>(<span class="dv">16</span>, .<span class="dv">9</span>, <span class="fl">1.1</span>), <span class="at">nrow =</span> <span class="dv">4</span>)</span>
<span id="cb553-2"><a href="variable-selection.html#cb553-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> sigma <span class="sc">%*%</span> <span class="fu">t</span>(sigma)</span>
<span id="cb553-3"><a href="variable-selection.html#cb553-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="dv">500</span>, <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">Sigma =</span> sigma)</span>
<span id="cb553-4"><a href="variable-selection.html#cb553-4" aria-hidden="true" tabindex="-1"></a>response <span class="ot">&lt;-</span> df[,<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> df[,<span class="dv">2</span>] <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> df[,<span class="dv">3</span>] <span class="sc">+</span> <span class="dv">4</span> <span class="sc">*</span> df[,<span class="dv">4</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">500</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span></code></pre></div>
<p>We will again use <code>glmnet</code>.</p>
<div class="sourceCode" id="cb554"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb554-1"><a href="variable-selection.html#cb554-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(<span class="at">x =</span> df, <span class="at">y =</span> response, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb554-2"><a href="variable-selection.html#cb554-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod, <span class="at">xvar =</span> <span class="st">&quot;lambda&quot;</span>, <span class="at">label =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="variable-selection.html#cb555-1" aria-hidden="true" tabindex="-1"></a>cv_mod <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> df, <span class="at">y =</span> response, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb555-2"><a href="variable-selection.html#cb555-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv_mod)</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<div class="sourceCode" id="cb556"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb556-1"><a href="variable-selection.html#cb556-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(cv_mod)</span></code></pre></div>
<pre><code>## 5 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                     1
## (Intercept) 0.1717041
## V1          2.9844920
## V2          1.6187466
## V3          1.4804404
## V4          3.4688456</code></pre>
<p>We see that the LASSO removed two of the variables, and the other two add up to about 10. (At least, that is what it seemed to be doing when I was practicing!) If we resample, then the LASSO will likely select different variables with different coefficients. So, LASSO doesn’t regularize as much as ridge regression, but it does do some variable selection. Let’s run it again on <code>tecator</code>.</p>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="variable-selection.html#cb558-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(<span class="at">x =</span> absorp, <span class="at">y =</span> endpoints[,<span class="dv">1</span>], <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb558-2"><a href="variable-selection.html#cb558-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod, <span class="at">xvar =</span> <span class="st">&quot;lambda&quot;</span>, <span class="at">label =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<div class="sourceCode" id="cb559"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb559-1"><a href="variable-selection.html#cb559-1" aria-hidden="true" tabindex="-1"></a>cv_mod <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(<span class="at">x =</span> absorp, <span class="at">y =</span> endpoints[,<span class="dv">1</span>], <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">type.measure =</span> <span class="st">&quot;mse&quot;</span>)</span>
<span id="cb559-2"><a href="variable-selection.html#cb559-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv_mod)</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="variable-selection.html#cb560-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">coef</span>(cv_mod))</span></code></pre></div>
<p><img src="05-variable-selection_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<div class="sourceCode" id="cb561"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb561-1"><a href="variable-selection.html#cb561-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(<span class="fu">coef</span>(cv_mod)) <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 20</code></pre>
<p>This model has 20 non-zero variables. That is quite a few more than PCR and PLS ended up with, but <strong>these are the original variables</strong> so we might have some hope of interpreting things. So, downside is more variables, upside is that the variables are more immediately interpretable. Now let’s just see what the estimated RMSE was. The first one is for the <span class="math inline">\(\lambda\)</span> that is one standard error away from the minimum value, and the second is the minimum MSE observed.</p>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="variable-selection.html#cb563-1" aria-hidden="true" tabindex="-1"></a>cv_mod<span class="sc">$</span>cvm[cv_mod<span class="sc">$</span>lambda <span class="sc">==</span> cv_mod<span class="sc">$</span>lambda<span class="fl">.1</span>se]</span></code></pre></div>
<pre><code>## [1] 8.325913</code></pre>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="variable-selection.html#cb565-1" aria-hidden="true" tabindex="-1"></a>cv_mod<span class="sc">$</span>cvm[cv_mod<span class="sc">$</span>lambda <span class="sc">==</span> cv_mod<span class="sc">$</span>lambda.min]</span></code></pre></div>
<pre><code>## [1] 7.859239</code></pre>
</div>
</div>
<div id="step-aic" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Step AIC</h2>
<p>We mentioned before that we would ideally like to minimize <span class="math inline">\(SSE_{L_0}\)</span>, which is the sum-squared error plus a penalty based on how many of the coefficients are non-zero. While checking all subsets of coefficients would take too long, we can try a <em>stepwise</em> approach, which would approximate this. Let’s see how this would work in the example from above that is running through the chapter, but let’s make the correlation between variables smaller.</p>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb567-1"><a href="variable-selection.html#cb567-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2292020</span>)</span>
<span id="cb567-2"><a href="variable-selection.html#cb567-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">runif</span>(<span class="dv">16</span>, <span class="sc">-</span>.<span class="dv">5</span>, <span class="fl">1.5</span>), <span class="at">nrow =</span> <span class="dv">4</span>)</span>
<span id="cb567-3"><a href="variable-selection.html#cb567-3" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> sigma <span class="sc">%*%</span> <span class="fu">t</span>(sigma)</span>
<span id="cb567-4"><a href="variable-selection.html#cb567-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="dv">500</span>, <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">Sigma =</span> sigma)</span>
<span id="cb567-5"><a href="variable-selection.html#cb567-5" aria-hidden="true" tabindex="-1"></a>response <span class="ot">&lt;-</span> df[,<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> df[,<span class="dv">2</span>] <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> df[,<span class="dv">3</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">500</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb567-6"><a href="variable-selection.html#cb567-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df)</span></code></pre></div>
<pre><code>##           [,1]       [,2]       [,3]       [,4]
## [1,] 1.0000000  0.3755164  0.5917336  0.5171758
## [2,] 0.3755164  1.0000000  0.9393433 -0.3369446
## [3,] 0.5917336  0.9393433  1.0000000 -0.1552404
## [4,] 0.5171758 -0.3369446 -0.1552404  1.0000000</code></pre>
<p>We do LOOCV on the full model, then we do LOOCV estimate of MSE after removing each variable separately. So, in all, we do 5 LOOCV MSE estimates. If none of the 4 reduced models are better, then we are done. If one is better, that becomes our new “full model” and we see whether we can remove any of the other three variables.</p>
<p>One twist, though, is that in the real algorithm, we would also want to check whether adding variables back in would improve the MSE. We will not implement that here.</p>
<p>The reason that we are using LOOCV is that it is easy to compute for linear models without actually doing the interation! We won’t go through the details, but we will include the code here for anyone interested.</p>
<p>First, we find the hat matrix and the leverage values.</p>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="variable-selection.html#cb569-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(df)</span>
<span id="cb569-2"><a href="variable-selection.html#cb569-2" aria-hidden="true" tabindex="-1"></a>dd<span class="sc">$</span>response <span class="ot">&lt;-</span> response</span>
<span id="cb569-3"><a href="variable-selection.html#cb569-3" aria-hidden="true" tabindex="-1"></a>full_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(response <span class="sc">~</span> ., <span class="at">data =</span> dd)</span>
<span id="cb569-4"><a href="variable-selection.html#cb569-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb569-5"><a href="variable-selection.html#cb569-5" aria-hidden="true" tabindex="-1"></a>df_intercept <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df, <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">500</span>))</span>
<span id="cb569-6"><a href="variable-selection.html#cb569-6" aria-hidden="true" tabindex="-1"></a>hat_matrix <span class="ot">&lt;-</span> df_intercept <span class="sc">%*%</span> </span>
<span id="cb569-7"><a href="variable-selection.html#cb569-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">solve</span>(<span class="fu">t</span>(df_intercept) <span class="sc">%*%</span> </span>
<span id="cb569-8"><a href="variable-selection.html#cb569-8" aria-hidden="true" tabindex="-1"></a>          df_intercept) <span class="sc">%*%</span> </span>
<span id="cb569-9"><a href="variable-selection.html#cb569-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>(df_intercept)  <span class="co">#this is the hat matrix</span></span>
<span id="cb569-10"><a href="variable-selection.html#cb569-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb569-11"><a href="variable-selection.html#cb569-11" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(hat_matrix)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] </span></code></pre></div>
<pre><code>## [1] 0.011226329 0.007003272 0.003909106 0.005312969 0.008961232</code></pre>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="variable-selection.html#cb571-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hatvalues</span>(full_mod)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] <span class="co">#see, the diagonal of the hat matrix is given by hatvalues!</span></span></code></pre></div>
<pre><code>##           1           2           3           4           5 
## 0.011226329 0.007003272 0.003909106 0.005312969 0.008961232</code></pre>
<div class="sourceCode" id="cb573"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb573-1"><a href="variable-selection.html#cb573-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(full_mod)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##         1         2         3         4         5 
## -8.117599 -8.990833  6.272003 -1.299794 13.264895</code></pre>
<div class="sourceCode" id="cb575"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb575-1"><a href="variable-selection.html#cb575-1" aria-hidden="true" tabindex="-1"></a>(hat_matrix <span class="sc">%*%</span> response)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] </span></code></pre></div>
<pre><code>## [1] -8.117599 -8.990833  6.272003 -1.299794 13.264895</code></pre>
<p>The hat matrix is called the hat matrix because when you multiply the hat matrix times the response, you get the predicted values! Sounds like magic, I know, but you can see that it is true above.</p>
<p>You can also get the residuals from the hat matrix:</p>
<div class="sourceCode" id="cb577"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb577-1"><a href="variable-selection.html#cb577-1" aria-hidden="true" tabindex="-1"></a>((<span class="fu">diag</span>(<span class="dv">1</span>, <span class="dv">500</span>) <span class="sc">-</span> hat_matrix) <span class="sc">%*%</span> response)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] -1.3411735 -0.5974403 -2.4618286  0.9980398 -3.2304093</code></pre>
<div class="sourceCode" id="cb579"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb579-1"><a href="variable-selection.html#cb579-1" aria-hidden="true" tabindex="-1"></a>full_mod<span class="sc">$</span>residuals[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##          1          2          3          4          5 
## -1.3411735 -0.5974403 -2.4618286  0.9980398 -3.2304093</code></pre>
<p>So far, this doesn’t seem too magical. But, check this out. We can get the LOOCV MSE score directly from the hat matrix.</p>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="variable-selection.html#cb581-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span><span class="dv">500</span> <span class="sc">*</span> <span class="fu">sum</span>(((<span class="fu">diag</span>(<span class="dv">1</span>, <span class="dv">500</span>) <span class="sc">-</span> hat_matrix) <span class="sc">%*%</span> response)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">hatvalues</span>(full_mod))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 8.008726</code></pre>
<p>Perhaps easier to understand:</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="variable-selection.html#cb583-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>((full_mod<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">hatvalues</span>(full_mod))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 8.008726</code></pre>
<p>It is the average value of the residuals squared, weighted by the reciprocal of 1 minus the leverage squared. Let’s verify through actual LOOCV.</p>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="variable-selection.html#cb585-1" aria-hidden="true" tabindex="-1"></a>errors <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">500</span>, <span class="cf">function</span>(x) {</span>
<span id="cb585-2"><a href="variable-selection.html#cb585-2" aria-hidden="true" tabindex="-1"></a>  dd_small <span class="ot">&lt;-</span> dd[<span class="sc">-</span>x,]</span>
<span id="cb585-3"><a href="variable-selection.html#cb585-3" aria-hidden="true" tabindex="-1"></a>  mod_small <span class="ot">&lt;-</span> <span class="fu">lm</span>(response <span class="sc">~</span> ., <span class="at">data =</span> dd_small)</span>
<span id="cb585-4"><a href="variable-selection.html#cb585-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(mod_small, <span class="at">newdata =</span> dd[x,]) <span class="sc">-</span> dd<span class="sc">$</span>response[x]</span>
<span id="cb585-5"><a href="variable-selection.html#cb585-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb585-6"><a href="variable-selection.html#cb585-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(errors<span class="sc">^</span><span class="dv">2</span>) <span class="co">#behold!</span></span></code></pre></div>
<pre><code>## [1] 8.008726</code></pre>
<p>Now, let’s remove each of the four variables separately, and estimate the MSE via LOOCV.</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="variable-selection.html#cb587-1" aria-hidden="true" tabindex="-1"></a>loocvs <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="cf">function</span>(x) {</span>
<span id="cb587-2"><a href="variable-selection.html#cb587-2" aria-hidden="true" tabindex="-1"></a>  dd_skinny <span class="ot">&lt;-</span> dd[,<span class="sc">-</span>x]</span>
<span id="cb587-3"><a href="variable-selection.html#cb587-3" aria-hidden="true" tabindex="-1"></a>  skinny_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(response <span class="sc">~</span> ., <span class="at">data =</span> dd_skinny)</span>
<span id="cb587-4"><a href="variable-selection.html#cb587-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>((skinny_mod<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fu">hatvalues</span>(skinny_mod))<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb587-5"><a href="variable-selection.html#cb587-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb587-6"><a href="variable-selection.html#cb587-6" aria-hidden="true" tabindex="-1"></a>loocvs</span></code></pre></div>
<pre><code>## [1] 8.661742 8.960961 9.540100 7.985612</code></pre>
<p>By inspection, we see that we should remove variable number 4, because doing so has the lowest LOOCV estimate of MSE, and it is lower than the full model, which was 8.0087257. Then, we would repeat the above, seeing if we can remove any of variables 1, 2 and 3.</p>
<p>There is another way of doing this, using the Akaike Information Criterion. It can be shown that under some assumptions, the AIC is asymptotically equivalent to doing LOOCV. Here, by asymptotically equivalent, I mean that as the number of data points goes to infinity, LOOCV with MSE and the AIC will both yield the same suggestion as to which variable to remove, or whether to stay with the model you have.</p>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="variable-selection.html#cb589-1" aria-hidden="true" tabindex="-1"></a>MASS<span class="sc">::</span><span class="fu">stepAIC</span>(full_mod, <span class="at">steps =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=1040.09
## response ~ V1 + V2 + V3 + V4
## 
##        Df Sum of Sq    RSS    AIC
## - V4    1      6.75 3930.5 1039.0
## &lt;none&gt;              3923.7 1040.1
## - V1    1    337.21 4260.9 1079.3
## - V2    1    481.29 4405.0 1095.9
## - V3    1    768.89 4692.6 1127.6
## 
## Step:  AIC=1038.95
## response ~ V1 + V2 + V3</code></pre>
<pre><code>## 
## Call:
## lm(formula = response ~ V1 + V2 + V3, data = dd)
## 
## Coefficients:
## (Intercept)           V1           V2           V3  
##      -0.128        1.183        2.226        2.697</code></pre>
<p>Note that, in this case, <code>stepAIC</code> also chooses to remove the 4th variable. It is not the case that these two techniques will always give the same suggestion, though, even though in the limit as the number of observations goes to infinity they will.</p>
<p>Let’s try them out on the tecator data set.</p>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="variable-selection.html#cb592-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;tecator&quot;</span>)</span>
<span id="cb592-2"><a href="variable-selection.html#cb592-2" aria-hidden="true" tabindex="-1"></a>compute_loocv <span class="ot">&lt;-</span> <span class="cf">function</span>(full_model) {</span>
<span id="cb592-3"><a href="variable-selection.html#cb592-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>((full_model<span class="sc">$</span>residuals)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fu">hatvalues</span>(full_model))<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb592-4"><a href="variable-selection.html#cb592-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb592-5"><a href="variable-selection.html#cb592-5" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(absorp)</span>
<span id="cb592-6"><a href="variable-selection.html#cb592-6" aria-hidden="true" tabindex="-1"></a>dd<span class="sc">$</span>response <span class="ot">&lt;-</span> endpoints[,<span class="dv">1</span>]</span>
<span id="cb592-7"><a href="variable-selection.html#cb592-7" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(response <span class="sc">~</span> ., <span class="at">data =</span> dd)</span>
<span id="cb592-8"><a href="variable-selection.html#cb592-8" aria-hidden="true" tabindex="-1"></a>mse_full <span class="ot">&lt;-</span> <span class="fu">compute_loocv</span>(full_model)</span>
<span id="cb592-9"><a href="variable-selection.html#cb592-9" aria-hidden="true" tabindex="-1"></a>mse_loocv <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(absorp), <span class="cf">function</span>(x) {</span>
<span id="cb592-10"><a href="variable-selection.html#cb592-10" aria-hidden="true" tabindex="-1"></a>  dd_skinny <span class="ot">&lt;-</span> dd[,<span class="sc">-</span>x]</span>
<span id="cb592-11"><a href="variable-selection.html#cb592-11" aria-hidden="true" tabindex="-1"></a>  skinny_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(response <span class="sc">~</span> ., <span class="at">data =</span> dd_skinny)</span>
<span id="cb592-12"><a href="variable-selection.html#cb592-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">compute_loocv</span>(skinny_model)</span>
<span id="cb592-13"><a href="variable-selection.html#cb592-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb592-14"><a href="variable-selection.html#cb592-14" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(mse_loocv)</span></code></pre></div>
<pre><code>## [1] 45</code></pre>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="variable-selection.html#cb594-1" aria-hidden="true" tabindex="-1"></a>mse_loocv[<span class="dv">45</span>]</span></code></pre></div>
<pre><code>## [1] 5.069154</code></pre>
<p>This suggests that our first move should be to remove variable 45, resulting in a decrease of almost a full unit in MSE! Now, let’s see what <code>stepAIC</code> suggests.</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="variable-selection.html#cb596-1" aria-hidden="true" tabindex="-1"></a>MASS<span class="sc">::</span><span class="fu">stepAIC</span>(full_model, <span class="at">steps =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=60.45
## response ~ V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + V9 + V10 + 
##     V11 + V12 + V13 + V14 + V15 + V16 + V17 + V18 + V19 + V20 + 
##     V21 + V22 + V23 + V24 + V25 + V26 + V27 + V28 + V29 + V30 + 
##     V31 + V32 + V33 + V34 + V35 + V36 + V37 + V38 + V39 + V40 + 
##     V41 + V42 + V43 + V44 + V45 + V46 + V47 + V48 + V49 + V50 + 
##     V51 + V52 + V53 + V54 + V55 + V56 + V57 + V58 + V59 + V60 + 
##     V61 + V62 + V63 + V64 + V65 + V66 + V67 + V68 + V69 + V70 + 
##     V71 + V72 + V73 + V74 + V75 + V76 + V77 + V78 + V79 + V80 + 
##     V81 + V82 + V83 + V84 + V85 + V86 + V87 + V88 + V89 + V90 + 
##     V91 + V92 + V93 + V94 + V95 + V96 + V97 + V98 + V99 + V100
## 
##        Df Sum of Sq    RSS    AIC
## - V53   1    0.0007 111.30 58.448
## - V46   1    0.0015 111.30 58.449
## - V33   1    0.0023 111.31 58.451
## - V100  1    0.0138 111.32 58.473
## - V62   1    0.0272 111.33 58.499
## - V49   1    0.0320 111.33 58.508
## - V92   1    0.0566 111.36 58.556
## - V98   1    0.0666 111.37 58.575
## - V65   1    0.0669 111.37 58.576
## - V83   1    0.0680 111.37 58.578
## - V66   1    0.0708 111.37 58.583
## - V8    1    0.0765 111.38 58.594
## - V57   1    0.0783 111.38 58.598
## - V93   1    0.0994 111.40 58.639
## - V82   1    0.1009 111.40 58.641
## - V71   1    0.1013 111.40 58.642
## - V35   1    0.1058 111.41 58.651
## - V84   1    0.1115 111.41 58.662
## - V88   1    0.1430 111.44 58.723
## - V89   1    0.1471 111.45 58.730
## - V17   1    0.1697 111.47 58.774
## - V38   1    0.2166 111.52 58.865
## - V27   1    0.2428 111.55 58.915
## - V31   1    0.2429 111.55 58.915
## - V21   1    0.3045 111.61 59.034
## - V23   1    0.3121 111.61 59.049
## - V10   1    0.3417 111.64 59.106
## - V3    1    0.3488 111.65 59.119
## - V90   1    0.3851 111.69 59.189
## - V58   1    0.4252 111.73 59.266
## - V32   1    0.4309 111.73 59.277
## - V77   1    0.4424 111.75 59.300
## - V15   1    0.4834 111.79 59.378
## - V96   1    0.5194 111.82 59.448
## - V99   1    0.5234 111.83 59.455
## - V91   1    0.6011 111.90 59.605
## - V44   1    0.6438 111.95 59.687
## - V48   1    0.7641 112.07 59.918
## - V85   1    0.8571 112.16 60.096
## - V24   1    0.8879 112.19 60.155
## - V16   1    0.8906 112.19 60.160
## - V86   1    0.9197 112.22 60.216
## - V19   1    0.9287 112.23 60.233
## - V76   1    0.9535 112.26 60.281
## &lt;none&gt;              111.30 60.447
## - V75   1    1.0744 112.38 60.512
## - V79   1    1.0843 112.39 60.531
## - V6    1    1.1885 112.49 60.730
## - V26   1    1.1969 112.50 60.746
## - V7    1    1.2217 112.52 60.794
## - V37   1    1.2328 112.53 60.815
## - V72   1    1.2393 112.54 60.827
## - V94   1    1.3491 112.65 61.037
## - V4    1    1.3614 112.66 61.060
## - V14   1    1.4448 112.75 61.220
## - V97   1    1.4506 112.75 61.231
## - V20   1    1.4895 112.79 61.305
## - V9    1    1.5530 112.86 61.426
## - V36   1    1.7076 113.01 61.720
## - V78   1    1.7111 113.01 61.727
## - V45   1    1.7674 113.07 61.834
## - V5    1    1.7865 113.09 61.870
## - V43   1    1.7958 113.10 61.888
## - V22   1    1.8900 113.19 62.067
## - V95   1    1.9140 113.22 62.112
## - V56   1    1.9799 113.28 62.238
## - V87   1    2.1377 113.44 62.537
## - V67   1    2.1895 113.49 62.635
## - V13   1    2.2347 113.54 62.721
## - V50   1    2.3598 113.66 62.957
## - V11   1    2.3943 113.70 63.022
## - V30   1    2.5125 113.81 63.246
## - V61   1    2.5446 113.85 63.307
## - V70   1    2.9922 114.30 64.150
## - V34   1    3.0151 114.32 64.193
## - V52   1    3.0318 114.33 64.225
## - V74   1    3.1353 114.44 64.419
## - V18   1    3.2424 114.55 64.620
## - V25   1    3.3923 114.69 64.902
## - V64   1    3.5160 114.82 65.133
## - V12   1    3.7266 115.03 65.527
## - V54   1    4.2069 115.51 66.423
## - V63   1    4.3076 115.61 66.610
## - V40   1    4.5296 115.83 67.023
## - V41   1    4.7874 116.09 67.501
## - V81   1    4.8758 116.18 67.665
## - V42   1    5.2058 116.51 68.275
## - V59   1    5.3076 116.61 68.462
## - V39   1    5.5383 116.84 68.887
## - V51   1    5.6801 116.98 69.148
## - V47   1    6.0536 117.36 69.833
## - V2    1    6.5034 117.81 70.656
## - V68   1    7.2777 118.58 72.064
## - V55   1    7.7127 119.02 72.852
## - V60   1    7.8261 119.13 73.056
## - V80   1    9.0669 120.37 75.284
## - V69   1    9.1436 120.45 75.421
## - V28   1   10.7574 122.06 78.283
## - V73   1   11.1660 122.47 79.001
## - V29   1   13.8452 125.15 83.654
## - V1    1   17.6484 128.95 90.090
## 
## Step:  AIC=58.45
## response ~ V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + V9 + V10 + 
##     V11 + V12 + V13 + V14 + V15 + V16 + V17 + V18 + V19 + V20 + 
##     V21 + V22 + V23 + V24 + V25 + V26 + V27 + V28 + V29 + V30 + 
##     V31 + V32 + V33 + V34 + V35 + V36 + V37 + V38 + V39 + V40 + 
##     V41 + V42 + V43 + V44 + V45 + V46 + V47 + V48 + V49 + V50 + 
##     V51 + V52 + V54 + V55 + V56 + V57 + V58 + V59 + V60 + V61 + 
##     V62 + V63 + V64 + V65 + V66 + V67 + V68 + V69 + V70 + V71 + 
##     V72 + V73 + V74 + V75 + V76 + V77 + V78 + V79 + V80 + V81 + 
##     V82 + V83 + V84 + V85 + V86 + V87 + V88 + V89 + V90 + V91 + 
##     V92 + V93 + V94 + V95 + V96 + V97 + V98 + V99 + V100</code></pre>
<pre><code>## 
## Call:
## lm(formula = response ~ V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + 
##     V9 + V10 + V11 + V12 + V13 + V14 + V15 + V16 + V17 + V18 + 
##     V19 + V20 + V21 + V22 + V23 + V24 + V25 + V26 + V27 + V28 + 
##     V29 + V30 + V31 + V32 + V33 + V34 + V35 + V36 + V37 + V38 + 
##     V39 + V40 + V41 + V42 + V43 + V44 + V45 + V46 + V47 + V48 + 
##     V49 + V50 + V51 + V52 + V54 + V55 + V56 + V57 + V58 + V59 + 
##     V60 + V61 + V62 + V63 + V64 + V65 + V66 + V67 + V68 + V69 + 
##     V70 + V71 + V72 + V73 + V74 + V75 + V76 + V77 + V78 + V79 + 
##     V80 + V81 + V82 + V83 + V84 + V85 + V86 + V87 + V88 + V89 + 
##     V90 + V91 + V92 + V93 + V94 + V95 + V96 + V97 + V98 + V99 + 
##     V100, data = dd)
## 
## Coefficients:
## (Intercept)           V1           V2           V3           V4           V5  
##       71.37    -10338.44     11550.42      4259.29    -14703.59     21567.86  
##          V6           V7           V8           V9          V10          V11  
##   -15454.15     10328.62     -1612.30     -5336.83     -3225.32     13370.83  
##         V12          V13          V14          V15          V16          V17  
##   -28943.35     28217.12    -19579.32      7543.65      6323.67      2103.59  
##         V18          V19          V20          V21          V22          V23  
##    -9108.90     -7061.12     15198.90      9252.58    -25652.88      8725.91  
##         V24          V25          V26          V27          V28          V29  
##    10599.14    -12988.63      5293.43      2450.95    -21885.34     37596.78  
##         V30          V31          V32          V33          V34          V35  
##   -22931.67      8458.75    -10202.41      -542.36     13335.26     -2013.96  
##         V36          V37          V38          V39          V40          V41  
##    -6198.43      5362.24      3036.97    -21844.96     27828.42    -34639.66  
##         V42          V43          V44          V45          V46          V47  
##    38549.25    -19187.86      7514.46     -9714.93       172.94      7110.41  
##         V48          V49          V50          V51          V52          V54  
##    -3144.88     -1084.80     12313.87    -25918.87     22976.77    -23841.37  
##         V55          V56          V57          V58          V59          V60  
##    24371.65     -7424.54     -1046.07     -2363.86      8526.48     -9102.37  
##         V61          V62          V63          V64          V65          V66  
##     4919.08      -533.98     -9006.74     10866.91     -1837.46      2162.23  
##         V67          V68          V69          V70          V71          V72  
##   -12315.99     21048.23    -20292.75     10473.39     -1790.42      5770.86  
##         V73          V74          V75          V76          V77          V78  
##   -15138.82      8224.69     -4318.45      3818.17     -2684.13      5921.11  
##         V79          V80          V81          V82          V83          V84  
##    -5136.84     17331.88    -15554.02      2602.40      2424.86      3371.18  
##         V85          V86          V87          V88          V89          V90  
##    -9400.50    -10783.81     18928.08     -4734.18     -4097.03      7079.03  
##         V91          V92          V93          V94          V95          V96  
##    -9836.26      2820.59     -3087.80     10464.46    -10748.35      4941.16  
##         V97          V98          V99         V100  
##     7866.82     -1532.22     -4723.08      -330.32</code></pre>
<p>Hmmm, it suggests to remove variable 53.</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="variable-selection.html#cb599-1" aria-hidden="true" tabindex="-1"></a>mse_loocv[<span class="dv">53</span>]</span></code></pre></div>
<pre><code>## [1] 5.826543</code></pre>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="variable-selection.html#cb601-1" aria-hidden="true" tabindex="-1"></a>mse_loocv[<span class="dv">45</span>]</span></code></pre></div>
<pre><code>## [1] 5.069154</code></pre>
<p>This really isn’t doing a good job of selling itself as a proxy for LOOCV.</p>
<div id="doing-lgocv-with-preprocessing" class="section level3" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Doing LGOCV with preprocessing</h3>
<ol style="list-style-type: decimal">
<li>If there are tuning parameters, set tuning parameter.</li>
<li>Split into test/train</li>
<li>Preprocess train based only on train.</li>
<li>Build model.</li>
<li>Process test based on the preprocessing model from 2.</li>
<li>Predict response from model built in 3.</li>
<li>Compute error</li>
<li>Repeat 1-6 100-ish times.</li>
<li>Take mean and standard deviation; that is the mean error estimate for this tuning parameter value.</li>
<li>Repeat for next tuning parameter value.</li>
<li>Choose the tuning parameter value that gives the simplest model that is within one standard deviation of the smallest mean error.</li>
</ol>
<p>Then, if you want to apply your model to new data that comes in, you build your model on the entire data with the best tuning parameter, including any preprocessing steps. Apply those same preprocessing steps to the new data and then predict.</p>
<p>Let’s run through the entire thing with the Chemical Manufacturing Process data.</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="variable-selection.html#cb603-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AppliedPredictiveModeling)</span>
<span id="cb603-2"><a href="variable-selection.html#cb603-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ChemicalManufacturingProcess&quot;</span>)</span></code></pre></div>
<p>Let’s pretend like the very last observation is the new data that will be coming in at the end.</p>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb604-1"><a href="variable-selection.html#cb604-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> ChemicalManufacturingProcess[<span class="dv">176</span>,]</span>
<span id="cb604-2"><a href="variable-selection.html#cb604-2" aria-hidden="true" tabindex="-1"></a>ChemicalManufacturingProcess <span class="ot">&lt;-</span> ChemicalManufacturingProcess[<span class="sc">-</span><span class="dv">176</span>,]</span></code></pre></div>
<p>We’ll do Johnson-Lindenstrauss dimension reduction followed by regression. We’ll choose either 2 or 3 dimensions to project onto, for simplicity.</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="variable-selection.html#cb605-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. If there are tuning parameters, set tuning parameter.</span></span>
<span id="cb605-2"><a href="variable-selection.html#cb605-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-3"><a href="variable-selection.html#cb605-3" aria-hidden="true" tabindex="-1"></a>num_dim <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb605-4"><a href="variable-selection.html#cb605-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-5"><a href="variable-selection.html#cb605-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Split into test/train</span></span>
<span id="cb605-6"><a href="variable-selection.html#cb605-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-7"><a href="variable-selection.html#cb605-7" aria-hidden="true" tabindex="-1"></a>train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ChemicalManufacturingProcess), <span class="dv">135</span>)</span>
<span id="cb605-8"><a href="variable-selection.html#cb605-8" aria-hidden="true" tabindex="-1"></a>test_indices <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">175</span>)[<span class="sc">-</span>train_indices]</span>
<span id="cb605-9"><a href="variable-selection.html#cb605-9" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> ChemicalManufacturingProcess[train_indices,]</span>
<span id="cb605-10"><a href="variable-selection.html#cb605-10" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> ChemicalManufacturingProcess[test_indices,]</span>
<span id="cb605-11"><a href="variable-selection.html#cb605-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-12"><a href="variable-selection.html#cb605-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Preprocess train based only on train. We only want to do this for the predictors.</span></span>
<span id="cb605-13"><a href="variable-selection.html#cb605-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-14"><a href="variable-selection.html#cb605-14" aria-hidden="true" tabindex="-1"></a>train_predictors <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(train_data, <span class="sc">-</span>Yield))</span>
<span id="cb605-15"><a href="variable-selection.html#cb605-15" aria-hidden="true" tabindex="-1"></a>train_response <span class="ot">&lt;-</span> train_data<span class="sc">$</span>Yield</span>
<span id="cb605-16"><a href="variable-selection.html#cb605-16" aria-hidden="true" tabindex="-1"></a>pre_model <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(<span class="at">x =</span> train_predictors, </span>
<span id="cb605-17"><a href="variable-selection.html#cb605-17" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, </span>
<span id="cb605-18"><a href="variable-selection.html#cb605-18" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;scale&quot;</span>, </span>
<span id="cb605-19"><a href="variable-selection.html#cb605-19" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;medianImpute&quot;</span>, </span>
<span id="cb605-20"><a href="variable-selection.html#cb605-20" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;nzv&quot;</span>))</span>
<span id="cb605-21"><a href="variable-selection.html#cb605-21" aria-hidden="true" tabindex="-1"></a>train_predictors <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_model, <span class="at">newdata =</span> train_predictors)</span>
<span id="cb605-22"><a href="variable-selection.html#cb605-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-23"><a href="variable-selection.html#cb605-23" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Build model.</span></span>
<span id="cb605-24"><a href="variable-selection.html#cb605-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-25"><a href="variable-selection.html#cb605-25" aria-hidden="true" tabindex="-1"></a>jl_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(<span class="fu">ncol</span>(train_predictors) <span class="sc">*</span> num_dim), <span class="at">ncol =</span> num_dim)</span>
<span id="cb605-26"><a href="variable-selection.html#cb605-26" aria-hidden="true" tabindex="-1"></a>projected_predictors <span class="ot">&lt;-</span> train_predictors <span class="sc">%*%</span> jl_matrix</span>
<span id="cb605-27"><a href="variable-selection.html#cb605-27" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(train_response <span class="sc">~</span> ., <span class="at">data =</span> <span class="fu">as.data.frame</span>(projected_predictors))</span>
<span id="cb605-28"><a href="variable-selection.html#cb605-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-29"><a href="variable-selection.html#cb605-29" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Process test based on the preprocessing model from 2.</span></span>
<span id="cb605-30"><a href="variable-selection.html#cb605-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-31"><a href="variable-selection.html#cb605-31" aria-hidden="true" tabindex="-1"></a>test_predictors <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(test_data, <span class="sc">-</span><span class="st">&quot;Yield&quot;</span>))</span>
<span id="cb605-32"><a href="variable-selection.html#cb605-32" aria-hidden="true" tabindex="-1"></a>test_response <span class="ot">&lt;-</span> test_data<span class="sc">$</span>Yield</span>
<span id="cb605-33"><a href="variable-selection.html#cb605-33" aria-hidden="true" tabindex="-1"></a>test_predictors <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_model, <span class="at">newdata =</span> test_predictors)</span>
<span id="cb605-34"><a href="variable-selection.html#cb605-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-35"><a href="variable-selection.html#cb605-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-36"><a href="variable-selection.html#cb605-36" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Predict response from model built in 3.</span></span>
<span id="cb605-37"><a href="variable-selection.html#cb605-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-38"><a href="variable-selection.html#cb605-38" aria-hidden="true" tabindex="-1"></a>test_projected <span class="ot">&lt;-</span> test_predictors <span class="sc">%*%</span> jl_matrix</span>
<span id="cb605-39"><a href="variable-selection.html#cb605-39" aria-hidden="true" tabindex="-1"></a>test_response_model <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fu">as.data.frame</span>(test_projected))</span>
<span id="cb605-40"><a href="variable-selection.html#cb605-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-41"><a href="variable-selection.html#cb605-41" aria-hidden="true" tabindex="-1"></a><span class="co"># 6. Compute error</span></span>
<span id="cb605-42"><a href="variable-selection.html#cb605-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb605-43"><a href="variable-selection.html#cb605-43" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> test_response_model <span class="sc">-</span> test_response</span>
<span id="cb605-44"><a href="variable-selection.html#cb605-44" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(error<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 4.157727</code></pre>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb607-1"><a href="variable-selection.html#cb607-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 7. Repeat 1-6 100-ish times.</span></span>
<span id="cb607-2"><a href="variable-selection.html#cb607-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb607-3"><a href="variable-selection.html#cb607-3" aria-hidden="true" tabindex="-1"></a>lgocv_errors <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, {</span>
<span id="cb607-4"><a href="variable-selection.html#cb607-4" aria-hidden="true" tabindex="-1"></a>  train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ChemicalManufacturingProcess), <span class="dv">135</span>)</span>
<span id="cb607-5"><a href="variable-selection.html#cb607-5" aria-hidden="true" tabindex="-1"></a>  test_indices <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">175</span>)[<span class="sc">-</span>train_indices]</span>
<span id="cb607-6"><a href="variable-selection.html#cb607-6" aria-hidden="true" tabindex="-1"></a>  train_data <span class="ot">&lt;-</span> ChemicalManufacturingProcess[train_indices,]</span>
<span id="cb607-7"><a href="variable-selection.html#cb607-7" aria-hidden="true" tabindex="-1"></a>  test_data <span class="ot">&lt;-</span> ChemicalManufacturingProcess[test_indices,]</span>
<span id="cb607-8"><a href="variable-selection.html#cb607-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb607-9"><a href="variable-selection.html#cb607-9" aria-hidden="true" tabindex="-1"></a>  train_predictors <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(train_data, <span class="sc">-</span>Yield))</span>
<span id="cb607-10"><a href="variable-selection.html#cb607-10" aria-hidden="true" tabindex="-1"></a>  train_response <span class="ot">&lt;-</span> train_data<span class="sc">$</span>Yield</span>
<span id="cb607-11"><a href="variable-selection.html#cb607-11" aria-hidden="true" tabindex="-1"></a>  pre_model <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(<span class="at">x =</span> train_predictors, </span>
<span id="cb607-12"><a href="variable-selection.html#cb607-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method =</span> <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, </span>
<span id="cb607-13"><a href="variable-selection.html#cb607-13" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">&quot;scale&quot;</span>, </span>
<span id="cb607-14"><a href="variable-selection.html#cb607-14" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">&quot;medianImpute&quot;</span>, </span>
<span id="cb607-15"><a href="variable-selection.html#cb607-15" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">&quot;nzv&quot;</span>))</span>
<span id="cb607-16"><a href="variable-selection.html#cb607-16" aria-hidden="true" tabindex="-1"></a>  train_predictors <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_model, <span class="at">newdata =</span> train_predictors)</span>
<span id="cb607-17"><a href="variable-selection.html#cb607-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb607-18"><a href="variable-selection.html#cb607-18" aria-hidden="true" tabindex="-1"></a>  jl_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(<span class="fu">ncol</span>(train_predictors) <span class="sc">*</span> num_dim), <span class="at">ncol =</span> num_dim)</span>
<span id="cb607-19"><a href="variable-selection.html#cb607-19" aria-hidden="true" tabindex="-1"></a>  projected_predictors <span class="ot">&lt;-</span> train_predictors <span class="sc">%*%</span> jl_matrix</span>
<span id="cb607-20"><a href="variable-selection.html#cb607-20" aria-hidden="true" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(train_response <span class="sc">~</span> ., <span class="at">data =</span> <span class="fu">as.data.frame</span>(projected_predictors))</span>
<span id="cb607-21"><a href="variable-selection.html#cb607-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb607-22"><a href="variable-selection.html#cb607-22" aria-hidden="true" tabindex="-1"></a>  test_predictors <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(test_data, <span class="sc">-</span><span class="st">&quot;Yield&quot;</span>))</span>
<span id="cb607-23"><a href="variable-selection.html#cb607-23" aria-hidden="true" tabindex="-1"></a>  test_response <span class="ot">&lt;-</span> test_data<span class="sc">$</span>Yield</span>
<span id="cb607-24"><a href="variable-selection.html#cb607-24" aria-hidden="true" tabindex="-1"></a>  test_predictors <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_model, <span class="at">newdata =</span> test_predictors)</span>
<span id="cb607-25"><a href="variable-selection.html#cb607-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb607-26"><a href="variable-selection.html#cb607-26" aria-hidden="true" tabindex="-1"></a>  test_projected <span class="ot">&lt;-</span> test_predictors <span class="sc">%*%</span> jl_matrix</span>
<span id="cb607-27"><a href="variable-selection.html#cb607-27" aria-hidden="true" tabindex="-1"></a>  test_response_model <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fu">as.data.frame</span>(test_projected))</span>
<span id="cb607-28"><a href="variable-selection.html#cb607-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb607-29"><a href="variable-selection.html#cb607-29" aria-hidden="true" tabindex="-1"></a>  error <span class="ot">&lt;-</span> test_response_model <span class="sc">-</span> test_response</span>
<span id="cb607-30"><a href="variable-selection.html#cb607-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(error<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb607-31"><a href="variable-selection.html#cb607-31" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb607-32"><a href="variable-selection.html#cb607-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb607-33"><a href="variable-selection.html#cb607-33" aria-hidden="true" tabindex="-1"></a><span class="co"># 8. Take mean and standard deviation; that is the mean error estimate for this tuning parameter value.</span></span>
<span id="cb607-34"><a href="variable-selection.html#cb607-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb607-35"><a href="variable-selection.html#cb607-35" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(lgocv_errors), <span class="at">sdev =</span> <span class="fu">sd</span>(lgocv_errors))</span></code></pre></div>
<pre><code>##     mean     sdev 
## 5.482381 5.347087</code></pre>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb609-1"><a href="variable-selection.html#cb609-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 9. Repeat for next tuning parameter value.</span></span>
<span id="cb609-2"><a href="variable-selection.html#cb609-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb609-3"><a href="variable-selection.html#cb609-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="cf">function</span>(num_dim) {</span>
<span id="cb609-4"><a href="variable-selection.html#cb609-4" aria-hidden="true" tabindex="-1"></a>  lgocv_errors <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, {</span>
<span id="cb609-5"><a href="variable-selection.html#cb609-5" aria-hidden="true" tabindex="-1"></a>    train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ChemicalManufacturingProcess), <span class="dv">135</span>)</span>
<span id="cb609-6"><a href="variable-selection.html#cb609-6" aria-hidden="true" tabindex="-1"></a>    test_indices <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">175</span>)[<span class="sc">-</span>train_indices]</span>
<span id="cb609-7"><a href="variable-selection.html#cb609-7" aria-hidden="true" tabindex="-1"></a>    train_data <span class="ot">&lt;-</span> ChemicalManufacturingProcess[train_indices,]</span>
<span id="cb609-8"><a href="variable-selection.html#cb609-8" aria-hidden="true" tabindex="-1"></a>    test_data <span class="ot">&lt;-</span> ChemicalManufacturingProcess[test_indices,]</span>
<span id="cb609-9"><a href="variable-selection.html#cb609-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb609-10"><a href="variable-selection.html#cb609-10" aria-hidden="true" tabindex="-1"></a>    train_predictors <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(train_data, <span class="sc">-</span>Yield))</span>
<span id="cb609-11"><a href="variable-selection.html#cb609-11" aria-hidden="true" tabindex="-1"></a>    train_response <span class="ot">&lt;-</span> train_data<span class="sc">$</span>Yield</span>
<span id="cb609-12"><a href="variable-selection.html#cb609-12" aria-hidden="true" tabindex="-1"></a>    pre_model <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(<span class="at">x =</span> train_predictors, </span>
<span id="cb609-13"><a href="variable-selection.html#cb609-13" aria-hidden="true" tabindex="-1"></a>                            <span class="at">method =</span> <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, </span>
<span id="cb609-14"><a href="variable-selection.html#cb609-14" aria-hidden="true" tabindex="-1"></a>                                       <span class="st">&quot;scale&quot;</span>, </span>
<span id="cb609-15"><a href="variable-selection.html#cb609-15" aria-hidden="true" tabindex="-1"></a>                                       <span class="st">&quot;medianImpute&quot;</span>, </span>
<span id="cb609-16"><a href="variable-selection.html#cb609-16" aria-hidden="true" tabindex="-1"></a>                                       <span class="st">&quot;nzv&quot;</span>))</span>
<span id="cb609-17"><a href="variable-selection.html#cb609-17" aria-hidden="true" tabindex="-1"></a>    train_predictors <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_model, <span class="at">newdata =</span> train_predictors)</span>
<span id="cb609-18"><a href="variable-selection.html#cb609-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb609-19"><a href="variable-selection.html#cb609-19" aria-hidden="true" tabindex="-1"></a>    jl_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(<span class="fu">ncol</span>(train_predictors) <span class="sc">*</span> num_dim), <span class="at">ncol =</span> num_dim)</span>
<span id="cb609-20"><a href="variable-selection.html#cb609-20" aria-hidden="true" tabindex="-1"></a>    projected_predictors <span class="ot">&lt;-</span> train_predictors <span class="sc">%*%</span> jl_matrix</span>
<span id="cb609-21"><a href="variable-selection.html#cb609-21" aria-hidden="true" tabindex="-1"></a>    mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(train_response <span class="sc">~</span> ., <span class="at">data =</span> <span class="fu">as.data.frame</span>(projected_predictors))</span>
<span id="cb609-22"><a href="variable-selection.html#cb609-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb609-23"><a href="variable-selection.html#cb609-23" aria-hidden="true" tabindex="-1"></a>    test_predictors <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(test_data, <span class="sc">-</span><span class="st">&quot;Yield&quot;</span>))</span>
<span id="cb609-24"><a href="variable-selection.html#cb609-24" aria-hidden="true" tabindex="-1"></a>    test_response <span class="ot">&lt;-</span> test_data<span class="sc">$</span>Yield</span>
<span id="cb609-25"><a href="variable-selection.html#cb609-25" aria-hidden="true" tabindex="-1"></a>    test_predictors <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_model, <span class="at">newdata =</span> test_predictors)</span>
<span id="cb609-26"><a href="variable-selection.html#cb609-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb609-27"><a href="variable-selection.html#cb609-27" aria-hidden="true" tabindex="-1"></a>    test_projected <span class="ot">&lt;-</span> test_predictors <span class="sc">%*%</span> jl_matrix</span>
<span id="cb609-28"><a href="variable-selection.html#cb609-28" aria-hidden="true" tabindex="-1"></a>    test_response_model <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fu">as.data.frame</span>(test_projected))</span>
<span id="cb609-29"><a href="variable-selection.html#cb609-29" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb609-30"><a href="variable-selection.html#cb609-30" aria-hidden="true" tabindex="-1"></a>    error <span class="ot">&lt;-</span> test_response_model <span class="sc">-</span> test_response</span>
<span id="cb609-31"><a href="variable-selection.html#cb609-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(error<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb609-32"><a href="variable-selection.html#cb609-32" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb609-33"><a href="variable-selection.html#cb609-33" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb609-34"><a href="variable-selection.html#cb609-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(lgocv_errors), <span class="at">sdev =</span> <span class="fu">sd</span>(lgocv_errors))</span>
<span id="cb609-35"><a href="variable-selection.html#cb609-35" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div>
<pre><code>##          [,1]     [,2]
## mean 6.187856 10.17358
## sdev 9.245854 16.81770</code></pre>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb611-1"><a href="variable-selection.html#cb611-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 10. Choose the tuning parameter value that gives the simplest model that is within one standard deviation of the smallest mean error. </span></span></code></pre></div>
<p>By inspection, the model with <code>num_dim = 2</code> is the one that is the best.</p>
</div>
</div>
<div id="interactions" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Interactions</h2>
<p>This section is long, long overdue. We are going to talk about interactions between variables. It can, and often does, happen that the values of one variable affect the way that another variable affects the response. For example, suppose you were measuring how fast honey emtpied out of a jar as a function of the angle that the jar is held and the ambient temperature. It is reasonable to wonder whether at higher temperatures, the angle will have a different effect on how quickly the honey drains than at lower temperatures. Another example would be estimating the drop in blood pressure per mg of drug pressure medicine administered. It is reasonable to wonder whether the rate at which drug pressure drops is different per mg for women than for men, or for children than for adults.</p>
<p>The interpretation of interactions is different depending on whether the predictors are categorical or numeric.</p>
<ol style="list-style-type: decimal">
<li><p>For categorical data, interactions are an effect for each combination of the levels in the categorical data.</p></li>
<li><p>For an interaction between categorical and numeric, interactions indicate a different slope for each of the levels of the categorical data.</p></li>
<li><p>For interaction between numeric data, the interactions indicate that at a fixed level of the first variable, there is a linear response in the other variable, but the slope of that response changes with the value of the first variable. In practice, interaction between numeric variables creates a new variable which is the product of the two variables, and includes that in the regression model.</p></li>
</ol>
<p>Let’s look at an example from ISwR.</p>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="variable-selection.html#cb612-1" aria-hidden="true" tabindex="-1"></a>juul <span class="ot">&lt;-</span> ISwR<span class="sc">::</span>juul</span></code></pre></div>
<p>We model <code>igf</code> on age, sex and tanner level, with interactions.</p>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb613-1"><a href="variable-selection.html#cb613-1" aria-hidden="true" tabindex="-1"></a>juul<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(juul<span class="sc">$</span>sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;boy&quot;</span>, <span class="st">&quot;girl&quot;</span>))</span>
<span id="cb613-2"><a href="variable-selection.html#cb613-2" aria-hidden="true" tabindex="-1"></a>juul<span class="sc">$</span>tanner <span class="ot">&lt;-</span> <span class="fu">factor</span>(juul<span class="sc">$</span>tanner)</span>
<span id="cb613-3"><a href="variable-selection.html#cb613-3" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(igf1 <span class="sc">~</span> (age <span class="sc">+</span> sex <span class="sc">+</span> tanner)<span class="sc">^</span><span class="dv">2</span>, <span class="at">data =</span> juul) <span class="co">#includes all interactions between pairs of variables</span></span>
<span id="cb613-4"><a href="variable-selection.html#cb613-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = igf1 ~ (age + sex + tanner)^2, data = juul)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -305.19  -64.79   -8.88   50.38  420.47 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       79.825     17.421   4.582 5.36e-06 ***
## age               14.886      2.003   7.433 2.82e-13 ***
## sexgirl          -32.310     31.855  -1.014 0.310761    
## tanner2          -69.726    130.855  -0.533 0.594291    
## tanner3          425.075    214.842   1.979 0.048221 *  
## tanner4          783.073    157.695   4.966 8.42e-07 ***
## tanner5          679.253     59.014  11.510  &lt; 2e-16 ***
## age:sexgirl        5.666      3.445   1.645 0.100421    
## age:tanner2       10.759     10.099   1.065 0.287051    
## age:tanner3      -17.335     15.563  -1.114 0.265680    
## age:tanner4      -36.425     10.118  -3.600 0.000338 ***
## age:tanner5      -31.978      3.511  -9.108  &lt; 2e-16 ***
## sexgirl:tanner2   19.597     33.013   0.594 0.552938    
## sexgirl:tanner3  -15.709     44.616  -0.352 0.724870    
## sexgirl:tanner4 -113.617     40.775  -2.786 0.005459 ** 
## sexgirl:tanner5  -49.724     35.264  -1.410 0.158933    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 105 on 776 degrees of freedom
##   (547 observations deleted due to missingness)
## Multiple R-squared:  0.6382, Adjusted R-squared:  0.6312 
## F-statistic: 91.26 on 15 and 776 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Let’s go through the interpretations. Note that if we do not re-code <code>sex</code> and <code>tanner</code> as categorical, then our output would have been quite different.</p>
<p>Looking at the <code>age</code> coefficient, we would be tempted to say that the <code>igf</code> level is associated with an increase of 14.887 micrograms/liter for each year of age increase. However, that can (read: would) be misleading. Looking further down the list, we see coefficients associated with <code>age:sex</code> and <code>age:tanner</code>. So, the increase of 14.886 per year is <strong>for boys</strong> in <strong>tanner level 1</strong>.</p>
<p>If we look at <code>age:sexgirl</code>, we see that we need to add 5.666 to the estimate for boys in order to get the estimate for the <code>igf</code> level increase per year. In other words, for girls (in tanner level 1), the increase is <code>14.866 + 5.666 = 20.532</code>. R has as its default that it reports the values for the first level of the factor, and then the interactions indicate the change from that first value for the other levels. It chose <code>boys</code> because we listed <code>boy</code> before <code>girl</code> in the <code>levels</code> argument to <code>factor</code>. It is important to know which level R is considering the base level for interpreting the coefficients!</p>
<p>Note that we didn’t specify the levels in the <code>tanner</code> variable. In this case, R chooses a natural order for the levels. If the data is numeric, it will arrange them in increasing order, and if the data is character, then it will arrange them in alphabetical order. If we want to be sure, we can type <code>levels(juul$tanner)</code> and it will give us the labels of the levels in the order that it has them.</p>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb615-1"><a href="variable-selection.html#cb615-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(juul<span class="sc">$</span>tanner)</span></code></pre></div>
<pre><code>## [1] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; &quot;5&quot;</code></pre>
<p>We see that tanner level 1 is the “base” level. So, the <code>igf</code> increases by 14.886 per year for <strong>boys</strong> in <strong>tanner 1</strong>. Girls in tanner 2 have a an estimated increase of 14.886 + 5.666 + 10.759 per year. (Note: this sounds like I am saying that for an individual girl, she would expect to see her igf1 level increase by this much per year. That is not what I mean. I mean that each extra year is associated with igf1 levels that are 31.291 micrograms/liter higher. What is the difference?)</p>
<p>Now, let’s estimate the mean <code>igf</code> level for girls in tanner 2 who are 12 years old. It would be</p>
<p><span class="math display">\[
79.825 -32.310 - 69.726 + (14.886124 + 5.666282 + 10.758917 ) * 12 + 19.597 =  373.1219
\]</span></p>
<p>I have used more sig digits in the slope of age because we are multiplying by 12, and otherwise it doesn’t match the answer given by predict very well.</p>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb617-1"><a href="variable-selection.html#cb617-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="dv">12</span>,</span>
<span id="cb617-2"><a href="variable-selection.html#cb617-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">sex =</span> <span class="st">&quot;girl&quot;</span>,</span>
<span id="cb617-3"><a href="variable-selection.html#cb617-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">tanner  =</span> <span class="st">&quot;2&quot;</span>))</span></code></pre></div>
<pre><code>##        1 
## 373.1214</code></pre>
<p>Now let’s look at significance. Dalgaard writes “The exact definition of the interaction terms and the interpretation of their associated regression coefficients can be elusive. Some peculiar things happen if an interaction term is present but one or more of the main effects are missing.” Note that if we re-do the model with the main effect <code>sex</code> missing, it simply reparametrizes the model. The <span class="math inline">\(R^2\)</span> and <span class="math inline">\(F\)</span> statistic are exactly the same.</p>
<div class="sourceCode" id="cb619"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb619-1"><a href="variable-selection.html#cb619-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(igf1 <span class="sc">~</span> age <span class="sc">+</span> tanner <span class="sc">+</span> age<span class="sc">:</span>tanner <span class="sc">+</span> sex<span class="sc">:</span>tanner <span class="sc">+</span> sex<span class="sc">:</span>age, <span class="at">data =</span> juul)</span>
<span id="cb619-2"><a href="variable-selection.html#cb619-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = igf1 ~ age + tanner + age:tanner + sex:tanner + 
##     sex:age, data = juul)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -305.19  -64.79   -8.88   50.38  420.47 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       79.825     17.421   4.582 5.36e-06 ***
## age               14.886      2.003   7.433 2.82e-13 ***
## tanner2          -69.726    130.855  -0.533 0.594291    
## tanner3          425.075    214.842   1.979 0.048221 *  
## tanner4          783.073    157.695   4.966 8.42e-07 ***
## tanner5          679.253     59.014  11.510  &lt; 2e-16 ***
## age:tanner2       10.759     10.099   1.065 0.287051    
## age:tanner3      -17.335     15.563  -1.114 0.265680    
## age:tanner4      -36.425     10.118  -3.600 0.000338 ***
## age:tanner5      -31.978      3.511  -9.108  &lt; 2e-16 ***
## tanner1:sexgirl  -32.310     31.855  -1.014 0.310761    
## tanner2:sexgirl  -12.713     50.409  -0.252 0.800957    
## tanner3:sexgirl  -48.019     59.208  -0.811 0.417602    
## tanner4:sexgirl -145.927     60.031  -2.431 0.015288 *  
## tanner5:sexgirl  -82.034     61.259  -1.339 0.180921    
## age:sexgirl        5.666      3.445   1.645 0.100421    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 105 on 776 degrees of freedom
##   (547 observations deleted due to missingness)
## Multiple R-squared:  0.6382, Adjusted R-squared:  0.6312 
## F-statistic: 91.26 on 15 and 776 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Let’s remind ourselves what the original model summary was.</p>
<div class="sourceCode" id="cb621"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb621-1"><a href="variable-selection.html#cb621-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = igf1 ~ (age + sex + tanner)^2, data = juul)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -305.19  -64.79   -8.88   50.38  420.47 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       79.825     17.421   4.582 5.36e-06 ***
## age               14.886      2.003   7.433 2.82e-13 ***
## sexgirl          -32.310     31.855  -1.014 0.310761    
## tanner2          -69.726    130.855  -0.533 0.594291    
## tanner3          425.075    214.842   1.979 0.048221 *  
## tanner4          783.073    157.695   4.966 8.42e-07 ***
## tanner5          679.253     59.014  11.510  &lt; 2e-16 ***
## age:sexgirl        5.666      3.445   1.645 0.100421    
## age:tanner2       10.759     10.099   1.065 0.287051    
## age:tanner3      -17.335     15.563  -1.114 0.265680    
## age:tanner4      -36.425     10.118  -3.600 0.000338 ***
## age:tanner5      -31.978      3.511  -9.108  &lt; 2e-16 ***
## sexgirl:tanner2   19.597     33.013   0.594 0.552938    
## sexgirl:tanner3  -15.709     44.616  -0.352 0.724870    
## sexgirl:tanner4 -113.617     40.775  -2.786 0.005459 ** 
## sexgirl:tanner5  -49.724     35.264  -1.410 0.158933    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 105 on 776 degrees of freedom
##   (547 observations deleted due to missingness)
## Multiple R-squared:  0.6382, Adjusted R-squared:  0.6312 
## F-statistic: 91.26 on 15 and 776 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We see a significant interaction between sex and tanner, between age and tanner, and but not between age and sex. It might be reasonable to remove the interaction term between age and sex. I don’t normally use <code>update</code>, but now would be a good time to start. Here are two ways of specifying the model.</p>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb623-1"><a href="variable-selection.html#cb623-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(igf1 <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> tanner <span class="sc">+</span> age<span class="sc">:</span>tanner <span class="sc">+</span> sex<span class="sc">:</span>tanner, <span class="at">data =</span> juul)</span>
<span id="cb623-2"><a href="variable-selection.html#cb623-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = igf1 ~ age + sex + tanner + age:tanner + sex:tanner, 
##     data = juul)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -304.62  -65.53  -11.11   49.80  420.05 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      72.9654    16.9334   4.309 1.85e-05 ***
## age              15.7618     1.9329   8.155 1.40e-15 ***
## sexgirl          15.9878    12.3617   1.293 0.196278    
## tanner2         -89.9559   130.4190  -0.690 0.490560    
## tanner3         413.8241   214.9690   1.925 0.054589 .  
## tanner4         752.8186   156.7903   4.801 1.89e-06 ***
## tanner5         592.5482    26.5562  22.313  &lt; 2e-16 ***
## age:tanner2      11.9745    10.0830   1.188 0.235354    
## age:tanner3     -16.8972    15.5773  -1.085 0.278377    
## age:tanner4     -34.9263    10.0877  -3.462 0.000565 ***
## age:tanner5     -27.4666     2.1939 -12.520  &lt; 2e-16 ***
## sexgirl:tanner2  40.3612    30.5379   1.322 0.186665    
## sexgirl:tanner3   6.8416    42.5043   0.161 0.872165    
## sexgirl:tanner4 -79.1319    35.0095  -2.260 0.024079 *  
## sexgirl:tanner5   0.6685    17.4808   0.038 0.969505    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 105.1 on 777 degrees of freedom
##   (547 observations deleted due to missingness)
## Multiple R-squared:  0.637,  Adjusted R-squared:  0.6304 
## F-statistic: 97.38 on 14 and 777 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb625"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb625-1"><a href="variable-selection.html#cb625-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">update</span>(mod, <span class="at">formula. =</span> . <span class="sc">~</span>. <span class="sc">-</span>age<span class="sc">:</span>sex)</span>
<span id="cb625-2"><a href="variable-selection.html#cb625-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = igf1 ~ age + sex + tanner + age:tanner + sex:tanner, 
##     data = juul)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -304.62  -65.53  -11.11   49.80  420.05 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      72.9654    16.9334   4.309 1.85e-05 ***
## age              15.7618     1.9329   8.155 1.40e-15 ***
## sexgirl          15.9878    12.3617   1.293 0.196278    
## tanner2         -89.9559   130.4190  -0.690 0.490560    
## tanner3         413.8241   214.9690   1.925 0.054589 .  
## tanner4         752.8186   156.7903   4.801 1.89e-06 ***
## tanner5         592.5482    26.5562  22.313  &lt; 2e-16 ***
## age:tanner2      11.9745    10.0830   1.188 0.235354    
## age:tanner3     -16.8972    15.5773  -1.085 0.278377    
## age:tanner4     -34.9263    10.0877  -3.462 0.000565 ***
## age:tanner5     -27.4666     2.1939 -12.520  &lt; 2e-16 ***
## sexgirl:tanner2  40.3612    30.5379   1.322 0.186665    
## sexgirl:tanner3   6.8416    42.5043   0.161 0.872165    
## sexgirl:tanner4 -79.1319    35.0095  -2.260 0.024079 *  
## sexgirl:tanner5   0.6685    17.4808   0.038 0.969505    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 105.1 on 777 degrees of freedom
##   (547 observations deleted due to missingness)
## Multiple R-squared:  0.637,  Adjusted R-squared:  0.6304 
## F-statistic: 97.38 on 14 and 777 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>At this point, the interaction between sex and tanner is significant, as is the interaction between age and tanner. I would not proceed any further with reducing the model. I tend to only consider removing main effect terms if all of the interactions associated with those terms are not significant. Note also that this is the default behavior of <code>stepAIC</code>, which can also be applied to models with interactions.</p>
<div class="sourceCode" id="cb627"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb627-1"><a href="variable-selection.html#cb627-1" aria-hidden="true" tabindex="-1"></a>MASS<span class="sc">::</span><span class="fu">stepAIC</span>(mod)</span></code></pre></div>
<pre><code>## Start:  AIC=7387.28
## igf1 ~ (age + sex + tanner)^2
## 
##              Df Sum of Sq     RSS    AIC
## &lt;none&gt;                    8550733 7387.3
## - age:sex     1     29810 8580542 7388.0
## - sex:tanner  4    114024 8664757 7389.8
## - age:tanner  4   1036392 9587125 7469.9</code></pre>
<pre><code>## 
## Call:
## lm(formula = igf1 ~ (age + sex + tanner)^2, data = juul)
## 
## Coefficients:
##     (Intercept)              age          sexgirl          tanner2  
##          79.825           14.886          -32.310          -69.726  
##         tanner3          tanner4          tanner5      age:sexgirl  
##         425.075          783.073          679.253            5.666  
##     age:tanner2      age:tanner3      age:tanner4      age:tanner5  
##          10.759          -17.335          -36.425          -31.978  
## sexgirl:tanner2  sexgirl:tanner3  sexgirl:tanner4  sexgirl:tanner5  
##          19.597          -15.709         -113.617          -49.724</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regression-predictive-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="non-linear-regression-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
