<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Causal Inference | Applied Regression with R</title>
  <meta name="description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Causal Inference | Applied Regression with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Causal Inference | Applied Regression with R" />
  
  <meta name="twitter:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

<meta name="author" content="Darrin Speegle" />


<meta name="date" content="2026-04-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
<link rel="prev" href="missing-data-1.html"/>
<link rel="next" href="the-retrofit-study.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Regression with R<br />&nbsp; Notes From STAT 4870/5087</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="classicaltheory.html"><a href="classicaltheory.html"><i class="fa fa-check"></i><b>2</b> Classical Theory of Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="classicaltheory.html"><a href="classicaltheory.html#review"><i class="fa fa-check"></i><b>2.1</b> Review</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-means-and-standard-deviations"><i class="fa fa-check"></i><b>2.1.1</b> Estimating Means and standard deviations</a></li>
<li class="chapter" data-level="2.1.2" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-the-density-of-an-rv"><i class="fa fa-check"></i><b>2.1.2</b> Estimating the density of an rv</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-overview"><i class="fa fa-check"></i><b>2.2</b> Linear Regression Overview</a></li>
<li class="chapter" data-level="2.3" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-with-no-intercept"><i class="fa fa-check"></i><b>2.3</b> Linear Regression with no intercept</a></li>
<li class="chapter" data-level="2.4" data-path="classicaltheory.html"><a href="classicaltheory.html#the-full-model"><i class="fa fa-check"></i><b>2.4</b> The full model</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="classicaltheory.html"><a href="classicaltheory.html#hypothesis-test-interlude"><i class="fa fa-check"></i><b>2.4.1</b> Hypothesis Test Interlude</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="classicaltheory.html"><a href="classicaltheory.html#using-different-loss-functions"><i class="fa fa-check"></i><b>2.5</b> Using different loss functions</a></li>
<li class="chapter" data-level="" data-path="classicaltheory.html"><a href="classicaltheory.html#vignette-a-dplyr-primer"><i class="fa fa-check"></i>Vignette: A dplyr primer</a></li>
<li class="chapter" data-level="2.6" data-path="classicaltheory.html"><a href="classicaltheory.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#anova"><i class="fa fa-check"></i><b>3.0.1</b> Aside on multiple R squared and ANOVA</a></li>
<li class="chapter" data-level="3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-variable-selection-anova"><i class="fa fa-check"></i><b>3.1</b> More Variable Selection: ANOVA</a></li>
<li class="chapter" data-level="3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#predictions"><i class="fa fa-check"></i><b>3.2</b> Predictions</a></li>
<li class="chapter" data-level="3.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#using-aic"><i class="fa fa-check"></i><b>3.3</b> Using AIC</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#likelihood-functions"><i class="fa fa-check"></i><b>3.3.1</b> Likelihood functions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercises-1"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html"><i class="fa fa-check"></i><b>4</b> Intro to Predictive Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#comparingtwomodels"><i class="fa fa-check"></i><b>4.1</b> Comparing Two Models</a></li>
<li class="chapter" data-level="4.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#a-brief-return-to-inference"><i class="fa fa-check"></i><b>4.2</b> A Brief Return to Inference</a></li>
<li class="chapter" data-level="4.3" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#simulations-of-expected-mse"><i class="fa fa-check"></i><b>4.3</b> Simulations of Expected MSE</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-and-bias-variance-tradeoff"><i class="fa fa-check"></i><b>4.3.1</b> Estimating MSE and Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-for-new-predictors-uniformly-sampled"><i class="fa fa-check"></i><b>4.3.2</b> Estimating MSE for new predictors uniformly sampled</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>4.4</b> Bias Variance Trade-off</a></li>
<li class="chapter" data-level="4.5" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#exercises-2"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html"><i class="fa fa-check"></i><b>5</b> Regression Predictive Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#preprocessing"><i class="fa fa-check"></i><b>5.1</b> Preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#missing-data"><i class="fa fa-check"></i><b>5.2</b> Missing Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#predicting-when-a-level-is-missing-from-the-training-set"><i class="fa fa-check"></i><b>5.2.1</b> Predicting when a level is missing from the training set</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#correlated-predictors"><i class="fa fa-check"></i><b>5.3</b> Correlated Predictors</a></li>
<li class="chapter" data-level="5.4" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#aside-on-pca"><i class="fa fa-check"></i><b>5.4</b> Aside on PCA</a></li>
<li class="chapter" data-level="5.5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#johnson-lindenstrauss-dimension-reduction"><i class="fa fa-check"></i><b>5.5</b> Johnson-Lindenstrauss Dimension Reduction</a></li>
<li class="chapter" data-level="5.6" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#exercises-3"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variable-selection.html"><a href="variable-selection.html"><i class="fa fa-check"></i><b>6</b> Variable Selection</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variable-selection.html"><a href="variable-selection.html#partial-least-squares"><i class="fa fa-check"></i><b>6.1</b> Partial Least Squares</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="variable-selection.html"><a href="variable-selection.html#optional-pls-stuff"><i class="fa fa-check"></i><b>6.1.1</b> Optional PLS Stuff</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variable-selection.html"><a href="variable-selection.html#ridgelasso-and-elastic-net"><i class="fa fa-check"></i><b>6.2</b> Ridge/Lasso and Elastic Net</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="variable-selection.html"><a href="variable-selection.html#ridge-regression"><i class="fa fa-check"></i><b>6.2.1</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.2.2" data-path="variable-selection.html"><a href="variable-selection.html#lasso"><i class="fa fa-check"></i><b>6.2.2</b> LASSO</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variable-selection.html"><a href="variable-selection.html#step-aic"><i class="fa fa-check"></i><b>6.3</b> Step AIC</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="variable-selection.html"><a href="variable-selection.html#doing-lgocv-with-preprocessing"><i class="fa fa-check"></i><b>6.3.1</b> Doing LGOCV with preprocessing</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variable-selection.html"><a href="variable-selection.html#interactions"><i class="fa fa-check"></i><b>6.4</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>7</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#logistic-regression"><i class="fa fa-check"></i><b>7.1</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#malaria-example-intro"><i class="fa fa-check"></i><b>7.1.1</b> Malaria Example (Intro)</a></li>
<li class="chapter" data-level="7.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#the-model-theory"><i class="fa fa-check"></i><b>7.1.2</b> The model (theory)</a></li>
<li class="chapter" data-level="7.1.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#estimating-parameters-using-mle"><i class="fa fa-check"></i><b>7.1.3</b> Estimating parameters using MLE</a></li>
<li class="chapter" data-level="7.1.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#estimating-parameters-via-loss-function"><i class="fa fa-check"></i><b>7.1.4</b> Estimating parameters via loss function</a></li>
<li class="chapter" data-level="7.1.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#interpreting-summary"><i class="fa fa-check"></i><b>7.1.5</b> Interpreting summary</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#mixed-effects-logistic-regression"><i class="fa fa-check"></i><b>7.2</b> Mixed Effects Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#nested-random-effects"><i class="fa fa-check"></i><b>7.2.1</b> Nested random effects</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#count-regression"><i class="fa fa-check"></i><b>7.3</b> Count Regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#mixed-effects-model"><i class="fa fa-check"></i><b>7.3.1</b> Mixed Effects Model</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#offsets"><i class="fa fa-check"></i><b>7.4</b> Offsets</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="lecture-notes.html"><a href="lecture-notes.html"><i class="fa fa-check"></i><b>8</b> Lecture Notes</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lecture-notes.html"><a href="lecture-notes.html#january-27"><i class="fa fa-check"></i><b>8.1</b> January 27</a></li>
<li class="chapter" data-level="8.2" data-path="lecture-notes.html"><a href="lecture-notes.html#february-3"><i class="fa fa-check"></i><b>8.2</b> February 3</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="lecture-notes.html"><a href="lecture-notes.html#simulating-data"><i class="fa fa-check"></i><b>8.2.1</b> Simulating Data</a></li>
<li class="chapter" data-level="8.2.2" data-path="lecture-notes.html"><a href="lecture-notes.html#building-models"><i class="fa fa-check"></i><b>8.2.2</b> Building Models</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="lecture-notes.html"><a href="lecture-notes.html#february-5"><i class="fa fa-check"></i><b>8.3</b> February 5</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="lecture-notes.html"><a href="lecture-notes.html#using-broomaugment"><i class="fa fa-check"></i><b>8.3.1</b> Using <code>broom::augment</code></a></li>
<li class="chapter" data-level="8.3.2" data-path="lecture-notes.html"><a href="lecture-notes.html#multicollinearity"><i class="fa fa-check"></i><b>8.3.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="lecture-notes.html"><a href="lecture-notes.html#february-10"><i class="fa fa-check"></i><b>8.4</b> February 10</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="lecture-notes.html"><a href="lecture-notes.html#anova-models"><i class="fa fa-check"></i><b>8.4.1</b> ANOVA Models</a></li>
<li class="chapter" data-level="8.4.2" data-path="lecture-notes.html"><a href="lecture-notes.html#penguins"><i class="fa fa-check"></i><b>8.4.2</b> Penguins</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="lecture-notes.html"><a href="lecture-notes.html#february-12"><i class="fa fa-check"></i><b>8.5</b> February 12</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="lecture-notes.html"><a href="lecture-notes.html#an-example"><i class="fa fa-check"></i><b>8.5.1</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="lecture-notes.html"><a href="lecture-notes.html#february-17"><i class="fa fa-check"></i><b>8.6</b> February 17</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-speaker-and-sentence-effects"><i class="fa fa-check"></i><b>8.6.1</b> Adding random speaker and sentence effects</a></li>
<li class="chapter" data-level="8.6.2" data-path="lecture-notes.html"><a href="lecture-notes.html#random-intercepts-with-continuous-predictor"><i class="fa fa-check"></i><b>8.6.2</b> Random intercepts with continuous predictor</a></li>
<li class="chapter" data-level="8.6.3" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-slopes"><i class="fa fa-check"></i><b>8.6.3</b> Adding random slopes</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="lecture-notes.html"><a href="lecture-notes.html#february-19"><i class="fa fa-check"></i><b>8.7</b> February 19</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="lecture-notes.html"><a href="lecture-notes.html#random-slopes"><i class="fa fa-check"></i><b>8.7.1</b> Random Slopes</a></li>
<li class="chapter" data-level="8.7.2" data-path="lecture-notes.html"><a href="lecture-notes.html#comparing-models"><i class="fa fa-check"></i><b>8.7.2</b> Comparing models</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="lecture-notes.html"><a href="lecture-notes.html#february-24"><i class="fa fa-check"></i><b>8.8</b> February 24</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="lecture-notes.html"><a href="lecture-notes.html#beethoven-tempo-example"><i class="fa fa-check"></i><b>8.8.1</b> Beethoven Tempo Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html"><i class="fa fa-check"></i><b>9</b> Maximum Likelihood Estimation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#mle-for-mixed-models"><i class="fa fa-check"></i><b>9.1</b> MLE for mixed models</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-z-tz-do"><i class="fa fa-check"></i><b>9.1.1</b> What does <code>Z %*% t(Z)</code> do?</a></li>
<li class="chapter" data-level="9.1.2" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-multiplying-by-tau2-do"><i class="fa fa-check"></i><b>9.1.2</b> What does multiplying by <code>tau2</code> do?</a></li>
<li class="chapter" data-level="9.1.3" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-sigma2-diagn-do"><i class="fa fa-check"></i><b>9.1.3</b> What does <code>sigma2 * diag(N)</code> do?</a></li>
<li class="chapter" data-level="9.1.4" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-the-final-matrix-represent"><i class="fa fa-check"></i><b>9.1.4</b> What does the final matrix represent?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="missing-data-1.html"><a href="missing-data-1.html"><i class="fa fa-check"></i><b>10</b> Missing Data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="missing-data-1.html"><a href="missing-data-1.html#technical-details"><i class="fa fa-check"></i><b>10.1</b> Technical Details</a></li>
<li class="chapter" data-level="10.2" data-path="missing-data-1.html"><a href="missing-data-1.html#diagnostics"><i class="fa fa-check"></i><b>10.2</b> Diagnostics</a></li>
<li class="chapter" data-level="10.3" data-path="missing-data-1.html"><a href="missing-data-1.html#pooling"><i class="fa fa-check"></i><b>10.3</b> Pooling</a></li>
<li class="chapter" data-level="10.4" data-path="missing-data-1.html"><a href="missing-data-1.html#simulations"><i class="fa fa-check"></i><b>10.4</b> Simulations</a></li>
<li class="chapter" data-level="10.5" data-path="missing-data-1.html"><a href="missing-data-1.html#sensitivity-analysis"><i class="fa fa-check"></i><b>10.5</b> Sensitivity Analysis</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="causal-inference.html"><a href="causal-inference.html"><i class="fa fa-check"></i><b>11</b> Causal Inference</a>
<ul>
<li class="chapter" data-level="11.0.1" data-path="causal-inference.html"><a href="causal-inference.html#baseline-differences-between-the-groups"><i class="fa fa-check"></i><b>11.0.1</b> Baseline Differences Between the Groups</a></li>
<li class="chapter" data-level="11.0.2" data-path="causal-inference.html"><a href="causal-inference.html#summary"><i class="fa fa-check"></i><b>11.0.2</b> Summary</a></li>
<li class="chapter" data-level="11.1" data-path="causal-inference.html"><a href="causal-inference.html#identification-assumptions-for-causal-adjustment"><i class="fa fa-check"></i><b>11.1</b> Identification Assumptions for Causal Adjustment</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="causal-inference.html"><a href="causal-inference.html#assumptions-for-causal-adjustment"><i class="fa fa-check"></i><b>11.1.1</b> Assumptions for Causal Adjustment</a></li>
<li class="chapter" data-level="11.1.2" data-path="causal-inference.html"><a href="causal-inference.html#the-lalonde-data-revisited"><i class="fa fa-check"></i><b>11.1.2</b> The Lalonde Data Revisited</a></li>
<li class="chapter" data-level="11.1.3" data-path="causal-inference.html"><a href="causal-inference.html#vocabulary-and-an-example"><i class="fa fa-check"></i><b>11.1.3</b> Vocabulary and an Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html"><i class="fa fa-check"></i><b>12</b> The <code>retrofit</code> study</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#worksheet"><i class="fa fa-check"></i><b>12.0.1</b> Worksheet</a></li>
<li class="chapter" data-level="12.0.2" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#solutions"><i class="fa fa-check"></i><b>12.0.2</b> Solutions</a></li>
<li class="chapter" data-level="12.1" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#collid3rs"><i class="fa fa-check"></i><b>12.1</b> Collid3rs</a></li>
<li class="chapter" data-level="12.2" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#post-treatment-variables-do-not-always-fit-neatly-into-one-box"><i class="fa fa-check"></i><b>12.2</b> Post-treatment variables do not always fit neatly into one box</a></li>
<li class="chapter" data-level="12.3" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#variables-measured-after-treatment-are-not-automatically-bad-controls"><i class="fa fa-check"></i><b>12.3</b> Variables measured after treatment are not automatically bad controls</a></li>
<li class="chapter" data-level="12.4" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#why-insulation_added-and-thermostat_setting_2025-play-different-roles"><i class="fa fa-check"></i><b>12.4</b> Why <code>insulation_added</code> and <code>thermostat_setting_2025</code> play different roles</a></li>
<li class="chapter" data-level="12.5" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#why-finalist_pool-or-special_review-can-be-problematic-in-more-than-one-way"><i class="fa fa-check"></i><b>12.5</b> Why <code>finalist_pool</code> or <code>special_review</code> can be problematic in more than one way</a></li>
<li class="chapter" data-level="12.6" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#a-compact-summary"><i class="fa fa-check"></i><b>12.6</b> A compact summary</a></li>
<li class="chapter" data-level="12.7" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#directed-acyclic-graphs-dags"><i class="fa fa-check"></i><b>12.7</b> Directed Acyclic Graphs (DAGs)</a></li>
<li class="chapter" data-level="12.8" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#matching"><i class="fa fa-check"></i><b>12.8</b> Matching</a></li>
<li class="chapter" data-level="12.9" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#propensity-scores-and-matching-in-the-lalonde-data"><i class="fa fa-check"></i><b>12.9</b> Propensity scores and matching in the Lalonde data</a></li>
<li class="chapter" data-level="12.10" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#bernoulli-outcomes"><i class="fa fa-check"></i><b>12.10</b> Bernoulli outcomes</a>
<ul>
<li class="chapter" data-level="12.10.1" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#rhc"><i class="fa fa-check"></i><b>12.10.1</b> <code>rhc</code></a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Regression with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="causal-inference" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Chapter 11</span> Causal Inference<a href="causal-inference.html#causal-inference" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, we begin our discussion of causal inference. We will not try to cover the subject in full here. Instead, we focus on a basic but important question: when we fit a regression model with a treatment variable, under what circumstances can we interpret the coefficient of that treatment variable causally?</p>
<p>A useful place to start is with observational data. In observational studies, the treated and untreated groups are often different before the treatment occurs. This means that a simple comparison of outcomes can mix together two things: the effect of the treatment itself, and baseline differences between the groups. Regression adjustment is one way to address this problem, but it does not solve it automatically.</p>
<p>We will work with the <code>lalonde</code> data set from the <code>MatchIt</code> package. The outcome variable is earnings in 1978 (<code>re78</code>), and the treatment variable <code>treat</code> indicates participation in a job-training program. The data also includes several pre-treatment covariates such as age, education, marital status, degree status, and earnings in 1974 and 1975.</p>
<div class="sourceCode" id="cb1243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1243-1"><a href="causal-inference.html#cb1243-1" tabindex="-1"></a><span class="fu">library</span>(MatchIt)</span>
<span id="cb1243-2"><a href="causal-inference.html#cb1243-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1243-3"><a href="causal-inference.html#cb1243-3" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1243-4"><a href="causal-inference.html#cb1243-4" tabindex="-1"></a></span>
<span id="cb1243-5"><a href="causal-inference.html#cb1243-5" tabindex="-1"></a></span>
<span id="cb1243-6"><a href="causal-inference.html#cb1243-6" tabindex="-1"></a></span>
<span id="cb1243-7"><a href="causal-inference.html#cb1243-7" tabindex="-1"></a>aa <span class="ot">&lt;-</span> MatchIt<span class="sc">::</span>lalonde <span class="sc">|&gt;</span> </span>
<span id="cb1243-8"><a href="causal-inference.html#cb1243-8" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span></code></pre></div>
<p>We begin by looking at the structure of the data.</p>
<div class="sourceCode" id="cb1244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1244-1"><a href="causal-inference.html#cb1244-1" tabindex="-1"></a>aa <span class="sc">|&gt;</span> </span>
<span id="cb1244-2"><a href="causal-inference.html#cb1244-2" tabindex="-1"></a>  <span class="fu">select</span>(treat, age, educ, married, nodegree, re74, re75, re78) <span class="sc">|&gt;</span> </span>
<span id="cb1244-3"><a href="causal-inference.html#cb1244-3" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>##      treat             age             educ          married      
##  Min.   :0.0000   Min.   :16.00   Min.   : 0.00   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:20.00   1st Qu.: 9.00   1st Qu.:0.0000  
##  Median :0.0000   Median :25.00   Median :11.00   Median :0.0000  
##  Mean   :0.3013   Mean   :27.36   Mean   :10.27   Mean   :0.4153  
##  3rd Qu.:1.0000   3rd Qu.:32.00   3rd Qu.:12.00   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :55.00   Max.   :18.00   Max.   :1.0000  
##     nodegree           re74            re75              re78        
##  Min.   :0.0000   Min.   :    0   Min.   :    0.0   Min.   :    0.0  
##  1st Qu.:0.0000   1st Qu.:    0   1st Qu.:    0.0   1st Qu.:  238.3  
##  Median :1.0000   Median : 1042   Median :  601.5   Median : 4759.0  
##  Mean   :0.6303   Mean   : 4558   Mean   : 2184.9   Mean   : 6792.8  
##  3rd Qu.:1.0000   3rd Qu.: 7888   3rd Qu.: 3249.0   3rd Qu.:10893.6  
##  Max.   :1.0000   Max.   :35040   Max.   :25142.2   Max.   :60307.9</code></pre>
<p>We start with the simplest possible regression model,</p>
<p><span class="math display">\[
\texttt{re78} = \beta_0 + \beta_1 \texttt{treat} + \varepsilon.
\]</span></p>
<p>This model compares 1978 earnings between the treated and untreated groups without adjusting for any other variables.</p>
<div class="sourceCode" id="cb1246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1246-1"><a href="causal-inference.html#cb1246-1" tabindex="-1"></a>mod_naive <span class="ot">&lt;-</span> <span class="fu">lm</span>(re78 <span class="sc">~</span> treat, <span class="at">data =</span> aa)</span>
<span id="cb1246-2"><a href="causal-inference.html#cb1246-2" tabindex="-1"></a></span>
<span id="cb1246-3"><a href="causal-inference.html#cb1246-3" tabindex="-1"></a>mod_naive <span class="sc">|&gt;</span></span>
<span id="cb1246-4"><a href="causal-inference.html#cb1246-4" tabindex="-1"></a>  <span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   term        estimate std.error statistic  p.value conf.low conf.high
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)    6984.      361.    19.4   1.64e-65    6276.     7693.
## 2 treat          -635.      657.    -0.966 3.34e- 1   -1926.      655.</code></pre>
<p>It is also useful to look at the group means directly.</p>
<div class="sourceCode" id="cb1248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1248-1"><a href="causal-inference.html#cb1248-1" tabindex="-1"></a>aa <span class="sc">|&gt;</span> </span>
<span id="cb1248-2"><a href="causal-inference.html#cb1248-2" tabindex="-1"></a>  <span class="fu">group_by</span>(treat) <span class="sc">|&gt;</span> </span>
<span id="cb1248-3"><a href="causal-inference.html#cb1248-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_re78 =</span> <span class="fu">mean</span>(re78), <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   treat mean_re78
##   &lt;int&gt;     &lt;dbl&gt;
## 1     0     6984.
## 2     1     6349.</code></pre>
<p>Note that getting the job training is not statistically significant, and the point estimate of the effect of training is <strong>negative</strong> 635 dollars. That means that the people who received traning had salaries on average <em>lower</em> than those who did not. One might conclude that the program did not help. However, this conclusion would be too quick. The data are observational, not randomized, so it is entirely possible that the treated and untreated groups differed before the program began.</p>
<div id="baseline-differences-between-the-groups" class="section level3 hasAnchor" number="11.0.1">
<h3><span class="header-section-number">11.0.1</span> Baseline Differences Between the Groups<a href="causal-inference.html#baseline-differences-between-the-groups" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To investigate this, we compare some pre-treatment covariates across the two groups.</p>
<div class="sourceCode" id="cb1250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1250-1"><a href="causal-inference.html#cb1250-1" tabindex="-1"></a>aa <span class="sc">|&gt;</span> </span>
<span id="cb1250-2"><a href="causal-inference.html#cb1250-2" tabindex="-1"></a>  <span class="fu">group_by</span>(treat) <span class="sc">|&gt;</span> </span>
<span id="cb1250-3"><a href="causal-inference.html#cb1250-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1250-4"><a href="causal-inference.html#cb1250-4" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">c</span>(age, educ, re74, re75), mean),</span>
<span id="cb1250-5"><a href="causal-inference.html#cb1250-5" tabindex="-1"></a>    <span class="at">married =</span> <span class="fu">mean</span>(married),</span>
<span id="cb1250-6"><a href="causal-inference.html#cb1250-6" tabindex="-1"></a>    <span class="at">nodegree =</span> <span class="fu">mean</span>(nodegree),</span>
<span id="cb1250-7"><a href="causal-inference.html#cb1250-7" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb1250-8"><a href="causal-inference.html#cb1250-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   treat   age  educ  re74  re75 married nodegree
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1     0  28.0  10.2 5619. 2466.   0.513    0.597
## 2     1  25.8  10.3 2096. 1532.   0.189    0.708</code></pre>
<p>We can also visualize one of the most important pre-treatment variables, namely earnings in 1975.</p>
<div class="sourceCode" id="cb1252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1252-1"><a href="causal-inference.html#cb1252-1" tabindex="-1"></a>aa <span class="sc">|&gt;</span> </span>
<span id="cb1252-2"><a href="causal-inference.html#cb1252-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">treat =</span> <span class="fu">factor</span>(treat, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Control&quot;</span>, <span class="st">&quot;Treated&quot;</span>))) <span class="sc">|&gt;</span> </span>
<span id="cb1252-3"><a href="causal-inference.html#cb1252-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treat, <span class="at">y =</span> re75)) <span class="sc">+</span></span>
<span id="cb1252-4"><a href="causal-inference.html#cb1252-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb1252-5"><a href="causal-inference.html#cb1252-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">&quot;1975 earnings&quot;</span>)</span></code></pre></div>
<p><img src="13-causal-inference_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>We see that the treated and untreated groups are not the same at baseline. In particular, prior earnings differ substantially. This matters because prior earnings are measured before treatment, and they are strongly related to later earnings. If the treated group started out at a disadvantage, then a raw treated-versus-control comparison is not isolating the effect of treatment. It is combining the effect of treatment with the fact that the treated and untreated groups were different to begin with.</p>
<p>This is the basic idea of <strong>confounding</strong>. A confounder is a variable that is related both to treatment assignment and to the outcome. Prior earnings are a natural example in this setting.</p>
<p>A natural first thing to do is to control for the observed pre-treatment covariates in a regression model. For example, we can fit</p>
<p><span class="math display">\[
\texttt{re78} = \beta_0 + \beta_1 \texttt{treat} + \beta_2 X + \varepsilon,
\]</span></p>
<p>where <span class="math inline">\(X\)</span> denotes the baseline covariates.</p>
<div class="sourceCode" id="cb1253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1253-1"><a href="causal-inference.html#cb1253-1" tabindex="-1"></a>mod_adj <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb1253-2"><a href="causal-inference.html#cb1253-2" tabindex="-1"></a>  re78 <span class="sc">~</span> treat <span class="sc">+</span> age <span class="sc">+</span> educ <span class="sc">+</span> race <span class="sc">+</span> married <span class="sc">+</span> nodegree <span class="sc">+</span> re74 <span class="sc">+</span> re75,</span>
<span id="cb1253-3"><a href="causal-inference.html#cb1253-3" tabindex="-1"></a>  <span class="at">data =</span> aa</span>
<span id="cb1253-4"><a href="causal-inference.html#cb1253-4" tabindex="-1"></a>)</span>
<span id="cb1253-5"><a href="causal-inference.html#cb1253-5" tabindex="-1"></a></span>
<span id="cb1253-6"><a href="causal-inference.html#cb1253-6" tabindex="-1"></a>mod_adj <span class="sc">|&gt;</span></span>
<span id="cb1253-7"><a href="causal-inference.html#cb1253-7" tabindex="-1"></a>  <span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 7
##    term         estimate std.error statistic     p.value   conf.low conf.high
##    &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
##  1 (Intercept) -1174.    2456.        -0.478 0.633       -5998.      3650.   
##  2 treat        1548.     781.         1.98  0.0480         13.9     3083.   
##  3 age            13.0     32.5        0.399 0.690         -50.8       76.8  
##  4 educ          404.     159.         2.54  0.0113         91.9      716.   
##  5 racehispan   1740.    1019.         1.71  0.0882       -261.      3740.   
##  6 racewhite    1241.     769.         1.61  0.107        -269.      2750.   
##  7 married       407.     695.         0.585 0.559        -959.      1772.   
##  8 nodegree      260.     847.         0.307 0.759       -1404.      1924.   
##  9 re74            0.296    0.0583     5.09  0.000000489     0.182      0.411
## 10 re75            0.232    0.105      2.21  0.0273          0.0261     0.437</code></pre>
<p>The treatment coefficient changes noticeably after adjustment. Now, it is statistically significant and <strong>positive</strong>. Our estimate is that the job training program is associated with an increase of 1548 dollars after adjusting for the other covariates.</p>
<p>Regression adjustment is therefore useful. It can remove bias due to <strong>observed</strong> baseline differences, at least when the model is doing a reasonable job of adjustment. At the same time, it is important not to say more than the model justifies. It would <strong>not</strong> be justified to say that participation in the pogram <strong>increased</strong> 1978 earnings, because that is assigning causality to the program. All we know is that it is <strong>associated</strong> with an increase after adjusting for the other covariates. In order to justify a causality claim, we would need to believe that after controlling for the observed pre-treatment covariates, the treated and untreated groups are comparable in all ways relevant to the outcome.</p>
<p>This is a much stronger claim than simply saying that we included several variables in a regression. A regression coefficient is not automatically causal just because it comes from a multiple regression model. The causal interpretation comes from the assumptions we are willing to defend.</p>
<p>A good way to summarize the distinction is the following:</p>
<ul>
<li>The naive model compares treated and untreated units directly.</li>
<li>The adjusted model compares treated and untreated units after controlling for observed baseline covariates.</li>
<li>A causal interpretation requires that this adjusted comparison be a good stand-in for the missing <em>counterfactual</em> comparison, see below for details on counterfactuals.</li>
</ul>
<p>One way to formalize the causal question is through the potential outcomes framework. For each individual <span class="math inline">\(i\)</span>, let</p>
<ul>
<li><span class="math inline">\(Y_i(1)\)</span> be the earnings that person <span class="math inline">\(i\)</span> would have if treated;</li>
<li><span class="math inline">\(Y_i(0)\)</span> be the earnings that person <span class="math inline">\(i\)</span> would have if untreated.</li>
</ul>
<p>The individual causal effect is then</p>
<p><span class="math display">\[
Y_i(1) - Y_i(0).
\]</span></p>
<p>The difficulty is that we never observe both values for the same person. If person <span class="math inline">\(i\)</span> is treated, then we observe <span class="math inline">\(Y_i(1)\)</span> but not <span class="math inline">\(Y_i(0)\)</span>. If person <span class="math inline">\(i\)</span> is untreated, then we observe <span class="math inline">\(Y_i(0)\)</span> but not <span class="math inline">\(Y_i(1)\)</span>. The observed outcome can be written as</p>
<p><span class="math display">\[
Y_i = D_iY_i(1) + (1-D_i)Y_i(0),
\]</span></p>
<p>where <span class="math inline">\(D_i\)</span> is the treatment indicator. That is, <span class="math inline">\(D_i = 1\)</span> if treatment is received and <span class="math inline">\(D_i = 0\)</span> if no treatment is received.</p>
<p>This is the fundamental problem of causal inference. For each person, one of the two relevant outcomes is missing. In observational data, we use untreated individuals as stand-ins for the missing untreated outcomes of the treated group, or treated individuals as stand-ins for the missing treated outcomes of the untreated group. The central question is whether those stand-ins are credible.</p>
<p>In the present example, the raw comparison is not especially credible because the groups differ so much at baseline. The adjusted regression is more credible, but only to the extent that the included covariates capture the important differences between the two groups. In particular, there is nothing about the multiple regression that directly tries to make the two groups comparable; if it happens, it is fortuitous.</p>
<p>Later, we will study a different way to organize this comparability problem. Rather than putting all of the adjustment into a single outcome regression, we can first ask how likely each unit was to receive treatment based on the observed pre-treatment covariates.</p>
<p>This leads to the <strong>propensity score</strong>, defined by</p>
<p><span class="math display">\[
e(X) = P(D = 1 \mid X).
\]</span></p>
<p>Here, <span class="math inline">\(X\)</span> denotes the observed pre-treatment covariates. Units with similar propensity scores have similar observed baseline characteristics, at least in the sense relevant for treatment assignment. The idea is then to compare treated and untreated units that were similarly likely to receive treatment in the first place.</p>
<p>We will not develop propensity scores fully in this section, but we can at least estimate them and inspect the results. A common first step is to fit a logistic regression for treatment.</p>
<div class="sourceCode" id="cb1255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1255-1"><a href="causal-inference.html#cb1255-1" tabindex="-1"></a>ps_mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb1255-2"><a href="causal-inference.html#cb1255-2" tabindex="-1"></a>  treat <span class="sc">~</span> age <span class="sc">+</span> educ <span class="sc">+</span> race <span class="sc">+</span> married <span class="sc">+</span> nodegree <span class="sc">+</span> re74 <span class="sc">+</span> re75,</span>
<span id="cb1255-3"><a href="causal-inference.html#cb1255-3" tabindex="-1"></a>  <span class="at">data =</span> aa,</span>
<span id="cb1255-4"><a href="causal-inference.html#cb1255-4" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>()</span>
<span id="cb1255-5"><a href="causal-inference.html#cb1255-5" tabindex="-1"></a>)</span>
<span id="cb1255-6"><a href="causal-inference.html#cb1255-6" tabindex="-1"></a></span>
<span id="cb1255-7"><a href="causal-inference.html#cb1255-7" tabindex="-1"></a>aa_ps <span class="ot">&lt;-</span> ps_mod <span class="sc">|&gt;</span></span>
<span id="cb1255-8"><a href="causal-inference.html#cb1255-8" tabindex="-1"></a>  <span class="fu">augment</span>(<span class="at">data =</span> aa, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1255-9"><a href="causal-inference.html#cb1255-9" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1255-10"><a href="causal-inference.html#cb1255-10" tabindex="-1"></a>    <span class="at">treat =</span> <span class="fu">factor</span>(treat, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Control&quot;</span>, <span class="st">&quot;Treated&quot;</span>))</span>
<span id="cb1255-11"><a href="causal-inference.html#cb1255-11" tabindex="-1"></a>  )</span>
<span id="cb1255-12"><a href="causal-inference.html#cb1255-12" tabindex="-1"></a></span>
<span id="cb1255-13"><a href="causal-inference.html#cb1255-13" tabindex="-1"></a>ps_mod <span class="sc">|&gt;</span></span>
<span id="cb1255-14"><a href="causal-inference.html#cb1255-14" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 9 × 5
##   term          estimate std.error statistic  p.value
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept) -1.66      0.971         -1.71 8.67e- 2
## 2 age          0.0158    0.0136         1.16 2.45e- 1
## 3 educ         0.161     0.0651         2.48 1.33e- 2
## 4 racehispan  -2.08      0.367         -5.67 1.44e- 8
## 5 racewhite   -3.07      0.287        -10.7  1.03e-26
## 6 married     -0.832     0.290         -2.87 4.15e- 3
## 7 nodegree     0.707     0.338          2.09 3.62e- 2
## 8 re74        -0.0000718 0.0000287     -2.50 1.25e- 2
## 9 re75         0.0000534 0.0000463      1.15 2.49e- 1</code></pre>
<p>We can now look at the estimated propensity scores by treatment group.</p>
<div class="sourceCode" id="cb1257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1257-1"><a href="causal-inference.html#cb1257-1" tabindex="-1"></a>aa_ps <span class="sc">|&gt;</span> </span>
<span id="cb1257-2"><a href="causal-inference.html#cb1257-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">fill =</span> treat)) <span class="sc">+</span></span>
<span id="cb1257-3"><a href="causal-inference.html#cb1257-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">position =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb1257-4"><a href="causal-inference.html#cb1257-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Estimated propensity score&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>, <span class="at">fill =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="13-causal-inference_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The plot is not itself a causal analysis, but it begins to show us something that the outcome regression did not show directly: how much overlap there is between the treated and untreated groups on the observed baseline covariates. Later, this idea of overlap will become central. In this particular plot, notice that there is not a lot of overlap between control and treated in the low propensity score group. This means that there is some combination of covariates which almost uniformly led participants not to get job training. That is somewhat bad news for causal analysis in general, and certainly should lead to hesitancy in interpreting the multiple regression output causally. We expect to see some predictive power of the covariates on whether the treatment was received, but we are hoping to still see significant overlap for our causal analysis. There are techniques for dealing with data like this which we will discuss in later sections.</p>
</div>
<div id="summary" class="section level3 hasAnchor" number="11.0.2">
<h3><span class="header-section-number">11.0.2</span> Summary<a href="causal-inference.html#summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This section makes three points.</p>
<p>First, a simple regression of outcome on treatment can be misleading in observational data because treated and untreated groups often differ before treatment occurs.</p>
<p>Second, regression adjustment can account for observed baseline differences and can change the treatment estimate substantially. In the job-training example, this is exactly what happens.</p>
<p>Third, even an adjusted regression is not automatically causal. The causal interpretation requires additional assumptions about comparability between the treated and untreated groups after adjustment.</p>
<p>Propensity scores give us another way to think about that comparability. They do not remove the need for assumptions, but they make the adjustment problem more explicit. In the next part of our causal inference discussion, we will use them to study matching and related methods.</p>
</div>
<div id="identification-assumptions-for-causal-adjustment" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> Identification Assumptions for Causal Adjustment<a href="causal-inference.html#identification-assumptions-for-causal-adjustment" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous section, we saw that a naive regression of later earnings on treatment in the Lalonde data gave a different answer than a regression that adjusted for observed baseline covariates. That already tells us something important: the treated and control groups were different before treatment. In observational work, that is the rule rather than the exception.</p>
<p>The next question is the more important one. When does an adjusted comparison deserve a causal interpretation? Regression adjustment can be part of a causal analysis, but the causal interpretation does not come from the software output. It comes from the assumptions that justify using treated and untreated units as stand-ins for one another’s missing counterfactual outcomes.</p>
<p>Throughout this section, we continue to use the Lalonde job-training data. The treatment is participation in the job-training program, and the outcome is earnings in 1978.</p>
<div class="sourceCode" id="cb1258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1258-1"><a href="causal-inference.html#cb1258-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1258-2"><a href="causal-inference.html#cb1258-2" tabindex="-1"></a><span class="fu">library</span>(MatchIt)</span>
<span id="cb1258-3"><a href="causal-inference.html#cb1258-3" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1258-4"><a href="causal-inference.html#cb1258-4" tabindex="-1"></a></span>
<span id="cb1258-5"><a href="causal-inference.html#cb1258-5" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;lalonde&quot;</span>)</span>
<span id="cb1258-6"><a href="causal-inference.html#cb1258-6" tabindex="-1"></a></span>
<span id="cb1258-7"><a href="causal-inference.html#cb1258-7" tabindex="-1"></a></span>
<span id="cb1258-8"><a href="causal-inference.html#cb1258-8" tabindex="-1"></a>aa <span class="ot">&lt;-</span> lalonde <span class="sc">|&gt;</span></span>
<span id="cb1258-9"><a href="causal-inference.html#cb1258-9" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb1258-10"><a href="causal-inference.html#cb1258-10" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1258-11"><a href="causal-inference.html#cb1258-11" tabindex="-1"></a>    <span class="at">treat =</span> <span class="fu">factor</span>(treat, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Control&quot;</span>, <span class="st">&quot;Treated&quot;</span>)),</span>
<span id="cb1258-12"><a href="causal-inference.html#cb1258-12" tabindex="-1"></a>    <span class="at">race =</span> <span class="fu">factor</span>(race),</span>
<span id="cb1258-13"><a href="causal-inference.html#cb1258-13" tabindex="-1"></a>    <span class="at">married =</span> <span class="fu">factor</span>(married, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)),</span>
<span id="cb1258-14"><a href="causal-inference.html#cb1258-14" tabindex="-1"></a>    <span class="at">nodegree =</span> <span class="fu">factor</span>(nodegree, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span>
<span id="cb1258-15"><a href="causal-inference.html#cb1258-15" tabindex="-1"></a>  )</span></code></pre></div>
<p>We will use the following observed pre-treatment covariates throughout this section:</p>
<ul>
<li><code>age</code></li>
<li><code>educ</code></li>
<li>`race``</li>
<li><code>married</code></li>
<li><code>nodegree</code></li>
<li><code>re74</code></li>
<li><code>re75</code></li>
</ul>
<div id="assumptions-for-causal-adjustment" class="section level3 hasAnchor" number="11.1.1">
<h3><span class="header-section-number">11.1.1</span> Assumptions for Causal Adjustment<a href="causal-inference.html#assumptions-for-causal-adjustment" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We continue to write the potential outcomes for person <span class="math inline">\(i\)</span> as <span class="math inline">\(Y_i(1)\)</span> and <span class="math inline">\(Y_i(0)\)</span>, where these represent that person’s 1978 earnings under treatment and under control, respectively. The observed outcome is</p>
<p><span class="math display">\[
Y_i = D_iY_i(1) + (1-D_i)Y_i(0).
\]</span></p>
<p>This is the formal statement of <strong>consistency</strong>. If a person is treated, then the observed outcome is the treated potential outcome; if a person is untreated, then the observed outcome is the untreated potential outcome. This sounds automatic, but it depends on the treatment being defined clearly enough that <span class="math inline">\(Y(1)\)</span> and <span class="math inline">\(Y(0)\)</span> are meaningful. If the treatment were simply coded as “exercise,” then the treated condition might bundle together walking, weight lifting, marathon training, yoga, and many other interventions. In that situation, the meaning of <span class="math inline">\(Y(1)\)</span> becomes murky. Likewise, if “job training” bundled together many radically different programs, then the treated potential outcome would be less clearly defined.</p>
<p>The most important assumption in observational work is <strong>ignorability</strong>:</p>
<p><span class="math display">\[
(Y(1), Y(0)) \perp D \mid X.
\]</span></p>
<p>In words, after conditioning on the observed pre-treatment covariates <span class="math inline">\(X\)</span>, treatment assignment is independent of the potential outcomes. A slightly more informal version is often easier to remember: once we control for the relevant observed pre-treatment variables, treated and untreated units are comparable on average. This assumption is also called <strong>no unmeasured confounding</strong> or <strong>selection on observables</strong>.</p>
<p>It is important to be clear about what ignorability does and does not say. It does not say that treatment is random in the raw data. It says that treatment is <em>as if random after conditioning on the chosen covariates</em>. That is why the choice of covariates matters so much.</p>
<p>This connects directly to the informal <strong>backdoor idea</strong>. If a variable is a common cause of treatment and outcome, then failing to adjust for it creates a noncausal association between treatment and outcome. In the Lalonde data, prior earnings are a natural example. Someone’s 1975 earnings may affect whether they enter the training program, and 1975 earnings will also help predict 1978 earnings. In that case, <code>re75</code> is a confounder, and adjusting for it blocks a noncausal path between treatment and outcome.</p>
<p>A third important assumption is <strong>positivity</strong>, sometimes called <strong>overlap</strong>:</p>
<p><span class="math display">\[
0 &lt; P(D = 1 \mid X = x) &lt; 1
\]</span></p>
<p>for the values of <span class="math inline">\(x\)</span> we care about. In plain language, this means that for covariate profiles of interest, there must be some chance of both treatment and control. If units with certain covariates are always treated, or always untreated, then we do not have comparable treated and control units in that part of the covariate space. In practice, this means that causal adjustment requires overlap. No overlap means no apples-to-apples comparison.</p>
<p>A final assumption that is worth stating <strong>no interference</strong>. One person’s treatment should not directly affect another person’s outcome. In the job-training setting, this could fail if treated and untreated workers are competing for the same jobs in the same market. We will not focus on interference in this chapter, but it is worth keeping in mind.</p>
<p>These assumptions help explain why regression is not the opposite of causal inference. Regression is one tool that causal inference can use. The causal interpretation depends on whether the regression is implementing a defensible comparison.</p>
<p>There is one more practical point to make before returning to the Lalonde data. A good control is generally a variable measured before treatment that affects both treatment assignment and the outcome. A bad control is a variable that is downstream of treatment or a collider. For example, if a job-search intervention improves later mental health partly by increasing job-search confidence, then controlling for job-search confidence would remove part of the very treatment effect we are trying to estimate. If the goal is the total effect of treatment, post-treatment mediators are bad controls.</p>
<p>The <code>jobs</code> data in the <code>mediation</code> package give a nice example. The treatment variable is <code>treat</code>, the outcome is <code>depress2</code>, and <code>job_seek</code> is a plausible post-treatment mediator. In the code below, the third model adds <code>job_seek</code> after treatment has already occurred.</p>
<div class="sourceCode" id="cb1259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1259-1"><a href="causal-inference.html#cb1259-1" tabindex="-1"></a>jobs2 <span class="ot">&lt;-</span> mediation<span class="sc">::</span>jobs <span class="sc">|&gt;</span></span>
<span id="cb1259-2"><a href="causal-inference.html#cb1259-2" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span>
<span id="cb1259-3"><a href="causal-inference.html#cb1259-3" tabindex="-1"></a></span>
<span id="cb1259-4"><a href="causal-inference.html#cb1259-4" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(depress2 <span class="sc">~</span> treat, <span class="at">data =</span> jobs2)</span>
<span id="cb1259-5"><a href="causal-inference.html#cb1259-5" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(depress2 <span class="sc">~</span> treat <span class="sc">+</span> econ_hard <span class="sc">+</span> sex <span class="sc">+</span> age, <span class="at">data =</span> jobs2)</span>
<span id="cb1259-6"><a href="causal-inference.html#cb1259-6" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(depress2 <span class="sc">~</span> treat <span class="sc">+</span> econ_hard <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> job_seek, <span class="at">data =</span> jobs2)</span>
<span id="cb1259-7"><a href="causal-inference.html#cb1259-7" tabindex="-1"></a></span>
<span id="cb1259-8"><a href="causal-inference.html#cb1259-8" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb1259-9"><a href="causal-inference.html#cb1259-9" tabindex="-1"></a>  <span class="fu">tidy</span>(mod1) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">&quot;Treatment only&quot;</span>),</span>
<span id="cb1259-10"><a href="causal-inference.html#cb1259-10" tabindex="-1"></a>  <span class="fu">tidy</span>(mod2) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">&quot;Baseline controls&quot;</span>),</span>
<span id="cb1259-11"><a href="causal-inference.html#cb1259-11" tabindex="-1"></a>  <span class="fu">tidy</span>(mod3) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">&quot;Adds post-treatment variable&quot;</span>)</span>
<span id="cb1259-12"><a href="causal-inference.html#cb1259-12" tabindex="-1"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb1259-13"><a href="causal-inference.html#cb1259-13" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;treat&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1259-14"><a href="causal-inference.html#cb1259-14" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(model, estimate, std.error, statistic, p.value)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   model                        estimate std.error statistic p.value
##   &lt;chr&gt;                           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 Treatment only                -0.0633    0.0461    -1.37    0.170
## 2 Baseline controls             -0.0560    0.0452    -1.24    0.215
## 3 Adds post-treatment variable  -0.0403    0.0435    -0.926   0.355</code></pre>
<p>When the coefficient on treatment changes after <code>job_seek</code> is added, that is not automatically an improvement. If <code>job_seek</code> lies on the causal pathway from treatment to the outcome, then controlling for it changes the estimand. This is why “control for everything” is not safe advice.</p>
</div>
<div id="the-lalonde-data-revisited" class="section level3 hasAnchor" number="11.1.2">
<h3><span class="header-section-number">11.1.2</span> The Lalonde Data Revisited<a href="causal-inference.html#the-lalonde-data-revisited" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We return now to the Lalonde data. The first thing to notice is that the treated and control groups differ on several observed pre-treatment covariates.</p>
<div class="sourceCode" id="cb1261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1261-1"><a href="causal-inference.html#cb1261-1" tabindex="-1"></a>aa <span class="sc">|&gt;</span></span>
<span id="cb1261-2"><a href="causal-inference.html#cb1261-2" tabindex="-1"></a>  <span class="fu">group_by</span>(treat) <span class="sc">|&gt;</span></span>
<span id="cb1261-3"><a href="causal-inference.html#cb1261-3" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb1261-4"><a href="causal-inference.html#cb1261-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb1261-5"><a href="causal-inference.html#cb1261-5" tabindex="-1"></a>    <span class="at">age =</span> <span class="fu">mean</span>(age),</span>
<span id="cb1261-6"><a href="causal-inference.html#cb1261-6" tabindex="-1"></a>    <span class="at">educ =</span> <span class="fu">mean</span>(educ),</span>
<span id="cb1261-7"><a href="causal-inference.html#cb1261-7" tabindex="-1"></a>    <span class="at">re74 =</span> <span class="fu">mean</span>(re74),</span>
<span id="cb1261-8"><a href="causal-inference.html#cb1261-8" tabindex="-1"></a>    <span class="at">re75 =</span> <span class="fu">mean</span>(re75),</span>
<span id="cb1261-9"><a href="causal-inference.html#cb1261-9" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb1261-10"><a href="causal-inference.html#cb1261-10" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 6
##   treat       n   age  educ  re74  re75
##   &lt;fct&gt;   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Control   429  28.0  10.2 5619. 2466.
## 2 Treated   185  25.8  10.3 2096. 1532.</code></pre>
<div class="sourceCode" id="cb1263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1263-1"><a href="causal-inference.html#cb1263-1" tabindex="-1"></a>aa <span class="sc">|&gt;</span></span>
<span id="cb1263-2"><a href="causal-inference.html#cb1263-2" tabindex="-1"></a>  <span class="fu">group_by</span>(treat) <span class="sc">|&gt;</span></span>
<span id="cb1263-3"><a href="causal-inference.html#cb1263-3" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb1263-4"><a href="causal-inference.html#cb1263-4" tabindex="-1"></a>    <span class="at">percent_black =</span> <span class="fu">mean</span>(race <span class="sc">==</span> <span class="st">&quot;black&quot;</span>),</span>
<span id="cb1263-5"><a href="causal-inference.html#cb1263-5" tabindex="-1"></a>    <span class="at">percent_hispanic =</span> <span class="fu">mean</span>(race <span class="sc">==</span> <span class="st">&quot;hispan&quot;</span>),</span>
<span id="cb1263-6"><a href="causal-inference.html#cb1263-6" tabindex="-1"></a>    <span class="at">percent_white =</span> <span class="fu">mean</span>(race <span class="sc">==</span> <span class="st">&quot;white&quot;</span>),</span>
<span id="cb1263-7"><a href="causal-inference.html#cb1263-7" tabindex="-1"></a>    <span class="at">married =</span> <span class="fu">mean</span>(married <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span>),</span>
<span id="cb1263-8"><a href="causal-inference.html#cb1263-8" tabindex="-1"></a>    <span class="at">nodegree =</span> <span class="fu">mean</span>(nodegree <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span>),</span>
<span id="cb1263-9"><a href="causal-inference.html#cb1263-9" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb1263-10"><a href="causal-inference.html#cb1263-10" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 6
##   treat   percent_black percent_hispanic percent_white married nodegree
##   &lt;fct&gt;           &lt;dbl&gt;            &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1 Control         0.203           0.142         0.655    0.513    0.597
## 2 Treated         0.843           0.0595        0.0973   0.189    0.708</code></pre>
<p>These are all pre-treatment variables, so differences here are a warning sign for confounding rather than an effect of treatment. In particular, prior earnings differ between the groups, and prior earnings are highly relevant for later earnings.</p>
<p>We can see again that the naive and adjusted regressions tell different stories.</p>
<div class="sourceCode" id="cb1265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1265-1"><a href="causal-inference.html#cb1265-1" tabindex="-1"></a>mod_naive <span class="ot">&lt;-</span> <span class="fu">lm</span>(re78 <span class="sc">~</span> treat, <span class="at">data =</span> aa)</span>
<span id="cb1265-2"><a href="causal-inference.html#cb1265-2" tabindex="-1"></a></span>
<span id="cb1265-3"><a href="causal-inference.html#cb1265-3" tabindex="-1"></a>mod_adj <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb1265-4"><a href="causal-inference.html#cb1265-4" tabindex="-1"></a>  re78 <span class="sc">~</span> treat <span class="sc">+</span> age <span class="sc">+</span> educ <span class="sc">+</span> race <span class="sc">+</span> married <span class="sc">+</span> nodegree <span class="sc">+</span> re74 <span class="sc">+</span> re75,</span>
<span id="cb1265-5"><a href="causal-inference.html#cb1265-5" tabindex="-1"></a>  <span class="at">data =</span> aa</span>
<span id="cb1265-6"><a href="causal-inference.html#cb1265-6" tabindex="-1"></a>)</span>
<span id="cb1265-7"><a href="causal-inference.html#cb1265-7" tabindex="-1"></a></span>
<span id="cb1265-8"><a href="causal-inference.html#cb1265-8" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb1265-9"><a href="causal-inference.html#cb1265-9" tabindex="-1"></a>  <span class="fu">tidy</span>(mod_naive, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">&quot;Naive&quot;</span>),</span>
<span id="cb1265-10"><a href="causal-inference.html#cb1265-10" tabindex="-1"></a>  <span class="fu">tidy</span>(mod_adj, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">&quot;Adjusted&quot;</span>)</span>
<span id="cb1265-11"><a href="causal-inference.html#cb1265-11" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb1265-12"><a href="causal-inference.html#cb1265-12" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;treatTreated&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1265-13"><a href="causal-inference.html#cb1265-13" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(model, estimate, conf.low, conf.high, p.value)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   model    estimate conf.low conf.high p.value
##   &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 Naive       -635.  -1926.       655.  0.334 
## 2 Adjusted    1548.     13.9     3083.  0.0480</code></pre>
<p>The sign change is a strong indication that the raw treatment comparison was confounded by observed baseline differences. This does not prove that the adjusted model is causal, but it does show that adjustment matters.</p>
<p>It is useful to visualize overlap directly. We start with one important pre-treatment covariate, 1975 earnings.</p>
<div class="sourceCode" id="cb1267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1267-1"><a href="causal-inference.html#cb1267-1" tabindex="-1"></a><span class="fu">ggplot</span>(aa, <span class="fu">aes</span>(<span class="at">x =</span> re75, <span class="at">fill =</span> treat)) <span class="sc">+</span></span>
<span id="cb1267-2"><a href="causal-inference.html#cb1267-2" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb1267-3"><a href="causal-inference.html#cb1267-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;1975 earnings&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>, <span class="at">fill =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="13-causal-inference_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Where the two distributions overlap, comparison is more plausible. Where they are far apart, adjustment begins to rely on extrapolation. This same idea can be summarized more compactly by the <strong>propensity score</strong>, which we define as</p>
<p><span class="math display">\[
e(X) = P(D = 1 \mid X).
\]</span></p>
<p>For now, we use the propensity score only as a way to study overlap. We estimate it with logistic regression using the observed pre-treatment covariates.</p>
<div class="sourceCode" id="cb1268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1268-1"><a href="causal-inference.html#cb1268-1" tabindex="-1"></a>ps_mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb1268-2"><a href="causal-inference.html#cb1268-2" tabindex="-1"></a>  treat <span class="sc">~</span> age <span class="sc">+</span> educ <span class="sc">+</span> race <span class="sc">+</span> married <span class="sc">+</span> nodegree <span class="sc">+</span> re74 <span class="sc">+</span> re75,</span>
<span id="cb1268-3"><a href="causal-inference.html#cb1268-3" tabindex="-1"></a>  <span class="at">data =</span> aa,</span>
<span id="cb1268-4"><a href="causal-inference.html#cb1268-4" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>()</span>
<span id="cb1268-5"><a href="causal-inference.html#cb1268-5" tabindex="-1"></a>)</span>
<span id="cb1268-6"><a href="causal-inference.html#cb1268-6" tabindex="-1"></a></span>
<span id="cb1268-7"><a href="causal-inference.html#cb1268-7" tabindex="-1"></a>aa_ps <span class="ot">&lt;-</span> ps_mod <span class="sc">|&gt;</span></span>
<span id="cb1268-8"><a href="causal-inference.html#cb1268-8" tabindex="-1"></a>  <span class="fu">augment</span>(<span class="at">data =</span> aa, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1268-9"><a href="causal-inference.html#cb1268-9" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps =</span> .fitted) <span class="sc">|&gt;</span></span>
<span id="cb1268-10"><a href="causal-inference.html#cb1268-10" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>.fitted)</span></code></pre></div>
<p>Now we look at the distributions of the estimated propensity scores in the treated and control groups.</p>
<div class="sourceCode" id="cb1269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1269-1"><a href="causal-inference.html#cb1269-1" tabindex="-1"></a><span class="fu">ggplot</span>(aa_ps, <span class="fu">aes</span>(<span class="at">x =</span> ps, <span class="at">fill =</span> treat)) <span class="sc">+</span></span>
<span id="cb1269-2"><a href="causal-inference.html#cb1269-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb1269-3"><a href="causal-inference.html#cb1269-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Estimated propensity score&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>, <span class="at">fill =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="13-causal-inference_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The treated units tend to have higher estimated probabilities of treatment than the control units. This is the expected direction. The issue is not that the graph is backwards. The issue is that the groups may be too separated. Good causal adjustment needs overlap, not simply a treatment model that predicts treatment well. If treated and control units have little overlap in propensity score, then there are few comparable units to compare.</p>
<p>This is the main reason to introduce propensity scores in the first place. Regression adjustment hides the comparability problem inside a single coefficient. Propensity scores make it easier to inspect whether treated and untreated units are similar on the observed pre-treatment covariates and whether common support is adequate.</p>
<p>The big lesson from this section is that adjusted comparisons only deserve a causal interpretation under assumptions. Consistency tells us that the treatment must be defined clearly enough for the potential outcomes to make sense. Ignorability says that after conditioning on the observed pre-treatment covariates, treatment assignment is as good as random. Positivity says that comparable treated and control units must exist. Finally, the discussion of bad controls reminds us that adjustment can go wrong when we condition on variables that are affected by treatment. The next section uses propensity scores more directly to organize causal comparisons in observational data.</p>
</div>
<div id="vocabulary-and-an-example" class="section level3 hasAnchor" number="11.1.3">
<h3><span class="header-section-number">11.1.3</span> Vocabulary and an Example<a href="causal-inference.html#vocabulary-and-an-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In causal inference, we imagine that each unit has more than one possible outcome. For a household in the <code>retrofit</code> study, one outcome is the amount of gas it would use if it received the retrofit, and another is the amount it would use if it did not. These are called the <strong>potential outcomes</strong>. We never observe both outcomes for the same household, which is why causal inference is difficult in the first place. The whole enterprise is an attempt to learn something about the missing counterfactual outcome from the data we do observe.</p>
<p><strong>Consistency</strong> says that the observed outcome under the treatment actually received is the corresponding potential outcome. If a household received the retrofit, then its observed gas use is its treated potential outcome; if it did not, then its observed gas use is its untreated potential outcome. This sounds automatic, but it depends on the treatment being defined clearly enough that the phrase “received the retrofit” has a reasonably stable meaning. If treated households received wildly different interventions, then the treated potential outcome <span class="math inline">\(Y(1)\)</span> would be less clearly defined.</p>
<p><strong>Ignorability</strong> means that after we condition on the observed pre-treatment covariates, treatment assignment is independent of the potential outcomes. In practice, this is the assumption that after adjusting for the right observed baseline variables, treated and untreated units are comparable on average. This is also called <strong>no unmeasured confounding</strong> or <strong>selection on observables</strong>. It is the key assumption that turns an adjusted observational comparison into a candidate causal estimate.</p>
<p>A <strong>confounder</strong> is a variable that affects both treatment assignment and the outcome. Confounders are the reason naive treated-versus-control comparisons can be misleading. A good confounder to keep in mind is a variable that helps explain both who receives treatment and what the outcome would have looked like anyway. In the <code>retrofit</code> example, prior gas use is a natural candidate because households with high prior gas use may be more likely to receive the retrofit and also more likely to have high future gas use.</p>
<p>The informal <strong>backdoor idea</strong> is a way to think about confounding without too much notation. If a variable is a common cause of treatment and outcome, then it creates a noncausal path between them. Adjusting for that variable blocks that path. This gives a practical way to think about which variables belong in an adjustment set: we look for pre-treatment variables that help explain why treated and untreated units differ before treatment begins.</p>
<p><strong>Positivity</strong>, also called <strong>overlap</strong>, means that for the covariate values we care about, there must be some chance of both treatment and control. In plain language, the treated and untreated groups must actually contain comparable units. Even if we measure many sensible covariates, a causal analysis becomes difficult if some kinds of units are almost always treated and others are almost always untreated. Lack of overlap is not something that adjustment can solve; it is a limitation of the data.</p>
<p>A <strong>propensity score</strong> is the probability of treatment given the observed pre-treatment covariates. It summarizes many baseline covariates into a single number that describes how likely treatment was, based on what we observed before treatment began. Propensity scores do not remove unmeasured confounding, but they are useful for checking overlap and organizing comparisons among units that look similar on the observed covariates.</p>
<p>A <strong>mediator</strong> is a variable that lies on the causal pathway from treatment to outcome. Mediators are important if we want to understand <em>how</em> treatment works, but they are usually bad controls if the goal is the <strong>total effect</strong> of treatment. Controlling for a mediator blocks part of the very effect we are trying to estimate.</p>
<p>A <strong>collider</strong> is a variable that is caused by two other variables. Conditioning on a collider can create a spurious association between those causes, which is why colliders are bad controls. This is different from the mediator problem. A mediator is bad because it blocks part of a real causal effect. A collider is bad because conditioning on it can open a false path and induce bias. Note that often a collider is caused by one variable in the data (such as treatment) and one unmeasured variable (such as organization or motivation). Colliders can be hard to see, but it is important not to condition on them.</p>
<p>A <strong>bad control</strong> is a variable that should not be conditioned on in a causal analysis. Two common kinds of bad controls are mediators and colliders. The main lesson is that “control for everything” is not a safe rule. Some variables help create comparability; others distort the comparison.</p>
<p>One last idea is that of <strong>no interference</strong>: one unit’s treatment should not directly affect another unit’s outcome. In the <code>retrofit</code> study, this would mean that one household’s retrofit does not directly change another household’s gas use.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="missing-data-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-retrofit-study.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
