<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Classical Theory of Simple Linear Regression | Applied Regression with R</title>
  <meta name="description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Classical Theory of Simple Linear Regression | Applied Regression with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Classical Theory of Simple Linear Regression | Applied Regression with R" />
  
  <meta name="twitter:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

<meta name="author" content="Darrin Speegle" />


<meta name="date" content="2026-04-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
<link rel="prev" href="index.html"/>
<link rel="next" href="multiple-linear-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Regression with R<br />&nbsp; Notes From STAT 4870/5087</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="classicaltheory.html"><a href="classicaltheory.html"><i class="fa fa-check"></i><b>2</b> Classical Theory of Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="classicaltheory.html"><a href="classicaltheory.html#review"><i class="fa fa-check"></i><b>2.1</b> Review</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-means-and-standard-deviations"><i class="fa fa-check"></i><b>2.1.1</b> Estimating Means and standard deviations</a></li>
<li class="chapter" data-level="2.1.2" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-the-density-of-an-rv"><i class="fa fa-check"></i><b>2.1.2</b> Estimating the density of an rv</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-overview"><i class="fa fa-check"></i><b>2.2</b> Linear Regression Overview</a></li>
<li class="chapter" data-level="2.3" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-with-no-intercept"><i class="fa fa-check"></i><b>2.3</b> Linear Regression with no intercept</a></li>
<li class="chapter" data-level="2.4" data-path="classicaltheory.html"><a href="classicaltheory.html#the-full-model"><i class="fa fa-check"></i><b>2.4</b> The full model</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="classicaltheory.html"><a href="classicaltheory.html#hypothesis-test-interlude"><i class="fa fa-check"></i><b>2.4.1</b> Hypothesis Test Interlude</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="classicaltheory.html"><a href="classicaltheory.html#using-different-loss-functions"><i class="fa fa-check"></i><b>2.5</b> Using different loss functions</a></li>
<li class="chapter" data-level="" data-path="classicaltheory.html"><a href="classicaltheory.html#vignette-a-dplyr-primer"><i class="fa fa-check"></i>Vignette: A dplyr primer</a></li>
<li class="chapter" data-level="2.6" data-path="classicaltheory.html"><a href="classicaltheory.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#anova"><i class="fa fa-check"></i><b>3.0.1</b> Aside on multiple R squared and ANOVA</a></li>
<li class="chapter" data-level="3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-variable-selection-anova"><i class="fa fa-check"></i><b>3.1</b> More Variable Selection: ANOVA</a></li>
<li class="chapter" data-level="3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#predictions"><i class="fa fa-check"></i><b>3.2</b> Predictions</a></li>
<li class="chapter" data-level="3.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#using-aic"><i class="fa fa-check"></i><b>3.3</b> Using AIC</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#likelihood-functions"><i class="fa fa-check"></i><b>3.3.1</b> Likelihood functions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercises-1"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html"><i class="fa fa-check"></i><b>4</b> Intro to Predictive Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#comparingtwomodels"><i class="fa fa-check"></i><b>4.1</b> Comparing Two Models</a></li>
<li class="chapter" data-level="4.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#a-brief-return-to-inference"><i class="fa fa-check"></i><b>4.2</b> A Brief Return to Inference</a></li>
<li class="chapter" data-level="4.3" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#simulations-of-expected-mse"><i class="fa fa-check"></i><b>4.3</b> Simulations of Expected MSE</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-and-bias-variance-tradeoff"><i class="fa fa-check"></i><b>4.3.1</b> Estimating MSE and Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-for-new-predictors-uniformly-sampled"><i class="fa fa-check"></i><b>4.3.2</b> Estimating MSE for new predictors uniformly sampled</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>4.4</b> Bias Variance Trade-off</a></li>
<li class="chapter" data-level="4.5" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#exercises-2"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html"><i class="fa fa-check"></i><b>5</b> Regression Predictive Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#preprocessing"><i class="fa fa-check"></i><b>5.1</b> Preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#missing-data"><i class="fa fa-check"></i><b>5.2</b> Missing Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#predicting-when-a-level-is-missing-from-the-training-set"><i class="fa fa-check"></i><b>5.2.1</b> Predicting when a level is missing from the training set</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#correlated-predictors"><i class="fa fa-check"></i><b>5.3</b> Correlated Predictors</a></li>
<li class="chapter" data-level="5.4" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#aside-on-pca"><i class="fa fa-check"></i><b>5.4</b> Aside on PCA</a></li>
<li class="chapter" data-level="5.5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#johnson-lindenstrauss-dimension-reduction"><i class="fa fa-check"></i><b>5.5</b> Johnson-Lindenstrauss Dimension Reduction</a></li>
<li class="chapter" data-level="5.6" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#exercises-3"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variable-selection.html"><a href="variable-selection.html"><i class="fa fa-check"></i><b>6</b> Variable Selection</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variable-selection.html"><a href="variable-selection.html#partial-least-squares"><i class="fa fa-check"></i><b>6.1</b> Partial Least Squares</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="variable-selection.html"><a href="variable-selection.html#optional-pls-stuff"><i class="fa fa-check"></i><b>6.1.1</b> Optional PLS Stuff</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variable-selection.html"><a href="variable-selection.html#ridgelasso-and-elastic-net"><i class="fa fa-check"></i><b>6.2</b> Ridge/Lasso and Elastic Net</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="variable-selection.html"><a href="variable-selection.html#ridge-regression"><i class="fa fa-check"></i><b>6.2.1</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.2.2" data-path="variable-selection.html"><a href="variable-selection.html#lasso"><i class="fa fa-check"></i><b>6.2.2</b> LASSO</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variable-selection.html"><a href="variable-selection.html#step-aic"><i class="fa fa-check"></i><b>6.3</b> Step AIC</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="variable-selection.html"><a href="variable-selection.html#doing-lgocv-with-preprocessing"><i class="fa fa-check"></i><b>6.3.1</b> Doing LGOCV with preprocessing</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variable-selection.html"><a href="variable-selection.html#interactions"><i class="fa fa-check"></i><b>6.4</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>7</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#logistic-regression"><i class="fa fa-check"></i><b>7.1</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#malaria-example-intro"><i class="fa fa-check"></i><b>7.1.1</b> Malaria Example (Intro)</a></li>
<li class="chapter" data-level="7.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#the-model-theory"><i class="fa fa-check"></i><b>7.1.2</b> The model (theory)</a></li>
<li class="chapter" data-level="7.1.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#estimating-parameters-using-mle"><i class="fa fa-check"></i><b>7.1.3</b> Estimating parameters using MLE</a></li>
<li class="chapter" data-level="7.1.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#estimating-parameters-via-loss-function"><i class="fa fa-check"></i><b>7.1.4</b> Estimating parameters via loss function</a></li>
<li class="chapter" data-level="7.1.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#interpreting-summary"><i class="fa fa-check"></i><b>7.1.5</b> Interpreting summary</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#mixed-effects-logistic-regression"><i class="fa fa-check"></i><b>7.2</b> Mixed Effects Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#nested-random-effects"><i class="fa fa-check"></i><b>7.2.1</b> Nested random effects</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#count-regression"><i class="fa fa-check"></i><b>7.3</b> Count Regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#mixed-effects-model"><i class="fa fa-check"></i><b>7.3.1</b> Mixed Effects Model</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#offsets"><i class="fa fa-check"></i><b>7.4</b> Offsets</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="lecture-notes.html"><a href="lecture-notes.html"><i class="fa fa-check"></i><b>8</b> Lecture Notes</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lecture-notes.html"><a href="lecture-notes.html#january-27"><i class="fa fa-check"></i><b>8.1</b> January 27</a></li>
<li class="chapter" data-level="8.2" data-path="lecture-notes.html"><a href="lecture-notes.html#february-3"><i class="fa fa-check"></i><b>8.2</b> February 3</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="lecture-notes.html"><a href="lecture-notes.html#simulating-data"><i class="fa fa-check"></i><b>8.2.1</b> Simulating Data</a></li>
<li class="chapter" data-level="8.2.2" data-path="lecture-notes.html"><a href="lecture-notes.html#building-models"><i class="fa fa-check"></i><b>8.2.2</b> Building Models</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="lecture-notes.html"><a href="lecture-notes.html#february-5"><i class="fa fa-check"></i><b>8.3</b> February 5</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="lecture-notes.html"><a href="lecture-notes.html#using-broomaugment"><i class="fa fa-check"></i><b>8.3.1</b> Using <code>broom::augment</code></a></li>
<li class="chapter" data-level="8.3.2" data-path="lecture-notes.html"><a href="lecture-notes.html#multicollinearity"><i class="fa fa-check"></i><b>8.3.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="lecture-notes.html"><a href="lecture-notes.html#february-10"><i class="fa fa-check"></i><b>8.4</b> February 10</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="lecture-notes.html"><a href="lecture-notes.html#anova-models"><i class="fa fa-check"></i><b>8.4.1</b> ANOVA Models</a></li>
<li class="chapter" data-level="8.4.2" data-path="lecture-notes.html"><a href="lecture-notes.html#penguins"><i class="fa fa-check"></i><b>8.4.2</b> Penguins</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="lecture-notes.html"><a href="lecture-notes.html#february-12"><i class="fa fa-check"></i><b>8.5</b> February 12</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="lecture-notes.html"><a href="lecture-notes.html#an-example"><i class="fa fa-check"></i><b>8.5.1</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="lecture-notes.html"><a href="lecture-notes.html#february-17"><i class="fa fa-check"></i><b>8.6</b> February 17</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-speaker-and-sentence-effects"><i class="fa fa-check"></i><b>8.6.1</b> Adding random speaker and sentence effects</a></li>
<li class="chapter" data-level="8.6.2" data-path="lecture-notes.html"><a href="lecture-notes.html#random-intercepts-with-continuous-predictor"><i class="fa fa-check"></i><b>8.6.2</b> Random intercepts with continuous predictor</a></li>
<li class="chapter" data-level="8.6.3" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-slopes"><i class="fa fa-check"></i><b>8.6.3</b> Adding random slopes</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="lecture-notes.html"><a href="lecture-notes.html#february-19"><i class="fa fa-check"></i><b>8.7</b> February 19</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="lecture-notes.html"><a href="lecture-notes.html#random-slopes"><i class="fa fa-check"></i><b>8.7.1</b> Random Slopes</a></li>
<li class="chapter" data-level="8.7.2" data-path="lecture-notes.html"><a href="lecture-notes.html#comparing-models"><i class="fa fa-check"></i><b>8.7.2</b> Comparing models</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="lecture-notes.html"><a href="lecture-notes.html#february-24"><i class="fa fa-check"></i><b>8.8</b> February 24</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="lecture-notes.html"><a href="lecture-notes.html#beethoven-tempo-example"><i class="fa fa-check"></i><b>8.8.1</b> Beethoven Tempo Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html"><i class="fa fa-check"></i><b>9</b> Maximum Likelihood Estimation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#mle-for-mixed-models"><i class="fa fa-check"></i><b>9.1</b> MLE for mixed models</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-z-tz-do"><i class="fa fa-check"></i><b>9.1.1</b> What does <code>Z %*% t(Z)</code> do?</a></li>
<li class="chapter" data-level="9.1.2" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-multiplying-by-tau2-do"><i class="fa fa-check"></i><b>9.1.2</b> What does multiplying by <code>tau2</code> do?</a></li>
<li class="chapter" data-level="9.1.3" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-sigma2-diagn-do"><i class="fa fa-check"></i><b>9.1.3</b> What does <code>sigma2 * diag(N)</code> do?</a></li>
<li class="chapter" data-level="9.1.4" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-the-final-matrix-represent"><i class="fa fa-check"></i><b>9.1.4</b> What does the final matrix represent?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="missing-data-1.html"><a href="missing-data-1.html"><i class="fa fa-check"></i><b>10</b> Missing Data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="missing-data-1.html"><a href="missing-data-1.html#technical-details"><i class="fa fa-check"></i><b>10.1</b> Technical Details</a></li>
<li class="chapter" data-level="10.2" data-path="missing-data-1.html"><a href="missing-data-1.html#diagnostics"><i class="fa fa-check"></i><b>10.2</b> Diagnostics</a></li>
<li class="chapter" data-level="10.3" data-path="missing-data-1.html"><a href="missing-data-1.html#pooling"><i class="fa fa-check"></i><b>10.3</b> Pooling</a></li>
<li class="chapter" data-level="10.4" data-path="missing-data-1.html"><a href="missing-data-1.html#simulations"><i class="fa fa-check"></i><b>10.4</b> Simulations</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>11</b> Solutions</a>
<ul>
<li class="chapter" data-level="11.1" data-path="solutions.html"><a href="solutions.html#chapter-2-solutions"><i class="fa fa-check"></i><b>11.1</b> Chapter 2 Solutions</a></li>
<li class="chapter" data-level="11.2" data-path="solutions.html"><a href="solutions.html#chapter-3-solutions"><i class="fa fa-check"></i><b>11.2</b> Chapter 3 Solutions</a></li>
<li class="chapter" data-level="11.3" data-path="solutions.html"><a href="solutions.html#chapter-5"><i class="fa fa-check"></i><b>11.3</b> Chapter 5</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Regression with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="classicaltheory" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Classical Theory of Simple Linear Regression<a href="classicaltheory.html#classicaltheory" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="review" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Review<a href="classicaltheory.html#review" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we review material that will be used in the first two chapters. The most important theory for this chapter is that related to <em>normal</em> random variables.</p>
<p>Recall, a <strong>normal</strong> random variable with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> has pdf given by
<span class="math display">\[
f(x) = \frac {1}{\sqrt{2\pi}\sigma} e^{-(x- \mu)^2/(2\sigma^2)}
\]</span>
We will not work much with the pdf directly, but rather use the built in R function <code>dnorm</code>, which has usage <code>dnorm(x, mu, sigma)</code>. Let’s look at a couple of plots of pdfs of normal random variables.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="classicaltheory.html#cb1-1" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">0</span>, <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">2</span>)), <span class="at">from =</span> <span class="sc">-</span><span class="dv">3</span>, <span class="at">to =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="dv">3</span>,</span>
<span id="cb1-2"><a href="classicaltheory.html#cb1-2" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;Normal rvs&quot;</span>, </span>
<span id="cb1-3"><a href="classicaltheory.html#cb1-3" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">&quot;likelihood&quot;</span>) <span class="co">#green</span></span>
<span id="cb1-4"><a href="classicaltheory.html#cb1-4" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">0</span>, <span class="dv">2</span>), <span class="at">add=</span> T, <span class="at">col =</span> <span class="dv">2</span>) <span class="co">#red</span></span>
<span id="cb1-5"><a href="classicaltheory.html#cb1-5" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">0</span>, <span class="dv">1</span>), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">1</span>) <span class="co">#black</span></span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-1"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-1-1.png" alt="Three overlapping bell curves centered at 0. Green is narrowest and tallest, black is medium, red is widest and flattest." width="672" />
<p class="caption">
Figure 2.1: Three normal probability density functions with mean 0. The green curve has the smallest standard deviation (sd = 1/sqrt(2), narrowest and tallest), the black curve has sd = 1 (medium width), and the red curve has sd = 2 (widest and flattest). All three are symmetric and bell-shaped around x = 0.
</p>
</div>
<p>Recall that the <em>area</em> under the curve between <span class="math inline">\(x = a\)</span> and <span class="math inline">\(x = b\)</span> of the pdf of <span class="math inline">\(X\)</span> gives <span class="math inline">\(P(a \le X \le b) = \int_a^b f(x)\, dx\)</span>. Probability density functions can also be used to find the <em>expected value</em> (also called the <em>mean</em>) of a random variable <span class="math inline">\(X\)</span> via</p>
<p><span class="math display">\[
\mu_X = E[X] = \int_{-\infty}^\infty x f(x)\, dx.
\]</span></p>
<div class="theorem">
<span class="divhead-plain theorem-before">Theorem 2.1</span>
<p><span id="thm:unlabeled-div-1" class="theorem"><strong>Theorem 2.1  </strong></span>Key facts about normal random variables.</p>
<ol style="list-style-type: decimal">
<li><p>If <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are independent normal random variables with means <span class="math inline">\(\mu_1, \mu_2\)</span> and standard deviations <span class="math inline">\(\sigma_1, \sigma_2\)</span>, then <span class="math inline">\(X_1 + X_2\)</span> is normal with mean <span class="math inline">\(\mu_1 + \mu_2\)</span> and standard deviation <span class="math inline">\(\sqrt{\sigma_1^2 + \sigma_2^2}\)</span>. if</p></li>
<li><p>If <span class="math inline">\(X \sim N(\mu, \sigma)\)</span> and <span class="math inline">\(a\)</span> is a real number, then <span class="math inline">\(X + a \sim N(\mu + a, \sigma)\)</span>.</p></li>
<li><p>If <span class="math inline">\(X \sim N(\mu, \sigma)\)</span> and <span class="math inline">\(a\)</span> is a real number, then <span class="math inline">\(aX \sim N(a\mu, a\sigma)\)</span>.<br />
</p></li>
</ol>
</div>
<p>The key things to remember are that the sum of independent normals is again normal, and that translating or scaling a normal is still normal. The means and standard deviations of the resulting random variables can be computed from general facts about sums of rvs, given below.</p>
<div class="theorem">
<span class="divhead-plain theorem-before">Theorem 2.2</span>
<p><span id="thm:meanfacts" class="theorem"><strong>Theorem 2.2  </strong></span>The following are facts about expected values of rvs.</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(E[X + Y] = E[X] + E[Y]\)</span>, whether <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent or dependent!</p></li>
<li><p><span class="math inline">\(E[a] = a\)</span>.</p></li>
<li><p><span class="math inline">\(E[aX] = aE[X]\)</span>.</p></li>
<li><p><span class="math inline">\(E[\sum_{i = 1}^n a_i X_i] = \sum_{i = 1}^n a_i E[X_i]\)</span>.<br />
</p></li>
</ol>
</div>
<p>Recall that the variance of an rv is <span class="math inline">\(V(X) = E[(X - \mu)^2] = E[X^2] - \mu^2\)</span>, and that the standard deviation is the square root of the variance.</p>
<div class="theorem">
<span class="divhead-plain theorem-before">Theorem 2.3</span>
<p><span id="thm:unlabeled-div-2" class="theorem"><strong>Theorem 2.3  </strong></span>Here are some key facts about variances of random variables.</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(V(aX) = a^2 V(X)\)</span></p></li>
<li><p><span class="math inline">\(V(\sum_{i = 1}^n a_i X_i) = \sum_{i = 1}^n a_i^2 V(X_i)\)</span>, <em>provided</em> that the random variables are independent!</p></li>
<li><p><span class="math inline">\(V(a) = 0\)</span><br />
</p></li>
</ol>
</div>
<p>The other key thing that you will need to remember is about simulations. We will be doing quite a bit of simulation work in this chapter.</p>
<div id="estimating-means-and-standard-deviations" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Estimating Means and standard deviations<a href="classicaltheory.html#estimating-means-and-standard-deviations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s recall how we can estimate the <em>mean</em> of a random variable given a random sample from that rv. Recall that <code>r</code> + <code>root</code> is the way that we can get random samples from known distributions. Here, we estimate the mean of a normal rv with mean 1 and standard deviation 2. Obviously, we hope to get approximately 1.</p>
<p>We first get a single sample from the rv, then we put it inside <code>replicate</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="classicaltheory.html#cb2-1" tabindex="-1"></a>one_sample <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb2-2"><a href="classicaltheory.html#cb2-2" tabindex="-1"></a>one_sample</span></code></pre></div>
<pre><code>## [1] 1.551524</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="classicaltheory.html#cb4-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb4-2"><a href="classicaltheory.html#cb4-2" tabindex="-1"></a>  one_sample <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb4-3"><a href="classicaltheory.html#cb4-3" tabindex="-1"></a>  one_sample</span>
<span id="cb4-4"><a href="classicaltheory.html#cb4-4" tabindex="-1"></a>})</span></code></pre></div>
<p>This creates a vector of length 10000 that is a random sample from a normal rv with mean 1 and sd 2. For simple examples like this, it would be more natural to do <code>sim_data &lt;- rnorm(10000, 1, 2)</code>, but the above will be easier to keep track of when we get to more complicated things, imho.</p>
<p>Next, we just take the mean (average) of the random sample.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="classicaltheory.html#cb5-1" tabindex="-1"></a><span class="fu">mean</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 1.023636</code></pre>
<p>And we see that we get pretty close to 1. Let’s verify that <span class="math inline">\(2 *X + 3 * Y\)</span> has mean <span class="math inline">\(2\mu_X + 3 \mu_Y\)</span> in the case that <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are normal with means 2 and 5 respectively.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="classicaltheory.html#cb7-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>) <span class="co">#chose sd = 1</span></span>
<span id="cb7-2"><a href="classicaltheory.html#cb7-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>) <span class="co">#chose different sd just to see if that matters</span></span>
<span id="cb7-3"><a href="classicaltheory.html#cb7-3" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> y</span></code></pre></div>
<pre><code>## [1] 20.46246</code></pre>
<p>That is one sample from <span class="math inline">\(2X + 3Y\)</span>. Let’s get a lot of samples.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="classicaltheory.html#cb9-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb9-2"><a href="classicaltheory.html#cb9-2" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>) <span class="co">#chose sd = 1</span></span>
<span id="cb9-3"><a href="classicaltheory.html#cb9-3" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>) <span class="co">#chose different sd just to see if that matters</span></span>
<span id="cb9-4"><a href="classicaltheory.html#cb9-4" tabindex="-1"></a>  <span class="dv">2</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> y</span>
<span id="cb9-5"><a href="classicaltheory.html#cb9-5" tabindex="-1"></a>})</span>
<span id="cb9-6"><a href="classicaltheory.html#cb9-6" tabindex="-1"></a><span class="fu">mean</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 18.8274</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="classicaltheory.html#cb11-1" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> <span class="dv">5</span></span></code></pre></div>
<pre><code>## [1] 19</code></pre>
<p>We compare the estimated mean to the true mean of 19, and see that we are pretty close. To be sure, we might run the simulation a couple of times and see whether it looks like it is staying close to 19; sometimes larger, sometimes smaller.</p>
<p>To estimate the variance of an rv, we take a large sample and use the R function <code>var</code>, which computes the sample variance. This is not as straightorward from a theoretical standpoint as taking the <code>mean</code>, but we will ignore the difficulties. We know from Theorem <a href="#thm:variancefacts"><strong>??</strong></a> that the variance of <span class="math inline">\(2X + 3Y\)</span> shoule be <span class="math inline">\(4 * 1 + 9 * 9 = 85\)</span>. Let’s check it out. We already have built our random sample, so we just use <code>var</code> on that.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="classicaltheory.html#cb13-1" tabindex="-1"></a><span class="fu">var</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 87.80047</code></pre>
<p>Let’s repeat a few times.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="classicaltheory.html#cb15-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb15-2"><a href="classicaltheory.html#cb15-2" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>) <span class="co">#chose sd = 1</span></span>
<span id="cb15-3"><a href="classicaltheory.html#cb15-3" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>) <span class="co">#chose different sd just to see if that matters</span></span>
<span id="cb15-4"><a href="classicaltheory.html#cb15-4" tabindex="-1"></a>  <span class="dv">2</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> y</span>
<span id="cb15-5"><a href="classicaltheory.html#cb15-5" tabindex="-1"></a>})</span>
<span id="cb15-6"><a href="classicaltheory.html#cb15-6" tabindex="-1"></a><span class="fu">var</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 88.03891</code></pre>
<p>Seems to be working. To estimate the standard deviation, we would take the square root, or use the <code>sd</code> R function.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="classicaltheory.html#cb17-1" tabindex="-1"></a><span class="fu">sd</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 9.382905</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="classicaltheory.html#cb19-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">var</span>(sim_data))</span></code></pre></div>
<pre><code>## [1] 9.382905</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="classicaltheory.html#cb21-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">85</span>)</span></code></pre></div>
<pre><code>## [1] 9.219544</code></pre>
<p>The reason it is tricky from a theoretical point of view to estimate the standard deviation is that, if you repeated the above a bunch of times, you would notice that <code>sd</code> is slighlty off on average. But, the variance is correct, on average.</p>
</div>
<div id="estimating-the-density-of-an-rv" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Estimating the density of an rv<a href="classicaltheory.html#estimating-the-density-of-an-rv" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this section, we see how to estimate the pdf of an rv and compare it to the pdf of a known distribution. We continue with the normal examples. Let’s verify that <span class="math inline">\(2X + 3Y\)</span> is normal, when <span class="math inline">\(X \sim N(0, 1)\)</span> and <span class="math inline">\(Y \sim N(1, 2)\)</span>. (<span class="math inline">\(Y\)</span> has standard deviation 2).</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="classicaltheory.html#cb23-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb23-2"><a href="classicaltheory.html#cb23-2" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb23-3"><a href="classicaltheory.html#cb23-3" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb23-4"><a href="classicaltheory.html#cb23-4" tabindex="-1"></a>  <span class="dv">2</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> y</span>
<span id="cb23-5"><a href="classicaltheory.html#cb23-5" tabindex="-1"></a>})</span>
<span id="cb23-6"><a href="classicaltheory.html#cb23-6" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(sim_data))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-9"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-9-1.png" alt="A single smooth bell-shaped curve centered around 3, showing the estimated density of the simulated distribution." width="672" />
<p class="caption">
Figure 2.2: Estimated probability density of the simulated random variable 2X + 3Y, where X is standard normal and Y is normal with mean 1 and standard deviation 2. The curve is smooth and bell-shaped, centered near 3.
</p>
</div>
<p>The <code>plot(density())</code> command gives an estimated density plot of the rv that has data given in the argument of <code>density</code>. Let’s a
a pdf of a normal rv with the correct mean and standard deviation to the above plot, and see whether they match. The correct mean is <span class="math inline">\(2 * 0 + 3 * 1\)</span> and the sd is <span class="math inline">\(\sqrt{4 * 1 + 9 * 4}\)</span></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="classicaltheory.html#cb24-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(sim_data))</span>
<span id="cb24-2"><a href="classicaltheory.html#cb24-2" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">3</span>, <span class="fu">sqrt</span>(<span class="dv">40</span>)), a</span>
<span id="cb24-3"><a href="classicaltheory.html#cb24-3" tabindex="-1"></a>      <span class="ot">=</span> T, <span class="at">col =</span> <span class="dv">2</span>) <span class="co">#shows up in red</span></span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-10-1.png" alt="Two nearly identical bell curves overlaid: a black estimated density and a red theoretical normal curve. They match closely, confirming normality." width="672" />
<p class="caption">
Figure 2.3: The estimated density of the simulated 2X + 3Y (black curve) overlaid with the theoretical normal distribution with mean 3 and standard deviation sqrt(40) (red curve). The two curves align closely, confirming that the distribution is normal.
</p>
</div>
<p>Alternatively, we could have used the simulated data and estimated the mean and sd.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="classicaltheory.html#cb25-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(sim_data))</span>
<span id="cb25-2"><a href="classicaltheory.html#cb25-2" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, </span>
<span id="cb25-3"><a href="classicaltheory.html#cb25-3" tabindex="-1"></a>            <span class="fu">mean</span>(sim_data), </span>
<span id="cb25-4"><a href="classicaltheory.html#cb25-4" tabindex="-1"></a>            <span class="fu">sd</span>(sim_data)), a</span>
<span id="cb25-5"><a href="classicaltheory.html#cb25-5" tabindex="-1"></a>      <span class="ot">=</span> T, <span class="at">col =</span> <span class="dv">2</span>) <span class="co">#shows up in red</span></span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-11"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-11-1.png" alt="Two overlapping bell curves: black estimated density and red normal curve using sample statistics. They align closely." width="672" />
<p class="caption">
Figure 2.4: Estimated density of simulated 2X + 3Y (black) overlaid with a normal curve using the sample mean and standard deviation (red). The curves match closely, showing the simulated distribution is well-approximated by the theoretical normal.
</p>
</div>
<p>Since the estimated pdf of the simulated data matches that of the <code>dnorm</code> (more or less), we conclude that the distributions are the same. Note that if there is a discontinuity in the pdf, then the simulation will not match well at that point of discontinuity. Since we will mostly be dealing with normal rvs, we’ll cross that bridge when we get to it.</p>
<div class="exercise">
<span class="divhead-definition exercise-before"> 2.1</span>
<p><span id="exr:unnamed-chunk-12" class="exercise"><strong>Exercise 2.1  </strong></span>Let <span class="math inline">\(X_1, \ldots, X_5\)</span> be normal random variables with means <span class="math inline">\(1, 2, 3, 4, 5\)</span> and variances <span class="math inline">\(1, 4, 9, 16, 25\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>What kind of rv is <span class="math inline">\(\overline{X}\)</span>? Include the values of any parameters.</p></li>
<li><p>Use simulation to plot the pdf of <span class="math inline">\(\overline{X}\)</span> and confirm your answer to part 1.</p></li>
</ol>
</div>
<p>One last concept that we will run across a lot is <em>independence</em>.
Two random variables are independent if knowledge of the outcome of one gives no probabilistic information about the outcome of the other one.
Formally, <span class="math inline">\(P(a \le X \le B|c \le Y \le d) = P(a \le X \le b)\)</span>
for all values of <span class="math inline">\(a, b, c\)</span> and <span class="math inline">\(d\)</span>.
It can be tricky to check this, and it is often something that we will <strong>assume</strong> rather than prove.
However, one fact that we will use is that if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent, then <span class="math inline">\(X + a\)</span> and <span class="math inline">\(Y + b\)</span> are also independent.</p>
</div>
</div>
<div id="linear-regression-overview" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Linear Regression Overview<a href="classicaltheory.html#linear-regression-overview" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We present the basic idea of regression.
Suppose that we have a collection of data that is naturally grouped into ordered pairs, <span class="math inline">\((x_1, y_1), \ldots, (x_n, y_n)\)</span>.
For example, we could be measuring the height and weight of adult women, or the heights of fathers and their adult sons.
In both instances, these data would naturally be grouped together into ordered pairs, and we would likely be interested in the <strong>relationship</strong> between the two variables.
In particular, we would not want to assume that the variables are independent.</p>
<p>In the R package <code>HistData</code>, there is a data set that is the heights of parents and their adult children. Let’s take a look.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="classicaltheory.html#cb26-1" tabindex="-1"></a>galton <span class="ot">&lt;-</span> HistData<span class="sc">::</span>Galton</span>
<span id="cb26-2"><a href="classicaltheory.html#cb26-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb26-3"><a href="classicaltheory.html#cb26-3" tabindex="-1"></a><span class="fu">ggplot</span>(galton, <span class="fu">aes</span>(parent, child)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="classicaltheory.html#cb26-4" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">5</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-13"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-13-1.png" alt="Scatterplot showing a positive linear trend between parent height and child height, with points scattered roughly around a diagonal line from lower-left to upper-right." width="672" />
<p class="caption">
Figure 2.5: Scatterplot of Galton height data: parent average height on the x-axis versus adult child height on the y-axis. Points are jittered to reduce overplotting. The data shows a positive association — taller parents tend to have taller children.
</p>
</div>
<p>It appears that there is a positive correlation between the height of a parent and the height of their adult child. (The parent value is the average of the father and mother of the child, and the child value has been adjusted for sex of the child. So, this may not be the best example of rigourous data collection!)</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="classicaltheory.html#cb27-1" tabindex="-1"></a><span class="fu">ggplot</span>(galton, <span class="fu">aes</span>(parent, child)) <span class="sc">+</span> </span>
<span id="cb27-2"><a href="classicaltheory.html#cb27-2" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="classicaltheory.html#cb27-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-14-1.png" alt="Scatterplot of parent vs child heights with a blue regression line showing a positive slope. Points are spread around the line indicating variability." width="672" />
<p class="caption">
Figure 2.6: Scatterplot of Galton height data with a fitted linear regression line. The positive slope confirms the trend: children of taller parents tend to be taller, though the relationship is not perfectly linear.
</p>
</div>
<p>The model that we are using for this data is
<span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]</span>
where the <span class="math inline">\(\epsilon_i\)</span> are independent normal random variables with mean 0 and unknown variance <span class="math inline">\(\sigma^2\)</span>.
The <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are unknown <strong>constants</strong>.
The only randomness in this model comes from the <span class="math inline">\(\epsilon_i\)</span>, which we think of as the error of the model or the residuals of the model.</p>
<p>In order to estimate the values of the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, we want to choose the values that minimize the total error associated with the line <span class="math inline">\(y = \beta_0 + \beta_1 x\)</span>. There are <em>lots</em> of ways to do this! Let’s begin by looking at the error at a single point, <span class="math inline">\(y_i - (\beta_0 + \beta_1 x_i)\)</span>. This is the <em>observed</em> value <span class="math inline">\(y_i\)</span> minus the <span class="math inline">\(predicted\)</span> value <span class="math inline">\(\beta_0 + \beta_1 x_i\)</span>. If we are trying to minimize the total error, we will want to take the absolute value or something of the error at each point and a
them up. Here are a few ways we could do this.</p>
<p><span class="math display">\[\begin{align}
SSE(\beta_0, \beta_1) &amp;= \sum_{i = 1}^n \bigl(y_i - (\beta_0 + \beta_1 x_i)\bigr)^2\\
L_1(\beta_0, \beta_1) &amp;= \sum_{i = 1}^n \bigl|y_i - (\beta_0 + \beta_1 x_i)\bigr|\\
E_g(\beta_0, \beta_1) &amp;= \sum_{i = 1}^n g(y_i - \beta_0 + \beta_1 x_i)
\end{align}\]</span></p>
<p>where <span class="math inline">\(g\)</span> is a <em>loss function</em> such that <span class="math inline">\(g(x) = g(-x)\)</span> and <span class="math inline">\(g(x) \le g(y)\)</span> whenever <span class="math inline">\(0 \le x \le y\)</span>. Here are a few more loss functions <span class="math inline">\(g\)</span> that are commonly used.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="classicaltheory.html#cb29-1" tabindex="-1"></a><span class="fu">curve</span>(x<span class="sc">^</span><span class="dv">2</span>, <span class="at">from =</span> <span class="sc">-</span><span class="dv">4</span>, <span class="at">to =</span> <span class="dv">4</span>, <span class="at">col =</span> <span class="dv">1</span>,</span>
<span id="cb29-2"><a href="classicaltheory.html#cb29-2" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;Common Loss Functions&quot;</span>) <span class="co">#black</span></span>
<span id="cb29-3"><a href="classicaltheory.html#cb29-3" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">abs</span>(x), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>) <span class="co">#red</span></span>
<span id="cb29-4"><a href="classicaltheory.html#cb29-4" tabindex="-1"></a>delta <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb29-5"><a href="classicaltheory.html#cb29-5" tabindex="-1"></a><span class="fu">curve</span>(delta<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span>(<span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">+</span> (x<span class="sc">/</span>delta)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="dv">1</span>),</span>
<span id="cb29-6"><a href="classicaltheory.html#cb29-6" tabindex="-1"></a>      <span class="at">add=</span> T,</span>
<span id="cb29-7"><a href="classicaltheory.html#cb29-7" tabindex="-1"></a>      <span class="at">col =</span> <span class="dv">3</span>) <span class="co">#green</span></span>
<span id="cb29-8"><a href="classicaltheory.html#cb29-8" tabindex="-1"></a><span class="fu">curve</span>(robustbase<span class="sc">::</span><span class="fu">Mchi</span>(x, <span class="at">cc =</span> <span class="fl">1.6</span>, <span class="at">psi =</span> <span class="st">&quot;bisquare&quot;</span>),</span>
<span id="cb29-9"><a href="classicaltheory.html#cb29-9" tabindex="-1"></a>      <span class="at">add=</span> T, </span>
<span id="cb29-10"><a href="classicaltheory.html#cb29-10" tabindex="-1"></a>      <span class="at">col =</span> <span class="dv">4</span>) <span class="co">#bue</span></span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-15"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-15-1.png" alt="Four curves on the same axes showing different loss functions. The black parabola grows fastest; the red V-shape grows linearly; the green pseudo-Huber is intermediate; the blue bisquare flattens out for large errors." width="672" />
<p class="caption">
Figure 2.7: Four common loss functions plotted over x from -4 to 4. Black: squared error (x squared), a parabola. Red: absolute value (L1), a V-shape. Green: pseudo-Huber with delta=2, which is quadratic near zero and linear in the tails. Blue: Tukey bisquare, which rises to a maximum and then levels off, capping the penalty for large errors.
</p>
</div>
<p>of the loss function evaluated at the differences between the observed and the predicted values. We will see in later sections how to do that via math, but we also have R, which is good at doing things like this.</p>
<p>Let’s look at a different data set. This is the world happiness data set. People were surveyed in various countries around the world and asked to imagine the best life possible for them as a 10, and the worst life possible as a 0. Then they were asked to assign a number to their current life between 0 and 10. The results of the survey are summarized <a href="https://mathstat.slu.edu/~speegle/Spring2020/4870/data/world_happiness_data.xls">here</a>.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="classicaltheory.html#cb30-1" tabindex="-1"></a>dd <span class="ot">&lt;-</span> ardata<span class="sc">::</span>world_happiness</span>
<span id="cb30-2"><a href="classicaltheory.html#cb30-2" tabindex="-1"></a></span>
<span id="cb30-3"><a href="classicaltheory.html#cb30-3" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">filter</span>(dd, year <span class="sc">==</span> <span class="dv">2018</span>)</span>
<span id="cb30-4"><a href="classicaltheory.html#cb30-4" tabindex="-1"></a></span>
<span id="cb30-5"><a href="classicaltheory.html#cb30-5" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">select</span>(dd, country_name, life_ladder, log_gdp_per_capita)</span>
<span id="cb30-6"><a href="classicaltheory.html#cb30-6" tabindex="-1"></a><span class="fu">ggplot</span>(dd, <span class="fu">aes</span>(<span class="at">x =</span> log_gdp_per_capita, <span class="at">y =</span> life_ladder))  <span class="sc">+</span> </span>
<span id="cb30-7"><a href="classicaltheory.html#cb30-7" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 9 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-16"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-16-1.png" alt="Scatterplot showing a positive trend between log GDP per capita and happiness scores. Points are scattered around an upward diagonal with some outliers below the main trend." width="672" />
<p class="caption">
Figure 2.8: Scatterplot of world happiness data: log GDP per capita on the x-axis versus life ladder score (0-10 happiness scale) on the y-axis. There is a clear positive association — wealthier countries tend to report higher happiness scores, though there is substantial variability.
</p>
</div>
<p>Let’s get rid of the data with missing values, and store the resulting variable in <code>happy</code> for future use, since <code>dd</code> will get overwritten later.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="classicaltheory.html#cb32-1" tabindex="-1"></a>dd<span class="ot">&lt;-</span> dd[<span class="fu">complete.cases</span>(dd),]</span>
<span id="cb32-2"><a href="classicaltheory.html#cb32-2" tabindex="-1"></a>happy <span class="ot">&lt;-</span> dd</span></code></pre></div>
<p>Now, let’s find values of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that minimize the SSE. (We’ll do the other loss functions below.)</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="classicaltheory.html#cb33-1" tabindex="-1"></a>sse <span class="ot">&lt;-</span> <span class="cf">function</span>(b0, b1) {</span>
<span id="cb33-2"><a href="classicaltheory.html#cb33-2" tabindex="-1"></a>  <span class="fu">sum</span>((dd<span class="sc">$</span>life_ladder <span class="sc">-</span> (b0 <span class="sc">+</span> b1 <span class="sc">*</span> dd<span class="sc">$</span>log_gdp_per_capita))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb33-3"><a href="classicaltheory.html#cb33-3" tabindex="-1"></a>}</span></code></pre></div>
<p>The minimization function that we are going to use requires the sse function to be in a format where it accepts a single <em>vector</em> of values.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="classicaltheory.html#cb34-1" tabindex="-1"></a>sse_one_argument <span class="ot">&lt;-</span> <span class="cf">function</span>(b) {</span>
<span id="cb34-2"><a href="classicaltheory.html#cb34-2" tabindex="-1"></a>  <span class="fu">sse</span>(b[<span class="dv">1</span>], b[<span class="dv">2</span>])</span>
<span id="cb34-3"><a href="classicaltheory.html#cb34-3" tabindex="-1"></a>}</span></code></pre></div>
<p>Now, we can call <code>optim</code> to <em>optimize</em> the SSE (which minimizes it).</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="classicaltheory.html#cb35-1" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">fn =</span> sse_one_argument)</span></code></pre></div>
<pre><code>## $par
## [1] -1.0302082  0.7047482
## 
## $value
## [1] 64.32955
## 
## $counts
## function gradient 
##       79       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We see that the intercept is about -1.03 and the slope is about 0.705. Let’s plot that on the scatterplot.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="classicaltheory.html#cb37-1" tabindex="-1"></a><span class="fu">ggplot</span>(dd, <span class="fu">aes</span>(<span class="at">x =</span> log_gdp_per_capita, <span class="at">y =</span> life_ladder))  <span class="sc">+</span> </span>
<span id="cb37-2"><a href="classicaltheory.html#cb37-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-3"><a href="classicaltheory.html#cb37-3" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="fl">0.705</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">1.03</span>) <span class="sc">+</span></span>
<span id="cb37-4"><a href="classicaltheory.html#cb37-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-21"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-21-1.png" alt="Scatterplot with two nearly identical upward-sloping lines overlaid on the points, confirming the SSE minimizer matches the lm output." width="672" />
<p class="caption">
Figure 2.9: Scatterplot of happiness versus log GDP per capita with the SSE-minimizing line of best fit (slope 0.705, intercept -1.03) overlaid. The line from optim and the line from lm overlap almost perfectly, confirming that both methods yield the same result.
</p>
</div>
<p>Yep. That’s the line that minimizes the sum of squares error, all right!</p>
<p>Let’s look at one more set of data, the <code>datasauRus</code>. You will need to install the datasauRus package if you have not already done so via <code>install.packages("datasauRus")</code>. The datasauRus package contains several interesting simulated data sets. The one we are interested in for now is the <code>datasaurus_dozen</code>, which we store into <code>dd</code>.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="classicaltheory.html#cb39-1" tabindex="-1"></a>dd <span class="ot">&lt;-</span> datasauRus<span class="sc">::</span>datasaurus_dozen</span></code></pre></div>
<p>We see that the <code>datasaurus_dozen</code> is a list of 12 data sets (I think), and that it has <span class="math inline">\((x, y)\)</span> coordinates, together with a dataset variable. Let’s see what datasets are available to us.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="classicaltheory.html#cb40-1" tabindex="-1"></a><span class="fu">unique</span>(dd<span class="sc">$</span>dataset)</span></code></pre></div>
<pre><code>##  [1] &quot;dino&quot;       &quot;away&quot;       &quot;h_lines&quot;    &quot;v_lines&quot;    &quot;x_shape&quot;   
##  [6] &quot;star&quot;       &quot;high_lines&quot; &quot;dots&quot;       &quot;circle&quot;     &quot;bullseye&quot;  
## [11] &quot;slant_up&quot;   &quot;slant_down&quot; &quot;wide_lines&quot;</code></pre>
<p>I’ll do this example with <code>star</code>, but, you should follow along with a different one.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="classicaltheory.html#cb42-1" tabindex="-1"></a>star <span class="ot">&lt;-</span> <span class="fu">filter</span>(dd, dataset <span class="sc">==</span> <span class="st">&quot;star&quot;</span>)</span>
<span id="cb42-2"><a href="classicaltheory.html#cb42-2" tabindex="-1"></a><span class="fu">ggplot</span>(star, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="classicaltheory.html#cb42-3" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-24"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-24-1.png" alt="Scatterplot where the data points form a recognizable five-pointed star shape, demonstrating that the data is clearly non-linear." width="672" />
<p class="caption">
Figure 2.10: Scatterplot of the ‘star’ dataset from datasauRus, showing points arranged in the shape of a five-pointed star. This illustrates that data can have a clear non-linear structure while a linear model can still technically be fitted — it just won’t be a meaningful fit.
</p>
</div>
<p>Yep, it looks like a star! This certainly is <strong>not</strong> of the form <span class="math inline">\(y = \beta_0 + \beta_1 x + \epsilon\)</span> (Why?), but we can still find the line that is the best fit of this data. Not saying it will be a good fit, but it is still the one that minimizes SSE.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="classicaltheory.html#cb43-1" tabindex="-1"></a>sse <span class="ot">&lt;-</span> <span class="cf">function</span>(b0, b1) {</span>
<span id="cb43-2"><a href="classicaltheory.html#cb43-2" tabindex="-1"></a>  <span class="fu">sum</span>((star<span class="sc">$</span>y <span class="sc">-</span> (b0 <span class="sc">+</span> b1 <span class="sc">*</span> star<span class="sc">$</span>x))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb43-3"><a href="classicaltheory.html#cb43-3" tabindex="-1"></a>}</span>
<span id="cb43-4"><a href="classicaltheory.html#cb43-4" tabindex="-1"></a>sse_one_argument <span class="ot">&lt;-</span> <span class="cf">function</span>(b){</span>
<span id="cb43-5"><a href="classicaltheory.html#cb43-5" tabindex="-1"></a>  <span class="fu">sse</span>(b[<span class="dv">1</span>], b[<span class="dv">2</span>])</span>
<span id="cb43-6"><a href="classicaltheory.html#cb43-6" tabindex="-1"></a>}</span>
<span id="cb43-7"><a href="classicaltheory.html#cb43-7" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">0</span>), <span class="at">fn =</span> sse_one_argument)</span></code></pre></div>
<pre><code>## $par
## [1] 53.331713 -0.101214
## 
## $value
## [1] 101853.4
## 
## $counts
## function gradient 
##       59       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We see that the line of best fit is <span class="math inline">\(y = 53.33 - .10124 x\)</span>. Now, let’s take a look at the line of best fit for all of the data sets. We’ll use <code>ggplot</code> and <code>facet_wrap</code>.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="classicaltheory.html#cb45-1" tabindex="-1"></a><span class="fu">ggplot</span>(dd, <span class="fu">aes</span>(x, y)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="classicaltheory.html#cb45-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb45-3"><a href="classicaltheory.html#cb45-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb45-4"><a href="classicaltheory.html#cb45-4" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>dataset)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-26"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-26-1.png" alt="Twelve small scatterplots in a grid. Each shows a different pattern of points (some forming recognizable shapes like a dinosaur or star), but each has a nearly flat regression line at approximately the same position, demonstrating that identical summary statistics can hide very different data structures." width="672" />
<p class="caption">
Figure 2.11: A 3-by-4 grid of scatterplots showing all 12 datasets in the datasaurus_dozen collection, each with its linear regression line overlaid. Despite the datasets having wildly different visual shapes — including a dinosaur, a star, concentric circles, and scattered clusters — all 12 regression lines have nearly identical slopes and intercepts. This is the key insight: summary statistics alone can be deeply misleading.
</p>
</div>
<p>It turns out that all 12 of these data sets have very similar lines of best fit!</p>
<div class="exercise">
<span class="divhead-definition exercise-before"> 2.2</span>
<p><span id="exr:unlabeled-div-3" class="exercise"><strong>Exercise 2.2  </strong></span>Consider the data set <code>ISwR::bp.obese</code>. If you have never installed the <code>ISwR</code> package, you will need to run <code>install.packages("ISwR")</code> before accessing this data set.</p>
<ol style="list-style-type: decimal">
<li><p>Find the line of best fit for modeling blood pressure versus obesity by minimizing the SSE.</p></li>
<li><p>Does it appear that the model <span class="math inline">\(y = \beta_0 + \beta_1 x + epsilon\)</span>, where <span class="math inline">\(y\)</span> is bp, <span class="math inline">\(x\)</span> is obese, and <span class="math inline">\(\epsilon\)</span> is normal with mean 0 and standard deviation <span class="math inline">\(\sigma\)</span> is correct for this data?</p></li>
</ol>
</div>
</div>
<div id="linear-regression-with-no-intercept" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Linear Regression with no intercept<a href="classicaltheory.html#linear-regression-with-no-intercept" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We will present the theory of linear regression with no intercept.
You will be asked as an exercise to repeat the arguments for linear regression with fixed slope of 1.
The theory in these cases is easier than in the general case, but the ideas are similar.</p>
<p>I hope that you will be able to better understand the general case after having worked through these two special cases. Our model is
<span class="math display">\[
y_i = \beta_1 x_i + \epsilon_i
\]</span>
where <span class="math inline">\(\epsilon_i\)</span> are assumed to be normal with mean 0 and unknown variance <span class="math inline">\(\sigma^2\)</span>. We still wish to minimize the sum-sqaured error of the predicted values (<span class="math inline">\(\beta_1 x_i\)</span>) relative to the observed values (<span class="math inline">\(y_i\)</span>). That is, we want to minimize
<span class="math display">\[
SSE(\beta_1) = \sum_{i = 1}^n \bigl(y_i - \beta_1 x_i\bigr)^2
\]</span>
In this case, there is only <em>one</em> unknown constant in the equation for SSE. (But, of course, we still don’t know <span class="math inline">\(\sigma\)</span>.) Let’s math it.</p>
<p><span class="math display">\[
\begin{aligned}
\frac {d}{d\beta_1} SSE(\beta_1) &amp;= \sum_{i = 1}^n 2(\bigl(y_i - \beta_1 x_i\bigr) x_i)\\
&amp;=2\sum_{i = 1}^n y_i x_i - 2\beta_1 \sum_{i = 1}^n x_i^2.
\end{aligned}
\]</span></p>
<p>Setting this equal to zero and solving for <span class="math inline">\(\beta_1\)</span> gives
<span class="math display">\[
\beta_1 = \frac{\sum_{i = 1}^n x_i y_i}{\sum_{i = 1}^n x_i^2}
\]</span>
This is our estimate for <span class="math inline">\(\beta_1\)</span>, so we add a ^ to it to make this indication. In general, hats on tops of constants will indicate our estimates for the constants based on data.
<span class="math display">\[
\hat \beta_1 = \frac{\sum_{i = 1}^n x_i y_i}{\sum_{i = 1}^n x_i^2}
\]</span></p>
<p>Let’s look at some simulated data to see how this performs.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="classicaltheory.html#cb47-1" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb47-2"><a href="classicaltheory.html#cb47-2" tabindex="-1"></a>ys <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb47-3"><a href="classicaltheory.html#cb47-3" tabindex="-1"></a><span class="fu">plot</span>(xs, ys)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-27"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-27-1.png" alt="Scatterplot with 30 points showing a positive trend from lower-left to upper-right, with spread increasing slightly as x increases." width="672" />
<p class="caption">
Figure 2.12: Scatterplot of 30 simulated data points following the model y = 2x + noise, where x ranges from 0 to 10. The points fan out slightly around a positive linear trend as x increases, consistent with constant variance around the line y = 2x.
</p>
</div>
<p>Our estimate for the slope is</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="classicaltheory.html#cb48-1" tabindex="-1"></a>beta1_hat <span class="ot">&lt;-</span> <span class="fu">sum</span>(xs <span class="sc">*</span> ys)<span class="sc">/</span><span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb48-2"><a href="classicaltheory.html#cb48-2" tabindex="-1"></a><span class="fu">plot</span>(xs, ys)</span>
<span id="cb48-3"><a href="classicaltheory.html#cb48-3" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="dv">0</span>, <span class="at">b =</span> beta1_hat)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-28"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-28-1.png" alt="Scatterplot with points following a positive trend and a straight line through the origin fitting the data closely." width="672" />
<p class="caption">
Figure 2.13: Scatterplot of simulated data with the estimated regression-through-origin line overlaid. The line passes through (0, 0) and has slope approximately 2, fitting the points well.
</p>
</div>
<p>That looks pretty good! Let’s look at the formula for <span class="math inline">\(\hat \beta_1\)</span> in some more detail. In particular, let’s assume that our model is correct, and that <span class="math inline">\(y_i = \beta_1 x_i + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\)</span> are independent normal rvs with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>. Under this model, the <span class="math inline">\(x_i\)</span> are <strong>constants</strong>; there is nothing random about them contained in the model. However, the <span class="math inline">\(y_i\)</span> are random variables! The <span class="math inline">\(y_i\)</span> are the sum of a constant (<span class="math inline">\(\beta_1 x_i\)</span>) and a normal random variable. By Theorem <a href="#thm:normalfacts"><strong>??</strong></a>, that means that <span class="math inline">\(y_i\)</span> is <strong>also normal</strong>. The mean of <span class="math inline">\(y_i\)</span> is <span class="math inline">\(\beta_1 x_i\)</span> and the variance of <span class="math inline">\(y_i\)</span> is <span class="math inline">\(\sigma^2\)</span>.</p>
<p><strong>Question</strong> Are the <span class="math inline">\(y_i\)</span> independent or dependent? There are spoilers below, so think about this before you read further.</p>
<p>So, up to know, we have that <span class="math inline">\(\hat \beta_1 = \frac{\sum x_i y_i}{\sum x_i^2} = \frac{1}{\sum x_i^2}\sum x_i y_i\)</span>. The pieces are the constants <span class="math inline">\(x_i\)</span> and the normal random variables <span class="math inline">\(y_i\)</span>. Let’s compute the expected value of <span class="math inline">\(\hat \beta_1\)</span>.</p>
<p><span class="math display">\[
\begin{aligned}
E[\hat \beta_1] &amp;= E\bigl[\frac {1}{\sum x_i^2}\sum x_i y_i\bigr]\\
&amp;= \frac {1}{\sum x_i^2} \sum_{i = 1}^n x_i E[y_i]\\
&amp;= \frac {1}{\sum x_i^2} \sum_{i = 1}^n x_i \beta_1 x_i\\
&amp;= \beta_1 \frac{\sum x_i^2}{\sum x_i^2}\\
&amp;= \beta_1
\end{aligned}
\]</span></p>
<p>That’s not an easy computation, but it says something <strong>really</strong> important about regression with no intercept. It says that the expected value of our estimate for the slope, is the slope itself! We expect, on average, to be exactly right in our estimate of the slope. These types of estimators are called <strong>unbiased</strong> estimators, and we have shown that <span class="math inline">\(\hat \beta_1\)</span> is an unbiased estimator of <span class="math inline">\(\beta_1\)</span>. That is definitely a desirable property of an estimator, though it is not necessarily a deal-breaker if an estimator is biased. I’m looking at you, sample standard deviation.</p>
<p>Let’s check out what this would mean via simulations. We assume that the data comes from <span class="math inline">\(y = 2 x + \epsilon\)</span>, where <span class="math inline">\(\epsilon \sim N(0,\sigma = 3)\)</span>. Let’s imagine that we have <em>fixed</em> values of <code>xs</code>, but this is not really necessary.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="classicaltheory.html#cb49-1" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">length.out =</span> <span class="dv">30</span>)</span></code></pre></div>
<p>Then we will create a data set and estimate the slope.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="classicaltheory.html#cb50-1" tabindex="-1"></a>ys <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb50-2"><a href="classicaltheory.html#cb50-2" tabindex="-1"></a><span class="fu">sum</span>(xs <span class="sc">*</span> ys)<span class="sc">/</span><span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.899664</code></pre>
<p>Next, we put that inside of <code>replicate</code> to get a large sample of possible estimates of slopes.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="classicaltheory.html#cb52-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb52-2"><a href="classicaltheory.html#cb52-2" tabindex="-1"></a>  ys <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb52-3"><a href="classicaltheory.html#cb52-3" tabindex="-1"></a>  <span class="fu">sum</span>(xs <span class="sc">*</span> ys)<span class="sc">/</span><span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb52-4"><a href="classicaltheory.html#cb52-4" tabindex="-1"></a>})</span></code></pre></div>
<p>And we compute the mean. We should get something really close to 2, which is the true value of the slope.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="classicaltheory.html#cb53-1" tabindex="-1"></a><span class="fu">mean</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 1.999716</code></pre>
<p>To be safe, we should repeat that a few times to see if the estimated expected value of <span class="math inline">\(\hat \beta_1\)</span> is on both sides of 2, and doesn’t seem to be biased. More generally, we know that <span class="math inline">\(\hat \beta_1\)</span> is a <strong>normal random variable</strong> with mean 2. What is its variance? Well, since the <span class="math inline">\(y_i\)</span> are independent, we can compute the variance as follows.</p>
<p><span class="math display">\[
\begin{aligned}
V(\hat \beta_1) &amp;= V(\frac {1}{\sum x_i^2}\sum x_i y_i)\\
&amp;= \frac{1}{(\sum x_i^2)^2} \sum x_i^2 V(y_i)\\
&amp;= \frac{1}{(\sum x_i^2)^2} \sum x_i^2 \sigma^2\\
&amp;= \frac{\sigma^2}{\sum x_i^2}
\end{aligned}
\]</span></p>
<p>Again, let’s check that is true via… simulations!</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="classicaltheory.html#cb55-1" tabindex="-1"></a><span class="fu">var</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 0.008805545</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="classicaltheory.html#cb57-1" tabindex="-1"></a><span class="dv">9</span><span class="sc">/</span>(<span class="fu">sum</span> (xs<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<pre><code>## [1] 0.008847458</code></pre>
<p>Looks pretty good! Again, we would need to repeat a few times to be sure. Finally, let’s estimate the density function of <span class="math inline">\(\hat \beta_1\)</span> and compare it to that of a normal with the above mean and standard deviation.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="classicaltheory.html#cb59-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(sim_data))</span>
<span id="cb59-2"><a href="classicaltheory.html#cb59-2" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">2</span>, <span class="fu">sqrt</span>(<span class="dv">9</span><span class="sc">/</span><span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>))),a</span>
<span id="cb59-3"><a href="classicaltheory.html#cb59-3" tabindex="-1"></a>      <span class="ot">=</span> T, <span class="at">col =</span> <span class="dv">2</span> )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-34"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-34-1.png" alt="Two overlapping bell curves centered near 2: a black estimated density from simulation and a red theoretical normal curve. They align closely, validating the theoretical distribution of the slope estimator." width="672" />
<p class="caption">
Figure 2.14: Estimated density of the simulated slope estimator beta-hat-1 (black curve) overlaid with the theoretical normal distribution with mean 2 and standard deviation sigma divided by sqrt(sum of x_i squared) (red curve). The curves match closely, confirming the theoretical result.
</p>
</div>
<p>That is compelling to me. We have seen that <span class="math inline">\(\hat \beta_1\)</span> is normal with mean <span class="math inline">\(\beta_1\)</span> and standard deviation <span class="math inline">\(\frac{\sigma}{\sqrt{\sum x_i^2}}\)</span>.</p>
<p>If we wanted to estimate <strong>all</strong> of the parameters in the model, though, we would need to come up with an estimate for <span class="math inline">\(\sigma\)</span> or <span class="math inline">\(\sigma^2\)</span>. The traditional way to estimate <span class="math inline">\(\sigma^2\)</span> given a random sample <span class="math inline">\(v_i\)</span> from a population with <strong>known</strong> mean <span class="math inline">\(\mu\)</span> is <span class="math inline">\(S^2 \approx \frac 1n \sum_{i = 1}^n (v_i - \mu)^2\)</span>. If we <strong>don’t</strong> know <span class="math inline">\(\mu\)</span>, then we estimate it from the data, and use <span class="math inline">\(S^2 = \frac 1{n-1} \sum_{i = 1}^n (v_i - \overline{v})^2\)</span>, where the rule of thumb is that you subtract one from the denominator for each parameter that you estimated. In this case, we estimated <span class="math inline">\(\mu\)</span>, so we subtract 1.</p>
<p>In our case, we have a random sample from a population with known mean 0, but we are estimating one parameter still, namely <span class="math inline">\(\beta\)</span>.
Recall that <span class="math inline">\(y_i \sim \beta x_i + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\)</span> are iid normal random variables with mean 0 and standard deviation <span class="math inline">\(\sigam\)</span>. Therefore, if we <strong>knew</strong> <span class="math inline">\(\beta\)</span>, it would be true that
<span class="math inline">\(y_i - \beta x_i \sim N(0, \sigma)\)</span>, and we could use that to estimate <span class="math inline">\(\sigma^2 \approx \frac 1n \sum_{i = 1}^n (y_i - \beta x_i)^2\)</span>. But, we don’t know <span class="math inline">\(\sigma\)</span>, so we have to approximate it with <span class="math inline">\(\hat \beta\)</span>, which means we subtract one from the downstairs. Our final guess is
<span class="math display">\[
\hat \sigma^2 = \frac 1{n - 1}\sum_{i = 1}^n \left(y_i - \hat \beta x_i\right)^2
\]</span>
Let’s check via simulation whether this is a good estimate.</p>
<p>We assume that the true generative process of the data is <span class="math inline">\(y = 2 * x + \epsilon\)</span>, where <span class="math inline">\(\epsilon \sim N(0, 3)\)</span>, so that <span class="math inline">\(\sigma^2 = 9\)</span>. We take a sample size of <span class="math inline">\(n = 100\)</span> as follows.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="classicaltheory.html#cb60-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4870</span>)</span>
<span id="cb60-2"><a href="classicaltheory.html#cb60-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb60-3"><a href="classicaltheory.html#cb60-3" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb60-4"><a href="classicaltheory.html#cb60-4" tabindex="-1"></a>beta_hat <span class="ot">&lt;-</span> <span class="fu">sum</span>(x <span class="sc">*</span> y) <span class="sc">/</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb60-5"><a href="classicaltheory.html#cb60-5" tabindex="-1"></a>sigma_hat <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">99</span> <span class="sc">*</span> <span class="fu">sum</span>((y <span class="sc">-</span> beta_hat <span class="sc">*</span> x)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb60-6"><a href="classicaltheory.html#cb60-6" tabindex="-1"></a>sigma_hat</span></code></pre></div>
<pre><code>## [1] 11.93586</code></pre>
<p>We get 11.9, which isn’t all that close to the correct value, but let’s see what happens on average if we repeat the process a bunch of times.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="classicaltheory.html#cb62-1" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb62-2"><a href="classicaltheory.html#cb62-2" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb62-3"><a href="classicaltheory.html#cb62-3" tabindex="-1"></a>  beta_hat <span class="ot">&lt;-</span> <span class="fu">sum</span>(x <span class="sc">*</span> y) <span class="sc">/</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb62-4"><a href="classicaltheory.html#cb62-4" tabindex="-1"></a>  sigma_hat <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">99</span> <span class="sc">*</span> <span class="fu">sum</span>((y <span class="sc">-</span> beta_hat <span class="sc">*</span> x)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb62-5"><a href="classicaltheory.html#cb62-5" tabindex="-1"></a>  sigma_hat</span>
<span id="cb62-6"><a href="classicaltheory.html#cb62-6" tabindex="-1"></a>})</span>
<span id="cb62-7"><a href="classicaltheory.html#cb62-7" tabindex="-1"></a><span class="fu">mean</span>(sigmas)</span></code></pre></div>
<pre><code>## [1] 9.011291</code></pre>
<p>We see that, on avereage, the estimate of <span class="math inline">\(\sigma^2\)</span> is right on! That is what we mean by an <strong>unbiased</strong> estimator of <span class="math inline">\(\sigma^2\)</span>.</p>
<div class="tryit">
<span class="divhead-plain tryit-before">Tryit 2.1</span>
<p>Show that <span class="math inline">\(\hat \sigma^2 = \frac 1n \sum_{i = 1}^n \left(y_i - 2 * x_i\right)^2\)</span> is an unbiased estimator for <span class="math inline">\(\sigma^2\)</span>, using the same set-up as above.</p>
</div>
<div class="exercise">
<span class="divhead-definition exercise-before"> 2.3</span>
<p><span id="exr:unnamed-chunk-38" class="exercise"><strong>Exercise 2.3  </strong></span>Suppose you wish to model data <span class="math inline">\((x_1, y_1), \ldots, (x_n, y_n)\)</span> by
<span class="math display">\[
y_i = \beta_0 + x_i + \epsilon_i  
\]</span>
<span class="math inline">\(\epsilon_i\)</span> are iid normal with mean 0 and standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>Find the <span class="math inline">\(\beta_0\)</span> that minimizes the SSE, <span class="math inline">\(\sum(y_i - (\beta_0 + x_i))^2\)</span> in terms of <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span>. Call this estimator <span class="math inline">\(\hat \beta_0\)</span>.</p></li>
<li><p>What kind of random variable is <span class="math inline">\(\hat \beta_0\)</span>? Be sure to include both its mean and standard deviation or variance (in terms of the <span class="math inline">\(x_i\)</span>).</p></li>
<li><p>Verify your answer via simulation when the true relationship is <span class="math inline">\(y = 2 + x + \epsilon\)</span>, where <span class="math inline">\(\epsilon\)</span> is normal with mean 0 and standard deviation 1.</p></li>
</ol>
</div>
</div>
<div id="the-full-model" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> The full model<a href="classicaltheory.html#the-full-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we discuss the model</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]</span></p>
<p>We minimize</p>
<p><span class="math display">\[
SSE(\beta_0, \beta_1) = \sum \bigl(y_i - (\beta_0 + \beta_1 x_i)\bigr)^2
\]</span>
over all choices of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> by taking the partials with respect to <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, setting equal to zero, and solving for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. We omit the details. But, here are the solutions that you obtain.</p>
<p><span class="math display">\[\hat \beta_0 = \overline{y} - \hat \beta_1 \overline{x}\]</span></p>
<p><span class="math display">\[\hat \beta_1 = \frac{\sum x_i y_i - \frac 1n \sum x_i \sum y_i}{\sum x_i^2 - \frac 1n \sum x_i \sum x_i}\]</span></p>
<p>As before, we can see that <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span> are linear combinations of the <span class="math inline">\(y_i\)</span>, so they are <strong>normal</strong> random variables. We won’t go through the algebraic details, but it is true that <span class="math inline">\(\hat \beta_0\)</span> is normal with mean <span class="math inline">\(\beta_0\)</span> and variance <span class="math inline">\(\sigma^2 \frac{\sum x_i^2}{n\sum x_i^2 - \sum x_i \sum x_i}\)</span>, while <span class="math inline">\(\hat \beta_1\)</span> is normal with mean <span class="math inline">\(\beta_1\)</span> and variance <span class="math inline">\(\frac{n\sigma^2}{n \sum x_i^2 - \sum x_i \sum x_i}\)</span>. Let’s check this with some simulations!</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="classicaltheory.html#cb64-1" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb64-2"><a href="classicaltheory.html#cb64-2" tabindex="-1"></a>sx <span class="ot">&lt;-</span> <span class="fu">sum</span>(xs)</span>
<span id="cb64-3"><a href="classicaltheory.html#cb64-3" tabindex="-1"></a>sx2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb64-4"><a href="classicaltheory.html#cb64-4" tabindex="-1"></a>ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb64-5"><a href="classicaltheory.html#cb64-5" tabindex="-1"></a><span class="fu">lm</span>(ys <span class="sc">~</span> xs)<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="co">#pulls out the intercept</span></span></code></pre></div>
<pre><code>## (Intercept) 
##  -0.3164941</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="classicaltheory.html#cb66-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb66-2"><a href="classicaltheory.html#cb66-2" tabindex="-1"></a>  ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb66-3"><a href="classicaltheory.html#cb66-3" tabindex="-1"></a>  <span class="fu">lm</span>(ys <span class="sc">~</span> xs)<span class="sc">$</span>coefficients[<span class="dv">1</span>]</span>
<span id="cb66-4"><a href="classicaltheory.html#cb66-4" tabindex="-1"></a>})</span>
<span id="cb66-5"><a href="classicaltheory.html#cb66-5" tabindex="-1"></a><span class="fu">mean</span>(sim_data) <span class="co">#should be close to 1</span></span></code></pre></div>
<pre><code>## [1] 1.003177</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="classicaltheory.html#cb68-1" tabindex="-1"></a><span class="fu">var</span>(sim_data) <span class="co">#should be close to:</span></span></code></pre></div>
<pre><code>## [1] 1.416889</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="classicaltheory.html#cb70-1" tabindex="-1"></a>(<span class="dv">9</span> <span class="sc">*</span> <span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>))<span class="sc">/</span>(<span class="dv">30</span> <span class="sc">*</span> <span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(xs) <span class="sc">*</span> <span class="fu">sum</span>(xs))</span></code></pre></div>
<pre><code>## [1] 1.411109</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="classicaltheory.html#cb72-1" tabindex="-1"></a>sigma_b0 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((<span class="dv">9</span> <span class="sc">*</span> <span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>))<span class="sc">/</span>(<span class="dv">30</span> <span class="sc">*</span> <span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(xs) <span class="sc">*</span> <span class="fu">sum</span>(xs)))</span></code></pre></div>
<p>Let’s also plot it to double check normality.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="classicaltheory.html#cb73-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(sim_data))</span>
<span id="cb73-2"><a href="classicaltheory.html#cb73-2" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">1</span>, sigma_b0), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-40"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-40-1.png" alt="Two overlapping bell curves centered near 1: a black simulated density and a red theoretical normal curve. They match closely." width="672" />
<p class="caption">
Figure 2.15: Estimated density of 10,000 simulated intercept estimates beta-hat-0 (black) overlaid with the theoretical normal distribution with mean 1 and the derived standard deviation sigma_b0 (red). The close match confirms that beta-hat-0 is approximately normally distributed with the predicted parameters.
</p>
</div>
<p>We do a similar simulation for <span class="math inline">\(\beta_1\)</span> below.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="classicaltheory.html#cb74-1" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb74-2"><a href="classicaltheory.html#cb74-2" tabindex="-1"></a>sx <span class="ot">&lt;-</span> <span class="fu">sum</span>(xs)</span>
<span id="cb74-3"><a href="classicaltheory.html#cb74-3" tabindex="-1"></a>sx2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb74-4"><a href="classicaltheory.html#cb74-4" tabindex="-1"></a>ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb74-5"><a href="classicaltheory.html#cb74-5" tabindex="-1"></a><span class="fu">lm</span>(ys <span class="sc">~</span> xs)<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="co">#pulls out the intercept</span></span></code></pre></div>
<pre><code>##      xs 
## 1.93346</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="classicaltheory.html#cb76-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb76-2"><a href="classicaltheory.html#cb76-2" tabindex="-1"></a>  ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb76-3"><a href="classicaltheory.html#cb76-3" tabindex="-1"></a>  <span class="fu">lm</span>(ys <span class="sc">~</span> xs)<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb76-4"><a href="classicaltheory.html#cb76-4" tabindex="-1"></a>})</span>
<span id="cb76-5"><a href="classicaltheory.html#cb76-5" tabindex="-1"></a><span class="fu">mean</span>(sim_data) <span class="co">#should be close to 2</span></span></code></pre></div>
<pre><code>## [1] 1.998499</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="classicaltheory.html#cb78-1" tabindex="-1"></a><span class="fu">var</span>(sim_data) <span class="co">#should be close to:</span></span></code></pre></div>
<pre><code>## [1] 0.02673423</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="classicaltheory.html#cb80-1" tabindex="-1"></a>sigma_b1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((<span class="dv">9</span> <span class="sc">*</span> <span class="dv">30</span>)<span class="sc">/</span>(<span class="dv">30</span> <span class="sc">*</span> <span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(xs) <span class="sc">*</span> <span class="fu">sum</span>(xs)))</span>
<span id="cb80-2"><a href="classicaltheory.html#cb80-2" tabindex="-1"></a>sigma_b1<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.0275661</code></pre>
<p>And again, we plot the density and compare to normal curve.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="classicaltheory.html#cb82-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(sim_data))</span>
<span id="cb82-2"><a href="classicaltheory.html#cb82-2" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">2</span>, sigma_b1), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-42"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-42-1.png" alt="Two overlapping bell curves centered near 2: a black simulated density and a red theoretical normal curve, closely aligned." width="672" />
<p class="caption">
Figure 2.16: Estimated density of 10,000 simulated slope estimates beta-hat-1 from the full model (black) overlaid with the theoretical normal distribution with mean 2 and standard deviation sigma_b1 (red). The curves overlap closely, confirming the theoretical distribution.
</p>
</div>
<p>We can use this information to perform hypothesis tests and create confidence intervals!</p>
<div id="hypothesis-test-interlude" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Hypothesis Test Interlude<a href="classicaltheory.html#hypothesis-test-interlude" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall how hypothesis tests work. We have a probability distribution that depends on a parameter <span class="math inline">\(\alpha\)</span>, say. There is some default, or conventional wisdom, idea about the value of <span class="math inline">\(\alpha\)</span>. We call this value <span class="math inline">\(\alpha_0\)</span>. We are testing whether <span class="math inline">\(\alpha = \alpha_0\)</span> or whether <span class="math inline">\(\alpha \not= \alpha_0\)</span>. Formally, we vall <span class="math inline">\(H_0: \alpha = \alpha_0\)</span> the <em>null hypothesis</em> and <span class="math inline">\(H_a: \alpha \not= \alpha_0\)</span> the alternative
hypothesis.</p>
<p>The format of the hypothesis test works as follows. We create a <em>test statistic</em> <span class="math inline">\(T\)</span> that depends on the random sample we take and the parameter <span class="math inline">\(\alpha\)</span>. We need to be able to derive or simulate the probability density function of <span class="math inline">\(T\)</span>. When we do that, we then compute a <span class="math inline">\(p\)</span>-value, which is the probability of obtaining a test statistic <span class="math inline">\(T\)</span>, which is as likely or more unlikely than the one that we did compute, assuming that <span class="math inline">\(H_0\)</span> is true. If this <span class="math inline">\(p\)</span>-value is small, say less than <span class="math inline">\(.05\)</span>, then we <em>reject <span class="math inline">\(H_0\)</span></em> in favor of <span class="math inline">\(H_a\)</span>. Otherwise, we fail to reject <span class="math inline">\(H_0\)</span>.</p>
<p>In regression, it is common to do hypothesis tests on <span class="math inline">\(\beta_1\)</span>, the slope. It is less common to do them on the intercept, because often the intercept is harder to interpret in the context of a problem. Let’s return to the happiness data, which is stored in <code>happy</code>. We computed a line of best fit of <span class="math inline">\(y = -1.03 + 0.705 x\)</span>. A natural question to ask is whether the slope is actually zero, or whether it is not zero. Formally, we have the hypothesis test <span class="math inline">\(H_0: \beta_1 = 0\)</span> versus <span class="math inline">\(H_a: \beta_1 \not= 0\)</span>.
We need to assume, at this point, that the variance of <span class="math inline">\(\epsilon_i\)</span> is <strong>known</strong>. We will see below what to do when it is not known. We assume that the variance is 1/2, so that the standard deviation is <span class="math inline">\(1/\sqrt{2} \approx 0.71\)</span>. Recall that <span class="math inline">\(\hat \beta_1\)</span> is <strong>normal</strong> with mean <span class="math inline">\(\beta_1\)</span> and standard deviation <span class="math inline">\(\sqrt{\frac{n\sigma^2}{n \sum x_i^2 - \sum x_i \sum x_i}}\)</span>. In this case, <span class="math inline">\(n = 127\)</span> and <span class="math inline">\(\sigma^2 = 1/2.\)</span> Therefore, the standard deviation of <span class="math inline">\(\hat \beta_1\)</span> is</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="classicaltheory.html#cb83-1" tabindex="-1"></a>sigma_b1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((<span class="dv">127</span> <span class="sc">*</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)<span class="sc">/</span>(<span class="dv">127</span> <span class="sc">*</span> <span class="fu">sum</span>(happy<span class="sc">$</span>log_gdp_per_capita<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(happy<span class="sc">$</span>log_gdp_per_capita)<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<p>Under the null hypothesis, we have that the <strong>mean</strong> of <span class="math inline">\(\hat \beta_1\)</span> is 0. So, if the null hypothesis is true, then <span class="math inline">\(\hat \beta_1\)</span> is normal with mean 0 and standard deviation about 0.053. Let’s plot the pdf.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="classicaltheory.html#cb84-1" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">0</span>, <span class="fl">0.053</span>), </span>
<span id="cb84-2"><a href="classicaltheory.html#cb84-2" tabindex="-1"></a>      <span class="at">from =</span> <span class="sc">-</span>.<span class="dv">8</span>, </span>
<span id="cb84-3"><a href="classicaltheory.html#cb84-3" tabindex="-1"></a>      <span class="at">to =</span> <span class="fl">0.8</span>,</span>
<span id="cb84-4"><a href="classicaltheory.html#cb84-4" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">&quot;likelihood&quot;</span>, </span>
<span id="cb84-5"><a href="classicaltheory.html#cb84-5" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;pdf of beta1 hat&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-44"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-44-1.png" alt="A narrow bell curve centered at 0, with the x-axis ranging from about -0.8 to 0.8. The curve is very tall and tight, showing that values as large as 0.705 would be in the extreme right tail." width="672" />
<p class="caption">
Figure 2.17: The probability density function of beta-hat-1 under the null hypothesis that beta-1 = 0, assuming known variance. The curve is a narrow normal distribution centered at 0 with standard deviation approximately 0.053. The observed slope of 0.705 falls far in the right tail, making it an extremely unlikely value under the null hypothesis.
</p>
</div>
<p>It is <strong>very</strong> unlikely that the computed slope would be 0.705 or larger! The <span class="math inline">\(p\)</span>-value is obtained by computing the probability of getting 0.705 or larger given that <span class="math inline">\(H_0\)</span> is true.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="classicaltheory.html#cb85-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">0.705</span>, <span class="dv">0</span>, .<span class="dv">053</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 1.1285e-40</code></pre>
<p>Wow! To be fair, we would also want to see the probability of getting less than -0.705, and add it to the above.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="classicaltheory.html#cb87-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">0.705</span>, <span class="dv">0</span>, .<span class="dv">053</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb87-2"><a href="classicaltheory.html#cb87-2" tabindex="-1"></a>  <span class="fu">pnorm</span>(<span class="sc">-</span>.<span class="dv">705</span>, <span class="dv">0</span>, .<span class="dv">053</span>)</span></code></pre></div>
<pre><code>## [1] 2.257e-40</code></pre>
<p>Our <span class="math inline">\(p\)</span>-value is <span class="math inline">\(2.257 \times 10^{-40}\)</span>. We reject <span class="math inline">\(H_0\)</span> and conclude that the slope is not zero.</p>
<p>That’s all well and good, <strong>but</strong>… We <em>don’t</em> know what <span class="math inline">\(\sigma\)</span> is at all in this setting. We need to figure out how to estimate <span class="math inline">\(\sigma\)</span>, and we need to figure out how that affects our <span class="math inline">\(p\)</span>-value computation!!</p>
<p>We start with figuring out how to estimate <span class="math inline">\(\sigma^2\)</span>. Let’s suppose that our data comes from <span class="math inline">\(y_i = 1 + 2 * x_i + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\)</span> is normal with mean 0 and standard deviation 3. We don’t assume that we know any of that information. But, if we <strong>did</strong> know <span class="math inline">\(\beta_0 = 1\)</span> and <span class="math inline">\(\beta_1 = 2\)</span>, then we could compute <span class="math inline">\(y_i - (1 + 2 * x_i)\)</span>, and that would be a random sample from <span class="math inline">\(\epsilon\)</span>! We could use <code>sd</code> to estimate the standard deviation or <code>var</code> to estimate the variance! Our idea, then, is to <em>estimate</em> <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span>, and then <span class="math inline">\(y_i - (\hat \beta_0 + \hat \beta_1 x_i)\)</span> is an <em>estimate</em> of a sample from <span class="math inline">\(\epsilon_i\)</span>! Maybe a good estimate for <span class="math inline">\(\sigma^2\)</span> would be to use <code>var</code> on that!</p>
<p>Notationally, we call <span class="math inline">\(y_i - (\hat \beta_0 + \hat \beta_1 x_i)\)</span> the <em>residuals</em> of the model.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="classicaltheory.html#cb89-1" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb89-2"><a href="classicaltheory.html#cb89-2" tabindex="-1"></a>ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb89-3"><a href="classicaltheory.html#cb89-3" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ys <span class="sc">~</span> xs)<span class="sc">$</span>coefficients[<span class="dv">1</span>]</span>
<span id="cb89-4"><a href="classicaltheory.html#cb89-4" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ys <span class="sc">~</span> xs)<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb89-5"><a href="classicaltheory.html#cb89-5" tabindex="-1"></a>ys <span class="sc">-</span> (beta_0 <span class="sc">+</span> beta_1 <span class="sc">*</span> xs)</span></code></pre></div>
<pre><code>##  [1] -0.1014982  2.5698578  3.6383951  0.7602879  1.6966693  1.2972465
##  [7] -5.7590968  0.3032853 -2.3750249  0.4603466  1.6151087  1.5963561
## [13] -3.3464870  0.5418336 -2.8979343  2.6085748 -1.5130296  4.3724794
## [19] -1.3967273  2.0385085 -2.5307011 -0.2403657 -2.1609787  2.7163617
## [25]  1.9960806 -2.7550912  1.4334889 -3.8552792  0.8306420 -1.5433087</code></pre>
<p>Now, to estimate <span class="math inline">\(\sigma^2\)</span>, we could use the <code>var</code> function.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="classicaltheory.html#cb91-1" tabindex="-1"></a><span class="fu">var</span>(ys <span class="sc">-</span> (beta_0 <span class="sc">+</span> beta_1 <span class="sc">*</span> xs)) <span class="co">#true value is 9</span></span></code></pre></div>
<pre><code>## [1] 5.984329</code></pre>
<p>Let’s put this inside of <code>replicate</code> to see whether this is an unbiased estimator of <span class="math inline">\(\sigma^2\)</span>.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="classicaltheory.html#cb93-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb93-2"><a href="classicaltheory.html#cb93-2" tabindex="-1"></a>  ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb93-3"><a href="classicaltheory.html#cb93-3" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(ys <span class="sc">~</span> xs)</span>
<span id="cb93-4"><a href="classicaltheory.html#cb93-4" tabindex="-1"></a>  beta_0 <span class="ot">&lt;-</span> mod<span class="sc">$</span>coefficients[<span class="dv">1</span>]</span>
<span id="cb93-5"><a href="classicaltheory.html#cb93-5" tabindex="-1"></a>  beta_1 <span class="ot">&lt;-</span> mod<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb93-6"><a href="classicaltheory.html#cb93-6" tabindex="-1"></a>  <span class="fu">var</span>(ys <span class="sc">-</span> (beta_0 <span class="sc">+</span> beta_1 <span class="sc">*</span> xs))</span>
<span id="cb93-7"><a href="classicaltheory.html#cb93-7" tabindex="-1"></a>})</span>
<span id="cb93-8"><a href="classicaltheory.html#cb93-8" tabindex="-1"></a><span class="fu">mean</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 8.701956</code></pre>
<p>Hmmm, it looks like it is <strong>too small</strong>. It can be provent hat estimating <span class="math inline">\(\sigma^2\)</span> in this way is a <strong>biased</strong> way to do it. The formula for <code>var</code> is <span class="math inline">\(\frac {1}{n-1} \sum_{i = 1}^n (x_i - \overline{x})^2\)</span>. There is a rule of thumb that, for each parameter that you estimate, you need to subtract one from the <span class="math inline">\(n\)</span> in the denominator in front of the sum. Since we are estimating <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, we would need to subtract 2 from <span class="math inline">\(n\)</span>. In other words, we need to multiple <code>var</code> by <span class="math inline">\(\frac {n-1}{n-2}\)</span>.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="classicaltheory.html#cb95-1" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb95-2"><a href="classicaltheory.html#cb95-2" tabindex="-1"></a>  ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb95-3"><a href="classicaltheory.html#cb95-3" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(ys <span class="sc">~</span> xs)</span>
<span id="cb95-4"><a href="classicaltheory.html#cb95-4" tabindex="-1"></a>  beta_0 <span class="ot">&lt;-</span> mod<span class="sc">$</span>coefficients[<span class="dv">1</span>]</span>
<span id="cb95-5"><a href="classicaltheory.html#cb95-5" tabindex="-1"></a>  beta_1 <span class="ot">&lt;-</span> mod<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb95-6"><a href="classicaltheory.html#cb95-6" tabindex="-1"></a>  <span class="fu">var</span>(ys <span class="sc">-</span> (beta_0 <span class="sc">+</span> beta_1 <span class="sc">*</span> xs)) <span class="sc">*</span> <span class="dv">29</span><span class="sc">/</span><span class="dv">28</span></span>
<span id="cb95-7"><a href="classicaltheory.html#cb95-7" tabindex="-1"></a>})</span>
<span id="cb95-8"><a href="classicaltheory.html#cb95-8" tabindex="-1"></a><span class="fu">mean</span>(sim_data)</span></code></pre></div>
<pre><code>## [1] 8.964182</code></pre>
<p>That looks better! That is our unbiased estimator of <span class="math inline">\(\sigma^2\)</span>! What kind of rv is <span class="math inline">\(\hat \sigma^2\)</span>, which is more commonly denoted <span class="math inline">\(S^2\)</span>. Well. <span class="math inline">\(S^2\)</span> itself is not one that we are familiar with, but <span class="math inline">\((n - 2) S^2/\sigma^2\)</span> is a <span class="math inline">\(\chi^2\)</span> random variable with <span class="math inline">\(n - 2\)</span> degrees of freedom.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="classicaltheory.html#cb97-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(<span class="dv">28</span> <span class="sc">*</span> sim_data<span class="sc">/</span><span class="dv">9</span>))</span>
<span id="cb97-2"><a href="classicaltheory.html#cb97-2" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dchisq</span>(x, <span class="dv">28</span>), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-51"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-51-1.png" alt="Two overlapping right-skewed curves: a black simulated density and a red chi-squared(28) curve. Both peak around x = 26-28 and have a long right tail. They align closely." width="672" />
<p class="caption">
Figure 2.18: Estimated density of the scaled variance estimator (n-2) S-squared divided by sigma-squared from simulation (black), overlaid with the chi-squared distribution with 28 degrees of freedom (red). The curves match closely, confirming the theoretical result that the scaled estimator follows a chi-squared distribution.
</p>
</div>
<p>Now, we are ready to do actual hypothesis testing on the slope without assuming that we know the underlying variance.</p>
<p>:::{.theorem, #betazerodist}
Let <span class="math inline">\((x_1, y_1), \ldots, (x_n, y_n)\)</span> be a random sample from the model
<span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i  
\]</span>
where <span class="math inline">\(\epsilon_i\)</span> are iid normal random variables with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>. Then,
<span class="math display">\[
\frac{\hat \beta_1 - \beta_1}{\sqrt{\frac{n S^2}{n \sum x_i^2 - \sum x_i \sum x_i}}}
\]</span>
follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n - 2\)</span> degrees of freedom.
:::</p>
<p>To prove this, we will once again use simulations. We assume <span class="math inline">\(\beta_0 = 1\)</span>, <span class="math inline">\(\beta_1 = 2\)</span> and <span class="math inline">\(\sigma = 3\)</span>.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="classicaltheory.html#cb98-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb98-2"><a href="classicaltheory.html#cb98-2" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb98-3"><a href="classicaltheory.html#cb98-3" tabindex="-1"></a>  ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb98-4"><a href="classicaltheory.html#cb98-4" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(ys <span class="sc">~</span> xs)</span>
<span id="cb98-5"><a href="classicaltheory.html#cb98-5" tabindex="-1"></a>  beta_1 <span class="ot">&lt;-</span> mod<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb98-6"><a href="classicaltheory.html#cb98-6" tabindex="-1"></a>  a <span class="ot">&lt;-</span> <span class="fu">summary</span>(mod)</span>
<span id="cb98-7"><a href="classicaltheory.html#cb98-7" tabindex="-1"></a>  (beta_1 <span class="sc">-</span> <span class="dv">2</span>)<span class="sc">/</span>(<span class="fu">sqrt</span>(n <span class="sc">*</span> a<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(n <span class="sc">*</span> <span class="fu">sum</span>(xs<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(xs)<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb98-8"><a href="classicaltheory.html#cb98-8" tabindex="-1"></a>})</span>
<span id="cb98-9"><a href="classicaltheory.html#cb98-9" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(sim_data))</span>
<span id="cb98-10"><a href="classicaltheory.html#cb98-10" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dt</span>(x, <span class="dv">28</span>), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-52"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-52-1.png" alt="Two overlapping bell-shaped curves centered at 0 with heavier tails than a normal distribution: a black simulated density and a red t(28) curve. They match closely." width="672" />
<p class="caption">
Figure 2.19: Estimated density of the standardized slope estimator (beta-hat-1 minus 2) divided by its standard error, from 10,000 simulations (black), overlaid with the t distribution with 28 degrees of freedom (red). The close match confirms Theorem betazerodist: the standardized slope estimator follows a t distribution.
</p>
</div>
<div class="example">
<span class="divhead-definition example-before">Example 2.1</span>
<p><span id="exm:unnamed-chunk-53" class="example"><strong>Example 2.1  </strong></span>Using the <span class="math inline">\(t\)</span> distribution to do a hypothesis test.</p>
</div>
<p>We consider the happiness data set again. Our model is <span class="math inline">\(y_i = \beta_0 + beta_1 x_i + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\)</span> are iid normal with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>. The null hypothesis is <span class="math inline">\(H_0: \beta_1 = 0\)</span> and the alternative is <span class="math inline">\(H_0: \beta_1 \not= 0\)</span>. Theorem <a href="#thm:betazerodist"><strong>??</strong></a> tells us that the <strong>test statistic</strong>
<span class="math display">\[
\frac{\hat \beta_1 - \beta_1}{\sqrt{\frac{n S^2}{n \sum x_i^2 - \sum x_i \sum x_i}}}
\]</span>
is <span class="math inline">\(t\)</span> with 125 degrees of freedom, since there are 127 observations in <code>happy</code>.</p>
<p>We compute the value of the test statistic by putting in our estimate for <span class="math inline">\(\hat \beta_1\)</span>, which we can pull out of <code>lm</code> as 0.7046, and our estimate for <span class="math inline">\(S^2\)</span>.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="classicaltheory.html#cb99-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_ladder <span class="sc">~</span> log_gdp_per_capita, <span class="at">data =</span> happy)</span>
<span id="cb99-2"><a href="classicaltheory.html#cb99-2" tabindex="-1"></a>beta_1_hat <span class="ot">&lt;-</span> mod<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb99-3"><a href="classicaltheory.html#cb99-3" tabindex="-1"></a>S <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(mod<span class="sc">$</span>residuals) <span class="sc">*</span> <span class="dv">126</span><span class="sc">/</span><span class="dv">125</span>)</span></code></pre></div>
<p>Therefore, the value of the test statistic is</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="classicaltheory.html#cb100-1" tabindex="-1"></a>(beta_1_hat <span class="sc">-</span> <span class="dv">0</span>)<span class="sc">/</span>(<span class="fu">sqrt</span>((<span class="dv">127</span> <span class="sc">*</span> S<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(<span class="dv">127</span> <span class="sc">*</span> <span class="fu">sum</span>(happy<span class="sc">$</span>log_gdp_per_capita<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(happy<span class="sc">$</span>log_gdp_per_capita)<span class="sc">^</span><span class="dv">2</span>)))</span></code></pre></div>
<pre><code>## log_gdp_per_capita 
##           13.08232</code></pre>
<p>That is, again, a very unlikely value for the test statistic that is <span class="math inline">\(t\)</span> with any degrees of freedom!!</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="classicaltheory.html#cb102-1" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dt</span>(x, <span class="dv">125</span>), <span class="at">from =</span> <span class="sc">-</span><span class="dv">21</span>, <span class="at">to =</span> <span class="dv">21</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-56"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-56-1.png" alt="A symmetric bell curve centered at 0 representing the t(125) distribution. The x-axis extends to ±21, but virtually all the density is between about -4 and 4, making the test statistic of 13 essentially invisible on the tail." width="672" />
<p class="caption">
Figure 2.20: The probability density function of the t distribution with 125 degrees of freedom, plotted from -21 to 21. The curve is symmetric and bell-shaped. The observed test statistic of approximately 13.08 falls far in the right tail, well outside the visible bulk of the distribution, indicating an extremely small p-value.
</p>
</div>
<p>To compute the <span class="math inline">\(p\)</span>-value, we use <code>pt</code> as follows:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="classicaltheory.html#cb103-1" tabindex="-1"></a><span class="fu">pt</span>(<span class="fl">13.08232</span>, <span class="dv">125</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 3.604795e-25</code></pre>
<p>And, we would reject the null hypothesis at any reasonable <span class="math inline">\(\alpha\)</span> level. However, note that the <span class="math inline">\(p\)</span>-value is 15 orders of magnitude greater than the <span class="math inline">\(p\)</span>-value that we computed when we assumed that we knew <span class="math inline">\(\sigma\)</span>. That is quite substantial!</p>
<div class="exercise">
<span class="divhead-definition exercise-before"> 2.4</span>
<p><span id="exr:unnamed-chunk-58" class="exercise"><strong>Exercise 2.4  </strong></span>Consider the data set <code>HistData::Galton</code> that we looked at briefly. Assume the model <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \epsilon_i\)</span>, and do a hypothesis test of <span class="math inline">\(H_0: \beta_1 = 1\)</span> versus <span class="math inline">\(H_a: \beta_1 \not= 1\)</span>. Explain what this means in the context of the data.</p>
</div>
</div>
</div>
<div id="using-different-loss-functions" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Using different loss functions<a href="classicaltheory.html#using-different-loss-functions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we return to the model
<span class="math display">\[
y = \beta_0 + \beta_1 x + \epsilon
\]</span>
where <span class="math inline">\(\epsilon\)</span> is normal with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>.</p>
<p>We show how to get values for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that minimize
<span class="math display">\[
\sum_{i = 1}^n g(y_i - (\beta_0 + \beta_1 x_i))^2
\]</span>
where <span class="math inline">\(g\)</span> is <em>even</em>, <span class="math inline">\(g\)</span> is decreasing for <span class="math inline">\(x \le 0\)</span>, and increasing for <span class="math inline">\(x \ge 0\)</span>. Examples of <span class="math inline">\(g\)</span> were given above, such as <span class="math inline">\(g(x) = x^2\)</span>, <span class="math inline">\(g(x) = |x|\)</span>, or any of the 4 plots in the graph here.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="classicaltheory.html#cb105-1" tabindex="-1"></a><span class="fu">curve</span>(x<span class="sc">^</span><span class="dv">2</span>, <span class="at">from =</span> <span class="sc">-</span><span class="dv">4</span>, <span class="at">to =</span> <span class="dv">4</span>, <span class="at">col =</span> <span class="dv">1</span>,</span>
<span id="cb105-2"><a href="classicaltheory.html#cb105-2" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;Common Loss Functions&quot;</span>) <span class="co">#black</span></span>
<span id="cb105-3"><a href="classicaltheory.html#cb105-3" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">abs</span>(x), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>) <span class="co">#red</span></span>
<span id="cb105-4"><a href="classicaltheory.html#cb105-4" tabindex="-1"></a>delta <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb105-5"><a href="classicaltheory.html#cb105-5" tabindex="-1"></a><span class="fu">curve</span>(delta<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span>(<span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">+</span> (x<span class="sc">/</span>delta)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="dv">1</span>),</span>
<span id="cb105-6"><a href="classicaltheory.html#cb105-6" tabindex="-1"></a>      <span class="at">add=</span> T,</span>
<span id="cb105-7"><a href="classicaltheory.html#cb105-7" tabindex="-1"></a>      <span class="at">col =</span> <span class="dv">3</span>) <span class="co">#green</span></span>
<span id="cb105-8"><a href="classicaltheory.html#cb105-8" tabindex="-1"></a><span class="fu">curve</span>(robustbase<span class="sc">::</span><span class="fu">Mchi</span>(x, <span class="at">cc =</span> <span class="fl">1.6</span>, <span class="at">psi =</span> <span class="st">&quot;bisquare&quot;</span>),</span>
<span id="cb105-9"><a href="classicaltheory.html#cb105-9" tabindex="-1"></a>      <span class="at">add=</span> T, </span>
<span id="cb105-10"><a href="classicaltheory.html#cb105-10" tabindex="-1"></a>      <span class="at">col =</span> <span class="dv">4</span>) <span class="co">#bue</span></span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-59"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-59-1.png" alt="Four curves on the same axes. The black parabola grows fastest; the red V-shape grows linearly; the green pseudo-Huber is intermediate; the blue bisquare flattens out for large errors." width="672" />
<p class="caption">
Figure 2.21: Four common loss functions plotted over x from -4 to 4. Black: squared error, a parabola. Red: absolute value (L1), a V-shape. Green: pseudo-Huber with delta=2, quadratic near zero and linear in the tails. Blue: Tukey bisquare with cc=1.6, which plateaus and caps the penalty for large errors.
</p>
</div>
<p>Let’s find the values of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that minimize the <span class="math inline">\(L^1\)</span> error, which is
<span class="math display">\[
\sum \bigl|y_i - (\beta_0 + \beta_1 x_i)|
\]</span>
in the happiness data set. We will also compare that to the values we got using SSE. Recall that the data is stored in `happy.</p>
<p>As a reminder, we can get the SSE estimator for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> via <code>lm</code> as follows.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="classicaltheory.html#cb106-1" tabindex="-1"></a><span class="fu">lm</span>(life_ladder <span class="sc">~</span> log_gdp_per_capita, <span class="at">data =</span> happy)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = life_ladder ~ log_gdp_per_capita, data = happy)
## 
## Coefficients:
##        (Intercept)  log_gdp_per_capita  
##            -1.0285              0.7046</code></pre>
<p>The usage <code>y ~ x</code> is read as “y as described by x” and the <em>response</em> variable always comes first. The predictor(s) come after the <code>~</code>.</p>
<p>Now let’s minimize the <span class="math inline">\(L^1\)</span> error. We start by defining our loss function, <span class="math inline">\(g\)</span>.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="classicaltheory.html#cb108-1" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb108-2"><a href="classicaltheory.html#cb108-2" tabindex="-1"></a>  <span class="fu">abs</span>(x)</span>
<span id="cb108-3"><a href="classicaltheory.html#cb108-3" tabindex="-1"></a>}</span></code></pre></div>
<p>Then, we define our total <span class="math inline">\(L^1\)</span> error as</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="classicaltheory.html#cb109-1" tabindex="-1"></a>loss_two <span class="ot">&lt;-</span> <span class="cf">function</span>(b0, b1) {</span>
<span id="cb109-2"><a href="classicaltheory.html#cb109-2" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">g</span>(happy<span class="sc">$</span>life_ladder <span class="sc">-</span> (b0 <span class="sc">+</span> b1 <span class="sc">*</span> happy<span class="sc">$</span>log_gdp_per_capita)))</span>
<span id="cb109-3"><a href="classicaltheory.html#cb109-3" tabindex="-1"></a>}</span></code></pre></div>
<p>As before, we have to re-write this function to only accept a single argument because that is how <code>optim</code> works.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="classicaltheory.html#cb110-1" tabindex="-1"></a>loss_one <span class="ot">&lt;-</span> <span class="cf">function</span>(b) {</span>
<span id="cb110-2"><a href="classicaltheory.html#cb110-2" tabindex="-1"></a>  <span class="fu">loss_two</span>(b[<span class="dv">1</span>], b[<span class="dv">2</span>])</span>
<span id="cb110-3"><a href="classicaltheory.html#cb110-3" tabindex="-1"></a>}</span></code></pre></div>
<p>Now we are ready! We need to provide a guess to <code>optim</code> and the function we are minimizing. Let’s try a slope of 1 and an intercept of 0.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="classicaltheory.html#cb111-1" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">fn =</span> loss_one)</span></code></pre></div>
<pre><code>## $par
## [1] -0.8373535  0.6910757
## 
## $value
## [1] 73.30576
## 
## $counts
## function gradient 
##       97       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We see that “the” line of best fit in this case is <span class="math inline">\(y = -0.837  0.691 x\)</span> rather than <span class="math inline">\(y =  -1.03 + 0.705 x\)</span>. I will leave it to you to decide whether the difference between those coefficients is meaningful. Let’s plot both lines.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="classicaltheory.html#cb113-1" tabindex="-1"></a><span class="fu">ggplot</span>(happy, <span class="fu">aes</span>(<span class="at">x =</span> log_gdp_per_capita, <span class="at">y =</span> life_ladder)) <span class="sc">+</span></span>
<span id="cb113-2"><a href="classicaltheory.html#cb113-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb113-3"><a href="classicaltheory.html#cb113-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="co">#SSE minimizer</span></span>
<span id="cb113-4"><a href="classicaltheory.html#cb113-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="fl">0.691</span>, <span class="at">intercept =</span> <span class="sc">-</span><span class="fl">0.837</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-65"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-65-1.png" alt="Scatterplot with two nearly parallel upward-sloping lines. The blue SSE line is pulled slightly toward low-happiness outliers; the black L1 line is more resistant to them." width="672" />
<p class="caption">
Figure 2.22: Scatterplot of happiness versus log GDP per capita with two overlaid lines of best fit: the blue line minimizes SSE (via lm), and the black line minimizes the L1 error (via optim). The two lines are similar but not identical — the L1 line is slightly less influenced by countries with unusually low happiness for their income level.
</p>
</div>
<p>What is happening? Well, when we look at the scatterplot, we see that there are some countries with abnormally low happiness for their gdp. The SSE worries about fitting those points more than the <span class="math inline">\(L^1\)</span> error does, and the corresponding line that minimizes SSE is closer to those points that are kind of far away from the lines. This behavior can either be a feature or a bug for the method chosen. Or both.</p>
<p>Next up, we look at the <em>psuedo-Huber loss function</em> <span class="math inline">\(g(x) = \delta^2 \sqrt{1 + (x/\delta)^2} - \delta^2\)</span>. In this loss function, there is a parameter <span class="math inline">\(\delta\)</span> that we can use to adjust the function. Let’s plot it for a few different values of <span class="math inline">\(\delta\)</span>.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="classicaltheory.html#cb115-1" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="dv">1</span>, <span class="at">from =</span> <span class="sc">-</span><span class="dv">5</span>, <span class="at">to =</span> <span class="dv">5</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>))</span>
<span id="cb115-2"><a href="classicaltheory.html#cb115-2" tabindex="-1"></a>delta <span class="ot">=</span> .<span class="dv">5</span></span>
<span id="cb115-3"><a href="classicaltheory.html#cb115-3" tabindex="-1"></a><span class="fu">curve</span>(delta<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>delta<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> delta<span class="sc">^</span><span class="dv">2</span>, <span class="at">add=</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span>
<span id="cb115-4"><a href="classicaltheory.html#cb115-4" tabindex="-1"></a>delta <span class="ot">=</span> <span class="dv">2</span></span>
<span id="cb115-5"><a href="classicaltheory.html#cb115-5" tabindex="-1"></a><span class="fu">curve</span>(delta<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>delta<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> delta<span class="sc">^</span><span class="dv">2</span>, <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">3</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-66"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-66-1.png" alt="Three smooth curves symmetric around x=0 and y=0. The red curve (delta=0.5) grows most steeply and linearly; the green curve (delta=2) is most parabolic near zero; the black curve (delta=1) is intermediate." width="672" />
<p class="caption">
Figure 2.23: Three pseudo-Huber loss functions plotted for delta = 1 (black), delta = 0.5 (red), and delta = 2 (green). All three are symmetric, equal zero at x = 0, and grow as x moves away from zero. Smaller delta values make the function behave more like L1 (linear growth); larger delta values make it behave more like squared error (quadratic growth).
</p>
</div>
<p>This loss function combines elements of both SSE and <span class="math inline">\(L^1\)</span>. When the error <span class="math inline">\(y_i - (\beta_0 + \beta_1 x_i)\)</span> is small, we get behavior that looks like a quadratic <span class="math inline">\(g(x) = x^2\)</span>. When the error is large, <span class="math inline">\(g\)</span> flattens out and looks like a straight line. When <span class="math inline">\(\delta\)</span> is small, the loss function behaves like <span class="math inline">\(L^1\)</span>, and when <span class="math inline">\(\delta\)</span> is big, it behaves like SSE.</p>
<p>This loss function is an attempt to strike a balance between the two methods that we have seen so far. With the set-up from above, we only need to change the function <span class="math inline">\(g\)</span> to find the lines of best fit.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="classicaltheory.html#cb116-1" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb116-2"><a href="classicaltheory.html#cb116-2" tabindex="-1"></a>  delta<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>delta<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> delta<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb116-3"><a href="classicaltheory.html#cb116-3" tabindex="-1"></a>}</span></code></pre></div>
<p>Now we can try this with a few different values of <span class="math inline">\(\delta\)</span>. Remember, when <span class="math inline">\(\delta\)</span> is small, we expect to get results similar to what we got with <span class="math inline">\(L^1\)</span>, and when <span class="math inline">\(\delta\)</span> is big, we expect to get similar to SSE, which as a reminder, were <span class="math inline">\(y = -0.837  0.691 x\)</span> rather than <span class="math inline">\(y =  -1.03 + 0.705 x\)</span></p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="classicaltheory.html#cb117-1" tabindex="-1"></a>delta <span class="ot">=</span> .<span class="dv">1</span></span>
<span id="cb117-2"><a href="classicaltheory.html#cb117-2" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">fn =</span> loss_one)</span></code></pre></div>
<pre><code>## $par
## [1] -0.8740431  0.6934752
## 
## $value
## [1] 6.284509
## 
## $counts
## function gradient 
##       77       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="classicaltheory.html#cb119-1" tabindex="-1"></a>delta <span class="ot">=</span> <span class="fl">1.345</span></span>
<span id="cb119-2"><a href="classicaltheory.html#cb119-2" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">fn =</span> loss_one)</span></code></pre></div>
<pre><code>## $par
## [1] -1.0306062  0.7062522
## 
## $value
## [1] 27.88364
## 
## $counts
## function gradient 
##       75       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>Indeed, we do get similar results, though not identical. If we are thinking of using this loss function, then we probably want to choose a value of <span class="math inline">\(\delta\)</span> that gives results that are in-between the two extremes, in some sense. The package <code>rlm</code> automates this, not from the point of view of trying to always get something in between, but from the point of view of controling outlier effects.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="classicaltheory.html#cb121-1" tabindex="-1"></a>MASS<span class="sc">::</span><span class="fu">rlm</span>(life_ladder <span class="sc">~</span> log_gdp_per_capita, </span>
<span id="cb121-2"><a href="classicaltheory.html#cb121-2" tabindex="-1"></a>    <span class="at">data =</span> happy, </span>
<span id="cb121-3"><a href="classicaltheory.html#cb121-3" tabindex="-1"></a>    <span class="at">psi =</span> MASS<span class="sc">::</span>psi.huber)</span></code></pre></div>
<pre><code>## Call:
## rlm(formula = life_ladder ~ log_gdp_per_capita, data = happy, 
##     psi = MASS::psi.huber)
## Converged in 4 iterations
## 
## Coefficients:
##        (Intercept) log_gdp_per_capita 
##         -1.0560121          0.7091396 
## 
## Degrees of freedom: 127 total; 125 residual
## Scale estimate: 0.837</code></pre>
<p>We see that we don’
coefficients that are in between the two sets of coefficients that we computed previously. However, I believe that <code>MASS</code> implements the true Huber loss function, rather than the psuedo-Huber loss function that we implemented above so we aren’t really comparing apples to apples.</p>
<p>The <code>rlm</code> function also implements <code>psi.bisquare</code>, which is Tukey’s bi-square function. This loss function also has a parameter, which is denoted by <code>cc</code> in the <code>robustbase</code> package. Here are some plots.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="classicaltheory.html#cb123-1" tabindex="-1"></a><span class="fu">curve</span>(robustbase<span class="sc">::</span><span class="fu">Mchi</span>(x, <span class="at">cc =</span> <span class="dv">1</span>, <span class="at">psi =</span> <span class="st">&quot;bisquare&quot;</span>), <span class="at">from =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">to =</span> <span class="dv">2</span>)</span>
<span id="cb123-2"><a href="classicaltheory.html#cb123-2" tabindex="-1"></a><span class="fu">curve</span>(robustbase<span class="sc">::</span><span class="fu">Mchi</span>(x, <span class="at">cc =</span> <span class="fl">0.5</span>, <span class="at">psi =</span> <span class="st">&quot;bisquare&quot;</span>), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span>
<span id="cb123-3"><a href="classicaltheory.html#cb123-3" tabindex="-1"></a><span class="fu">curve</span>(robustbase<span class="sc">::</span><span class="fu">Mchi</span>(x, <span class="at">cc =</span> <span class="dv">2</span>, <span class="at">psi =</span> <span class="st">&quot;bisquare&quot;</span>), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">3</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-71"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-71-1.png" alt="Three smooth curves that rise from zero, reach a flat maximum, and stay flat. The red curve (cc=0.5) plateaus closest to zero; the green curve (cc=2) plateaus furthest out; the black (cc=1) is in between." width="672" />
<p class="caption">
Figure 2.24: Three Tukey bisquare loss functions with different cc parameters: cc=1 (black), cc=0.5 (red), cc=2 (green). All three rise from zero at x=0 and then plateau at a maximum of 1. The cc parameter controls where the plateau begins: smaller cc values plateau sooner, meaning errors beyond that threshold are all penalized equally.
</p>
</div>
<p>The thing to know about this loss function is that for “small” errors, the loss function behaves like SSE. But, there is a maximum error allowed of 1, and the <code>cc</code> parameter gives the value of the raw error that corresponds to when the loss function starts equaling 1. In other words, if <code>cc = 1</code>, then all errors between observed and predicted that are bigger than 1 are penalized the same amount! This has the benefit of limiting the impact that a single (or multiple) outliers can have on the estimation of the line of best fit. Let’s first look at what happens with the happiness data, then we’ll switch over to simulated data.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="classicaltheory.html#cb124-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="classicaltheory.html#cb127-1" tabindex="-1"></a><span class="fu">rlm</span>(life_ladder <span class="sc">~</span> log_gdp_per_capita, <span class="at">data =</span> happy, <span class="at">psi =</span> psi.bisquare)</span></code></pre></div>
<pre><code>## Call:
## rlm(formula = life_ladder ~ log_gdp_per_capita, data = happy, 
##     psi = psi.bisquare)
## Converged in 4 iterations
## 
## Coefficients:
##        (Intercept) log_gdp_per_capita 
##         -1.0410932          0.7076074 
## 
## Degrees of freedom: 127 total; 125 residual
## Scale estimate: 0.839</code></pre>
<p>We don’t see a big change by doing it like this.</p>
<p>Now let’s set up a funky simulated data set.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="classicaltheory.html#cb129-1" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">20</span>, <span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>)</span>
<span id="cb129-2"><a href="classicaltheory.html#cb129-2" tabindex="-1"></a>ys <span class="ot">&lt;-</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">0</span>, .<span class="dv">5</span>)</span>
<span id="cb129-3"><a href="classicaltheory.html#cb129-3" tabindex="-1"></a><span class="fu">plot</span>(xs, ys)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-73"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-73-1.png" alt="Scatterplot of 20 points tightly clustered around the line y = x, ranging from about -5 to 5 on both axes." width="672" />
<p class="caption">
Figure 2.25: Scatterplot of 20 simulated data points where y is approximately equal to x plus small random noise. The points fall tightly along a diagonal line from lower-left to upper-right, indicating a strong positive linear relationship.
</p>
</div>
<p>This data looks a lot like <span class="math inline">\(y = x\)</span>. Indeed,</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="classicaltheory.html#cb130-1" tabindex="-1"></a><span class="fu">lm</span>(ys <span class="sc">~</span> xs)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs)
## 
## Coefficients:
## (Intercept)           xs  
##     -0.1094       1.0060</code></pre>
<p>Let’s see what happens when we add an outlier that changes it to look like possible <span class="math inline">\(y = -x\)</span>.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="classicaltheory.html#cb132-1" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">c</span>(xs, <span class="sc">-</span><span class="dv">10</span>)</span>
<span id="cb132-2"><a href="classicaltheory.html#cb132-2" tabindex="-1"></a>ys <span class="ot">&lt;-</span> <span class="fu">c</span>(ys, <span class="dv">10</span>)</span>
<span id="cb132-3"><a href="classicaltheory.html#cb132-3" tabindex="-1"></a><span class="fu">plot</span>(xs, ys)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-75"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-75-1.png" alt="Scatterplot with 20 points along a positive diagonal and one isolated point in the upper-left corner at about x=-10, y=10, suggesting a conflicting negative trend." width="672" />
<p class="caption">
Figure 2.26: Scatterplot after adding one extreme outlier at approximately (-10, 10). The original 20 points still cluster tightly around y = x, but the single outlier in the upper-left corner pulls the visual trend toward a negative slope.
</p>
</div>
<p>If we just use <code>lm</code>, which uses SSE.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="classicaltheory.html#cb133-1" tabindex="-1"></a><span class="fu">lm</span>(ys <span class="sc">~</span> xs)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs)
## 
## Coefficients:
## (Intercept)           xs  
##     -0.5012       0.1422</code></pre>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="classicaltheory.html#cb135-1" tabindex="-1"></a><span class="fu">plot</span>(xs, ys)</span>
<span id="cb135-2"><a href="classicaltheory.html#cb135-2" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(ys <span class="sc">~</span> xs))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-77"></span>
<img src="01-classical_theory_files/figure-html/unnamed-chunk-77-1.png" alt="Scatterplot where the regression line is tilted toward the upper-left outlier, resulting in a much flatter slope than the true underlying y=x relationship." width="672" />
<p class="caption">
Figure 2.27: Scatterplot with SSE-minimizing regression line fit to the data including the outlier. The line has been pulled substantially toward the outlier compared to what it would look like without it, now showing a near-zero or slightly negative slope instead of the true positive slope.
</p>
</div>
<p>Repeat the above, replacing the outlier with successively bigger outliers, and see what happens to the line of best fit. Convince yourself that when the outlier is big enough, the line of best fit is perpendicular to the original line.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="classicaltheory.html#cb136-1" tabindex="-1"></a>xs[<span class="dv">21</span>] <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">20</span></span>
<span id="cb136-2"><a href="classicaltheory.html#cb136-2" tabindex="-1"></a>ys[<span class="dv">21</span>] <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb136-3"><a href="classicaltheory.html#cb136-3" tabindex="-1"></a><span class="fu">lm</span>(ys <span class="sc">~</span> xs)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ys ~ xs)
## 
## Coefficients:
## (Intercept)           xs  
##     -1.3940      -0.5616</code></pre>
<p>When you are done using <code>MASS</code>, I always recommend detaching it. The reason is that <code>MASS</code> has a function called <code>select</code> that masks <code>dplyr::select</code> if we load <code>MASS</code> after loading <code>dplyr</code>.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="classicaltheory.html#cb138-1" tabindex="-1"></a><span class="fu">detach</span>(<span class="st">&quot;package:MASS&quot;</span>, <span class="at">unload =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="vignette-a-dplyr-primer" class="section level2 unnumbered hasAnchor">
<h2>Vignette: A dplyr primer<a href="classicaltheory.html#vignette-a-dplyr-primer" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <code>dplyr</code> package is perhaps the most popular package in the <code>tidyverse</code>, and one of R’s most popular packages overall.
It provides a powerful and intuitive way of wrangling and manipulating data into the forms that we will need for analysis and visualization.
We assume that the data frame in question consists of a number of <strong>observations</strong> (rows) of various <strong>variables</strong> (columns).
Each row should correspond to a single observation, and each column should be measuring a single thing, and have a meaningful name.
In this vignette, we discuss the basics of <code>dplyr</code> along with some string manipulation and time manipulation.</p>
<p>There are <strong>many</strong> functions inside of <code>dplyr</code>, but if you learn the following 6, then you will be well on your way to being a data wrangling boffin.</p>
<ol style="list-style-type: decimal">
<li><p><code>filter</code> Use this to create a subset of <strong>observations</strong> of data. That is, we remove some of the rows from the data frame, and keep the rest of them.</p></li>
<li><p><code>select</code> Use this to create a subset of <strong>variables</strong> of data. That is, we remove some of the columns from the data frame, and keep the rest of them.</p></li>
<li><p><code>mutate</code> Use this to create a new variable that gets added to the data frame. The new variable can be a combination of the other variables in the data frame.</p></li>
<li><p><code>summarize</code> Use this to reduce the data frame down to a single value. This is most often used in conjunction with <code>group_by</code> below, which means <strong>each group</strong> is reduced down to a single value via some computation.</p></li>
<li><p><code>group_by</code> Organize the data frame into groups. Primarily used with <code>summarize</code> but sometimes also with <code>mutate</code>. The function <code>n()</code> returns the number of observations (rows) in each group.</p></li>
<li><p><code>%&gt;%</code> The pipe. Without the pipe, <code>dplyr</code> never would have gained popularity. The pipe allows us to chain together operations so that the data wrangling can follow our natural language manner of doing the wrangling.</p></li>
</ol>
<p>Let’s see how these work with some examples. Consider the <code>babynames</code> package in the <code>babynames</code> library.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="classicaltheory.html#cb139-1" tabindex="-1"></a>bb <span class="ot">&lt;-</span> babynames<span class="sc">::</span>babynames</span>
<span id="cb139-2"><a href="classicaltheory.html#cb139-2" tabindex="-1"></a>bb</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 × 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724
##  2  1880 F     Anna       2604 0.0267
##  3  1880 F     Emma       2003 0.0205
##  4  1880 F     Elizabeth  1939 0.0199
##  5  1880 F     Minnie     1746 0.0179
##  6  1880 F     Margaret   1578 0.0162
##  7  1880 F     Ida        1472 0.0151
##  8  1880 F     Alice      1414 0.0145
##  9  1880 F     Bertha     1320 0.0135
## 10  1880 F     Sarah      1288 0.0132
## # ℹ 1,924,655 more rows</code></pre>
<p>This data set lists all names in the United States given to at least 5 babies in a year. It has almost 2 million observations of 5 variables.</p>
<div class="example">
<span class="divhead-definition example-before">Example 2.2</span>
<p><span id="exm:unlabeled-div-4" class="example"><strong>Example 2.2  </strong></span>Create a data frame that contains only those babies born in 1899.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="classicaltheory.html#cb141-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb141-2"><a href="classicaltheory.html#cb141-2" tabindex="-1"></a><span class="fu">filter</span>(bb, year <span class="sc">==</span> <span class="dv">1899</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3,042 × 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1899 F     Mary      13172 0.0532
##  2  1899 F     Anna       5115 0.0207
##  3  1899 F     Helen      5048 0.0204
##  4  1899 F     Margaret   4249 0.0172
##  5  1899 F     Ruth       3912 0.0158
##  6  1899 F     Florence   3314 0.0134
##  7  1899 F     Elizabeth  3287 0.0133
##  8  1899 F     Marie      3156 0.0128
##  9  1899 F     Ethel      2999 0.0121
## 10  1899 F     Lillian    2703 0.0109
## # ℹ 3,032 more rows</code></pre>
<p>Create a data frame that contains only those babies born in 1899 that were assigned Female at birth.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="classicaltheory.html#cb143-1" tabindex="-1"></a><span class="fu">filter</span>(bb, year <span class="sc">==</span> <span class="dv">1899</span>, sex <span class="sc">==</span> <span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1,842 × 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1899 F     Mary      13172 0.0532
##  2  1899 F     Anna       5115 0.0207
##  3  1899 F     Helen      5048 0.0204
##  4  1899 F     Margaret   4249 0.0172
##  5  1899 F     Ruth       3912 0.0158
##  6  1899 F     Florence   3314 0.0134
##  7  1899 F     Elizabeth  3287 0.0133
##  8  1899 F     Marie      3156 0.0128
##  9  1899 F     Ethel      2999 0.0121
## 10  1899 F     Lillian    2703 0.0109
## # ℹ 1,832 more rows</code></pre>
<p>As you can see, if we have multiple conditions separated by a comma, <code>filter</code> interprets that as an <strong>and</strong> condition. If we want to use <strong>or</strong>, we need to use the vector valued or operator <code>|</code>.</p>
<p>Create a data frame that contains only those babies born either in 1900 or 2000.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="classicaltheory.html#cb145-1" tabindex="-1"></a><span class="fu">filter</span>(bb, year <span class="sc">==</span> <span class="dv">1900</span><span class="sc">|</span>year <span class="sc">==</span> <span class="dv">2000</span>)</span></code></pre></div>
<pre><code>## # A tibble: 33,499 × 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1900 F     Mary      16706 0.0526
##  2  1900 F     Helen      6343 0.0200
##  3  1900 F     Anna       6114 0.0192
##  4  1900 F     Margaret   5304 0.0167
##  5  1900 F     Ruth       4765 0.0150
##  6  1900 F     Elizabeth  4096 0.0129
##  7  1900 F     Florence   3920 0.0123
##  8  1900 F     Ethel      3896 0.0123
##  9  1900 F     Marie      3856 0.0121
## 10  1900 F     Lillian    3414 0.0107
## # ℹ 33,489 more rows</code></pre>
</div>
<p>The <code>select</code> function is not as complicated or really as useful as the <code>filter</code> function.</p>
<div class="example">
<span class="divhead-definition example-before">Example 2.3</span>
<p><span id="exm:unlabeled-div-5" class="example"><strong>Example 2.3  </strong></span>Create a data frame that only contains <code>year</code> and <code>name</code>.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="classicaltheory.html#cb147-1" tabindex="-1"></a><span class="fu">select</span>(bb, year, name)</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 × 2
##     year name     
##    &lt;dbl&gt; &lt;chr&gt;    
##  1  1880 Mary     
##  2  1880 Anna     
##  3  1880 Emma     
##  4  1880 Elizabeth
##  5  1880 Minnie   
##  6  1880 Margaret 
##  7  1880 Ida      
##  8  1880 Alice    
##  9  1880 Bertha   
## 10  1880 Sarah    
## # ℹ 1,924,655 more rows</code></pre>
<p>Select can be useful if you know regular expressions and want to select from a long list of variables. Instead of putting the variable name in, you use <code>matches("")</code> and put a regular expression inside the quotes. For example, to select all variables that start with n.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="classicaltheory.html#cb149-1" tabindex="-1"></a><span class="fu">select</span>(bb, <span class="fu">matches</span>(<span class="st">&quot;^n&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 × 2
##    name          n
##    &lt;chr&gt;     &lt;int&gt;
##  1 Mary       7065
##  2 Anna       2604
##  3 Emma       2003
##  4 Elizabeth  1939
##  5 Minnie     1746
##  6 Margaret   1578
##  7 Ida        1472
##  8 Alice      1414
##  9 Bertha     1320
## 10 Sarah      1288
## # ℹ 1,924,655 more rows</code></pre>
<p>If you don’t know regular expressions, that’s OK. The <code>^</code> indicates that we only want to find matches at the beginning of the variable name, and the <code>n</code> indicates what we want to match. In this instance, since there are no other variables with an <code>n</code> in them, we wouldn’t have to include the <code>^</code>.</p>
</div>
<div class="example">
<span class="divhead-definition example-before">Example 2.4</span>
<p><span id="exm:unlabeled-div-6" class="example"><strong>Example 2.4  </strong></span>Suppose we wanted to create a new variable which contains the <strong>percentage</strong> of babies with of that gender and name in a given year. To do this, we would need to multiple <code>prop</code> by 100 and store it in a new variable.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="classicaltheory.html#cb151-1" tabindex="-1"></a><span class="fu">mutate</span>(bb, <span class="at">percent =</span> prop <span class="sc">*</span> <span class="dv">100</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 × 6
##     year sex   name          n   prop percent
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;   &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724    7.24
##  2  1880 F     Anna       2604 0.0267    2.67
##  3  1880 F     Emma       2003 0.0205    2.05
##  4  1880 F     Elizabeth  1939 0.0199    1.99
##  5  1880 F     Minnie     1746 0.0179    1.79
##  6  1880 F     Margaret   1578 0.0162    1.62
##  7  1880 F     Ida        1472 0.0151    1.51
##  8  1880 F     Alice      1414 0.0145    1.45
##  9  1880 F     Bertha     1320 0.0135    1.35
## 10  1880 F     Sarah      1288 0.0132    1.32
## # ℹ 1,924,655 more rows</code></pre>
<p>A more complicated example would be to create a new variable which contains the first letter of each baby’s name.
We would need to use <code>mutate</code> to do that, along with some string work to pull out the first letter of the name.
We will use the <code>stringr</code> package to manipulate strings.
The particular function we need for this task is <code>str_extract</code>.
Again, we will need a regular expression which matches the first letter of the baby’s name.
Since the first letter is (perhaps?) the only one capitalized, we could probably use <code>"[A-Z]"</code>, which matches any letter between A and Z.
But, to be safe, we <strong>anchor</strong> the match at the front of the name using <code>^</code>, just like we did above with variable names.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="classicaltheory.html#cb153-1" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb153-2"><a href="classicaltheory.html#cb153-2" tabindex="-1"></a><span class="fu">mutate</span>(bb, <span class="at">first_letter =</span> <span class="fu">str_extract</span>(name, <span class="st">&quot;^[A-Z]&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 × 6
##     year sex   name          n   prop first_letter
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt;       
##  1  1880 F     Mary       7065 0.0724 M           
##  2  1880 F     Anna       2604 0.0267 A           
##  3  1880 F     Emma       2003 0.0205 E           
##  4  1880 F     Elizabeth  1939 0.0199 E           
##  5  1880 F     Minnie     1746 0.0179 M           
##  6  1880 F     Margaret   1578 0.0162 M           
##  7  1880 F     Ida        1472 0.0151 I           
##  8  1880 F     Alice      1414 0.0145 A           
##  9  1880 F     Bertha     1320 0.0135 B           
## 10  1880 F     Sarah      1288 0.0132 S           
## # ℹ 1,924,655 more rows</code></pre>
</div>
<p>Now, we get to some more interesting tasks which incolve <code>group_by</code> and <code>summary</code>.</p>
<div class="example">
<span class="divhead-definition example-before">Example 2.5</span>
<p><span id="exm:unlabeled-div-7" class="example"><strong>Example 2.5  </strong></span>How many babies are there from 1880? We first filter so that only 1880 is shown, then we <code>summarize</code> by adding up all of the values of <code>n</code>.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="classicaltheory.html#cb155-1" tabindex="-1"></a>bb_1880 <span class="ot">&lt;-</span> <span class="fu">filter</span>(bb, year <span class="sc">==</span> <span class="dv">1880</span>)</span>
<span id="cb155-2"><a href="classicaltheory.html#cb155-2" tabindex="-1"></a><span class="fu">summarize</span>(bb_1880, <span class="at">tot =</span> <span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##      tot
##    &lt;int&gt;
## 1 201484</code></pre>
<p>This is a bit awkward since we created the intermediate data frame <code>bb_1880</code>. It would have been nice to just use the result from <code>filter</code> directly in <code>summarize</code>. That’s exactly what pipes do!</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="classicaltheory.html#cb157-1" tabindex="-1"></a>bb <span class="sc">%&gt;%</span> </span>
<span id="cb157-2"><a href="classicaltheory.html#cb157-2" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1880</span>) <span class="sc">%&gt;%</span> <span class="co">#same as filter(bb, year == 1880)</span></span>
<span id="cb157-3"><a href="classicaltheory.html#cb157-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">tot =</span> <span class="fu">sum</span>(n)) <span class="co">#same as summarize(filter(bb, year == 1880), tot = sum(n))</span></span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##      tot
##    &lt;int&gt;
## 1 201484</code></pre>
<p>You read the above as follows. “Take bb, filter to year is only 1880, and then summarize by adding the values of n.” The pipes take the place of the statement “and then” when you are thinking to yourself about how to break down a problem.</p>
<p>Now let’s add <code>group_by</code>. The <code>group_by</code> function groups the data frame according to values of one or more variable so that you can perform computations on each group separately. So, if we wanted to find the total number of babies in each year separately, we would proceed as follows:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="classicaltheory.html#cb159-1" tabindex="-1"></a>bb <span class="sc">%&gt;%</span> </span>
<span id="cb159-2"><a href="classicaltheory.html#cb159-2" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span> </span>
<span id="cb159-3"><a href="classicaltheory.html#cb159-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">tot =</span> <span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 138 × 2
##     year    tot
##    &lt;dbl&gt;  &lt;int&gt;
##  1  1880 201484
##  2  1881 192696
##  3  1882 221533
##  4  1883 216946
##  5  1884 243462
##  6  1885 240854
##  7  1886 255317
##  8  1887 247394
##  9  1888 299473
## 10  1889 288946
## # ℹ 128 more rows</code></pre>
<p>If we wanted to do the same thing, but for Females and Males separately:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="classicaltheory.html#cb161-1" tabindex="-1"></a>bb <span class="sc">%&gt;%</span> </span>
<span id="cb161-2"><a href="classicaltheory.html#cb161-2" tabindex="-1"></a>  <span class="fu">group_by</span>(year, sex) <span class="sc">%&gt;%</span> </span>
<span id="cb161-3"><a href="classicaltheory.html#cb161-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">tot =</span> <span class="fu">sum</span>(n))</span></code></pre></div>
<pre><code>## `summarise()` has regrouped the output.
## ℹ Summaries were computed grouped by year and sex.
## ℹ Output is grouped by year.
## ℹ Use `summarise(.groups = &quot;drop_last&quot;)` to silence this message.
## ℹ Use `summarise(.by = c(year, sex))` for per-operation grouping
##   (`?dplyr::dplyr_by`) instead.</code></pre>
<pre><code>## # A tibble: 276 × 3
## # Groups:   year [138]
##     year sex      tot
##    &lt;dbl&gt; &lt;chr&gt;  &lt;int&gt;
##  1  1880 F      90993
##  2  1880 M     110491
##  3  1881 F      91953
##  4  1881 M     100743
##  5  1882 F     107847
##  6  1882 M     113686
##  7  1883 F     112319
##  8  1883 M     104627
##  9  1884 F     129020
## 10  1884 M     114442
## # ℹ 266 more rows</code></pre>
<p>Finally, what if we wanted to count the number of distinct names given to babies in each year? Here, we would use <code>n()</code>, which is a special function that returns the number of observations in a data frame. If it is done with a <strong>grouped</strong> data frame, then it computes the number of observations in each group.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="classicaltheory.html#cb164-1" tabindex="-1"></a>bb <span class="sc">%&gt;%</span> </span>
<span id="cb164-2"><a href="classicaltheory.html#cb164-2" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span> </span>
<span id="cb164-3"><a href="classicaltheory.html#cb164-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 138 × 2
##     year count
##    &lt;dbl&gt; &lt;int&gt;
##  1  1880  2000
##  2  1881  1935
##  3  1882  2127
##  4  1883  2084
##  5  1884  2297
##  6  1885  2294
##  7  1886  2392
##  8  1887  2373
##  9  1888  2651
## 10  1889  2590
## # ℹ 128 more rows</code></pre>
</div>
<p>Next steps: the above 6 functions can take you far. If you want to take your manipulation skills to the next level, the next functions I would learn would be <code>pivot_longer</code>, <code>pivot_wider</code>, <code>left_join</code>, <code>slice_*</code> (the family of <code>slice</code> functions), and start learning about the <code>stringr</code> and <code>lubridate</code> packages. There is a homework problem that requires you to use <code>lubridate</code>, so here is a quick example, where we convert <code>seoulweather</code> date into a <code>lubridate</code> object for plotting purposes.</p>
<p>First, note that if we just pass date to <code>ggplot2</code> and plot it, it looks terrible. That’s because <code>ggplot</code> doesn’t know <code>date</code> is a date.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="classicaltheory.html#cb166-1" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(fosdata<span class="sc">::</span>seoulweather)</span>
<span id="cb166-2"><a href="classicaltheory.html#cb166-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb166-3"><a href="classicaltheory.html#cb166-3" tabindex="-1"></a><span class="fu">ggplot</span>(ss, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> next_tmax)) <span class="sc">+</span> </span>
<span id="cb166-4"><a href="classicaltheory.html#cb166-4" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 27 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="01-classical_theory_files/figure-html/unnamed-chunk-174-1.png" width="672" /></p>
<p>After we change <code>date</code> to a date variable, things look much better, even though there would still be a lot to do to make this make sense. For your homework, you will want to filter down to the mentioned stations and year, use a grouping variable (or color) and then use <code>geom_line</code>. This problem is hard. Don’t be discouraged if you don’t get it. Come and get help in office hours.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="classicaltheory.html#cb168-1" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb168-2"><a href="classicaltheory.html#cb168-2" tabindex="-1"></a>ss <span class="ot">&lt;-</span> ss <span class="sc">%&gt;%</span> </span>
<span id="cb168-3"><a href="classicaltheory.html#cb168-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">ymd</span>(date))</span>
<span id="cb168-4"><a href="classicaltheory.html#cb168-4" tabindex="-1"></a><span class="fu">ggplot</span>(ss, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> next_tmax)) <span class="sc">+</span> </span>
<span id="cb168-5"><a href="classicaltheory.html#cb168-5" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 29 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="01-classical_theory_files/figure-html/unnamed-chunk-175-1.png" width="672" /></p>
<p>Something like this is what you are looking for in the homework, but don’t worry if yours doesn’t look exactly like this.</p>
<p><img src="01-classical_theory_files/figure-html/unnamed-chunk-176-1.png" width="672" /></p>
</div>
<div id="exercises" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Exercises<a href="classicaltheory.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Let <span class="math inline">\(X_1, \ldots, X_5\)</span> be normal random variables with means <span class="math inline">\(1, 2, 3, 4, 5\)</span> and variances <span class="math inline">\(1, 4, 9, 16, 25\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>What kind of rv is <span class="math inline">\(\overline{X}\)</span>? Include the values of any parameters.</p></li>
<li><p>Use simulation to plot the pdf of <span class="math inline">\(\overline{X}\)</span> and confirm your answer to part 1.</p></li>
</ol>
<p> </p></li>
<li><p>Consider the data set <code>ISwR::bp.obese</code>. If you have never installed the <code>ISwR</code> package, you will need to run <code>install.packages("ISwR")</code> before accessing this data set.</p>
<ol style="list-style-type: decimal">
<li><p>Find the line of best fit for modeling blood pressure versus obesity by minimizing the SSE.</p></li>
<li><p>Does it appear that the model <span class="math inline">\(y = \beta_0 + \beta_1 x + epsilon\)</span>, where <span class="math inline">\(y\)</span> is bp, <span class="math inline">\(x\)</span> is obese, and <span class="math inline">\(\epsilon\)</span> is normal with mean 0 and standard deviation <span class="math inline">\(\sigma\)</span> is correct for this data?</p></li>
</ol>
<p> </p></li>
<li><p>Suppose you wish to model data <span class="math inline">\((x_1, y_1), \ldots, (x_n, y_n)\)</span> by
<span class="math display">\[
y_i = \beta_0 + x_i + \epsilon_i  
\]</span>
<span class="math inline">\(\epsilon_i\)</span> are iid normal with mean 0 and standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>Find the <span class="math inline">\(\beta_0\)</span> that minimizes the SSE, <span class="math inline">\(\sum(y_i - (\beta_0 + x_i))^2\)</span> in terms of <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span>. Call this estimator <span class="math inline">\(\hat \beta_0\)</span>.</p></li>
<li><p>What kind of random variable is <span class="math inline">\(\hat \beta_0\)</span>? Be sure to include both its mean and standard deviation or variance (in terms of the <span class="math inline">\(x_i\)</span>).</p></li>
<li><p>Verify your answer via simulation when the true relationship is <span class="math inline">\(y = 2 + x + \epsilon\)</span>, where <span class="math inline">\(\epsilon\)</span> is normal with mean 0 and standard deviation 1.</p></li>
</ol>
<p> </p></li>
<li><p>Consider the data set <code>HistData::Galton</code> that we looked at briefly. Assume the model <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \epsilon_i\)</span>, and do a hypothesis test of <span class="math inline">\(H_0: \beta_1 = 1\)</span> versus <span class="math inline">\(H_a: \beta_1 \not= 1\)</span>. Explain what this means in the context of the data.</p></li>
<li><p>Consider your model <span class="math inline">\(y_i = \beta_0 + x_i + \epsilon_i\)</span>, where <span class="math inline">\(\epsilon_i\)</span> are independent normal random variables with mean 0 and standard deviation <span class="math inline">\(\sigma\)</span>. You showed above that <span class="math inline">\(\hat \beta_0 = \overline{y} - \overline{x}\)</span> is normal with mean <span class="math inline">\(\beta_0\)</span> and standard deviation <span class="math inline">\(\sigma/\sqrt{n}\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Fix a value of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\sigma\)</span>. The residuals are <span class="math inline">\(y_i - \hat \beta_0 - x_i\)</span>. Find an unbiased estimator for <span class="math inline">\(\sigma^2\)</span> in terms of the residuals. Call this estimator <span class="math inline">\(S^2\)</span>.</p></li>
<li><p>What kind of random variable is <span class="math inline">\(\frac{\hat \beta_0 - \beta_0}{\sigma/\sqrt{n}}\)</span>?</p></li>
<li><p>What kind of random variable is <span class="math inline">\(\frac{\hat \beta_0 - \beta_0}{S/\sqrt{n}}\)</span>?</p></li>
<li><p>Download the data <code>problem_2_5.csv</code> <a href="https://stat.slu.edu/~speegle/Spring2020/4870/data">here</a>. Model <span class="math inline">\(ys \sim \beta_0 + xs + \epsilon\)</span> and perform a hypothesis test of <span class="math inline">\(H_0: \beta_0 = 2\)</span> versus <span class="math inline">\(H_a: \beta_0 \not= 2\)</span> at the <span class="math inline">\(\alpha = .05\)</span> level.</p></li>
</ol>
<p> </p></li>
<li><p>Consider the data set <code>carData::Davis</code>. This data set gives the recorded weight and the self-reported weight for about 200 patients. We are interested in modeling <code>weight</code> as a function of <code>repwt</code>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Confirm that there is an outlier in this data set. Do not fix the outlier.</p></li>
<li><p>Find the line of best fit using SSE, using the Huber or psuedo-Huber loss function, and using the Tukey bisquare loss function. Comment.</p></li>
</ol></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-linear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
