<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Generalized Linear Models | Applied Regression with R</title>
  <meta name="description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Generalized Linear Models | Applied Regression with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Generalized Linear Models | Applied Regression with R" />
  
  <meta name="twitter:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

<meta name="author" content="Darrin Speegle" />


<meta name="date" content="2026-02-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
<link rel="prev" href="tree-regression-models.html"/>
<link rel="next" href="lecture-notes.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Regression with R<br />&nbsp; Notes From STAT 4870/5087</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="classicaltheory.html"><a href="classicaltheory.html"><i class="fa fa-check"></i><b>2</b> Classical Theory of Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="classicaltheory.html"><a href="classicaltheory.html#review"><i class="fa fa-check"></i><b>2.1</b> Review</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-means-and-standard-deviations"><i class="fa fa-check"></i><b>2.1.1</b> Estimating Means and standard deviations</a></li>
<li class="chapter" data-level="2.1.2" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-the-density-of-an-rv"><i class="fa fa-check"></i><b>2.1.2</b> Estimating the density of an rv</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-overview"><i class="fa fa-check"></i><b>2.2</b> Linear Regression Overview</a></li>
<li class="chapter" data-level="2.3" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-with-no-intercept"><i class="fa fa-check"></i><b>2.3</b> Linear Regression with no intercept</a></li>
<li class="chapter" data-level="2.4" data-path="classicaltheory.html"><a href="classicaltheory.html#the-full-model"><i class="fa fa-check"></i><b>2.4</b> The full model</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="classicaltheory.html"><a href="classicaltheory.html#hypothesis-test-interlude"><i class="fa fa-check"></i><b>2.4.1</b> Hypothesis Test Interlude</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="classicaltheory.html"><a href="classicaltheory.html#using-different-loss-functions"><i class="fa fa-check"></i><b>2.5</b> Using different loss functions</a></li>
<li class="chapter" data-level="" data-path="classicaltheory.html"><a href="classicaltheory.html#vignette-a-dplyr-primer"><i class="fa fa-check"></i>Vignette: A dplyr primer</a></li>
<li class="chapter" data-level="2.6" data-path="classicaltheory.html"><a href="classicaltheory.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#anova"><i class="fa fa-check"></i><b>3.0.1</b> Aside on multiple R squared and ANOVA</a></li>
<li class="chapter" data-level="3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-variable-selection-anova"><i class="fa fa-check"></i><b>3.1</b> More Variable Selection: ANOVA</a></li>
<li class="chapter" data-level="3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#predictions"><i class="fa fa-check"></i><b>3.2</b> Predictions</a></li>
<li class="chapter" data-level="3.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#using-aic"><i class="fa fa-check"></i><b>3.3</b> Using AIC</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#likelihood-functions"><i class="fa fa-check"></i><b>3.3.1</b> Likelihood functions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercises-1"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html"><i class="fa fa-check"></i><b>4</b> Intro to Predictive Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#comparingtwomodels"><i class="fa fa-check"></i><b>4.1</b> Comparing Two Models</a></li>
<li class="chapter" data-level="4.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#a-brief-return-to-inference"><i class="fa fa-check"></i><b>4.2</b> A Brief Return to Inference</a></li>
<li class="chapter" data-level="4.3" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#simulations-of-expected-mse"><i class="fa fa-check"></i><b>4.3</b> Simulations of Expected MSE</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-and-bias-variance-tradeoff"><i class="fa fa-check"></i><b>4.3.1</b> Estimating MSE and Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-for-new-predictors-uniformly-sampled"><i class="fa fa-check"></i><b>4.3.2</b> Estimating MSE for new predictors uniformly sampled</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>4.4</b> Bias Variance Trade-off</a></li>
<li class="chapter" data-level="4.5" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#exercises-2"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html"><i class="fa fa-check"></i><b>5</b> Regression Predictive Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#preprocessing"><i class="fa fa-check"></i><b>5.1</b> Preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#missing-data"><i class="fa fa-check"></i><b>5.2</b> Missing Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#predicting-when-a-level-is-missing-from-the-training-set"><i class="fa fa-check"></i><b>5.2.1</b> Predicting when a level is missing from the training set</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#correlated-predictors"><i class="fa fa-check"></i><b>5.3</b> Correlated Predictors</a></li>
<li class="chapter" data-level="5.4" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#aside-on-pca"><i class="fa fa-check"></i><b>5.4</b> Aside on PCA</a></li>
<li class="chapter" data-level="5.5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#johnson-lindenstrauss-dimension-reduction"><i class="fa fa-check"></i><b>5.5</b> Johnson-Lindenstrauss Dimension Reduction</a></li>
<li class="chapter" data-level="5.6" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#exercises-3"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variable-selection.html"><a href="variable-selection.html"><i class="fa fa-check"></i><b>6</b> Variable Selection</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variable-selection.html"><a href="variable-selection.html#partial-least-squares"><i class="fa fa-check"></i><b>6.1</b> Partial Least Squares</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="variable-selection.html"><a href="variable-selection.html#optional-pls-stuff"><i class="fa fa-check"></i><b>6.1.1</b> Optional PLS Stuff</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variable-selection.html"><a href="variable-selection.html#ridgelasso-and-elastic-net"><i class="fa fa-check"></i><b>6.2</b> Ridge/Lasso and Elastic Net</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="variable-selection.html"><a href="variable-selection.html#ridge-regression"><i class="fa fa-check"></i><b>6.2.1</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.2.2" data-path="variable-selection.html"><a href="variable-selection.html#lasso"><i class="fa fa-check"></i><b>6.2.2</b> LASSO</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variable-selection.html"><a href="variable-selection.html#step-aic"><i class="fa fa-check"></i><b>6.3</b> Step AIC</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="variable-selection.html"><a href="variable-selection.html#doing-lgocv-with-preprocessing"><i class="fa fa-check"></i><b>6.3.1</b> Doing LGOCV with preprocessing</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variable-selection.html"><a href="variable-selection.html#interactions"><i class="fa fa-check"></i><b>6.4</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html"><i class="fa fa-check"></i><b>7</b> Non-Linear Regression Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#support-vector-regression"><i class="fa fa-check"></i><b>7.1</b> Support Vector Regression</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#plot-twist"><i class="fa fa-check"></i><b>7.1.1</b> PLOT TWIST</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>7.2</b> K Nearest Neighbors</a></li>
<li class="chapter" data-level="7.3" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#exercises-4"><i class="fa fa-check"></i><b>7.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tree-regression-models.html"><a href="tree-regression-models.html"><i class="fa fa-check"></i><b>8</b> Tree Regression Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="tree-regression-models.html"><a href="tree-regression-models.html#basic-regression-trees"><i class="fa fa-check"></i><b>8.1</b> Basic Regression Trees</a></li>
<li class="chapter" data-level="8.2" data-path="tree-regression-models.html"><a href="tree-regression-models.html#regression-model-trees"><i class="fa fa-check"></i><b>8.2</b> Regression Model Trees</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="tree-regression-models.html"><a href="tree-regression-models.html#choosing-variable-to-split"><i class="fa fa-check"></i><b>8.2.1</b> Choosing Variable to Split</a></li>
<li class="chapter" data-level="8.2.2" data-path="tree-regression-models.html"><a href="tree-regression-models.html#choosing-split-value"><i class="fa fa-check"></i><b>8.2.2</b> Choosing Split Value</a></li>
<li class="chapter" data-level="8.2.3" data-path="tree-regression-models.html"><a href="tree-regression-models.html#predicting-values-smoothing"><i class="fa fa-check"></i><b>8.2.3</b> Predicting values (Smoothing)</a></li>
<li class="chapter" data-level="8.2.4" data-path="tree-regression-models.html"><a href="tree-regression-models.html#using-r-functions"><i class="fa fa-check"></i><b>8.2.4</b> Using R functions</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="tree-regression-models.html"><a href="tree-regression-models.html#bagging"><i class="fa fa-check"></i><b>8.3</b> Bagging</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>9</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="9.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#logistic-regression"><i class="fa fa-check"></i><b>9.1</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#maximum-likelihood-estimation"><i class="fa fa-check"></i><b>9.1.1</b> Maximum Likelihood Estimation</a></li>
<li class="chapter" data-level="9.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#model-diagnostics"><i class="fa fa-check"></i><b>9.1.2</b> Model Diagnostics</a></li>
<li class="chapter" data-level="9.1.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#case-study"><i class="fa fa-check"></i><b>9.1.3</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#count-response-models"><i class="fa fa-check"></i><b>9.2</b> Count response models</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#overdispersion"><i class="fa fa-check"></i><b>9.2.1</b> Overdispersion</a></li>
<li class="chapter" data-level="9.2.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#negative-binomial-regression"><i class="fa fa-check"></i><b>9.2.2</b> Negative Binomial Regression</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-truncated-and-zero-inflated-models"><i class="fa fa-check"></i><b>9.3</b> Zero-truncated and Zero-inflated models</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-truncated-poisson"><i class="fa fa-check"></i><b>9.3.1</b> Zero-truncated Poisson</a></li>
<li class="chapter" data-level="9.3.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-truncated-negative-binomial"><i class="fa fa-check"></i><b>9.3.2</b> Zero-truncated Negative Binomial</a></li>
<li class="chapter" data-level="9.3.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#zero-inflated-poisson-and-negative-binomial"><i class="fa fa-check"></i><b>9.3.3</b> Zero-Inflated Poisson and Negative Binomial</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="lecture-notes.html"><a href="lecture-notes.html"><i class="fa fa-check"></i><b>10</b> Lecture Notes</a>
<ul>
<li class="chapter" data-level="10.1" data-path="lecture-notes.html"><a href="lecture-notes.html#january-27"><i class="fa fa-check"></i><b>10.1</b> January 27</a></li>
<li class="chapter" data-level="10.2" data-path="lecture-notes.html"><a href="lecture-notes.html#february-3"><i class="fa fa-check"></i><b>10.2</b> February 3</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="lecture-notes.html"><a href="lecture-notes.html#simulating-data"><i class="fa fa-check"></i><b>10.2.1</b> Simulating Data</a></li>
<li class="chapter" data-level="10.2.2" data-path="lecture-notes.html"><a href="lecture-notes.html#building-models"><i class="fa fa-check"></i><b>10.2.2</b> Building Models</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="lecture-notes.html"><a href="lecture-notes.html#february-5"><i class="fa fa-check"></i><b>10.3</b> February 5</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="lecture-notes.html"><a href="lecture-notes.html#using-broomaugment"><i class="fa fa-check"></i><b>10.3.1</b> Using <code>broom::augment</code></a></li>
<li class="chapter" data-level="10.3.2" data-path="lecture-notes.html"><a href="lecture-notes.html#multicollinearity"><i class="fa fa-check"></i><b>10.3.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="lecture-notes.html"><a href="lecture-notes.html#february-10"><i class="fa fa-check"></i><b>10.4</b> February 10</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="lecture-notes.html"><a href="lecture-notes.html#anova-models"><i class="fa fa-check"></i><b>10.4.1</b> ANOVA Models</a></li>
<li class="chapter" data-level="10.4.2" data-path="lecture-notes.html"><a href="lecture-notes.html#penguins"><i class="fa fa-check"></i><b>10.4.2</b> Penguins</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="lecture-notes.html"><a href="lecture-notes.html#february-12"><i class="fa fa-check"></i><b>10.5</b> February 12</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="lecture-notes.html"><a href="lecture-notes.html#an-example"><i class="fa fa-check"></i><b>10.5.1</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="lecture-notes.html"><a href="lecture-notes.html#february-17"><i class="fa fa-check"></i><b>10.6</b> February 17</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-speaker-and-sentence-effects"><i class="fa fa-check"></i><b>10.6.1</b> Adding random speaker and sentence effects</a></li>
<li class="chapter" data-level="10.6.2" data-path="lecture-notes.html"><a href="lecture-notes.html#random-intercepts-with-continuous-predictor"><i class="fa fa-check"></i><b>10.6.2</b> Random intercepts with continuous predictor</a></li>
<li class="chapter" data-level="10.6.3" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-slopes"><i class="fa fa-check"></i><b>10.6.3</b> Adding random slopes</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="lecture-notes.html"><a href="lecture-notes.html#february-19"><i class="fa fa-check"></i><b>10.7</b> February 19</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="lecture-notes.html"><a href="lecture-notes.html#random-slopes"><i class="fa fa-check"></i><b>10.7.1</b> Random Slopes</a></li>
<li class="chapter" data-level="10.7.2" data-path="lecture-notes.html"><a href="lecture-notes.html#comparing-models"><i class="fa fa-check"></i><b>10.7.2</b> Comparing models</a></li>
<li class="chapter" data-level="10.7.3" data-path="lecture-notes.html"><a href="lecture-notes.html#some-theory"><i class="fa fa-check"></i><b>10.7.3</b> Some Theory</a></li>
<li class="chapter" data-level="10.7.4" data-path="lecture-notes.html"><a href="lecture-notes.html#intro-to-random-effects-and-mixed-effect-models---terminology-and-first-examples"><i class="fa fa-check"></i><b>10.7.4</b> Intro to Random Effects and Mixed Effect Models - Terminology and First Examples</a></li>
<li class="chapter" data-level="10.7.5" data-path="lecture-notes.html"><a href="lecture-notes.html#comparison-of-models"><i class="fa fa-check"></i><b>10.7.5</b> Comparison of Models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>11</b> Solutions</a>
<ul>
<li class="chapter" data-level="11.1" data-path="solutions.html"><a href="solutions.html#chapter-2-solutions"><i class="fa fa-check"></i><b>11.1</b> Chapter 2 Solutions</a></li>
<li class="chapter" data-level="11.2" data-path="solutions.html"><a href="solutions.html#chapter-3-solutions"><i class="fa fa-check"></i><b>11.2</b> Chapter 3 Solutions</a></li>
<li class="chapter" data-level="11.3" data-path="solutions.html"><a href="solutions.html#chapter-5"><i class="fa fa-check"></i><b>11.3</b> Chapter 5</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Regression with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="generalized-linear-models" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Generalized Linear Models<a href="generalized-linear-models.html#generalized-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, we discuss a family of models called <em>generalized linear models</em>. These models include ordinary least squares regression, and many others. All<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> of the models presented in this chapter can be realized as examples of a common framework. We won’t present the common framework in this book, but focus on two specific examples - <em>logistic regression</em> and <em>Poisson regression</em>. We will also return to the more classical framework of regression, where we are interested in the theory and assessing the fit of the model, rather than focussing exclusively on predictive modeling. We will do <em>a lot</em> of estimates of regression coefficients for various models in this chapter. I hope that by the time you get to the end of reading it, you will be able to set these up in your sleep.</p>
<p>Since generalized linear models include OLS, let’s take a brief review of OLS. Recall that our model is</p>
<p><span class="math display">\[
y = \beta_0 + \sum_{i = 1}^p \beta_i x_i + \epsilon
\]</span></p>
<p>where <span class="math inline">\(\epsilon\)</span> is normal with mean 0 and unknown variance <span class="math inline">\(\sigma^2\)</span>. Another way of thinking about this is that we are modeling the <em>expected value</em> of the response via a linear (affine) equation.</p>
<p><span class="math display">\[
E[y] = \beta_0 + \sum_{i = 1}^p \beta_i x_i
\]</span></p>
<p>and we are assuming that we have <em>normal errors</em> or deviations from the expected value. Another way to think about it is that the response <span class="math inline">\(y\)</span> is normal with mean <span class="math inline">\(\mu = \beta_0 + \sum_{i = 1}^p \beta_i x_i\)</span> and variance <span class="math inline">\(\sigma^2\)</span>.</p>
<div id="logistic-regression" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Logistic Regression<a href="generalized-linear-models.html#logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Logistic regression is used to model responses that can only be two values. Such variables are called <em>binary</em> variables. Examples include determining whether a flipped coin comes up as Heads or Tails, or whether a person recovers or doesn’t recover from a disease, or whether a person votes yes or no in an election. Many times, we have additional information that is naturally grouped with the outcome. For example, we may have a persons age, height, weight, the amount and type of medicine they were given in addition to whether they recovered or didn’t recover from the disease. The goal is to be able to model the recovery or non-recovery from the disease on the predictors.</p>
<p>We’ll start in the simple case where we have a single predictor and a binary response. Let’s have a specific data set in mind so that we can be concrete about things.</p>
<div class="sourceCode" id="cb841"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb841-1"><a href="generalized-linear-models.html#cb841-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb841-2"><a href="generalized-linear-models.html#cb841-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4072020</span>)</span>
<span id="cb841-3"><a href="generalized-linear-models.html#cb841-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">rnorm</span>(<span class="dv">200</span>, <span class="dv">0</span>, <span class="fl">1.2</span>))</span>
<span id="cb841-4"><a href="generalized-linear-models.html#cb841-4" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">response =</span> <span class="fu">rbinom</span>(<span class="dv">200</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="sc">/</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="dv">1</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>x) <span class="sc">+</span> <span class="dv">1</span>)))</span></code></pre></div>
<p>Let’s look at some summary statistics.</p>
<div class="sourceCode" id="cb842"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb842-1"><a href="generalized-linear-models.html#cb842-1" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code></pre></div>
<pre><code>##        x                 response    
##  Min.   :-3.4261064   Min.   :0.000  
##  1st Qu.:-0.7071214   1st Qu.:0.000  
##  Median : 0.0024246   Median :1.000  
##  Mean   : 0.0007739   Mean   :0.605  
##  3rd Qu.: 0.7752691   3rd Qu.:1.000  
##  Max.   : 3.4201922   Max.   :1.000</code></pre>
<div class="sourceCode" id="cb844"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb844-1"><a href="generalized-linear-models.html#cb844-1" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>x, df<span class="sc">$</span>response)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>This is a very typical and promising plot for wanting to do logistic regression. We see that as <span class="math inline">\(x\)</span> gets larger, more of the responses are 1 and as <span class="math inline">\(x\)</span> gets smaller, more of the responses are 0. We will see later that this synthetic data was generated <strong>exactly</strong> according to the logistic regression model, much like a response of <code>1 + 2*x + rnorm(100, 0, 3)</code> would be exactly according to OLS.</p>
<p>If we are reasoning analogously to OLS, we might think that we should try to model the <em>expected value</em> of the response as a linear (affine) equation of the predictors, as in</p>
<p><span class="math display">\[
E[y] = \beta_0 + \sum_{i = 1}^p \beta_i x_i.
\]</span></p>
<p>Sometimes that is appropriate, but if we are thinking of the response as a 0/1 random variable, then its expected value is the <strong>probability</strong> of a success. The affine equation above can be negative or bigger than 1, which would be impossible for a probability. Alternatively, let <span class="math inline">\(p = E[y]\)</span>, and we could model the <strong>log odds</strong> of the response as an affine equation of the predictors:</p>
<p><span class="math display">\[
\log \frac{p}{1-p} = \beta_0 + \sum_{i = 1}^p \beta_i x_i
\]</span></p>
<p>This is the approach that is taken in logistic regression. For completeness, let’s solve the above equation for <span class="math inline">\(p\)</span>:</p>
<p><span class="math display">\[
p = \frac{e^{\beta_0 + \sum_{i = 1}^p \beta_i x_i}}{1 + e^{\beta_0 + \sum_{i = 1}^p \beta_i x_i}} = \frac{1}{1 + e^{-\beta_0 - \sum_{i = 1}^p \beta_i x_i}}
\]</span></p>
<p>The <em>error</em> component in this model is not as easy to see as in the normal case, because it isn’t simply added as a random variable. But we can see that the random component of the response is binomial with <span class="math inline">\(n = 1\)</span> and <span class="math inline">\(p = \frac{1}{1 + e^{-\beta_0 - \sum_{i = 1}^p \beta_i x_i}}\)</span>. This is is often referred to as “binomial error” or “binomial noise”, but the term <em>random component</em> makes more sense to me. The predictors can be either continuous or categorical, but we will be going through the derivations only for a single continuous predictor (just like we did with OLS). One final piece of terminology is the <em>link function</em>. In the case of logistic regression, the link function is <span class="math inline">\(\log \frac{x}{1-x}\)</span>. This is the link between the linear combination of predictors and the expected value of the response.</p>
<p>For the specific example that we are considering, we have only a single predictor <span class="math inline">\(x\)</span>, so our model is</p>
<p><span class="math display">\[
\log \frac{p}{1-p} = \beta_0 + \beta_1 x
\]</span></p>
<p>The first question you might have is: how do we get estimates of <span class="math inline">\(\beta_i\)</span>? The classical way is using <em>maximum likelihood estimation</em>, which we will get to momentarily. But, if we are coming to this through the lense of what we have covered so far in these notes, which we are, then why not minimize some error function? Let’s imagine that we have our values for <span class="math inline">\(\log \frac {p}{1-p}\)</span> in terms of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, so <span class="math inline">\(\log \frac {p_i}{1-p_i} = \beta_0 + \beta_1 x_{1i}\)</span>. Ideally, the log odds would be positive and very large when <span class="math inline">\(y_i\)</span> are 1, and would be negative with large absolute value when <span class="math inline">\(y_i\)</span> are 0. Here are three natural loss functions to minimize, which were taken from <a href="https://projecteuclid.org/download/pdf_1/euclid.aos/1079120130">Zhang</a>.</p>
<p><strong>Note</strong> To proceed, we need to transform the response into a <span class="math inline">\(-1/1\)</span> random variable. That is, we change all of the zero responses to <span class="math inline">\(-1\)</span>. This just simplifies the notation. We also write <span class="math inline">\(\text{logit}(p_i) = \log \frac {p_i}{1 - p_i}\)</span></p>
<p>The three loss functions are all of the form
<span class="math display">\[
\frac{1}n \sum_{i = 1}^n \Phi(\text{logit}(p_i) y_i)
\]</span></p>
<p>where <span class="math inline">\(\Phi\)</span> is one of</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\Phi_1(x) = \max(1-x,0)^2\)</span>, <em>modified least squares</em>.</li>
<li><span class="math inline">\(\Phi_2(x) = e^{-x}\)</span>, <em>AdaBoost</em>.</li>
<li><span class="math inline">\(\Phi_3(x) = \log(1 + e^{-x})\)</span>, <em>logistic regression</em>.</li>
</ol>
<p>In order to be a good loss function for this model, we would like for <em>positive values</em> of <span class="math inline">\(\text{logit}(p_i)y_i\)</span> to be associated with <em>small</em> errors. Think about this: if the log odds are bigger than 0, then <span class="math inline">\(p_i &gt; 1 - p_i\)</span>, so <span class="math inline">\(p_i &gt; 1/2\)</span>. So, if the log odds are bigger than zero and the response is 1, that’s a good thing! Similarly if the log odds are less than zero and the response is <span class="math inline">\(-1\)</span>, then that’s also a good thing! The bigger the value of <span class="math inline">\(\text{logit}(p_i)y_i\)</span>, the better it predicts. The smaller the value of <span class="math inline">\(\text{logit}(p_i)y_i\)</span> (i.e., big and negative), the worse it predicts <a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</p>
<p>We plot the three loss functions so that you can see what the graphs look like.</p>
<div class="sourceCode" id="cb845"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb845-1"><a href="generalized-linear-models.html#cb845-1" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb845-2"><a href="generalized-linear-models.html#cb845-2" tabindex="-1"></a>  <span class="fu">pmax</span>(<span class="dv">1</span> <span class="sc">-</span> x, <span class="dv">0</span>)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb845-3"><a href="generalized-linear-models.html#cb845-3" tabindex="-1"></a>}</span>
<span id="cb845-4"><a href="generalized-linear-models.html#cb845-4" tabindex="-1"></a><span class="fu">curve</span>(f, <span class="at">from =</span> <span class="sc">-</span><span class="dv">3</span>, <span class="at">to =</span> <span class="dv">2</span>, <span class="at">main =</span> <span class="st">&quot;Comparison of three loss functions&quot;</span>) <span class="co">#black</span></span>
<span id="cb845-5"><a href="generalized-linear-models.html#cb845-5" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">exp</span>(<span class="sc">-</span>x), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>) <span class="co">#red</span></span>
<span id="cb845-6"><a href="generalized-linear-models.html#cb845-6" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">log</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>x)), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">3</span>) <span class="co">#green</span></span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>All three functions have varying degrees of penalties for misclassifying the response. <em>AdaBoost</em> has an exponential penalty, <em>modified least squares</em> has a quadratic penalty, and <em>logistic regression</em> has a linear penalty. As usual, this has implications in terms of robustness to outliers and other aspects of the estimates.</p>
<p>OK, let’s see how our good friend <code>optim</code> can do with these functions! We’ll start with the modified least squares, even though that one definitely feels like the hardest because of a lack of differentiability at 1. We first have to get the sse function set up properly.</p>
<div class="sourceCode" id="cb846"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb846-1"><a href="generalized-linear-models.html#cb846-1" tabindex="-1"></a>sse_1 <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, dat) {</span>
<span id="cb846-2"><a href="generalized-linear-models.html#cb846-2" tabindex="-1"></a>  beta_0 <span class="ot">&lt;-</span> beta[<span class="dv">1</span>]</span>
<span id="cb846-3"><a href="generalized-linear-models.html#cb846-3" tabindex="-1"></a>  beta_1 <span class="ot">&lt;-</span> beta[<span class="dv">2</span>]</span>
<span id="cb846-4"><a href="generalized-linear-models.html#cb846-4" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">f</span>((beta_0 <span class="sc">+</span> beta_1<span class="sc">*</span>dat<span class="sc">$</span>x) <span class="sc">*</span> dat<span class="sc">$</span>y))</span>
<span id="cb846-5"><a href="generalized-linear-models.html#cb846-5" tabindex="-1"></a>}</span>
<span id="cb846-6"><a href="generalized-linear-models.html#cb846-6" tabindex="-1"></a><span class="fu">names</span>(df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;x&quot;</span>, <span class="st">&quot;y&quot;</span>)</span>
<span id="cb846-7"><a href="generalized-linear-models.html#cb846-7" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">y =</span> <span class="fu">ifelse</span>(y <span class="sc">==</span> <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, y))</span>
<span id="cb846-8"><a href="generalized-linear-models.html#cb846-8" tabindex="-1"></a><span class="fu">sse_1</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), df)</span></code></pre></div>
<pre><code>## [1] 0.606441</code></pre>
<p>OK, here we go.</p>
<div class="sourceCode" id="cb848"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb848-1"><a href="generalized-linear-models.html#cb848-1" tabindex="-1"></a>best <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">fn =</span> sse_1, <span class="at">dat =</span> df)</span>
<span id="cb848-2"><a href="generalized-linear-models.html#cb848-2" tabindex="-1"></a>best</span></code></pre></div>
<pre><code>## $par
## [1] 0.2659848 0.6850055
## 
## $value
## [1] 0.5108565
## 
## $counts
## function gradient 
##       53       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We get values of the parameters to be <span class="math inline">\(\beta_0\)</span> =0.266 and <span class="math inline">\(\beta_1\)</span> = 0.685. Note that these values are not particularly close to the true values that we know: <span class="math inline">\(\beta_0 = 1\)</span> and <span class="math inline">\(\beta_1 = 2\)</span>.</p>
<p>Now, we plot the logistic probability curve on the same graph as the data. We will want to change the responses back to 0/1.</p>
<div class="sourceCode" id="cb850"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb850-1"><a href="generalized-linear-models.html#cb850-1" tabindex="-1"></a>df_zero <span class="ot">&lt;-</span> df</span>
<span id="cb850-2"><a href="generalized-linear-models.html#cb850-2" tabindex="-1"></a>df_zero<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>y <span class="sc">==</span> <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, df<span class="sc">$</span>y)</span>
<span id="cb850-3"><a href="generalized-linear-models.html#cb850-3" tabindex="-1"></a>logit <span class="ot">&lt;-</span> <span class="cf">function</span>(p) {</span>
<span id="cb850-4"><a href="generalized-linear-models.html#cb850-4" tabindex="-1"></a>  <span class="fu">log</span>(p<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p))</span>
<span id="cb850-5"><a href="generalized-linear-models.html#cb850-5" tabindex="-1"></a>}</span>
<span id="cb850-6"><a href="generalized-linear-models.html#cb850-6" tabindex="-1"></a>inv_logit <span class="ot">&lt;-</span> <span class="cf">function</span>(y, beta_0, beta_1) {</span>
<span id="cb850-7"><a href="generalized-linear-models.html#cb850-7" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>beta_0 <span class="sc">-</span> beta_1 <span class="sc">*</span> y))</span>
<span id="cb850-8"><a href="generalized-linear-models.html#cb850-8" tabindex="-1"></a>}</span>
<span id="cb850-9"><a href="generalized-linear-models.html#cb850-9" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> best<span class="sc">$</span>par[<span class="dv">1</span>]</span>
<span id="cb850-10"><a href="generalized-linear-models.html#cb850-10" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> best<span class="sc">$</span>par[<span class="dv">2</span>]</span>
<span id="cb850-11"><a href="generalized-linear-models.html#cb850-11" tabindex="-1"></a><span class="fu">plot</span>(df_zero<span class="sc">$</span>x, df_zero<span class="sc">$</span>y)</span>
<span id="cb850-12"><a href="generalized-linear-models.html#cb850-12" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">inv_logit</span>(x, beta_0, beta_1), <span class="at">add =</span> T)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>As an exercise, you are asked to repeat the above for the other two loss functions. Before doing so, you should think a bit about what you expect to get, relative to what we got for this one. The graph you are looking to get is below.</p>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div id="maximum-likelihood-estimation" class="section level3 hasAnchor" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Maximum Likelihood Estimation<a href="generalized-linear-models.html#maximum-likelihood-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The more traditional way of arriving at the estimates for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in logistic regression is via <strong>maximum likelihood</strong>. Here, if we have <span class="math inline">\(p_i\)</span> is the probability of success associated with observation <span class="math inline">\(i\)</span>, the likelihood of observing <span class="math inline">\(y_i\)</span> would be <span class="math inline">\(p_i^{y_i}(1 - p_i)^{1 - y_i}\)</span>. Note that this is a fancy way of writing that the likelihood would be <span class="math inline">\(p_i\)</span> if <span class="math inline">\(y_i = 1\)</span> and it would be <span class="math inline">\((1 - p_i)\)</span> if <span class="math inline">\(y_i = 0\)</span>. The likelihood of observing the sequence <span class="math inline">\(y_1, \ldots, y_n\)</span> would be given by the <em>product</em> of the individual likelihoods, since we are assuming independence. Therefore, given <span class="math inline">\(p_i\)</span>, the likelihood function is</p>
<p><span class="math display">\[
\Pi_{i = 1}^n p_i^{y_i}(1 - p_i)^{1 - y_i}
\]</span></p>
<p>A common trick when dealing with likelihood functions is to take the log. We will use below the fact that a positive function <span class="math inline">\(f\)</span> has a maximum at <span class="math inline">\(x = x_0\)</span> if and only if the function <span class="math inline">\(\log f\)</span> has a maximum at <span class="math inline">\(x = x_0\)</span>. Taking logs of the likelihood function, we get (after a bit of algebra)</p>
<p><span class="math display">\[
\sum_{i = 1}^n y_i \log(p_i) + (1 - y_i) \log(1 - p_i) = \sum_{\{i: y_i = 1\}} \log(p_i) + \sum_{\{i:y_i = 0\}} \log(1 - p_i)
\]</span></p>
<p>Finally, we are assuming the following relationship between <span class="math inline">\(p_i\)</span>, the <span class="math inline">\(\beta\)</span>’s and <span class="math inline">\(x_i\)</span>: <span class="math inline">\(p_i = \frac{1}{1 + e^{-\beta_0 - \beta_1 x_i}}\)</span>. Therefore, we have the following likelihood that we are trying to maximize:</p>
<p><span class="math display">\[
\sum_{\{i: y_i = 1\}} \log\biggl(\frac{1}{1 + e^{-\beta_0 - \beta_1 x_i}}\biggr) + \sum_{\{i:y_i = 0\}} \log\biggl(1 - \frac{1}{1 + e^{-\beta_0 - \beta_1 x_i}}\biggr)
\]</span></p>
<p>The sum on the right can be simplified some, but we do not bother. So, that is the function that we want to <em>maximize</em> over all choices of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. Let’s do it.</p>
<div class="sourceCode" id="cb851"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb851-1"><a href="generalized-linear-models.html#cb851-1" tabindex="-1"></a>log_mle <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, dat) {</span>
<span id="cb851-2"><a href="generalized-linear-models.html#cb851-2" tabindex="-1"></a>  beta_0 <span class="ot">&lt;-</span> beta[<span class="dv">1</span>]</span>
<span id="cb851-3"><a href="generalized-linear-models.html#cb851-3" tabindex="-1"></a>  beta_1 <span class="ot">&lt;-</span> beta[<span class="dv">2</span>]</span>
<span id="cb851-4"><a href="generalized-linear-models.html#cb851-4" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">inv_logit</span>(dat<span class="sc">$</span>x, beta_0, beta_1)</span>
<span id="cb851-5"><a href="generalized-linear-models.html#cb851-5" tabindex="-1"></a>  <span class="sc">-</span><span class="dv">1</span> <span class="sc">*</span> <span class="fu">sum</span>(dat<span class="sc">$</span>y <span class="sc">*</span> <span class="fu">log</span>(p) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> dat<span class="sc">$</span>y) <span class="sc">*</span> <span class="fu">log</span>(<span class="dv">1</span> <span class="sc">-</span> p))</span>
<span id="cb851-6"><a href="generalized-linear-models.html#cb851-6" tabindex="-1"></a>}</span>
<span id="cb851-7"><a href="generalized-linear-models.html#cb851-7" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), <span class="at">fn =</span> log_mle, <span class="at">dat =</span> df_zero)</span></code></pre></div>
<pre><code>## $par
## [1] 0.7783362 2.1695154
## 
## $value
## [1] 76.20191
## 
## $counts
## function gradient 
##       55       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We see that the values for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that yield the maximum likelihood of the data are approximately the same as the values that we computed above when doing the logistic regression error function.</p>
<p>As an aside, we can also do maximum likelihood estimation in classical OLS. Let’s see how it would work for the case of a single numeric predictor. Our model is that</p>
<p><span class="math display">\[
y_i \sim \text{rnorm}(\beta_0 + \beta_1 x_i, \sigma)
\]</span></p>
<p>So, the basic model has three parameters in it that we will need to estimate. The likelihood of data <span class="math inline">\((x_1, y_1), \ldots, (x_n, y_n)\)</span> given parameter values <span class="math inline">\(\beta_0, \beta_1\)</span> and <span class="math inline">\(\sigma\)</span> is given by</p>
<p><span class="math display">\[
L(\text{data}|\text{parameters}) = \Pi_{i = 1}^n \text{dnorm}(y_i, \beta_0 + \beta_1 x_i, \sigma)
\]</span></p>
<p>Given data, we would maximize the log likelihood function using <code>optim</code>.</p>
<div class="sourceCode" id="cb853"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb853-1"><a href="generalized-linear-models.html#cb853-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4112020</span>)</span>
<span id="cb853-2"><a href="generalized-linear-models.html#cb853-2" tabindex="-1"></a>ols <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">20</span>, <span class="dv">0</span>, <span class="dv">10</span>))</span>
<span id="cb853-3"><a href="generalized-linear-models.html#cb853-3" tabindex="-1"></a>ols<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> ols<span class="sc">$</span>x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb853-4"><a href="generalized-linear-models.html#cb853-4" tabindex="-1"></a></span>
<span id="cb853-5"><a href="generalized-linear-models.html#cb853-5" tabindex="-1"></a>log_likelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(params, data) {</span>
<span id="cb853-6"><a href="generalized-linear-models.html#cb853-6" tabindex="-1"></a>  beta_0 <span class="ot">&lt;-</span> params[<span class="dv">1</span>]</span>
<span id="cb853-7"><a href="generalized-linear-models.html#cb853-7" tabindex="-1"></a>  beta_1 <span class="ot">&lt;-</span> params[<span class="dv">2</span>]</span>
<span id="cb853-8"><a href="generalized-linear-models.html#cb853-8" tabindex="-1"></a>  sigma <span class="ot">&lt;-</span> params[<span class="dv">3</span>]</span>
<span id="cb853-9"><a href="generalized-linear-models.html#cb853-9" tabindex="-1"></a>  <span class="sc">-</span><span class="dv">1</span> <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(<span class="fu">dnorm</span>(data<span class="sc">$</span>y, beta_0 <span class="sc">+</span> beta_1 <span class="sc">*</span> data<span class="sc">$</span>x, sigma)))</span>
<span id="cb853-10"><a href="generalized-linear-models.html#cb853-10" tabindex="-1"></a>}</span>
<span id="cb853-11"><a href="generalized-linear-models.html#cb853-11" tabindex="-1"></a></span>
<span id="cb853-12"><a href="generalized-linear-models.html#cb853-12" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="at">fn =</span> log_likelihood, <span class="at">data =</span> ols)</span></code></pre></div>
<pre><code>## $par
## [1] 0.4766699 2.0267131 2.6393589
## 
## $value
## [1] 47.78663
## 
## $counts
## function gradient 
##      120       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<div class="sourceCode" id="cb855"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb855-1"><a href="generalized-linear-models.html#cb855-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> ols))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = ols)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.6885 -1.0360  0.0879  1.9647  3.3761 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.4771     1.3636   0.350    0.731    
## x             2.0263     0.2119   9.565 1.76e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.782 on 18 degrees of freedom
## Multiple R-squared:  0.8356, Adjusted R-squared:  0.8265 
## F-statistic: 91.48 on 1 and 18 DF,  p-value: 1.763e-08</code></pre>
<p>We see that the maximum likelihood estimators of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are close to the values from <code>lm</code>, but the maximum likelihood estimator of <span class="math inline">\(\sigma\)</span> is different from the residual standard error reported in <code>lm</code>. If you run this code multiple times (without setting seed), you will see that this is consistently the case.</p>
<p>Finally, we see how to use the R function <code>glm</code> to find the parameters associated with the maximum likelihood/logistic regression error function.</p>
<div class="sourceCode" id="cb857"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb857-1"><a href="generalized-linear-models.html#cb857-1" tabindex="-1"></a><span class="fu">glm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df_zero, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = y ~ x, family = &quot;binomial&quot;, data = df_zero)
## 
## Coefficients:
## (Intercept)            x  
##      0.7782       2.1698  
## 
## Degrees of Freedom: 199 Total (i.e. Null);  198 Residual
## Null Deviance:       268.4 
## Residual Deviance: 152.4     AIC: 156.4</code></pre>
</div>
<div id="model-diagnostics" class="section level3 hasAnchor" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Model Diagnostics<a href="generalized-linear-models.html#model-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We start by looking at the (residual) deviance. This is twice the difference between the log-likelihood of the <em>saturated model</em> and the log-likelihood of the model under consideration. The saturated model has a parameter for each observation, so the estimates will be <span class="math inline">\(\hat p_j = 1\)</span> if <span class="math inline">\(y_j = 1\)</span> and <span class="math inline">\(\hat p_j = 0\)</span> if <span class="math inline">\(y_j = 0\)</span>. The likelihood of this data under this set of <span class="math inline">\(\hat p_j\)</span> is exactly 1, so the log-likelihood is zero. Sjoe!<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> That’s a long way of saying that the saturated model contributes nothing to the deviance, and we compute the deviance by negative 2 times the log likelihood function of our model, which was computed above.</p>
<p><span class="math display">\[
-2 \sum_j y_j \log \hat p_j + (1 - y_j) \log (1 - \hat p_j)
\]</span></p>
<p>Generally speaking, the smaller the deviance is, the closer the model under consideration is to the saturated model (which models the data perfectly). Therefore, smaller deviances are preferred to larger ones. Suppose we had another variable in our data set that wasn’t related to the response it all. We would expect the deviance of a model with that predictor to be much higher than the deviance with the predictor that we know models the data pretty well, based on how we generated the data.</p>
<div class="sourceCode" id="cb859"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb859-1"><a href="generalized-linear-models.html#cb859-1" tabindex="-1"></a>df_zero<span class="sc">$</span>bad <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">200</span>)</span>
<span id="cb859-2"><a href="generalized-linear-models.html#cb859-2" tabindex="-1"></a><span class="fu">glm</span>(y <span class="sc">~</span> bad, <span class="at">data =</span> df_zero, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = y ~ bad, family = &quot;binomial&quot;, data = df_zero)
## 
## Coefficients:
## (Intercept)          bad  
##      0.4164      -0.1741  
## 
## Degrees of Freedom: 199 Total (i.e. Null);  198 Residual
## Null Deviance:       268.4 
## Residual Deviance: 267.1     AIC: 271.1</code></pre>
<div class="sourceCode" id="cb861"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb861-1"><a href="generalized-linear-models.html#cb861-1" tabindex="-1"></a><span class="fu">glm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df_zero, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = y ~ x, family = &quot;binomial&quot;, data = df_zero)
## 
## Coefficients:
## (Intercept)            x  
##      0.7782       2.1698  
## 
## Degrees of Freedom: 199 Total (i.e. Null);  198 Residual
## Null Deviance:       268.4 
## Residual Deviance: 152.4     AIC: 156.4</code></pre>
<p>Looking under the residual deviance, we see that the model with the variable <code>bad</code> is indeed bad, and has residual deviance very close to the null deviance! The null deviance is just the log-likelihood of the data under the model with a single parameter; that is, all <span class="math inline">\(y_j\)</span> are predicted by the same probability <span class="math inline">\(\hat p_j = \hat p\)</span>. See that the null and residual deviance are identical in the following model.</p>
<div class="sourceCode" id="cb863"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb863-1"><a href="generalized-linear-models.html#cb863-1" tabindex="-1"></a><span class="fu">glm</span>(y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> df_zero, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = y ~ 1, family = &quot;binomial&quot;, data = df_zero)
## 
## Coefficients:
## (Intercept)  
##      0.4263  
## 
## Degrees of Freedom: 199 Total (i.e. Null);  199 Residual
## Null Deviance:       268.4 
## Residual Deviance: 268.4     AIC: 270.4</code></pre>
<p>We could use the residual deviances of nested models to test whether the variables are necessary for the model, much like we did with ANOVA in regression, but we leave that topic for another book.</p>
<p>In OLS, we examined the residuals in order to get a feel for whether the model’s hypotheses are met. In this section, we do a similar thing for logistic regression. We do this for the case of a single predictor, but the ideas are the same for multiple predictors and/or interactions. There are some technicalities that arise in the case of categorical predictors, so we will be assuming a single, numeric predictor, as in our example. The type of residual that we will be dealing with in this section is the <em>deviance residual</em> (you don’t get confused between breakfast and a fast break, do you? then why should deviance residuals and residual deviances be confusing?).</p>
<p><span class="math display">\[
d(y_j, \hat p_j) = \begin{cases}-\sqrt{2 |\log(1 - \hat p_j)|} &amp; y_j = 0\\
\sqrt{2 |\log (\hat p_j)|} &amp; y_j = 1
\end{cases}
\]</span></p>
<p>We will use the deviance residuals to assess the model fit via a <strong>Hosmer Lemeshow</strong> test, which we now describe.</p>
<ol style="list-style-type: decimal">
<li>Arrange the data in order based on the fitted values</li>
<li>Group the data into 10 groups of roughly equal size.</li>
<li>Compute the expected number of successes in each group, together with the observed number of successes in each group.</li>
<li>Perform a <span class="math inline">\(\chi^2\)</span> goodness of fit test. The null hypothesis is that the probabilities computed from the model are correct, and the alternative is that they are not. If we reject the null hypothesis, that means that the logistic regression model that we built is not modelling the data well. Note: this is different than saying that it performs poorly on some cross-validation metric. It is saying that the probabilities that we are assigning do not match reality, even for the data that we used to assign those probabilities!</li>
</ol>
<p>Let’s see how to do this step-by-step using R.</p>
<div class="sourceCode" id="cb865"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb865-1"><a href="generalized-linear-models.html#cb865-1" tabindex="-1"></a><span class="co"># Arrange the data by fitted values</span></span>
<span id="cb865-2"><a href="generalized-linear-models.html#cb865-2" tabindex="-1"></a></span>
<span id="cb865-3"><a href="generalized-linear-models.html#cb865-3" tabindex="-1"></a>df_zero<span class="sc">$</span>bad <span class="ot">&lt;-</span> <span class="cn">NULL</span> <span class="co">#remove the bad variable</span></span>
<span id="cb865-4"><a href="generalized-linear-models.html#cb865-4" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x, </span>
<span id="cb865-5"><a href="generalized-linear-models.html#cb865-5" tabindex="-1"></a>           <span class="at">data =</span> df_zero,</span>
<span id="cb865-6"><a href="generalized-linear-models.html#cb865-6" tabindex="-1"></a>           <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb865-7"><a href="generalized-linear-models.html#cb865-7" tabindex="-1"></a>df_zero<span class="sc">$</span>fitted_values <span class="ot">&lt;-</span> <span class="fu">fitted.values</span>(mod)</span>
<span id="cb865-8"><a href="generalized-linear-models.html#cb865-8" tabindex="-1"></a>df_zero<span class="sc">$</span>deviance_residuals <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod)</span>
<span id="cb865-9"><a href="generalized-linear-models.html#cb865-9" tabindex="-1"></a>df_zero<span class="sc">$</span>pearson_residuals <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod, <span class="at">type =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb865-10"><a href="generalized-linear-models.html#cb865-10" tabindex="-1"></a>df_zero <span class="ot">&lt;-</span> <span class="fu">arrange</span>(df_zero, fitted_values)</span>
<span id="cb865-11"><a href="generalized-linear-models.html#cb865-11" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x, </span>
<span id="cb865-12"><a href="generalized-linear-models.html#cb865-12" tabindex="-1"></a>           <span class="at">data =</span> df_zero,</span>
<span id="cb865-13"><a href="generalized-linear-models.html#cb865-13" tabindex="-1"></a>           <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>) <span class="co">#We recompute this so that the model matches the current data frame!</span></span>
<span id="cb865-14"><a href="generalized-linear-models.html#cb865-14" tabindex="-1"></a></span>
<span id="cb865-15"><a href="generalized-linear-models.html#cb865-15" tabindex="-1"></a></span>
<span id="cb865-16"><a href="generalized-linear-models.html#cb865-16" tabindex="-1"></a><span class="co"># Split into 10 groups of equal size (by fitted value)</span></span>
<span id="cb865-17"><a href="generalized-linear-models.html#cb865-17" tabindex="-1"></a></span>
<span id="cb865-18"><a href="generalized-linear-models.html#cb865-18" tabindex="-1"></a>df_zero<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">each =</span> <span class="dv">20</span>) </span>
<span id="cb865-19"><a href="generalized-linear-models.html#cb865-19" tabindex="-1"></a>df_zero <span class="sc">%&gt;%</span> </span>
<span id="cb865-20"><a href="generalized-linear-models.html#cb865-20" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb865-21"><a href="generalized-linear-models.html#cb865-21" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>(),</span>
<span id="cb865-22"><a href="generalized-linear-models.html#cb865-22" tabindex="-1"></a>            <span class="at">p =</span> <span class="fu">mean</span>(fitted_values))</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    group count      p
##    &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
##  1     1    20 0.0201
##  2     2    20 0.114 
##  3     3    20 0.314 
##  4     4    20 0.493 
##  5     5    20 0.628 
##  6     6    20 0.738 
##  7     7    20 0.853 
##  8     8    20 0.924 
##  9     9    20 0.973 
## 10    10    20 0.993</code></pre>
<div class="sourceCode" id="cb867"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb867-1"><a href="generalized-linear-models.html#cb867-1" tabindex="-1"></a><span class="co"># Compute the expected and observed number of successes</span></span>
<span id="cb867-2"><a href="generalized-linear-models.html#cb867-2" tabindex="-1"></a></span>
<span id="cb867-3"><a href="generalized-linear-models.html#cb867-3" tabindex="-1"></a>df_zero <span class="sc">%&gt;%</span> </span>
<span id="cb867-4"><a href="generalized-linear-models.html#cb867-4" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb867-5"><a href="generalized-linear-models.html#cb867-5" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">expected =</span> <span class="fu">sum</span>(fitted_values),</span>
<span id="cb867-6"><a href="generalized-linear-models.html#cb867-6" tabindex="-1"></a>            <span class="at">observed =</span> <span class="fu">sum</span>(y))</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    group expected observed
##    &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;
##  1     1    0.401        1
##  2     2    2.28         0
##  3     3    6.28         4
##  4     4    9.86        14
##  5     5   12.6         12
##  6     6   14.8         15
##  7     7   17.1         18
##  8     8   18.5         18
##  9     9   19.5         20
## 10    10   19.9         19</code></pre>
<p>Now, for those of you who have used <span class="math inline">\(\chi^2\)</span> tests a lot, you see that we have a problem. The normal rule of thumb is to require the expected number of each cell to be at least 5 or so in order for the test to be run. For this reason, we should probably have used fewer groups, so that the expected values wouldn’t be so close to zero.</p>
<p>Another issue with what we have done so far is that we have arbitrarily only counted the expected successes. We can also count the expected failures and bind it to the bottom.</p>
<div class="sourceCode" id="cb869"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb869-1"><a href="generalized-linear-models.html#cb869-1" tabindex="-1"></a><span class="co"># Expected and observed number of failures</span></span>
<span id="cb869-2"><a href="generalized-linear-models.html#cb869-2" tabindex="-1"></a></span>
<span id="cb869-3"><a href="generalized-linear-models.html#cb869-3" tabindex="-1"></a>df_zero <span class="sc">%&gt;%</span> </span>
<span id="cb869-4"><a href="generalized-linear-models.html#cb869-4" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb869-5"><a href="generalized-linear-models.html#cb869-5" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">expected =</span> <span class="fu">sum</span>(<span class="dv">1</span> <span class="sc">-</span> fitted_values),</span>
<span id="cb869-6"><a href="generalized-linear-models.html#cb869-6" tabindex="-1"></a>            <span class="at">observed =</span> <span class="fu">sum</span>(<span class="dv">1</span> <span class="sc">-</span> y))</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    group expected observed
##    &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;
##  1     1   19.6         19
##  2     2   17.7         20
##  3     3   13.7         16
##  4     4   10.1          6
##  5     5    7.45         8
##  6     6    5.23         5
##  7     7    2.94         2
##  8     8    1.53         2
##  9     9    0.538        0
## 10    10    0.130        1</code></pre>
<div class="sourceCode" id="cb871"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb871-1"><a href="generalized-linear-models.html#cb871-1" tabindex="-1"></a>for_chisq <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb871-2"><a href="generalized-linear-models.html#cb871-2" tabindex="-1"></a>  df_zero <span class="sc">%&gt;%</span> </span>
<span id="cb871-3"><a href="generalized-linear-models.html#cb871-3" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb871-4"><a href="generalized-linear-models.html#cb871-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">expected =</span> <span class="fu">sum</span>(fitted_values),</span>
<span id="cb871-5"><a href="generalized-linear-models.html#cb871-5" tabindex="-1"></a>            <span class="at">observed =</span> <span class="fu">sum</span>(y)),</span>
<span id="cb871-6"><a href="generalized-linear-models.html#cb871-6" tabindex="-1"></a>  df_zero <span class="sc">%&gt;%</span> </span>
<span id="cb871-7"><a href="generalized-linear-models.html#cb871-7" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb871-8"><a href="generalized-linear-models.html#cb871-8" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">expected =</span> <span class="fu">sum</span>(<span class="dv">1</span> <span class="sc">-</span> fitted_values),</span>
<span id="cb871-9"><a href="generalized-linear-models.html#cb871-9" tabindex="-1"></a>            <span class="at">observed =</span> <span class="fu">sum</span>(<span class="dv">1</span> <span class="sc">-</span> y)))</span>
<span id="cb871-10"><a href="generalized-linear-models.html#cb871-10" tabindex="-1"></a>for_chisq</span></code></pre></div>
<pre><code>## # A tibble: 20 × 3
##    group expected observed
##    &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;
##  1     1    0.401        1
##  2     2    2.28         0
##  3     3    6.28         4
##  4     4    9.86        14
##  5     5   12.6         12
##  6     6   14.8         15
##  7     7   17.1         18
##  8     8   18.5         18
##  9     9   19.5         20
## 10    10   19.9         19
## 11     1   19.6         19
## 12     2   17.7         20
## 13     3   13.7         16
## 14     4   10.1          6
## 15     5    7.45         8
## 16     6    5.23         5
## 17     7    2.94         2
## 18     8    1.53         2
## 19     9    0.538        0
## 20    10    0.130        1</code></pre>
<p>Now, we perform the <span class="math inline">\(\chi^2\)</span> goodness of fit test on the expected and the observed cell levels. According to Hosmer and Lemeshow, the value of <code>t_stat</code> given below should have approximately a <span class="math inline">\(\chi^2\)</span> distribution with 8 degrees of freedom; that is, the number of groups minus 2.</p>
<div class="sourceCode" id="cb873"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb873-1"><a href="generalized-linear-models.html#cb873-1" tabindex="-1"></a>t_stat <span class="ot">&lt;-</span> <span class="fu">sum</span>((for_chisq<span class="sc">$</span>observed <span class="sc">-</span> for_chisq<span class="sc">$</span>expected)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>for_chisq<span class="sc">$</span>expected)</span>
<span id="cb873-2"><a href="generalized-linear-models.html#cb873-2" tabindex="-1"></a><span class="fu">pchisq</span>(t_stat, <span class="dv">8</span>, <span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 0.05708811</code></pre>
<div class="sourceCode" id="cb875"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb875-1"><a href="generalized-linear-models.html#cb875-1" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb875-2"><a href="generalized-linear-models.html#cb875-2" tabindex="-1"></a><span class="fu">hoslem.test</span>(<span class="at">x =</span> df_zero<span class="sc">$</span>y, df_zero<span class="sc">$</span>fitted_values, <span class="at">g =</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## 
##  Hosmer and Lemeshow goodness of fit (GOF) test
## 
## data:  df_zero$y, df_zero$fitted_values
## X-squared = 15.108, df = 8, p-value = 0.05709</code></pre>
<p>This <span class="math inline">\(p\)</span>-value is not likely to be accurate, since we know that the assumptions of the <span class="math inline">\(\chi^2\)</span> goodness of fit test have not been met. Let’s re-run it with <span class="math inline">\(g = 8\)</span>, which will likely be closer to meeting the assumptions, though <span class="math inline">\(g = 10\)</span> is certainly the traditional choice.</p>
<div class="sourceCode" id="cb877"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb877-1"><a href="generalized-linear-models.html#cb877-1" tabindex="-1"></a><span class="fu">hoslem.test</span>(<span class="at">x =</span> df_zero<span class="sc">$</span>y, df_zero<span class="sc">$</span>fitted_values, <span class="at">g =</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## 
##  Hosmer and Lemeshow goodness of fit (GOF) test
## 
## data:  df_zero$y, df_zero$fitted_values
## X-squared = 9.827, df = 6, p-value = 0.1321</code></pre>
<p>We can see some problems with this test of fit. First, we are very likely to have expected cell counts that are close to zero, depending on the data set. This problem will be mitigated somewhat as the number of observations gets larger. A second problem is that we can get different recommendations based on the number of cells that we use. A third problem is that we are not sure what the power of this test is, even if it does meet all of the assumptions. The Hosmer-Lemeshow test for fit is widely used, but for the above reasons, it is not unconditionally recommended.</p>
<p>One final use of deviance residuals is to see whether there are any high leverage points in our model. We want to examine the deviance residuals and see which ones are abnormally large. It may be worth examining those points to see whether there is anything odd about them. Let’s consider our running example. We plot the residuals versus the predictors and versus the predicted values, to see if we have any trends.</p>
<div class="sourceCode" id="cb879"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb879-1"><a href="generalized-linear-models.html#cb879-1" tabindex="-1"></a><span class="fu">plot</span>(df_zero<span class="sc">$</span>x, df_zero<span class="sc">$</span>deviance_residuals)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<div class="sourceCode" id="cb880"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb880-1"><a href="generalized-linear-models.html#cb880-1" tabindex="-1"></a><span class="fu">plot</span>(df_zero<span class="sc">$</span>fitted_values, df_zero<span class="sc">$</span>deviance_residuals)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-19-2.png" width="672" /></p>
<p>We see that there are two points that seem to have large residuals. Let’s examine the two points.</p>
<div class="sourceCode" id="cb881"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb881-1"><a href="generalized-linear-models.html#cb881-1" tabindex="-1"></a><span class="fu">which.max</span>(df_zero<span class="sc">$</span>deviance_residuals)</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb883"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb883-1"><a href="generalized-linear-models.html#cb883-1" tabindex="-1"></a><span class="fu">which.min</span>(df_zero<span class="sc">$</span>deviance_residuals)</span></code></pre></div>
<pre><code>## [1] 195</code></pre>
<div class="sourceCode" id="cb885"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb885-1"><a href="generalized-linear-models.html#cb885-1" tabindex="-1"></a>df_zero<span class="sc">$</span>color <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">200</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">195</span>), <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb885-2"><a href="generalized-linear-models.html#cb885-2" tabindex="-1"></a><span class="fu">ggplot</span>(df_zero, <span class="fu">aes</span>(x, y, <span class="at">color =</span> color)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>And they are the two points that we would have expected from the plot! We can also pull out the leverage of the points. If we plot them against the predictor, we get a typical looking plot. Note that the leverage tends to be very small where the probability of success is close to zero or one, as well as in the middle. There is usually this bimodal distribution.</p>
<div class="sourceCode" id="cb886"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb886-1"><a href="generalized-linear-models.html#cb886-1" tabindex="-1"></a><span class="fu">plot</span>(df_zero<span class="sc">$</span>fitted_values, <span class="fu">influence</span>(mod)<span class="sc">$</span>hat)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>We can see what the most influential point is.</p>
<div class="sourceCode" id="cb887"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb887-1"><a href="generalized-linear-models.html#cb887-1" tabindex="-1"></a><span class="fu">which.max</span>(<span class="fu">influence</span>(mod)<span class="sc">$</span>hat)</span></code></pre></div>
<pre><code>## 36 
## 36</code></pre>
<div class="sourceCode" id="cb889"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb889-1"><a href="generalized-linear-models.html#cb889-1" tabindex="-1"></a>df_zero<span class="sc">$</span>color <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">200</span> <span class="sc">==</span> <span class="dv">36</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb889-2"><a href="generalized-linear-models.html#cb889-2" tabindex="-1"></a><span class="fu">ggplot</span>(df_zero, <span class="fu">aes</span>(x, y, <span class="at">color =</span> color)) <span class="sc">+</span> <span class="fu">geom_point</span>() </span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Kind of a surprising value to have the maximum influence! As with OLS, we can find high leverage outliers via the <code>plot</code> function. We see that the same two points with highest deviance residuals are the ones that have the most leverage.</p>
<div class="sourceCode" id="cb890"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb890-1"><a href="generalized-linear-models.html#cb890-1" tabindex="-1"></a><span class="fu">plot</span>(mod, <span class="at">which =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="case-study" class="section level3 hasAnchor" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Case Study<a href="generalized-linear-models.html#case-study" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s consider a more realistic data set that isn’t just simulated data. The <code>MASS</code> package contains a data frame called <code>birthwt</code>, which is 189 births in the US. We are trying to model low birth weight, which is classified as less than 2.5kg.</p>
<div class="sourceCode" id="cb891"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb891-1"><a href="generalized-linear-models.html#cb891-1" tabindex="-1"></a>bwt <span class="ot">&lt;-</span> MASS<span class="sc">::</span>birthwt</span>
<span id="cb891-2"><a href="generalized-linear-models.html#cb891-2" tabindex="-1"></a><span class="fu">summary</span>(bwt)</span></code></pre></div>
<pre><code>##       low              age             lwt             race      
##  Min.   :0.0000   Min.   :14.00   Min.   : 80.0   Min.   :1.000  
##  1st Qu.:0.0000   1st Qu.:19.00   1st Qu.:110.0   1st Qu.:1.000  
##  Median :0.0000   Median :23.00   Median :121.0   Median :1.000  
##  Mean   :0.3122   Mean   :23.24   Mean   :129.8   Mean   :1.847  
##  3rd Qu.:1.0000   3rd Qu.:26.00   3rd Qu.:140.0   3rd Qu.:3.000  
##  Max.   :1.0000   Max.   :45.00   Max.   :250.0   Max.   :3.000  
##      smoke             ptl               ht                ui        
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000  
##  Median :0.0000   Median :0.0000   Median :0.00000   Median :0.0000  
##  Mean   :0.3915   Mean   :0.1958   Mean   :0.06349   Mean   :0.1481  
##  3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.0000  
##  Max.   :1.0000   Max.   :3.0000   Max.   :1.00000   Max.   :1.0000  
##       ftv              bwt      
##  Min.   :0.0000   Min.   : 709  
##  1st Qu.:0.0000   1st Qu.:2414  
##  Median :0.0000   Median :2977  
##  Mean   :0.7937   Mean   :2945  
##  3rd Qu.:1.0000   3rd Qu.:3487  
##  Max.   :6.0000   Max.   :4990</code></pre>
<p>While the actual birthweight is available, we are certainly not allowed to use that in our model! Looking at the help page, we make the following changes.</p>
<div class="sourceCode" id="cb893"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb893-1"><a href="generalized-linear-models.html#cb893-1" tabindex="-1"></a>bwt<span class="sc">$</span>race <span class="ot">&lt;-</span> <span class="fu">factor</span>(bwt<span class="sc">$</span>race, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;white&quot;</span>, <span class="st">&quot;black&quot;</span>, <span class="st">&quot;other&quot;</span>))</span>
<span id="cb893-2"><a href="generalized-linear-models.html#cb893-2" tabindex="-1"></a>bwt<span class="sc">$</span>smoke <span class="ot">&lt;-</span> <span class="fu">factor</span>(bwt<span class="sc">$</span>smoke, <span class="at">levels =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span></code></pre></div>
<p>We make a coupld of other changes. We change <code>ftv</code> to be a simple yes/no did the mother visit a physician in the first trimester. Simlarly, we use whether a woman has had a premature labor as an indicator.</p>
<div class="sourceCode" id="cb894"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb894-1"><a href="generalized-linear-models.html#cb894-1" tabindex="-1"></a>bwt<span class="sc">$</span>ftv <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(bwt<span class="sc">$</span>ftv <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>))</span>
<span id="cb894-2"><a href="generalized-linear-models.html#cb894-2" tabindex="-1"></a>bwt<span class="sc">$</span>ptl <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(bwt<span class="sc">$</span>ptl <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>))</span>
<span id="cb894-3"><a href="generalized-linear-models.html#cb894-3" tabindex="-1"></a>bwt<span class="sc">$</span>ht <span class="ot">&lt;-</span> <span class="fu">factor</span>(bwt<span class="sc">$</span>ht, <span class="at">levels =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span>
<span id="cb894-4"><a href="generalized-linear-models.html#cb894-4" tabindex="-1"></a>bwt<span class="sc">$</span>ui <span class="ot">&lt;-</span> <span class="fu">factor</span>(bwt<span class="sc">$</span>ui, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span>
<span id="cb894-5"><a href="generalized-linear-models.html#cb894-5" tabindex="-1"></a><span class="fu">summary</span>(bwt)</span></code></pre></div>
<pre><code>##       low              age             lwt           race    smoke    
##  Min.   :0.0000   Min.   :14.00   Min.   : 80.0   white:96   No :115  
##  1st Qu.:0.0000   1st Qu.:19.00   1st Qu.:110.0   black:26   Yes: 74  
##  Median :0.0000   Median :23.00   Median :121.0   other:67            
##  Mean   :0.3122   Mean   :23.24   Mean   :129.8                       
##  3rd Qu.:1.0000   3rd Qu.:26.00   3rd Qu.:140.0                       
##  Max.   :1.0000   Max.   :45.00   Max.   :250.0                       
##   ptl        ht        ui       ftv           bwt      
##  No :159   No :177   No :161   No :100   Min.   : 709  
##  Yes: 30   Yes: 12   Yes: 28   Yes: 89   1st Qu.:2414  
##                                          Median :2977  
##                                          Mean   :2945  
##                                          3rd Qu.:3487  
##                                          Max.   :4990</code></pre>
<p>Let’s build our first model.</p>
<div class="sourceCode" id="cb896"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb896-1"><a href="generalized-linear-models.html#cb896-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(low <span class="sc">~</span> .<span class="sc">-</span>bwt, <span class="at">data =</span> bwt, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb896-2"><a href="generalized-linear-models.html#cb896-2" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = low ~ . - bwt, family = &quot;binomial&quot;, data = bwt)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  0.666501   1.237944   0.538  0.59031   
## age         -0.035441   0.038502  -0.920  0.35731   
## lwt         -0.014907   0.007051  -2.114  0.03450 * 
## raceblack    1.202241   0.533613   2.253  0.02426 * 
## raceother    0.772704   0.459673   1.681  0.09277 . 
## smokeYes     0.814845   0.420334   1.939  0.05255 . 
## ptlYes       1.235554   0.465545   2.654  0.00795 **
## htYes        1.823618   0.705267   2.586  0.00972 **
## uiYes        0.702132   0.464575   1.511  0.13070   
## ftvYes      -0.121458   0.375657  -0.323  0.74645   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 234.67  on 188  degrees of freedom
## Residual deviance: 196.73  on 179  degrees of freedom
## AIC: 216.73
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>We see that the residual deviance is lower than the null deviance. We see that, moeroever, the residual deviance is roughly the same as its degree of freedom, so we have no serious reason to question the fit. We now remove some of the variables, using <code>stepAIC</code>.</p>
<div class="sourceCode" id="cb898"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb898-1"><a href="generalized-linear-models.html#cb898-1" tabindex="-1"></a>mod_reduced <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">stepAIC</span>(mod, <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb898-2"><a href="generalized-linear-models.html#cb898-2" tabindex="-1"></a><span class="fu">summary</span>(mod_reduced)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = low ~ lwt + race + smoke + ptl + ht + ui, family = &quot;binomial&quot;, 
##     data = bwt)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) -0.125326   0.967561  -0.130  0.89694   
## lwt         -0.015918   0.006954  -2.289  0.02207 * 
## raceblack    1.300856   0.528484   2.461  0.01384 * 
## raceother    0.854414   0.440907   1.938  0.05264 . 
## smokeYes     0.866582   0.404469   2.143  0.03215 * 
## ptlYes       1.128857   0.450388   2.506  0.01220 * 
## htYes        1.866895   0.707373   2.639  0.00831 **
## uiYes        0.750649   0.458815   1.636  0.10183   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 234.67  on 188  degrees of freedom
## Residual deviance: 197.85  on 181  degrees of freedom
## AIC: 213.85
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Now, let’s consider interactions. We start with the variables that we already have as a lower model, then we have as an upper model all interactions, together with age and lwt squared. Note that doing it this way keeps us from getting fitted probabilities of 0/1, which is generally better to avoid. That being said, I am not sure I would have thought to do this! This is how Venables and Ripley did it in their book. I recommend that you run this code below in your own terminal with <code>trace = 1</code> so that you can see what models it was considering.</p>
<div class="sourceCode" id="cb900"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb900-1"><a href="generalized-linear-models.html#cb900-1" tabindex="-1"></a>mod2_reduced <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">stepAIC</span>(mod, <span class="sc">~</span> .<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">scale</span>(age)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">scale</span>(lwt)<span class="sc">^</span><span class="dv">2</span>), <span class="at">trace =</span> <span class="dv">0</span>)</span></code></pre></div>
<p>Now, we see what percentage of observations in the data set are misclassified.</p>
<div class="sourceCode" id="cb901"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb901-1"><a href="generalized-linear-models.html#cb901-1" tabindex="-1"></a>bwt<span class="sc">$</span>fitted_values <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod2_reduced, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb901-2"><a href="generalized-linear-models.html#cb901-2" tabindex="-1"></a>bwt<span class="sc">$</span>prediction <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(bwt<span class="sc">$</span>fitted_values <span class="sc">&gt;</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb901-3"><a href="generalized-linear-models.html#cb901-3" tabindex="-1"></a><span class="fu">mean</span>(bwt<span class="sc">$</span>prediction <span class="sc">==</span> bwt<span class="sc">$</span>low)</span></code></pre></div>
<pre><code>## [1] 0.7513228</code></pre>
<p>The plots of residuals versus fitted and leverage don’t indicate any problems.</p>
<div class="sourceCode" id="cb903"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb903-1"><a href="generalized-linear-models.html#cb903-1" tabindex="-1"></a><span class="fu">plot</span>(mod2_reduced, <span class="at">which =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<div class="sourceCode" id="cb904"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb904-1"><a href="generalized-linear-models.html#cb904-1" tabindex="-1"></a><span class="fu">plot</span>(mod2_reduced, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-31-2.png" width="672" /></p>
</div>
</div>
<div id="count-response-models" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Count response models<a href="generalized-linear-models.html#count-response-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we discuss models when the response is a count variable. That is, the response is an integer that can at least be interpreted as the count of some number of items. Examples might include the number of days of hospital stays for patients, the number of cigarettes smoked on a given day, or the number of likes that a tweet receives.</p>
<p>We start by reviewing two distributions that will come up in this section. A random variable <span class="math inline">\(X\)</span> is a <em>Poisson</em> with rate <span class="math inline">\(\lambda\)</span> if <span class="math inline">\(X\)</span> is a discrete rv and has probability mass function given by</p>
<p><span class="math display">\[
P(X = x) = e^{-\lambda} \frac{\lambda^x}{x!} \qquad x = 0, 1, \ldots
\]</span></p>
<p>Recall that we use Poisson rv’s to model the number of occurrences in a Poisson process over some time interval, such as the number of accidents at an intersection over a month or the number of typos in one page of typing. For more review, see <a href="https://mathstat.slu.edu/~speegle/_book/randomvariables.html#other-special-random-variables">here</a>.</p>
<p>Now, we imagine that we have data of the form <span class="math inline">\(({\bf {x}}_1, y_1), \ldots, ({\bf x}_n, y_n)\)</span>, where <span class="math inline">\(y_i\)</span> are the responses, and <span class="math inline">\({\bf x}_i\)</span> are the predictors. We also imagine that the <span class="math inline">\(y_i\)</span> are nonnegative integers, and we suspect that they could be random samples from a Poisson random variable, whose mean <span class="math inline">\(\lambda\)</span> depends on the values of the predictors. We model the relationship between predictors and <span class="math inline">\(\lambda\)</span> as</p>
<p><span class="math display">\[
\log \lambda = \beta_0 + \sum_{i = 1}^P \beta_i x_i
\]</span></p>
<p>The <strong>random component</strong> of the response is Poisson with <span class="math inline">\(\lambda = e^{\beta_0 + \sum_{i = 1}^P \beta_i x_i}\)</span>. The<em>link function</em> is <span class="math inline">\(\log x\)</span>. This is the link between the linear combination of predictors and the expected value of the response, while the inverse link function is <span class="math inline">\(e^x\)</span>.</p>
<p>Let’s set up some simulated data. Note that we are choosing the data to follow precisely a Poisson regression model with one predictor and <span class="math inline">\(\beta_0 = 2\)</span>, <span class="math inline">\(\beta_1 = 1\)</span>.</p>
<div class="sourceCode" id="cb905"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb905-1"><a href="generalized-linear-models.html#cb905-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">2</span>)</span>
<span id="cb905-2"><a href="generalized-linear-models.html#cb905-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="dv">100</span>, <span class="at">lambda =</span> <span class="fu">exp</span>(<span class="dv">2</span> <span class="sc">+</span> x))</span>
<span id="cb905-3"><a href="generalized-linear-models.html#cb905-3" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)</span>
<span id="cb905-4"><a href="generalized-linear-models.html#cb905-4" tabindex="-1"></a><span class="fu">plot</span>(x, y)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Looking at the plot, we see that the variance of the response depends on the mean of the response! That is because the response is Poisson, and the mean of a Poisson with rate <span class="math inline">\(\lambda\)</span> is <span class="math inline">\(\lambda\)</span>, while the standard deviation is <span class="math inline">\(\sqrt{\lambda}\)</span>. This is an important observation. In order for a Poisson regression model to be accurate, the mean of the response should also be the variance. From a practical point of view, if you are looking at a graph of data, then the range of values near where the mean of the response is <span class="math inline">\(y_0\)</span> should be about <span class="math inline">\(y_0 \pm 2\sqrt{y_0}\)</span>. We will see more detailed ways of checking this assumption later in the chapter.</p>
<p>Next, we want to estimate the parameters of the model. In this case, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. Let’s start by minimizing the SSE, like we did in OLS.</p>
<div class="sourceCode" id="cb906"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb906-1"><a href="generalized-linear-models.html#cb906-1" tabindex="-1"></a>sse <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, dat) {</span>
<span id="cb906-2"><a href="generalized-linear-models.html#cb906-2" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">abs</span>(dat<span class="sc">$</span>y <span class="sc">-</span> <span class="fu">exp</span>(beta[<span class="dv">1</span>] <span class="sc">+</span> beta[<span class="dv">2</span>] <span class="sc">*</span> dat<span class="sc">$</span>x))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb906-3"><a href="generalized-linear-models.html#cb906-3" tabindex="-1"></a>}</span>
<span id="cb906-4"><a href="generalized-linear-models.html#cb906-4" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">fn =</span> sse, <span class="at">dat =</span> dd)</span></code></pre></div>
<pre><code>## $par
## [1] 1.993814 1.006778
## 
## $value
## [1] 2689.943
## 
## $counts
## function gradient 
##       67       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We see that the estimates of <span class="math inline">\(\beta_0 = 1.9415\)</span> and <span class="math inline">\(\beta_1 = 0.9943\)</span> are pretty accurate! As before, we can modify the error function so that it is more or less sensitive to outliers, say by replacing it with a Huber function or a support vector function. These lead to different estimates for the parameters, which we could chose from based on cross-validation, if we were so inclined. In this chapter, however, we are covering the more classical theory, which uses Maximum Likelihood to estimate the parameters. As we will see, while minimizing SSE can give something pretty close to the maximum likelihood estimators, it is not exactly the same thing.</p>
<p>Recall that the likelihhod function is the product of the likelihood functio of the model, evaluated at the data points. In this case, it is</p>
<p><span class="math display">\[
\Pi\ \text{dpois}(y_i, e^{\beta_0 + \beta_1 x_i})
\]</span></p>
<p>As before, we will take the log of this so that we don’t have issues with overflow. The function that we are maximizing is:</p>
<p><span class="math display">\[
\sum \log \ \text{dpois}(y_i, e^{\beta_0 + \beta_1 x_i})
\]</span></p>
<div class="sourceCode" id="cb908"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb908-1"><a href="generalized-linear-models.html#cb908-1" tabindex="-1"></a>neg_log_likelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, dat) {</span>
<span id="cb908-2"><a href="generalized-linear-models.html#cb908-2" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">log</span>(<span class="fu">dpois</span>(dat<span class="sc">$</span>y, <span class="fu">exp</span>(beta[<span class="dv">1</span>] <span class="sc">+</span> beta[<span class="dv">2</span>] <span class="sc">*</span> dat<span class="sc">$</span>x))))</span>
<span id="cb908-3"><a href="generalized-linear-models.html#cb908-3" tabindex="-1"></a>}</span>
<span id="cb908-4"><a href="generalized-linear-models.html#cb908-4" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">fn =</span> neg_log_likelihood, <span class="at">dat =</span> dd)</span></code></pre></div>
<pre><code>## $par
## [1] 1.976600 1.018178
## 
## $value
## [1] 293.7288
## 
## $counts
## function gradient 
##       75       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We get very similar estimates for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, but not exactly the same. Let’s plot the expected value of <span class="math inline">\(Y\)</span> versus <span class="math inline">\(x\)</span> along with the data.</p>
<div class="sourceCode" id="cb910"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb910-1"><a href="generalized-linear-models.html#cb910-1" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">fn =</span> neg_log_likelihood, <span class="at">dat =</span> dd)<span class="sc">$</span>par</span>
<span id="cb910-2"><a href="generalized-linear-models.html#cb910-2" tabindex="-1"></a><span class="fu">plot</span>(x, y)</span>
<span id="cb910-3"><a href="generalized-linear-models.html#cb910-3" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">exp</span>(beta[<span class="dv">1</span>] <span class="sc">+</span> beta[<span class="dv">2</span>] <span class="sc">*</span> x), <span class="at">add =</span> T)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Looks like a pretty good fit to me!</p>
<p>The built in R way of doing this is to use <code>glm</code> with <code>family = "poisson"</code>.</p>
<div class="sourceCode" id="cb911"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb911-1"><a href="generalized-linear-models.html#cb911-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dd, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb911-2"><a href="generalized-linear-models.html#cb911-2" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x, family = &quot;poisson&quot;, data = dd)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.97652    0.05732   34.48   &lt;2e-16 ***
## x            1.01828    0.03913   26.02   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 845.437  on 99  degrees of freedom
## Residual deviance:  98.568  on 98  degrees of freedom
## AIC: 591.46
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The residual deviance plays a similar role in Poisson regression to what it played in logistic regression. We see that we have reduced the deviance from the null deviance by quite a large margin, so we are explaining a good deal of the variance through the model. There is one aspect, however, where residual deviance plays an expanded role in Poisson regression. We use it to detect <strong>overdispersion</strong>.</p>
<p>Recall that an important aspect of our model was that we are assuming that the response is Poisson, so the variance of the response should increase with the mean of the response. This is something that we really want to check. The data exhibits overdispersion if the variance is larger than the mean, and underdispersion if the variance is smaller than the mean. Underdispersion is generally less of a problem than overdispersion.</p>
<p>Let’s see how to check overdispersion. We first want to see what the distribution of the residual deviance will be under the null hypothesis. So, we replicate the entire process of sampling data, building a model and computing the residual deviance.</p>
<div class="sourceCode" id="cb913"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb913-1"><a href="generalized-linear-models.html#cb913-1" tabindex="-1"></a>res_dev <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb913-2"><a href="generalized-linear-models.html#cb913-2" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">2</span>)</span>
<span id="cb913-3"><a href="generalized-linear-models.html#cb913-3" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="dv">100</span>, <span class="at">lambda =</span> <span class="fu">exp</span>(<span class="dv">2</span> <span class="sc">+</span> x))</span>
<span id="cb913-4"><a href="generalized-linear-models.html#cb913-4" tabindex="-1"></a>  dd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)</span>
<span id="cb913-5"><a href="generalized-linear-models.html#cb913-5" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dd, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb913-6"><a href="generalized-linear-models.html#cb913-6" tabindex="-1"></a>  <span class="fu">deviance</span>(mod) <span class="co">#returns the residual deviance</span></span>
<span id="cb913-7"><a href="generalized-linear-models.html#cb913-7" tabindex="-1"></a>})</span></code></pre></div>
<p>Now, let’s plot it.</p>
<div class="sourceCode" id="cb914"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb914-1"><a href="generalized-linear-models.html#cb914-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(res_dev))</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>Looks plausibly normal, but probably has some skewness. So let’s compare to a <span class="math inline">\(\chi^2\)</span>.</p>
<div class="sourceCode" id="cb915"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb915-1"><a href="generalized-linear-models.html#cb915-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(res_dev))</span>
<span id="cb915-2"><a href="generalized-linear-models.html#cb915-2" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dchisq</span>(x, <span class="at">df =</span> <span class="dv">98</span>), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>To test for overdispersion, we would compare the observed residual deviance to a <span class="math inline">\(\chi^2\)</span> with <span class="math inline">\(n - 2\)</span> degrees of freedom. If the result is unlikely, we conclude that the model is not a good fit, at least possibly because of overdispersion.</p>
<div class="sourceCode" id="cb916"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb916-1"><a href="generalized-linear-models.html#cb916-1" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fu">deviance</span>(mod), <span class="at">df =</span> <span class="dv">98</span>, <span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 0.4648875</code></pre>
<p>For the data that we have here, we would not reject the null hypothesis, and ther is no reason to believe that the model is fitting poorly. Let’s look an example that <strong>does</strong> exhibit overdispersion.</p>
<div class="sourceCode" id="cb918"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb918-1"><a href="generalized-linear-models.html#cb918-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4212020</span>)</span>
<span id="cb918-2"><a href="generalized-linear-models.html#cb918-2" tabindex="-1"></a>rqpois <span class="ot">=</span> <span class="cf">function</span>(n, lambda, phi) {</span>
<span id="cb918-3"><a href="generalized-linear-models.html#cb918-3" tabindex="-1"></a>  mu <span class="ot">=</span> lambda</span>
<span id="cb918-4"><a href="generalized-linear-models.html#cb918-4" tabindex="-1"></a>  k <span class="ot">=</span> mu<span class="sc">/</span>phi<span class="sc">/</span>(<span class="dv">1-1</span><span class="sc">/</span>phi)</span>
<span id="cb918-5"><a href="generalized-linear-models.html#cb918-5" tabindex="-1"></a>  <span class="fu">rnbinom</span>(n, <span class="at">mu =</span> mu, <span class="at">size =</span> k)</span>
<span id="cb918-6"><a href="generalized-linear-models.html#cb918-6" tabindex="-1"></a>}</span>
<span id="cb918-7"><a href="generalized-linear-models.html#cb918-7" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">2</span>))</span>
<span id="cb918-8"><a href="generalized-linear-models.html#cb918-8" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">mutate</span>(dd, <span class="at">y =</span> <span class="fu">rqpois</span>(<span class="dv">100</span>, <span class="fu">exp</span>(<span class="dv">2</span> <span class="sc">+</span> x), <span class="dv">4</span>))</span>
<span id="cb918-9"><a href="generalized-linear-models.html#cb918-9" tabindex="-1"></a><span class="fu">plot</span>(dd)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>The overdispersion is not obvious in the plot, but notice that when the mean is about 50, the range of values of the response is about 40, which indicates a standard deviation closer to 10 than to the square root of 50.</p>
<div class="sourceCode" id="cb919"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb919-1"><a href="generalized-linear-models.html#cb919-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dd, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb919-2"><a href="generalized-linear-models.html#cb919-2" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x, family = &quot;poisson&quot;, data = dd)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.92922    0.05533   34.87   &lt;2e-16 ***
## x            1.04647    0.03889   26.91   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 1101.05  on 99  degrees of freedom
## Residual deviance:  318.27  on 98  degrees of freedom
## AIC: 792.56
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Note that the residual deviance is quite larger than its degrees of freedom! That is an indicator of overdispersion. We run the test based on the <span class="math inline">\(\chi^2\)</span> statistic:</p>
<div class="sourceCode" id="cb921"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb921-1"><a href="generalized-linear-models.html#cb921-1" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fu">deviance</span>(mod), <span class="dv">98</span>, <span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 4.30472e-25</code></pre>
<p>We see that we would reject the null hypothesis that the model fits the data. One possible reason for this could be overdispersion, but this is not in and of itself a specific test for overdispersion. The <a href="https://www.sciencedirect.com/science/article/abs/pii/030440769090014K">test</a> below, based on work by Cameron and Trivedi, is specifically designed to detect overdispersion.</p>
<p>This tests <span class="math inline">\(H_0: \alpha = 0\)</span> versus <span class="math inline">\(H_a: \alpha &gt; 0\)</span> in the model for variance of <span class="math inline">\(\sigma^2 = \mu + \alpha \mu\)</span>.</p>
<div class="sourceCode" id="cb923"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb923-1"><a href="generalized-linear-models.html#cb923-1" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb923-2"><a href="generalized-linear-models.html#cb923-2" tabindex="-1"></a><span class="fu">dispersiontest</span>(mod, <span class="at">trafo =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
##  Overdispersion test
## 
## data:  mod
## z = 4.1488, p-value = 1.671e-05
## alternative hypothesis: true alpha is greater than 0
## sample estimates:
##    alpha 
## 2.054704</code></pre>
<p>We see that we reject the null hypothesis in favor of the alternative, and we estimate that the relationship between variance and the mean is <span class="math inline">\(\sigma^2 \approx 3\mu\)</span>. In particular, Poisson regression is inappropriate for this data set.</p>
<p><strong>Example</strong> From <a href="https://www.routledge.com/Advanced-Regression-Models-with-SAS-and-R/Korosteleva/p/book/9781138049017">Advanced Regression Models with SAS and R</a>. The number of days of hospital stay was recorded for 45 patients with chest pain, along with their gender, age and history of cardial illness. The data is available [here]</p>
<div class="sourceCode" id="cb925"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb925-1"><a href="generalized-linear-models.html#cb925-1" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://mathstat.slu.edu/~speegle/Spring2020/4870/data/Example5.1Data.csv&quot;</span>)</span></code></pre></div>
<pre><code>##       days          gender               age          illness         
##  Min.   :0.000   Length:45          Min.   :28.00   Length:45         
##  1st Qu.:1.000   Class :character   1st Qu.:44.00   Class :character  
##  Median :2.000   Mode  :character   Median :52.00   Mode  :character  
##  Mean   :1.956                      Mean   :53.07                     
##  3rd Qu.:3.000                      3rd Qu.:68.00                     
##  Max.   :6.000                      Max.   :77.00</code></pre>
<p>We build a model of the number of days in the hospital based on the other variables.</p>
<div class="sourceCode" id="cb927"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb927-1"><a href="generalized-linear-models.html#cb927-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(days <span class="sc">~</span> ., <span class="at">data =</span> dd, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb927-2"><a href="generalized-linear-models.html#cb927-2" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = days ~ ., family = &quot;poisson&quot;, data = dd)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) -0.826269   0.470206  -1.757  0.07888 . 
## genderM      0.226425   0.233142   0.971  0.33145   
## age          0.020469   0.007871   2.600  0.00931 **
## illnessyes   0.447653   0.222305   2.014  0.04404 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 54.421  on 44  degrees of freedom
## Residual deviance: 36.654  on 41  degrees of freedom
## AIC: 144.43
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>We see that the data is perhaps <em>underdispersed</em>, that is, the variance is less than the mean. This isn’t as big of a problem as overdispersion, at least at this level of underdispersion. In general, though, we would want to make sure that we are modeling things correctly. I have seen underdispersion that was explained by <strong>zero inflation</strong>, especially when most of the responses are small anyway. Zero-inflation is when the response is Poisson, except for the fact that there are too many zeros. In general, there are just a lot of things to check when modeling count data!</p>
<p>We can do variable selection via AIC, using the <code>stepAIC</code> function from <code>MASS</code>.</p>
<div class="sourceCode" id="cb929"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb929-1"><a href="generalized-linear-models.html#cb929-1" tabindex="-1"></a>mod_final <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">stepAIC</span>(mod)</span></code></pre></div>
<pre><code>## Start:  AIC=144.43
## days ~ gender + age + illness
## 
##           Df Deviance    AIC
## - gender   1   37.623 143.40
## &lt;none&gt;         36.654 144.43
## - illness  1   40.719 146.49
## - age      1   43.828 149.60
## 
## Step:  AIC=143.4
## days ~ age + illness
## 
##           Df Deviance    AIC
## &lt;none&gt;         37.623 143.40
## - illness  1   41.945 145.72
## - age      1   45.596 149.37</code></pre>
<p>We see that gender is removed, and that we predict the days in hospital based on previous illness of the patient and the age of the patient. We estimate the mean length of stay for patients who are age 50 with previous illness to be</p>
<div class="sourceCode" id="cb931"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb931-1"><a href="generalized-linear-models.html#cb931-1" tabindex="-1"></a><span class="fu">coef</span>(mod_final)</span></code></pre></div>
<pre><code>## (Intercept)         age  illnessyes 
## -0.72142577  0.02111739  0.46362688</code></pre>
<p><span class="math display">\[
\log \lambda = -0.72142577 + 0.02111739 \times 50 + 0.46362688
\]</span></p>
<p>so $= 2.221251. We can also get this via</p>
<div class="sourceCode" id="cb933"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb933-1"><a href="generalized-linear-models.html#cb933-1" tabindex="-1"></a><span class="fu">predict</span>(mod_final, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="dv">50</span>, <span class="at">illness =</span> <span class="st">&quot;yes&quot;</span>), <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<pre><code>##        1 
## 2.221252</code></pre>
<div id="overdispersion" class="section level3 hasAnchor" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> Overdispersion<a href="generalized-linear-models.html#overdispersion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s consider the <code>quine</code> data set from <code>MASS</code>. This is a typical example of an overdispersed data set. We are modeling the days absent from school for students based on several predictor variables.</p>
<div class="sourceCode" id="cb935"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb935-1"><a href="generalized-linear-models.html#cb935-1" tabindex="-1"></a>qq <span class="ot">&lt;-</span> MASS<span class="sc">::</span>quine</span>
<span id="cb935-2"><a href="generalized-linear-models.html#cb935-2" tabindex="-1"></a><span class="fu">summary</span>(qq)</span></code></pre></div>
<pre><code>##  Eth    Sex    Age     Lrn          Days      
##  A:69   F:80   F0:27   AL:83   Min.   : 0.00  
##  N:77   M:66   F1:46   SL:63   1st Qu.: 5.00  
##                F2:40           Median :11.00  
##                F3:33           Mean   :16.46  
##                                3rd Qu.:22.75  
##                                Max.   :81.00</code></pre>
<p>If we run a Poisson regression, we get:</p>
<div class="sourceCode" id="cb937"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb937-1"><a href="generalized-linear-models.html#cb937-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(Days <span class="sc">~</span> ., <span class="at">data =</span> qq, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb937-2"><a href="generalized-linear-models.html#cb937-2" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Days ~ ., family = &quot;poisson&quot;, data = qq)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.71538    0.06468  41.980  &lt; 2e-16 ***
## EthN        -0.53360    0.04188 -12.740  &lt; 2e-16 ***
## SexM         0.16160    0.04253   3.799 0.000145 ***
## AgeF1       -0.33390    0.07009  -4.764 1.90e-06 ***
## AgeF2        0.25783    0.06242   4.131 3.62e-05 ***
## AgeF3        0.42769    0.06769   6.319 2.64e-10 ***
## LrnSL        0.34894    0.05204   6.705 2.02e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 2073.5  on 145  degrees of freedom
## Residual deviance: 1696.7  on 139  degrees of freedom
## AIC: 2299.2
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>At a first glance, it appears that all of the variables are significant with very low <span class="math inline">\(p\)</span>-values. However, note that the residual deviance is considerably larger than its degrees of freedom, which is an indicator for overdispersion. This should cause us to seriously doubt the accuracy of the <span class="math inline">\(p\)</span>-values.</p>
<p>There are a couple of options for modeling with overdisperion, including <em>quasipoisson</em> regression and <em>negative binomial</em> regression. For now, we use quaispoisson, which adds a parameter that attempts to deal with the overdispersion.</p>
<div class="sourceCode" id="cb939"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb939-1"><a href="generalized-linear-models.html#cb939-1" tabindex="-1"></a>mod_quasi <span class="ot">&lt;-</span> <span class="fu">glm</span>(Days <span class="sc">~</span> ., <span class="at">data =</span> qq, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span>
<span id="cb939-2"><a href="generalized-linear-models.html#cb939-2" tabindex="-1"></a><span class="fu">summary</span>(mod_quasi)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Days ~ ., family = &quot;quasipoisson&quot;, data = qq)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.7154     0.2347  11.569  &lt; 2e-16 ***
## EthN         -0.5336     0.1520  -3.511 0.000602 ***
## SexM          0.1616     0.1543   1.047 0.296914    
## AgeF1        -0.3339     0.2543  -1.313 0.191413    
## AgeF2         0.2578     0.2265   1.138 0.256938    
## AgeF3         0.4277     0.2456   1.741 0.083831 .  
## LrnSL         0.3489     0.1888   1.848 0.066760 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 13.16691)
## 
##     Null deviance: 2073.5  on 145  degrees of freedom
## Residual deviance: 1696.7  on 139  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>There is a significant difference in <span class="math inline">\(p\)</span>-values between this model and the previous, and we would draw very different conclusions about what variables are significant for modeling days absent. The quasipoisson model is preferred over the Poisson model in this case.</p>
</div>
<div id="negative-binomial-regression" class="section level3 hasAnchor" number="9.2.2">
<h3><span class="header-section-number">9.2.2</span> Negative Binomial Regression<a href="generalized-linear-models.html#negative-binomial-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One downside of using quasipoisson is that AIC is not defined for the quasiPoisson model. If we wish to use AIC for variable selection, then we can use <em>negative binomial</em> regression instead. Let’s look at some details. First, we recall that a negative binomial random variable counts the number of failures before the <span class="math inline">\(k\)</span>th success in a series of Bernoulli trials, each with probability of success <span class="math inline">\(p\)</span>. It has probability mass function given by</p>
<p><span class="math display">\[
P(X = x) = {{x + k -1}\choose {k-1}}p^k(1 - p)^{x - k}, \qquad x = 0, 1, 2, \ldots
\]</span></p>
<p>Another realization of a negative binomial with parameters <span class="math inline">\(k\)</span> and <span class="math inline">\(p\)</span> is that it is the sum of <span class="math inline">\(k\)</span> independent geometric rvs. In particular, the mean of <span class="math inline">\(X\)</span> will be <span class="math inline">\(\mu = k \frac{1-p}{p}\)</span> and the variance will be <span class="math inline">\(\sigma^2 = k \frac{1-p}{p^2}\)</span>. In particular, since <span class="math inline">\(1/p^2 &gt; 1/p\)</span>, negative binomial rvs have variances <strong>larger than</strong> their means. For this reason, they are often suggested for modeling count responses that are overdispersed relative to a Poisson response.</p>
<p>Moving away from our intuition of number of trials until the <span class="math inline">\(k\)</span>th success, we can formally replace the factorials in <span class="math inline">\({{x + k -1}\choose {k-1}}\)</span> with gamma functions, and then <span class="math inline">\(k\)</span> can be any positive integer! In this case, we have the probability mass function is given by</p>
<p><span class="math display">\[
P(X = x) = \frac{\Gamma(x + k)}{\Gamma(k) x!} p^k(1 - p)^{x - k}, \qquad x = 0, 1, 2, \ldots
\]</span></p>
<p>While this may defy straightforward interpretation in terms of Bernoulli trials, having the additional flexibility to choose <span class="math inline">\(k\)</span> to be non-integral will be useful when modeling.</p>
<p>An alternative parameterization that yields the same family of random variables is by the <em>mean</em> parameter <span class="math inline">\(\mu\)</span> and the <em>dispersion</em> parameter, given by <code>size</code>. The variance in this parameterization is <span class="math inline">\(\sigma^2 = \mu + \mu^2/{\text{size}}\)</span>. We can go from the mean/dispersion parameterization to the one given above by letting <span class="math inline">\(p = {\text{size}/({\text{size} + \mu)\)</span> and <span class="math inline">\(k = {\text{size}\)</span>. Let’s check it with some R.</p>
<div class="sourceCode" id="cb941"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb941-1"><a href="generalized-linear-models.html#cb941-1" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb941-2"><a href="generalized-linear-models.html#cb941-2" tabindex="-1"></a>size <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb941-3"><a href="generalized-linear-models.html#cb941-3" tabindex="-1"></a>k <span class="ot">&lt;-</span> size</span>
<span id="cb941-4"><a href="generalized-linear-models.html#cb941-4" tabindex="-1"></a>p <span class="ot">&lt;-</span> size<span class="sc">/</span>(size <span class="sc">+</span> mu)</span>
<span id="cb941-5"><a href="generalized-linear-models.html#cb941-5" tabindex="-1"></a><span class="fu">dnbinom</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> size, <span class="at">prob =</span> p)</span></code></pre></div>
<pre><code>##  [1] 0.01903969 0.03399944 0.04857063 0.06071328 0.06938661 0.07434280
##  [7] 0.07586000 0.07450535 0.07095748 0.06588909</code></pre>
<div class="sourceCode" id="cb943"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb943-1"><a href="generalized-linear-models.html#cb943-1" tabindex="-1"></a><span class="fu">dnbinom</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> size, <span class="at">mu =</span> mu)</span></code></pre></div>
<pre><code>##  [1] 0.01903969 0.03399944 0.04857063 0.06071328 0.06938661 0.07434280
##  [7] 0.07586000 0.07450535 0.07095748 0.06588909</code></pre>
<p>With the mean-dispersion parameterization, we can see that the variance can be any value that is larger than the mean. This allows quite a bit of fliexibility for modeling overdispersed count processes.</p>
<p>Now, suppose we have data <span class="math inline">\((x_1, y_1), \ldots, (x_n, y_n)\)</span> and we believe that the expected value of the response <span class="math inline">\(Y\)</span> given <span class="math inline">\(x\)</span> is modeled by
<span class="math display">\[
\log E[Y|X = x] = \beta_0 + \beta_1 x
\]</span>
then we would have
<span class="math display">\[
\log \mu = \beta_0 + \beta_1 x
\]</span>
The inverse link function is <span class="math inline">\(\mu = e^{\beta_0 + \beta_1 x}\)</span>, and the random component of the model is negative binomial.</p>
<p>Let’s create some simulated data.</p>
<div class="sourceCode" id="cb945"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb945-1"><a href="generalized-linear-models.html#cb945-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4282020</span>)</span>
<span id="cb945-2"><a href="generalized-linear-models.html#cb945-2" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">10</span>))</span>
<span id="cb945-3"><a href="generalized-linear-models.html#cb945-3" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">mutate</span>(dd, <span class="at">y =</span> <span class="fu">rnbinom</span>(<span class="dv">100</span>, <span class="at">size =</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">10</span>), <span class="at">mu =</span> <span class="fu">exp</span>(<span class="dv">1</span> <span class="sc">+</span> .<span class="dv">2</span> <span class="sc">*</span> x)))</span>
<span id="cb945-4"><a href="generalized-linear-models.html#cb945-4" tabindex="-1"></a><span class="fu">plot</span>(dd)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>Recall that if this were Poisson, then the range would be roughly the expected value <span class="math inline">\(y_0 \pm 2\sqrt{y_0}\)</span>, which is not correct. When <span class="math inline">\(x \approx 10\)</span>, <span class="math inline">\(y \approx 15\)</span>, but the range is bigger than <span class="math inline">\(15 \pm 8\)</span>. Let’s set up the likelihood function for the model. There are three parameters in the model, <span class="math inline">\(\beta_0, \beta_1\)</span> and the size parameter, which estimates the amount of overdispersion.</p>
<p><span class="math display">\[
\Pi \ {\text{dnbinom}}(y_i, mu = e^{\beta_0 + \beta_1 x_i}, size = k)
\]</span></p>
<p>Let’s maximize the log likelihood.</p>
<div class="sourceCode" id="cb946"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb946-1"><a href="generalized-linear-models.html#cb946-1" tabindex="-1"></a>neg_log_likelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(par, dat) {</span>
<span id="cb946-2"><a href="generalized-linear-models.html#cb946-2" tabindex="-1"></a>  <span class="sc">-</span><span class="dv">1</span> <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(<span class="fu">dnbinom</span>(dat<span class="sc">$</span>y, <span class="at">mu =</span> <span class="fu">exp</span>(par[<span class="dv">1</span>] <span class="sc">+</span> par[<span class="dv">2</span>] <span class="sc">*</span> dat<span class="sc">$</span>x), <span class="at">size =</span> par[<span class="dv">3</span>])))</span>
<span id="cb946-3"><a href="generalized-linear-models.html#cb946-3" tabindex="-1"></a>}</span>
<span id="cb946-4"><a href="generalized-linear-models.html#cb946-4" tabindex="-1"></a></span>
<span id="cb946-5"><a href="generalized-linear-models.html#cb946-5" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">fn =</span> neg_log_likelihood, <span class="at">dat =</span> dd)<span class="sc">$</span>par</span></code></pre></div>
<pre><code>## [1] 0.9586144 0.2090342 3.5983988</code></pre>
<p>We get an estimate of <span class="math inline">\(\beta_0 = 0.9586, \beta_1 = 0.209\)</span> and dispersion parameter of 3.598. That’s close to the true values of <span class="math inline">\(1, 2\)</span> and unknown. Let’s run the analysis using <code>MASS:glm.nb</code>.</p>
<div class="sourceCode" id="cb948"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb948-1"><a href="generalized-linear-models.html#cb948-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">glm.nb</span>(y <span class="sc">~</span> ., <span class="at">data =</span> dd)</span>
<span id="cb948-2"><a href="generalized-linear-models.html#cb948-2" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## MASS::glm.nb(formula = y ~ ., data = dd, init.theta = 3.598485478, 
##     link = log)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.95853    0.13877   6.907 4.95e-12 ***
## x            0.20905    0.02093   9.989  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(3.5985) family taken to be 1)
## 
##     Null deviance: 210.32  on 99  degrees of freedom
## Residual deviance: 109.87  on 98  degrees of freedom
## AIC: 591.29
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  3.598 
##           Std. Err.:  0.784 
## 
##  2 x log-likelihood:  -585.286</code></pre>
<p><code>MASS::stapAIC</code> also works with models built with <code>glm.nb</code>, so we can do variable selection using AIC when we have a larger collection of variables. Let’s look at the <code>quine</code> data set.</p>
<div class="sourceCode" id="cb950"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb950-1"><a href="generalized-linear-models.html#cb950-1" tabindex="-1"></a>quine <span class="ot">&lt;-</span> MASS<span class="sc">::</span>quine</span>
<span id="cb950-2"><a href="generalized-linear-models.html#cb950-2" tabindex="-1"></a>mod <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">glm.nb</span>(Days <span class="sc">~</span> ., <span class="at">data =</span> quine)</span>
<span id="cb950-3"><a href="generalized-linear-models.html#cb950-3" tabindex="-1"></a>mod_final <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">stepAIC</span>(mod, <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb950-4"><a href="generalized-linear-models.html#cb950-4" tabindex="-1"></a><span class="fu">summary</span>(mod_final)</span></code></pre></div>
<pre><code>## 
## Call:
## MASS::glm.nb(formula = Days ~ Eth + Age + Lrn, data = quine, 
##     init.theta = 1.271992937, link = log)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   2.9351     0.2017  14.551  &lt; 2e-16 ***
## EthN         -0.5627     0.1535  -3.667 0.000246 ***
## AgeF1        -0.4703     0.2363  -1.990 0.046590 *  
## AgeF2         0.1009     0.2363   0.427 0.669391    
## AgeF3         0.3591     0.2452   1.465 0.142999    
## LrnSL         0.2848     0.1848   1.541 0.123203    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(1.272) family taken to be 1)
## 
##     Null deviance: 194.92  on 145  degrees of freedom
## Residual deviance: 167.89  on 140  degrees of freedom
## AIC: 1107.4
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  1.272 
##           Std. Err.:  0.161 
## 
##  2 x log-likelihood:  -1093.401</code></pre>
<p>Venables and Ripley consider interactions and get a much different looking model. See their book, Modern Applied Statistics with S, Section 7.4 for details.</p>
</div>
</div>
<div id="zero-truncated-and-zero-inflated-models" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Zero-truncated and Zero-inflated models<a href="generalized-linear-models.html#zero-truncated-and-zero-inflated-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we present two relatively common occurrences when we have a count response. A count response is <em>zero truncated</em> if all of the observations with zero as a response are removed from the data set. A count response is <em>zero inflated</em> if there are more zeros than there should be in a Poisson response.</p>
<p>The reasons for zero truncated could be that we only have a mechanism for collecting data in the case that the response is nonzero. For example, if we are counting the number of days a person with a certain type of disease spends in the hosptial, we might not know how many people have that disease but never need to go to the hospital. We would only discover them once the response is 1 or greater.</p>
<p>One reason for zero inflated data could be that there is a group of observations that are zero, while the others follow a Poisson model. If we count the number of cigarettes that people smoke in a two-hour period, there could be two sources of zeros. One source of zeros would be people who smoke, but just didn’t smoke in that two hour window. That would follow a Poisson response, possibly. However, another source of zeros could be people who never smoke. Adding those zeros in could make the response look like it is not Poisson. The two sources of zeros are called <em>structural</em> zeros and <em>chance</em> zeros, and we will have to build a model that takes this into account.</p>
<div id="zero-truncated-poisson" class="section level3 hasAnchor" number="9.3.1">
<h3><span class="header-section-number">9.3.1</span> Zero-truncated Poisson<a href="generalized-linear-models.html#zero-truncated-poisson" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s start with zero-truncated models. The zero-truncated Poisson random variable has pmf given by</p>
<p><span class="math display">\[
P(X = x) = \frac{e^{-\lambda} \lambda^x}{x!(1 - e^{-\lambda})} \qquad x =1, 2, \ldots
\]</span></p>
<p>The mean of a zero truncated Poisson is <span class="math inline">\(\mu = \frac{\lambda}{(1 - e^{-\lambda})^2}\)</span>. We assume that the mean of the <strong>underlying Poisson process</strong> is modeled by</p>
<p><span class="math display">\[
\log \lambda = \beta_0 + \beta_1 x_1 + \cdots + \beta_p x_p
\]</span></p>
<p>In the language from above, the random component of our model is a zero-truncated Poisson, the model is <span class="math inline">\(\log \lambda = \beta_0 + \beta_1 x_1 + \cdots + \beta_p x_p\)</span>, the link function is <span class="math inline">\(\log x\)</span> and the inverse link function is <span class="math inline">\(e^x\)</span>. Formally, this procedure may not belong in the generalized linear model section, because we are not modeling the <em>expected value</em> of the random component given the parameters, but rather the expected value of some other process. The same comment applies to the next section, where we discuss zero-truncated negative binomial regression.</p>
<p>We will again use maximum likelihood to estimate the <span class="math inline">\(\lambda\)</span> in the zero-truncated Poisson regression. The pmf is available in the <code>actuar</code> package via <code>actuar::dztpois(x, lambda, log = FALSE)</code>. Let’s suppose we collect data <span class="math inline">\((x_1, y_1), \ldots, (x_n, y_n)\)</span> and we wish to find the MLE of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in our model. This is how we can do it. We first create some simulated data.</p>
<div class="sourceCode" id="cb952"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb952-1"><a href="generalized-linear-models.html#cb952-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4282020</span>)</span>
<span id="cb952-2"><a href="generalized-linear-models.html#cb952-2" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb952-3"><a href="generalized-linear-models.html#cb952-3" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">mutate</span>(dd, <span class="at">y =</span> <span class="fu">rpois</span>(<span class="dv">100</span>, <span class="at">lambda =</span> <span class="fu">exp</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> x)))</span>
<span id="cb952-4"><a href="generalized-linear-models.html#cb952-4" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">filter</span>(dd, y <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="co">#zero truncated</span></span></code></pre></div>
<p>Fitting zero-truncated Poisson regression to this data using maximum likelihood is an exercise. We can use the <code>vglm</code> function in the <code>VGAM</code> package to fit the data to the model and perform hypothesis testing as follows.</p>
<div class="sourceCode" id="cb953"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb953-1"><a href="generalized-linear-models.html#cb953-1" tabindex="-1"></a><span class="fu">library</span>(VGAM)</span>
<span id="cb953-2"><a href="generalized-linear-models.html#cb953-2" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">vglm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dd, <span class="at">family =</span> <span class="fu">pospoisson</span>())</span>
<span id="cb953-3"><a href="generalized-linear-models.html#cb953-3" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## vglm(formula = y ~ x, family = pospoisson(), data = dd)
## 
## Coefficients: 
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   1.0218     0.1013   10.09   &lt;2e-16 ***
## x             1.9396     0.1383   14.03   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Name of linear predictor: loglink(lambda) 
## 
## Log-likelihood: -159.8879 on 77 degrees of freedom
## 
## Number of Fisher scoring iterations: 6</code></pre>
<p>We see that the MLE of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are pretty close to the true values of 1 and 2.</p>
</div>
<div id="zero-truncated-negative-binomial" class="section level3 hasAnchor" number="9.3.2">
<h3><span class="header-section-number">9.3.2</span> Zero-truncated Negative Binomial<a href="generalized-linear-models.html#zero-truncated-negative-binomial" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The zero-truncated negative binomial random variable is a negative binomial random variable which suppresses all instances of 0. For example, if you are counting the number of failures until the second success in a sequence of Bernoulli trials, but you only record an answer if there is at least one failure! That would be a zero-truncated negative binomial random variable.</p>
<p>It has pmf given by</p>
<p><span class="math display">\[
P(X = x) =  \frac{\Gamma(x+r) p^r (1-p)^x}{\Gamma(r) x! (1-p^r)}
\]</span></p>
<p>where <span class="math inline">\(p\)</span> is the probability of success, <span class="math inline">\(r\)</span> is the number of successes, and <span class="math inline">\(x\)</span> is the number of failures before the <span class="math inline">\(r\)</span>th success. As with the regular negative binomial rv, when using this for modeling we will not concern ourselves with forcing <span class="math inline">\(r\)</span> to be an integer. Again, we want to re-parameterize this by the mean/coefficient of variation parameterization. However, I don’t know of an R package that has the zero-truncated negative binomial rv with the mean/coefficient of variation parameterization. So, we’ll just have to figure it out ourselves. The key observation is that the zero-truncated pmf is just the regular pmf divided by <span class="math inline">\(1 - P(X = 0)\)</span>. So, we can use the <code>dnbinom</code> function and divide by one minus the probability that <span class="math inline">\(X = 0\)</span>.</p>
<div class="sourceCode" id="cb955"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb955-1"><a href="generalized-linear-models.html#cb955-1" tabindex="-1"></a><span class="fu">library</span>(actuar)</span>
<span id="cb955-2"><a href="generalized-linear-models.html#cb955-2" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb955-3"><a href="generalized-linear-models.html#cb955-3" tabindex="-1"></a>size <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb955-4"><a href="generalized-linear-models.html#cb955-4" tabindex="-1"></a>k <span class="ot">&lt;-</span> size</span>
<span id="cb955-5"><a href="generalized-linear-models.html#cb955-5" tabindex="-1"></a>p <span class="ot">&lt;-</span> size<span class="sc">/</span>(size <span class="sc">+</span> mu)</span>
<span id="cb955-6"><a href="generalized-linear-models.html#cb955-6" tabindex="-1"></a></span>
<span id="cb955-7"><a href="generalized-linear-models.html#cb955-7" tabindex="-1"></a>my_dztnbinom <span class="ot">&lt;-</span> <span class="cf">function</span> (x, size, mu) {</span>
<span id="cb955-8"><a href="generalized-linear-models.html#cb955-8" tabindex="-1"></a>  <span class="fu">dnbinom</span>(x, <span class="at">size =</span> size, <span class="at">mu =</span> mu)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">dnbinom</span>(<span class="dv">0</span>, <span class="at">size =</span> size, <span class="at">mu =</span> mu))</span>
<span id="cb955-9"><a href="generalized-linear-models.html#cb955-9" tabindex="-1"></a>}</span>
<span id="cb955-10"><a href="generalized-linear-models.html#cb955-10" tabindex="-1"></a><span class="fu">dztnbinom</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> size, <span class="at">prob =</span> p)</span></code></pre></div>
<pre><code>##  [1] 0.01916742 0.03422753 0.04889647 0.06112058 0.06985210 0.07484153
##  [7] 0.07636891 0.07500518 0.07143350 0.06633111</code></pre>
<div class="sourceCode" id="cb957"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb957-1"><a href="generalized-linear-models.html#cb957-1" tabindex="-1"></a><span class="fu">my_dztnbinom</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> size, <span class="at">mu =</span> mu)</span></code></pre></div>
<pre><code>##  [1] 0.01916742 0.03422753 0.04889647 0.06112058 0.06985210 0.07484153
##  [7] 0.07636891 0.07500518 0.07143350 0.06633111</code></pre>
<p>Now we can overwrite the <code>dztnbinom</code> function to allow for the new parameterization.</p>
<div class="sourceCode" id="cb959"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb959-1"><a href="generalized-linear-models.html#cb959-1" tabindex="-1"></a>dztnbinom <span class="ot">&lt;-</span> <span class="cf">function</span> (x, size, prob, mu, <span class="at">log =</span> <span class="cn">FALSE</span>) </span>
<span id="cb959-2"><a href="generalized-linear-models.html#cb959-2" tabindex="-1"></a>{</span>
<span id="cb959-3"><a href="generalized-linear-models.html#cb959-3" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">missing</span>(mu)) {</span>
<span id="cb959-4"><a href="generalized-linear-models.html#cb959-4" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">missing</span>(prob)) </span>
<span id="cb959-5"><a href="generalized-linear-models.html#cb959-5" tabindex="-1"></a>      <span class="fu">stop</span>(<span class="st">&quot;&#39;prob&#39; and &#39;mu&#39; both specified&quot;</span>)</span>
<span id="cb959-6"><a href="generalized-linear-models.html#cb959-6" tabindex="-1"></a>    <span class="fu">dnbinom</span>(x, <span class="at">size =</span> size, <span class="at">mu =</span> mu, <span class="at">log =</span> log)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">dnbinom</span>(<span class="dv">0</span>, <span class="at">size =</span> size, <span class="at">mu =</span> mu, <span class="at">log =</span> log))</span>
<span id="cb959-7"><a href="generalized-linear-models.html#cb959-7" tabindex="-1"></a>  }</span>
<span id="cb959-8"><a href="generalized-linear-models.html#cb959-8" tabindex="-1"></a>  <span class="cf">else</span> </span>
<span id="cb959-9"><a href="generalized-linear-models.html#cb959-9" tabindex="-1"></a>    <span class="fu">dnbinom</span>(x, <span class="at">prob =</span> prob, <span class="at">mu =</span> mu, <span class="at">log =</span> log)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">dnbinom</span>(<span class="dv">0</span>, <span class="at">prob =</span> prob, <span class="at">mu =</span> mu, <span class="at">log =</span> log))</span>
<span id="cb959-10"><a href="generalized-linear-models.html#cb959-10" tabindex="-1"></a>}</span>
<span id="cb959-11"><a href="generalized-linear-models.html#cb959-11" tabindex="-1"></a><span class="fu">dztnbinom</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> size, <span class="at">mu =</span> mu)</span></code></pre></div>
<pre><code>##  [1] 0.01916742 0.03422753 0.04889647 0.06112058 0.06985210 0.07484153
##  [7] 0.07636891 0.07500518 0.07143350 0.06633111</code></pre>
<div class="sourceCode" id="cb961"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb961-1"><a href="generalized-linear-models.html#cb961-1" tabindex="-1"></a><span class="fu">dztnbinom</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> size, <span class="at">mu =</span> mu)</span></code></pre></div>
<pre><code>##  [1] 0.01916742 0.03422753 0.04889647 0.06112058 0.06985210 0.07484153
##  [7] 0.07636891 0.07500518 0.07143350 0.06633111</code></pre>
<p>And now we are ready to do some MLE! Let’s specify our model. We want the mean of the <strong>underlying negative binomial</strong> process to be modeled as follows</p>
<p><span class="math display">\[
\log \mu = \beta_0 + \beta_1 x
\]</span></p>
<p>In the previous terminology, <span class="math inline">\(\log x\)</span> is the link function between the mean and an affine combination of the data. The random component is a zero-truncated negative binomial. The inverse link function is <span class="math inline">\(e^x\)</span>. Let’s simulate some data so that we can see how to estimate the regression coefficients.</p>
<div class="sourceCode" id="cb963"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb963-1"><a href="generalized-linear-models.html#cb963-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4262020</span>)</span>
<span id="cb963-2"><a href="generalized-linear-models.html#cb963-2" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb963-3"><a href="generalized-linear-models.html#cb963-3" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">mutate</span>(dd, <span class="at">y =</span> <span class="fu">rnbinom</span>(<span class="dv">100</span>, <span class="at">size =</span> .<span class="dv">5</span>, <span class="at">mu =</span> <span class="fu">exp</span>(<span class="dv">2</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> x)))</span>
<span id="cb963-4"><a href="generalized-linear-models.html#cb963-4" tabindex="-1"></a>dd</span></code></pre></div>
<pre><code>##                x  y
## 1    0.170993186 18
## 2    0.375300541  0
## 3    0.281447049  6
## 4   -0.854342901  2
## 5    0.150880047  0
## 6   -0.815236508  1
## 7   -0.738369224  5
## 8   -0.440263602  7
## 9    0.489286514  6
## 10   0.744745331  0
## 11   0.232549767  3
## 12   0.258230929  6
## 13  -0.112918955  0
## 14  -0.923138482  9
## 15  -0.562771956  0
## 16   0.051223283 13
## 17  -0.485341243  1
## 18   0.610339857  5
## 19   0.819750741  0
## 20   0.783148877  3
## 21  -0.244826317  7
## 22  -0.409389773  8
## 23   0.068875154  3
## 24   0.926476205 51
## 25  -0.999843684  1
## 26  -0.970835708  1
## 27  -0.264972612 11
## 28  -0.119498989 19
## 29  -0.081942339 13
## 30   0.967341606  4
## 31   0.076330998 12
## 32   0.507778269 48
## 33   0.303157959 10
## 34   0.711482182  8
## 35  -0.797571424  3
## 36  -0.439347654  8
## 37   0.009510677  2
## 38  -0.067575793  9
## 39  -0.798861790  1
## 40   0.228011895  0
## 41   0.087560974  3
## 42  -0.296066989  1
## 43   0.492838309  2
## 44   0.964433337 27
## 45   0.098588133  0
## 46  -0.399391057  2
## 47  -0.168859638  0
## 48  -0.677089159  0
## 49   0.115597256  1
## 50   0.633840136  1
## 51   0.220166541 39
## 52  -0.347090407  1
## 53  -0.844580242  0
## 54  -0.035160714 10
## 55  -0.131569571  0
## 56  -0.319573729 22
## 57   0.392324590  4
## 58  -0.095381256  5
## 59  -0.319805362  0
## 60  -0.504306185  0
## 61  -0.137330514 62
## 62   0.265613862 12
## 63   0.329149127  1
## 64  -0.247087092  0
## 65   0.907833416 26
## 66  -0.668449968  4
## 67  -0.254085941  3
## 68  -0.772649831  0
## 69   0.565478984  2
## 70   0.763608859  1
## 71  -0.226325991  1
## 72  -0.373414507 10
## 73   0.130113899  0
## 74   0.067783114  4
## 75  -0.772828367  3
## 76   0.366145706  7
## 77  -0.496201407 10
## 78  -0.043936161  6
## 79  -0.452359735  1
## 80  -0.445651472  6
## 81  -0.239117800  0
## 82  -0.252871985  0
## 83  -0.622016171  0
## 84  -0.678720623  2
## 85  -0.488304695  0
## 86  -0.130424898  3
## 87  -0.810557025  7
## 88   0.237559375 16
## 89  -0.803594951  3
## 90  -0.817366301  1
## 91   0.328819702  0
## 92   0.740088642 39
## 93  -0.058261213  0
## 94  -0.104794809  0
## 95   0.036119353  7
## 96  -0.937294856  9
## 97   0.661555759  8
## 98   0.174056601 12
## 99   0.639136216 11
## 100  0.708411426 75</code></pre>
<div class="sourceCode" id="cb965"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb965-1"><a href="generalized-linear-models.html#cb965-1" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">filter</span>(dd, y <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="co">#zero-truncated!</span></span></code></pre></div>
<p>Now we set up the log-likelihood function and maximize it, as before.</p>
<div class="sourceCode" id="cb966"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb966-1"><a href="generalized-linear-models.html#cb966-1" tabindex="-1"></a>neg_log_likelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(pars, data) {</span>
<span id="cb966-2"><a href="generalized-linear-models.html#cb966-2" tabindex="-1"></a>  <span class="sc">-</span><span class="dv">1</span> <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(<span class="fu">dztnbinom</span>(data<span class="sc">$</span>y, <span class="at">size =</span> pars[<span class="dv">3</span>], <span class="at">mu =</span> <span class="fu">exp</span>(pars[<span class="dv">1</span>] <span class="sc">+</span> pars[<span class="dv">2</span>] <span class="sc">*</span> data<span class="sc">$</span>x))))</span>
<span id="cb966-3"><a href="generalized-linear-models.html#cb966-3" tabindex="-1"></a>}</span>
<span id="cb966-4"><a href="generalized-linear-models.html#cb966-4" tabindex="-1"></a></span>
<span id="cb966-5"><a href="generalized-linear-models.html#cb966-5" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,.<span class="dv">1</span>), <span class="at">fn =</span> neg_log_likelihood, <span class="at">data =</span> dd)</span></code></pre></div>
<pre><code>## $par
## [1] 1.9502840 1.1872732 0.5729213
## 
## $value
## [1] 235.3658
## 
## $counts
## function gradient 
##      126       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We see that our estimate are <span class="math inline">\(\hat \beta_0 = 1.95\)</span>, <span class="math inline">\(\hat \beta_1 = 1.19\)</span> and <span class="math inline">\(\hat size = 0.573\)</span>. Let’s compare to what happens when we use the built in R function.</p>
<div class="sourceCode" id="cb968"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb968-1"><a href="generalized-linear-models.html#cb968-1" tabindex="-1"></a><span class="fu">library</span>(VGAM)</span>
<span id="cb968-2"><a href="generalized-linear-models.html#cb968-2" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">vgam</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dd, <span class="at">family =</span> <span class="fu">posnegbinomial</span>())</span>
<span id="cb968-3"><a href="generalized-linear-models.html#cb968-3" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## vgam(formula = y ~ x, family = posnegbinomial(), data = dd)
## 
## Names of additive predictors: loglink(munb), loglink(size)
## 
## Dispersion Parameter for posnegbinomial family:   1
## 
## Log-likelihood: -235.3658 on 149 degrees of freedom
## 
## Number of Fisher scoring iterations:  5 
## 
## DF for Terms and Approximate Chi-squares for Nonparametric Effects
## 
##               Df Npar Df Npar Chisq P(Chi)
## (Intercept):1  1                          
## (Intercept):2  1                          
## x              1</code></pre>
<div class="sourceCode" id="cb970"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb970-1"><a href="generalized-linear-models.html#cb970-1" tabindex="-1"></a><span class="fu">coefficients</span>(mod)</span></code></pre></div>
<pre><code>## (Intercept):1 (Intercept):2             x 
##     1.9503818    -0.5568325     1.1874578</code></pre>
<p>The first intercept is <span class="math inline">\(\hat \beta_0\)</span>, while the second intercept is <span class="math inline">\(\log \hat{size}\)</span> and the <span class="math inline">\(x\)</span> coefficient is <span class="math inline">\(\hat \beta_1\)</span>. These values match what we computed with <code>optim</code>.</p>
<div class="sourceCode" id="cb972"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb972-1"><a href="generalized-linear-models.html#cb972-1" tabindex="-1"></a><span class="fu">log</span>(.<span class="dv">573</span>) <span class="co">#compare to (Intercept):2</span></span></code></pre></div>
<pre><code>## [1] -0.5568696</code></pre>
</div>
<div id="zero-inflated-poisson-and-negative-binomial" class="section level3 hasAnchor" number="9.3.3">
<h3><span class="header-section-number">9.3.3</span> Zero-Inflated Poisson and Negative Binomial<a href="generalized-linear-models.html#zero-inflated-poisson-and-negative-binomial" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this last section of the notes, we discuss <strong>zero-inflated</strong> count responses. We assume that the response is Poisson (except for the zero inflation) and that the mean of the poisson response depends on an affine combination of the predictors via a log-link function. We also assume that the inflation at zero depends on an affine combination of the predictors via a logit (log-odds) link. That is, we assume that</p>
<p><span class="math display">\[
P(Y = y) = \begin{cases}
\pi + ( 1- \pi) e^{-\lambda} &amp;y = 0\\
(1 - \pi) e^{-\lambda} \lambda^y/y!&amp; y = 1, 2, \ldots
\end{cases}
\]</span></p>
<p>We model <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\pi\)</span> on the data as follows:</p>
<p><span class="math display">\[
\log \frac{\pi}{1-\pi} = \beta_0 + \beta_1 x_1 + \cdots + \beta_p x_p
\]</span></p>
<p><span class="math display">\[
\log \lambda = \beta_0 + \beta_{p+1} x_{p+1} + \cdots \beta_m x_m
\]</span></p>
<p>Note that we are using some of the variables to predict the <em>structural zero</em> and the other variables are used to predict the rate of the Poisson. Deciding which variables should be used for which purpose can be challenging. We can also allow variables to serve both purposes, which often makes the most intuitive sense: if a predictor is important for whether a response is non-zero, why wouldn’t it also be important for the magnitude of the response? We can use <span class="math inline">\(p\)</span>-values to eliminate variables in our models, or use AIC.
Solving the relationships between parameters and predictors for the parameters, we have <span class="math inline">\(\pi = \frac{1}{1 + e^{- \beta_0 - \sum \beta_i x_i}}\)</span> and <span class="math inline">\(\lambda = e^{\beta_0 + \sum \beta_i x_i}\)</span>. We will use the function <code>dzipois</code> in the <code>VGAM</code> library to access the zero-inflated Poisson pmf.</p>
<p><strong>Example</strong> Suppose you randomly select a person from a population and count the number of cigarettes that person smokes in one hour. In your population, 40% of the people do not smoke, and 60% of the people do smoke. Among those people who do smoke, the rate of cigarettes smoked is 2 cigarettes per hour. What is the probability that the person you selected smokes one cigarette in the hour you observe?</p>
<p>The zero-inflated negative binomial response is similar in the sense that it adds a log odds model for <span class="math inline">\(\pi\)</span> on top of the base negative binomial model. Details are omitted.</p>
<p>Let’s look at an example. In the <code>pscl</code> package there is a data set called <code>bioChemists</code> that can be loaded via the following commands.</p>
<div class="sourceCode" id="cb974"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb974-1"><a href="generalized-linear-models.html#cb974-1" tabindex="-1"></a><span class="fu">library</span>(pscl)</span>
<span id="cb974-2"><a href="generalized-linear-models.html#cb974-2" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;bioChemists&quot;</span>)</span></code></pre></div>
<p>Let’s explore the data a bit. The response variable is <code>art</code>, which is the number of articles produced during the last 3 years of PhD. The predictors are gebder <code>fem</code>, marital status <code>mar</code>, number of children under 5 <code>kid5</code>, the prestige of the PhD department <code>phd</code> and the number of articles published by the PhD mentor in the last three years <code>ment</code>. Let’s look at some visualizations.</p>
<div class="sourceCode" id="cb975"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb975-1"><a href="generalized-linear-models.html#cb975-1" tabindex="-1"></a><span class="fu">plot</span>(bioChemists)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>I am especially interested in the top row, which shows how <code>art</code> related to each predictor individually. We leave <code>kid5</code> as numeric, though we might revisit this decision later. Let’s start with a basic Poisson regression on all of the variables.</p>
<div class="sourceCode" id="cb976"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb976-1"><a href="generalized-linear-models.html#cb976-1" tabindex="-1"></a>mod_pois <span class="ot">&lt;-</span> <span class="fu">glm</span>(art <span class="sc">~</span> ., <span class="at">data =</span> bioChemists, <span class="at">family =</span> poisson)</span>
<span id="cb976-2"><a href="generalized-linear-models.html#cb976-2" tabindex="-1"></a><span class="fu">summary</span>(mod_pois)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = art ~ ., family = poisson, data = bioChemists)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.304617   0.102981   2.958   0.0031 ** 
## femWomen    -0.224594   0.054613  -4.112 3.92e-05 ***
## marMarried   0.155243   0.061374   2.529   0.0114 *  
## kid5        -0.184883   0.040127  -4.607 4.08e-06 ***
## phd          0.012823   0.026397   0.486   0.6271    
## ment         0.025543   0.002006  12.733  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 1817.4  on 914  degrees of freedom
## Residual deviance: 1634.4  on 909  degrees of freedom
## AIC: 3314.1
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>We see that this is unlikely to be a good model, because of overdispersion. There may also be other reasons this is not a good model!</p>
<p>Let’s try negative binomial.</p>
<div class="sourceCode" id="cb978"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb978-1"><a href="generalized-linear-models.html#cb978-1" tabindex="-1"></a>mod_nb <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">glm.nb</span>(art <span class="sc">~</span> ., <span class="at">data =</span> bioChemists)</span>
<span id="cb978-2"><a href="generalized-linear-models.html#cb978-2" tabindex="-1"></a><span class="fu">summary</span>(mod_nb)</span></code></pre></div>
<pre><code>## 
## Call:
## MASS::glm.nb(formula = art ~ ., data = bioChemists, init.theta = 2.264387695, 
##     link = log)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.256144   0.137348   1.865 0.062191 .  
## femWomen    -0.216418   0.072636  -2.979 0.002887 ** 
## marMarried   0.150489   0.082097   1.833 0.066791 .  
## kid5        -0.176415   0.052813  -3.340 0.000837 ***
## phd          0.015271   0.035873   0.426 0.670326    
## ment         0.029082   0.003214   9.048  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(2.2644) family taken to be 1)
## 
##     Null deviance: 1109.0  on 914  degrees of freedom
## Residual deviance: 1004.3  on 909  degrees of freedom
## AIC: 3135.9
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  2.264 
##           Std. Err.:  0.271 
## 
##  2 x log-likelihood:  -3121.917</code></pre>
<div class="sourceCode" id="cb980"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb980-1"><a href="generalized-linear-models.html#cb980-1" tabindex="-1"></a><span class="fu">plot</span>(mod_nb, <span class="at">which =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="08-generalized-linear-models_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
<p>This model looks fine. Let’s see how it compares to the zero inflated model. We need to specify which variables are part of the model for <span class="math inline">\(\lambda\)</span> and which variables are part of the model for <span class="math inline">\(\pi\)</span>, using a <code>|</code>. The variables before the <code>|</code> are for <span class="math inline">\(\lambda\)</span>.</p>
<div class="sourceCode" id="cb981"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb981-1"><a href="generalized-linear-models.html#cb981-1" tabindex="-1"></a>mod_zif_nb <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(art <span class="sc">~</span> . <span class="sc">|</span> ., <span class="at">data =</span> bioChemists, <span class="at">dist =</span> <span class="st">&quot;negbin&quot;</span>)</span>
<span id="cb981-2"><a href="generalized-linear-models.html#cb981-2" tabindex="-1"></a><span class="fu">summary</span>(mod_zif_nb)</span></code></pre></div>
<pre><code>## 
## Call:
## zeroinfl(formula = art ~ . | ., data = bioChemists, dist = &quot;negbin&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -1.2942 -0.7601 -0.2909  0.4448  6.4155 
## 
## Count model coefficients (negbin with log link):
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.4167465  0.1435966   2.902  0.00371 ** 
## femWomen    -0.1955068  0.0755926  -2.586  0.00970 ** 
## marMarried   0.0975826  0.0844520   1.155  0.24789    
## kid5        -0.1517325  0.0542061  -2.799  0.00512 ** 
## phd         -0.0007001  0.0362697  -0.019  0.98460    
## ment         0.0247862  0.0034927   7.097 1.28e-12 ***
## Log(theta)   0.9763565  0.1354695   7.207 5.71e-13 ***
## 
## Zero-inflation model coefficients (binomial with logit link):
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) -0.19169    1.32282  -0.145  0.88478   
## femWomen     0.63593    0.84892   0.749  0.45379   
## marMarried  -1.49947    0.93867  -1.597  0.11017   
## kid5         0.62843    0.44278   1.419  0.15582   
## phd         -0.03771    0.30801  -0.122  0.90254   
## ment        -0.88229    0.31623  -2.790  0.00527 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Theta = 2.6548 
## Number of iterations in BFGS optimization: 43 
## Log-likelihood: -1550 on 13 Df</code></pre>
<p>The residuals look worse in this model, but notice that they are the <strong>Pearson</strong> residuals and not the <strong>deviance residuals</strong>. To compare apples to apples, let’s look at the Pearson residuals in the original negative binomial model. These seem more or less the same as the model we built.</p>
<div class="sourceCode" id="cb983"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb983-1"><a href="generalized-linear-models.html#cb983-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">residuals</span>(mod_nb, <span class="at">type =</span> <span class="st">&quot;pearson&quot;</span>))</span></code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -1.267713 -0.875449 -0.261250 -0.001516  0.498346  6.657253</code></pre>
<p>There are several things that we need to do now. We should remove predictors that aren’t significant to the model, and we also need to figure out which model we should be using. I don’t have definitive answers for you on this.</p>
<ol style="list-style-type: decimal">
<li>I have seen it argued that negative binomial models are already flexible enough that we don’t normally need to have zero inflated negative binomial responses.</li>
<li>Some people use the Vuong test to determine whether to use the zero inflated model. Others have problems with the Vuong test. The current consensus seems to be that it is inappropriate to use it, but you shouldn’t be surprised to see it <a href="https://stats.idre.ucla.edu/r/dae/zip/">in the wild</a>. I will not discuss how to use it or interpret it.</li>
<li>That leaves us with few options to evaluate our models! Let’s look at the number of zeros that we have in our data, compared to the number of zeros that our models predict. I would point out that this has low power, but it does test directly what we are trying to do.</li>
<li>One last option is to base the model on expert opinion, and see whether any of the predictors are significant for the zero inflation part. This is also tricky.</li>
</ol>
<p>To do this, we really have to understand what <code>glm.nb</code> is doing. The dispersion parameter is the value of <code>size</code> in <code>dnbinom</code>, and the coefficients are how we get <code>mu</code>. If we supply those values to <code>rnbinom</code>, we get a simulated data set that should match the data set that we already got. Then, we can check to see whether we are predicting enough zeros in our simulated data set.</p>
<div class="sourceCode" id="cb985"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb985-1"><a href="generalized-linear-models.html#cb985-1" tabindex="-1"></a><span class="fu">summary</span>(mod_nb)</span></code></pre></div>
<pre><code>## 
## Call:
## MASS::glm.nb(formula = art ~ ., data = bioChemists, init.theta = 2.264387695, 
##     link = log)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.256144   0.137348   1.865 0.062191 .  
## femWomen    -0.216418   0.072636  -2.979 0.002887 ** 
## marMarried   0.150489   0.082097   1.833 0.066791 .  
## kid5        -0.176415   0.052813  -3.340 0.000837 ***
## phd          0.015271   0.035873   0.426 0.670326    
## ment         0.029082   0.003214   9.048  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(2.2644) family taken to be 1)
## 
##     Null deviance: 1109.0  on 914  degrees of freedom
## Residual deviance: 1004.3  on 909  degrees of freedom
## AIC: 3135.9
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  2.264 
##           Std. Err.:  0.271 
## 
##  2 x log-likelihood:  -3121.917</code></pre>
<div class="sourceCode" id="cb987"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb987-1"><a href="generalized-linear-models.html#cb987-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(mod_nb, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)) <span class="co">#means</span></span></code></pre></div>
<pre><code>##        1        2        3        4        5        6 
## 1.913039 1.278293 1.311913 1.398619 2.346989 0.951584</code></pre>
<div class="sourceCode" id="cb989"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb989-1"><a href="generalized-linear-models.html#cb989-1" tabindex="-1"></a><span class="fu">rnbinom</span>(<span class="dv">915</span>, <span class="at">size =</span> <span class="fl">2.264387695</span>, <span class="at">mu =</span> <span class="fu">predict</span>(mod_nb, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>))</span></code></pre></div>
<pre><code>##   [1]  1  1  2  2  3  1  0  1  2  1  1  2  0  1  0  1  2  2  3  2  0  4  1  1  1
##  [26]  0  1  0  3  1  0  0  0  1  0  3  0  0  3  1  1  0  1  0  1  1  3  5  2  3
##  [51]  1  0  4  3  1  3  3  1  0  0  2  1  3  0  0  1  2  2  2  2  2  1  3  2  1
##  [76]  1  0  0  0  0  1  2  6  8  0  3  4  2  2  1  0  0  1  5  0  1  2  0  0  2
## [101]  1  0  6  1  0  3  0  1  2  0  3  0  1  3  0  2 12  0  0  1  0  1  1  0  0
## [126]  2  1  1  1  4  1  1  1  0  0  2  0  0  0  1  2  2  0  0  1  0  1  3  5  0
## [151]  2  0  3  0  1  0  1  0  0  2  2  2  1  2  0  1  1  5  1  0  0  1  2  3  0
## [176]  0  0  4  2  0  0  0  5  1  2  0  1  2  0  0  1  1  2  2  4  0  0  1  4  3
## [201]  1  0  1  2  0  1  2  2  0  1  2  1  1  0  3  0  0  1  0  0  0  2  1  2  0
## [226]  0  2  0  2  5  1  2  3  2  0  0  3  1  0  0  1  0  3  1  2  8  0  1  2  2
## [251]  7  0  1  5  1  0  2  1  1  3  0  0  2  0  2  0  2  0  3  0  0  4  1  4  7
## [276]  1  3  7  1  0  2  2  1  1  0  0  1  7  0  1  0  0  3  1  1  1  1  0  3  0
## [301]  1  2  3  0  0  1  0  1  4  2  2  1  1  2  1  3  4  0  0  0  1  2  5  2  3
## [326]  0  1 16  1  1  1  0  2  7  1  5  1  0  1  2  2  0  0  0  1  0  2  0  0  0
## [351]  2  2  0  0  2  2  1  0  2  1  7  1  1  4  1  1  2  1  0  0  3  0  0  2  0
## [376]  1  1  1  1  3  5  4  1  0  0  1  2  4  2  1  0  1  3  2  5  1  0  1  2  3
## [401]  2  2  2  4  1  3  2  1  1  2  1  1  2  3  5  0  4  0  2  0  1  1  1  0  0
## [426]  0  2  0  5  1  4  1  0  2  1  1  1  2  1  1  5  3  0  3  2  0  0  2  0  0
## [451]  1  2  0  0  4  2  0  1  0  2  2  3  0  0  2  2  0  0  3  1  1  4  3  0  0
## [476]  4  0  1  2  2  3  3  3  0  0  0  1  0  1  0  1  0  1  4  0  0  2  0  9  2
## [501]  1  4  4  0  3  0  3  1  5  1  2  8  1  0  2  0  0  0  2  2  1  3  1  0  3
## [526]  1  0  1  1  0  1  1  3  0  0  1  4  2  0  1  2  3  0  2  1  5  8  2  1  0
## [551]  3  1  0  0  0  0  3  2  0  4  0  1  0  0  1  3  1  0  4  0  1  0  4  6  0
## [576]  5  2  7  2  1  0  1  1  4  0  0  1  0  0  0  0  3  3  0  0  0  2  4  1  1
## [601]  2  0  0  1  0  1  3  4  1  0  6  1  4  0  1  0  2  1  2  0  0  0  1  3  0
## [626]  0  5  1  1  2  4  1  0  0  0  3  1  0  3  1  0  2  2  1  4  1  1  1  3  0
## [651]  3  2  2  1  0  3  7  2  0  4  2  3  1  0  1  3  2  0  0  0  0  0  2  4  2
## [676]  0  3 10  5  0  0  5  5  0  1  1  0  1  0  2  2  0  4  0  0  1  1  0  3  2
## [701]  1  0  2  2  0  1  1  1  6  1  3  0  1  0  0  2  3  0  0  0  0  0  0  0  1
## [726]  2  2  2  0  1  2  0  2  1  0  8  2  0  9  1  1  2  5  2  2  3  2  1  1  9
## [751]  5  1  3  0  3  0  3  1  0  0  1  2  1  2  3  1  1  5  3  2  1  4  2  0  4
## [776]  0  2  1  4  2  0  2  2  9  0  1  2  0  0  2  0  6  1  0  5  1  2  0  1  4
## [801]  3  4  8  1  2  1  0  5  0  2  1  3  0  3  0  1  3  2  4  0  2  2  5  0  2
## [826]  0  0  2  2  1  4  2  0  4  1  1  2  2  3  4  1  3  2  0  0  2  2  1  1  3
## [851]  5  1  0  1  1  0  4  0  2  1  4  1  1  5  0  5  0  2  1  1  2  3  6  2  2
## [876]  3  0  7  2  4  3  1  1  1  2  6  0  5  6  1  1  1  6  0  2  2  2  0  4  9
## [901]  9  0  3  2  1  1  0  4  4  1  3 14  1  1  4</code></pre>
<div class="sourceCode" id="cb991"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb991-1"><a href="generalized-linear-models.html#cb991-1" tabindex="-1"></a>zeros <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb991-2"><a href="generalized-linear-models.html#cb991-2" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">rnbinom</span>(<span class="dv">915</span>, </span>
<span id="cb991-3"><a href="generalized-linear-models.html#cb991-3" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">2.264387695</span>, </span>
<span id="cb991-4"><a href="generalized-linear-models.html#cb991-4" tabindex="-1"></a>          <span class="at">mu =</span> <span class="fu">predict</span>(mod_nb, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)) <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb991-5"><a href="generalized-linear-models.html#cb991-5" tabindex="-1"></a>})</span>
<span id="cb991-6"><a href="generalized-linear-models.html#cb991-6" tabindex="-1"></a><span class="fu">quantile</span>(zeros, <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">975</span>))</span></code></pre></div>
<pre><code>##  2.5% 97.5% 
##   252   303</code></pre>
<div class="sourceCode" id="cb993"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb993-1"><a href="generalized-linear-models.html#cb993-1" tabindex="-1"></a><span class="fu">sum</span>(bioChemists<span class="sc">$</span>art <span class="sc">==</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 275</code></pre>
<p>This indicates that the negative binomial model without zero inflation seems to be doing an OK job modeling the number of zeros in the data set. Just as a test, let’s add a bunch of structural zeros and see whether it then fails this test.</p>
<div class="sourceCode" id="cb995"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb995-1"><a href="generalized-linear-models.html#cb995-1" tabindex="-1"></a>zif_bio <span class="ot">&lt;-</span> bioChemists</span>
<span id="cb995-2"><a href="generalized-linear-models.html#cb995-2" tabindex="-1"></a>zif_bio<span class="sc">$</span>art[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">915</span>, <span class="dv">200</span>)] <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="co">#zero inflated</span></span>
<span id="cb995-3"><a href="generalized-linear-models.html#cb995-3" tabindex="-1"></a>mod_nb_zif <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">glm.nb</span>(art <span class="sc">~</span> ., <span class="at">data =</span> zif_bio)</span>
<span id="cb995-4"><a href="generalized-linear-models.html#cb995-4" tabindex="-1"></a><span class="fu">summary</span>(mod_nb_zif)</span></code></pre></div>
<pre><code>## 
## Call:
## MASS::glm.nb(formula = art ~ ., data = zif_bio, init.theta = 1.090060048, 
##     link = log)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.01268    0.17459  -0.073  0.94213    
## femWomen    -0.27950    0.09240  -3.025  0.00249 ** 
## marMarried   0.21728    0.10473   2.075  0.03801 *  
## kid5        -0.19395    0.06658  -2.913  0.00358 ** 
## phd          0.01852    0.04567   0.405  0.68515    
## ment         0.03024    0.00423   7.149 8.73e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(1.0901) family taken to be 1)
## 
##     Null deviance: 1018.01  on 914  degrees of freedom
## Residual deviance:  944.38  on 909  degrees of freedom
## AIC: 2867
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  1.090 
##           Std. Err.:  0.113 
## 
##  2 x log-likelihood:  -2852.988</code></pre>
<div class="sourceCode" id="cb997"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb997-1"><a href="generalized-linear-models.html#cb997-1" tabindex="-1"></a>zeros <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb997-2"><a href="generalized-linear-models.html#cb997-2" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">rnbinom</span>(<span class="dv">915</span>, </span>
<span id="cb997-3"><a href="generalized-linear-models.html#cb997-3" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">1.110856224</span>, </span>
<span id="cb997-4"><a href="generalized-linear-models.html#cb997-4" tabindex="-1"></a>          <span class="at">mu =</span> <span class="fu">predict</span>(mod_nb, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)) <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb997-5"><a href="generalized-linear-models.html#cb997-5" tabindex="-1"></a>})</span>
<span id="cb997-6"><a href="generalized-linear-models.html#cb997-6" tabindex="-1"></a><span class="fu">quantile</span>(zeros, <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">975</span>))</span></code></pre></div>
<pre><code>##  2.5% 97.5% 
##   316   370</code></pre>
<div class="sourceCode" id="cb999"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb999-1"><a href="generalized-linear-models.html#cb999-1" tabindex="-1"></a><span class="fu">sum</span>(zif_bio<span class="sc">$</span>art <span class="sc">==</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 408</code></pre>
<p>Now we see that the model is <strong>not</strong> accurately picking up all of the zeros, and we would want to switch to a zero inflated model. We would recommend checking that the true zeros are now in the 95% quantile interval of predicted zeros from data simulated via the model, but we will not go through that in detail in these notes. We do notice that none of the predictors are significant for the structural zeros, which makes sense because we arbitrarily assigned 200 values to zero (though many of those were likely already zero).</p>
<div class="sourceCode" id="cb1001"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1001-1"><a href="generalized-linear-models.html#cb1001-1" tabindex="-1"></a>mod_zifbio_nb <span class="ot">&lt;-</span> <span class="fu">zeroinfl</span>(art <span class="sc">~</span> . <span class="sc">|</span> ., <span class="at">data =</span> zif_bio, <span class="at">dist =</span> <span class="st">&quot;negbin&quot;</span>)</span>
<span id="cb1001-2"><a href="generalized-linear-models.html#cb1001-2" tabindex="-1"></a><span class="fu">summary</span>(mod_zifbio_nb)</span></code></pre></div>
<pre><code>## 
## Call:
## zeroinfl(formula = art ~ . | ., data = zif_bio, dist = &quot;negbin&quot;)
## 
## Pearson residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0488 -0.7219 -0.2998  0.4572  6.2857 
## 
## Count model coefficients (negbin with log link):
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.321917   0.221100   1.456  0.14540    
## femWomen    -0.316392   0.105040  -3.012  0.00259 ** 
## marMarried   0.177843   0.119743   1.485  0.13749    
## kid5        -0.157391   0.077027  -2.043  0.04102 *  
## phd         -0.013983   0.052012  -0.269  0.78805    
## ment         0.022024   0.004951   4.448 8.65e-06 ***
## Log(theta)   0.395066   0.196216   2.013  0.04407 *  
## 
## Zero-inflation model coefficients (binomial with logit link):
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  -0.1376     1.1184  -0.123    0.902
## femWomen     -0.3278     0.6852  -0.478    0.632
## marMarried   -0.5026     0.8221  -0.611    0.541
## kid5          0.3046     0.3563   0.855    0.393
## phd          -0.1582     0.2935  -0.539    0.590
## ment         -0.1904     0.1184  -1.608    0.108
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1 
## 
## Theta = 1.4845 
## Number of iterations in BFGS optimization: 43 
## Log-likelihood: -1421 on 13 Df</code></pre>
<div class="sourceCode" id="cb1003"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1003-1"><a href="generalized-linear-models.html#cb1003-1" tabindex="-1"></a><span class="fu">vuong</span>(mod_nb, mod_zif_nb)</span></code></pre></div>
<pre><code>## Vuong Non-Nested Hypothesis Test-Statistic: 
## (test-statistic is asymptotically distributed N(0,1) under the
##  null that the models are indistinguishible)
## -------------------------------------------------------------
##               Vuong z-statistic             H_A  p-value
## Raw                   -2.241831 model2 &gt; model1 0.012486
## AIC-corrected         -1.015385 model2 &gt; model1 0.154961
## BIC-corrected          1.939690 model1 &gt; model2 0.026209</code></pre>
<p>We see that the Vuong test is non-commital about whether the zero inflated model is better. It depends on which version of the test that you use.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>Not all.<a href="generalized-linear-models.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Extra credit: diagram the sentence “The bigger the value of the log odds, the better.”<a href="generalized-linear-models.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>Pronounced: “shoe!”<a href="generalized-linear-models.html#fnref4" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tree-regression-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lecture-notes.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
