<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Maximum Likelihood Estimation | Applied Regression with R</title>
  <meta name="description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Maximum Likelihood Estimation | Applied Regression with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Maximum Likelihood Estimation | Applied Regression with R" />
  
  <meta name="twitter:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

<meta name="author" content="Darrin Speegle" />


<meta name="date" content="2026-03-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
<link rel="prev" href="lecture-notes.html"/>
<link rel="next" href="solutions.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Regression with R<br />&nbsp; Notes From STAT 4870/5087</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="classicaltheory.html"><a href="classicaltheory.html"><i class="fa fa-check"></i><b>2</b> Classical Theory of Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="classicaltheory.html"><a href="classicaltheory.html#review"><i class="fa fa-check"></i><b>2.1</b> Review</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-means-and-standard-deviations"><i class="fa fa-check"></i><b>2.1.1</b> Estimating Means and standard deviations</a></li>
<li class="chapter" data-level="2.1.2" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-the-density-of-an-rv"><i class="fa fa-check"></i><b>2.1.2</b> Estimating the density of an rv</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-overview"><i class="fa fa-check"></i><b>2.2</b> Linear Regression Overview</a></li>
<li class="chapter" data-level="2.3" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-with-no-intercept"><i class="fa fa-check"></i><b>2.3</b> Linear Regression with no intercept</a></li>
<li class="chapter" data-level="2.4" data-path="classicaltheory.html"><a href="classicaltheory.html#the-full-model"><i class="fa fa-check"></i><b>2.4</b> The full model</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="classicaltheory.html"><a href="classicaltheory.html#hypothesis-test-interlude"><i class="fa fa-check"></i><b>2.4.1</b> Hypothesis Test Interlude</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="classicaltheory.html"><a href="classicaltheory.html#using-different-loss-functions"><i class="fa fa-check"></i><b>2.5</b> Using different loss functions</a></li>
<li class="chapter" data-level="" data-path="classicaltheory.html"><a href="classicaltheory.html#vignette-a-dplyr-primer"><i class="fa fa-check"></i>Vignette: A dplyr primer</a></li>
<li class="chapter" data-level="2.6" data-path="classicaltheory.html"><a href="classicaltheory.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#anova"><i class="fa fa-check"></i><b>3.0.1</b> Aside on multiple R squared and ANOVA</a></li>
<li class="chapter" data-level="3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-variable-selection-anova"><i class="fa fa-check"></i><b>3.1</b> More Variable Selection: ANOVA</a></li>
<li class="chapter" data-level="3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#predictions"><i class="fa fa-check"></i><b>3.2</b> Predictions</a></li>
<li class="chapter" data-level="3.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#using-aic"><i class="fa fa-check"></i><b>3.3</b> Using AIC</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#likelihood-functions"><i class="fa fa-check"></i><b>3.3.1</b> Likelihood functions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercises-1"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html"><i class="fa fa-check"></i><b>4</b> Intro to Predictive Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#comparingtwomodels"><i class="fa fa-check"></i><b>4.1</b> Comparing Two Models</a></li>
<li class="chapter" data-level="4.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#a-brief-return-to-inference"><i class="fa fa-check"></i><b>4.2</b> A Brief Return to Inference</a></li>
<li class="chapter" data-level="4.3" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#simulations-of-expected-mse"><i class="fa fa-check"></i><b>4.3</b> Simulations of Expected MSE</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-and-bias-variance-tradeoff"><i class="fa fa-check"></i><b>4.3.1</b> Estimating MSE and Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-for-new-predictors-uniformly-sampled"><i class="fa fa-check"></i><b>4.3.2</b> Estimating MSE for new predictors uniformly sampled</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>4.4</b> Bias Variance Trade-off</a></li>
<li class="chapter" data-level="4.5" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#exercises-2"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html"><i class="fa fa-check"></i><b>5</b> Regression Predictive Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#preprocessing"><i class="fa fa-check"></i><b>5.1</b> Preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#missing-data"><i class="fa fa-check"></i><b>5.2</b> Missing Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#predicting-when-a-level-is-missing-from-the-training-set"><i class="fa fa-check"></i><b>5.2.1</b> Predicting when a level is missing from the training set</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#correlated-predictors"><i class="fa fa-check"></i><b>5.3</b> Correlated Predictors</a></li>
<li class="chapter" data-level="5.4" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#aside-on-pca"><i class="fa fa-check"></i><b>5.4</b> Aside on PCA</a></li>
<li class="chapter" data-level="5.5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#johnson-lindenstrauss-dimension-reduction"><i class="fa fa-check"></i><b>5.5</b> Johnson-Lindenstrauss Dimension Reduction</a></li>
<li class="chapter" data-level="5.6" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#exercises-3"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variable-selection.html"><a href="variable-selection.html"><i class="fa fa-check"></i><b>6</b> Variable Selection</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variable-selection.html"><a href="variable-selection.html#partial-least-squares"><i class="fa fa-check"></i><b>6.1</b> Partial Least Squares</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="variable-selection.html"><a href="variable-selection.html#optional-pls-stuff"><i class="fa fa-check"></i><b>6.1.1</b> Optional PLS Stuff</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variable-selection.html"><a href="variable-selection.html#ridgelasso-and-elastic-net"><i class="fa fa-check"></i><b>6.2</b> Ridge/Lasso and Elastic Net</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="variable-selection.html"><a href="variable-selection.html#ridge-regression"><i class="fa fa-check"></i><b>6.2.1</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.2.2" data-path="variable-selection.html"><a href="variable-selection.html#lasso"><i class="fa fa-check"></i><b>6.2.2</b> LASSO</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variable-selection.html"><a href="variable-selection.html#step-aic"><i class="fa fa-check"></i><b>6.3</b> Step AIC</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="variable-selection.html"><a href="variable-selection.html#doing-lgocv-with-preprocessing"><i class="fa fa-check"></i><b>6.3.1</b> Doing LGOCV with preprocessing</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variable-selection.html"><a href="variable-selection.html#interactions"><i class="fa fa-check"></i><b>6.4</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="lecture-notes.html"><a href="lecture-notes.html"><i class="fa fa-check"></i><b>7</b> Lecture Notes</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lecture-notes.html"><a href="lecture-notes.html#january-27"><i class="fa fa-check"></i><b>7.1</b> January 27</a></li>
<li class="chapter" data-level="7.2" data-path="lecture-notes.html"><a href="lecture-notes.html#february-3"><i class="fa fa-check"></i><b>7.2</b> February 3</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="lecture-notes.html"><a href="lecture-notes.html#simulating-data"><i class="fa fa-check"></i><b>7.2.1</b> Simulating Data</a></li>
<li class="chapter" data-level="7.2.2" data-path="lecture-notes.html"><a href="lecture-notes.html#building-models"><i class="fa fa-check"></i><b>7.2.2</b> Building Models</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="lecture-notes.html"><a href="lecture-notes.html#february-5"><i class="fa fa-check"></i><b>7.3</b> February 5</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="lecture-notes.html"><a href="lecture-notes.html#using-broomaugment"><i class="fa fa-check"></i><b>7.3.1</b> Using <code>broom::augment</code></a></li>
<li class="chapter" data-level="7.3.2" data-path="lecture-notes.html"><a href="lecture-notes.html#multicollinearity"><i class="fa fa-check"></i><b>7.3.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="lecture-notes.html"><a href="lecture-notes.html#february-10"><i class="fa fa-check"></i><b>7.4</b> February 10</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="lecture-notes.html"><a href="lecture-notes.html#anova-models"><i class="fa fa-check"></i><b>7.4.1</b> ANOVA Models</a></li>
<li class="chapter" data-level="7.4.2" data-path="lecture-notes.html"><a href="lecture-notes.html#penguins"><i class="fa fa-check"></i><b>7.4.2</b> Penguins</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="lecture-notes.html"><a href="lecture-notes.html#february-12"><i class="fa fa-check"></i><b>7.5</b> February 12</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="lecture-notes.html"><a href="lecture-notes.html#an-example"><i class="fa fa-check"></i><b>7.5.1</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="lecture-notes.html"><a href="lecture-notes.html#february-17"><i class="fa fa-check"></i><b>7.6</b> February 17</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-speaker-and-sentence-effects"><i class="fa fa-check"></i><b>7.6.1</b> Adding random speaker and sentence effects</a></li>
<li class="chapter" data-level="7.6.2" data-path="lecture-notes.html"><a href="lecture-notes.html#random-intercepts-with-continuous-predictor"><i class="fa fa-check"></i><b>7.6.2</b> Random intercepts with continuous predictor</a></li>
<li class="chapter" data-level="7.6.3" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-slopes"><i class="fa fa-check"></i><b>7.6.3</b> Adding random slopes</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="lecture-notes.html"><a href="lecture-notes.html#february-19"><i class="fa fa-check"></i><b>7.7</b> February 19</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="lecture-notes.html"><a href="lecture-notes.html#random-slopes"><i class="fa fa-check"></i><b>7.7.1</b> Random Slopes</a></li>
<li class="chapter" data-level="7.7.2" data-path="lecture-notes.html"><a href="lecture-notes.html#comparing-models"><i class="fa fa-check"></i><b>7.7.2</b> Comparing models</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="lecture-notes.html"><a href="lecture-notes.html#february-24"><i class="fa fa-check"></i><b>7.8</b> February 24</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="lecture-notes.html"><a href="lecture-notes.html#beethoven-tempo-example"><i class="fa fa-check"></i><b>7.8.1</b> Beethoven Tempo Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html"><i class="fa fa-check"></i><b>8</b> Maximum Likelihood Estimation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#mle-for-mixed-models"><i class="fa fa-check"></i><b>8.1</b> MLE for mixed models</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>9</b> Solutions</a>
<ul>
<li class="chapter" data-level="9.1" data-path="solutions.html"><a href="solutions.html#chapter-2-solutions"><i class="fa fa-check"></i><b>9.1</b> Chapter 2 Solutions</a></li>
<li class="chapter" data-level="9.2" data-path="solutions.html"><a href="solutions.html#chapter-3-solutions"><i class="fa fa-check"></i><b>9.2</b> Chapter 3 Solutions</a></li>
<li class="chapter" data-level="9.3" data-path="solutions.html"><a href="solutions.html#chapter-5"><i class="fa fa-check"></i><b>9.3</b> Chapter 5</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Regression with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="maximum-likelihood-estimation" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Maximum Likelihood Estimation<a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Consider the problem of estimating a parameter in a model. For example, if we take a random sample from a normal distribution with unknown mean <span class="math inline">\(\mu\)</span> and variance 1, what is a good estimator for <span class="math inline">\(\mu\)</span>? I hope you immediately think of the <em>sample mean</em> <span class="math inline">\(\overline{x}\)</span>. How could we come to that decision systematically, though? And what if the parameter doesn’t have quite the same obvious interpretation as <span class="math inline">\(\mu\)</span> from a normal distribution?</p>
<p>We will use the method of maximum likelihood. Realistically, I should have talked about this long ago in class, but we are going to do it now.</p>
<p>Given a probability density function <span class="math inline">\(f\)</span> of a random variable <span class="math inline">\(X\)</span>, we can associate the value of <span class="math inline">\(f(x)\)</span> with the relative likelihood that <span class="math inline">\(x\)</span> is an observed value from <span class="math inline">\(X\)</span>. The values themselves don’t mean much, but if <span class="math inline">\(f(x) = 2f(y)\)</span>, then we can say that <span class="math inline">\(x\)</span> is twice as likely as <span class="math inline">\(y\)</span>. If we have a single observation from <span class="math inline">\(X\)</span> which is normally distributed with mean <span class="math inline">\(\mu\)</span>, the most likely outcome is the mean, <span class="math inline">\(\mu\)</span>.</p>
<p>Now, we can turn the thought process upside down. Suppose we don’t know the value of <span class="math inline">\(\mu\)</span>, but we observe a single value <span class="math inline">\(x\)</span>. The value of <span class="math inline">\(\mu\)</span> which makes <span class="math inline">\(x\)</span> most likely is <span class="math inline">\(x\)</span> itself<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>. Let’s check that really is true.</p>
<div class="sourceCode" id="cb922"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb922-1"><a href="maximum-likelihood-estimation.html#cb922-1" tabindex="-1"></a>like_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(mu) {</span>
<span id="cb922-2"><a href="maximum-likelihood-estimation.html#cb922-2" tabindex="-1"></a>  <span class="fu">dnorm</span>(x, <span class="at">mean =</span> mu, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb922-3"><a href="maximum-likelihood-estimation.html#cb922-3" tabindex="-1"></a>}</span>
<span id="cb922-4"><a href="maximum-likelihood-estimation.html#cb922-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb922-5"><a href="maximum-likelihood-estimation.html#cb922-5" tabindex="-1"></a><span class="fu">optimize</span>(like_fun, <span class="at">interval =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">8</span>, <span class="dv">8</span>), <span class="at">maximum =</span> T)</span></code></pre></div>
<pre><code>## $maximum
## [1] 2.000015
## 
## $objective
## [1] 0.3989423</code></pre>
<p>If you try a few more values of <span class="math inline">\(x\)</span>, you will see that indeed, this is the case.</p>
<p>OK, but how would we do this if we have more than one value of <span class="math inline">\(x\)</span>? We would then compute the likelihood function given all of the samples. If the samples are independent (a common assumption, but <strong>not</strong> the case in mixed models), then we can just multiply the separate pdfs together. Let’s see how to do it if we have a sample of size <span class="math inline">\(n = 4\)</span> consisting of <code>c(1, 2, 3, 4)</code>.</p>
<div class="sourceCode" id="cb924"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb924-1"><a href="maximum-likelihood-estimation.html#cb924-1" tabindex="-1"></a>like_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(mu) {</span>
<span id="cb924-2"><a href="maximum-likelihood-estimation.html#cb924-2" tabindex="-1"></a>  <span class="fu">prod</span>(<span class="fu">dnorm</span>(x, <span class="at">mean =</span> mu, <span class="at">sd =</span> <span class="dv">1</span>))</span>
<span id="cb924-3"><a href="maximum-likelihood-estimation.html#cb924-3" tabindex="-1"></a>}</span>
<span id="cb924-4"><a href="maximum-likelihood-estimation.html#cb924-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb924-5"><a href="maximum-likelihood-estimation.html#cb924-5" tabindex="-1"></a><span class="fu">optimize</span>(like_fun, <span class="at">interval =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">8</span>, <span class="dv">8</span>), <span class="at">maximum =</span> T)</span></code></pre></div>
<pre><code>## $maximum
## [1] 2.500003
## 
## $objective
## [1] 0.002079237</code></pre>
<p>This works fine for small data sets, but when we have a lot of data, the product of the pdfs could get extermely small. It is better to minimze the negative of the log of the likelihood. We also have to change <code>prod</code> to <code>sum</code>.</p>
<div class="sourceCode" id="cb926"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb926-1"><a href="maximum-likelihood-estimation.html#cb926-1" tabindex="-1"></a>like_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(mu) {</span>
<span id="cb926-2"><a href="maximum-likelihood-estimation.html#cb926-2" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">dnorm</span>(x, <span class="at">mean =</span> mu, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">log =</span> T))</span>
<span id="cb926-3"><a href="maximum-likelihood-estimation.html#cb926-3" tabindex="-1"></a>}</span>
<span id="cb926-4"><a href="maximum-likelihood-estimation.html#cb926-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb926-5"><a href="maximum-likelihood-estimation.html#cb926-5" tabindex="-1"></a><span class="fu">optimize</span>(like_fun, <span class="at">interval =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">8</span>, <span class="dv">8</span>), <span class="at">maximum =</span> T)</span></code></pre></div>
<pre><code>## $maximum
## [1] 2.5
## 
## $objective
## [1] -6.175754</code></pre>
<p>OK, now what if we have two parameters that we need to estimate simultaneously? There are several things that need to change:</p>
<ul>
<li>We have to pass two parameters to our likelihood function instead of just one.</li>
<li>We have to use <code>optim</code> instead of <code>optimize</code></li>
<li>We have to provide <code>optim</code> with a starting estimate.</li>
<li><code>optim</code> will only minimize, so we need to minimize negative likelihood, which is the same as maximizing positive likelihood.</li>
</ul>
<p>It works like this in the case we are estimating the mean and the standard deviation.</p>
<div class="sourceCode" id="cb928"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb928-1"><a href="maximum-likelihood-estimation.html#cb928-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb928-2"><a href="maximum-likelihood-estimation.html#cb928-2" tabindex="-1"></a>like_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(par) {</span>
<span id="cb928-3"><a href="maximum-likelihood-estimation.html#cb928-3" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> par[<span class="dv">1</span>]</span>
<span id="cb928-4"><a href="maximum-likelihood-estimation.html#cb928-4" tabindex="-1"></a>  sigma <span class="ot">&lt;-</span> par[<span class="dv">2</span>]</span>
<span id="cb928-5"><a href="maximum-likelihood-estimation.html#cb928-5" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dnorm</span>(x, mu, sigma, <span class="at">log =</span> T))</span>
<span id="cb928-6"><a href="maximum-likelihood-estimation.html#cb928-6" tabindex="-1"></a>}</span>
<span id="cb928-7"><a href="maximum-likelihood-estimation.html#cb928-7" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">fn =</span> like_fun, <span class="at">lower =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>), <span class="at">method =</span> <span class="st">&quot;L-BFGS-B&quot;</span>)</span></code></pre></div>
<pre><code>## $par
## [1] 2.500001 1.118036
## 
## $value
## [1] 6.122041
## 
## $counts
## function gradient 
##       14       14 
## 
## $convergence
## [1] 0
## 
## $message
## [1] &quot;CONVERGENCE: REL_REDUCTION_OF_F &lt;= FACTR*EPSMCH&quot;</code></pre>
<p>This works quite generally. If we have data between 0 and 1 and we wish to estimate the parameters associated with a beta distribution, we can do the following:</p>
<div class="sourceCode" id="cb930"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb930-1"><a href="maximum-likelihood-estimation.html#cb930-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb930-2"><a href="maximum-likelihood-estimation.html#cb930-2" tabindex="-1"></a>shapes <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>, <span class="dv">2</span>)</span>
<span id="cb930-3"><a href="maximum-likelihood-estimation.html#cb930-3" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(<span class="dv">30</span>, <span class="at">shape1 =</span> shapes[<span class="dv">1</span>], <span class="at">shape2 =</span> shapes[<span class="dv">2</span>])</span>
<span id="cb930-4"><a href="maximum-likelihood-estimation.html#cb930-4" tabindex="-1"></a>like_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(par) {</span>
<span id="cb930-5"><a href="maximum-likelihood-estimation.html#cb930-5" tabindex="-1"></a>  shape1 <span class="ot">&lt;-</span> par[<span class="dv">1</span>]</span>
<span id="cb930-6"><a href="maximum-likelihood-estimation.html#cb930-6" tabindex="-1"></a>  shape2 <span class="ot">&lt;-</span> par[<span class="dv">2</span>]</span>
<span id="cb930-7"><a href="maximum-likelihood-estimation.html#cb930-7" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dbeta</span>(data, shape1, shape2, <span class="at">log =</span> T))</span>
<span id="cb930-8"><a href="maximum-likelihood-estimation.html#cb930-8" tabindex="-1"></a>}</span>
<span id="cb930-9"><a href="maximum-likelihood-estimation.html#cb930-9" tabindex="-1"></a>oo <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">fn =</span> like_fun, <span class="at">lower =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.01</span>, <span class="fl">0.01</span>), <span class="at">method =</span> <span class="st">&quot;L-BFGS-B&quot;</span>)</span>
<span id="cb930-10"><a href="maximum-likelihood-estimation.html#cb930-10" tabindex="-1"></a>oo</span></code></pre></div>
<pre><code>## $par
## [1]  5.252771 53.286377
## 
## $value
## [1] -57.80793
## 
## $counts
## function gradient 
##       20       20 
## 
## $convergence
## [1] 0
## 
## $message
## [1] &quot;CONVERGENCE: REL_REDUCTION_OF_F &lt;= FACTR*EPSMCH&quot;</code></pre>
<p>Are estimates are 5.252771 for shape1 and 53.2863773 for <code>shape2</code>. If we have data that follows the model</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]</span>
where <span class="math inline">\(\epsilon_i\)</span> are iid <span class="math inline">\(N(0, \sigma)\)</span> random variables, then it gets a little bit more complicated. We would do it like this. We suppose we want to estimate the parameters associated with modeling <code>imu_top_speed_ms</code> on <code>stride_length_m</code> in the data set <code>ardata::running_speed</code>. The main thing to notice is that the values of <span class="math inline">\(y_i\)</span> are independent, normally distributed with mean <span class="math inline">\(\beta_0 + \beta_1 x_i\)</span> and variance <span class="math inline">\(\sigma^2\)</span>.</p>
<div class="sourceCode" id="cb932"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb932-1"><a href="maximum-likelihood-estimation.html#cb932-1" tabindex="-1"></a>rr <span class="ot">&lt;-</span> ardata<span class="sc">::</span>running_speed</span>
<span id="cb932-2"><a href="maximum-likelihood-estimation.html#cb932-2" tabindex="-1"></a>like_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(par) {</span>
<span id="cb932-3"><a href="maximum-likelihood-estimation.html#cb932-3" tabindex="-1"></a>  beta0 <span class="ot">&lt;-</span> par[<span class="dv">1</span>]</span>
<span id="cb932-4"><a href="maximum-likelihood-estimation.html#cb932-4" tabindex="-1"></a>  beta1 <span class="ot">&lt;-</span> par[<span class="dv">2</span>]</span>
<span id="cb932-5"><a href="maximum-likelihood-estimation.html#cb932-5" tabindex="-1"></a>  sigma <span class="ot">&lt;-</span> par[<span class="dv">3</span>]</span>
<span id="cb932-6"><a href="maximum-likelihood-estimation.html#cb932-6" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dnorm</span>(rr<span class="sc">$</span>imu_top_speed_ms, beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> rr<span class="sc">$</span>stride_length_m, sigma, <span class="at">log =</span> T))</span>
<span id="cb932-7"><a href="maximum-likelihood-estimation.html#cb932-7" tabindex="-1"></a>}</span>
<span id="cb932-8"><a href="maximum-likelihood-estimation.html#cb932-8" tabindex="-1"></a>oo <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">fn =</span> like_fun, <span class="at">lower =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.01</span>), <span class="at">method =</span> <span class="st">&quot;L-BFGS-B&quot;</span>)</span>
<span id="cb932-9"><a href="maximum-likelihood-estimation.html#cb932-9" tabindex="-1"></a>oo<span class="sc">$</span>par</span></code></pre></div>
<pre><code>## [1] 2.2157883 1.5566788 0.5272198</code></pre>
<div class="sourceCode" id="cb934"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb934-1"><a href="maximum-likelihood-estimation.html#cb934-1" tabindex="-1"></a><span class="fu">lm</span>(imu_top_speed_ms <span class="sc">~</span> stride_length_m, <span class="at">data =</span> rr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = imu_top_speed_ms ~ stride_length_m, data = rr)
## 
## Coefficients:
##     (Intercept)  stride_length_m  
##           2.216            1.557</code></pre>
<div id="mle-for-mixed-models" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> MLE for mixed models<a href="maximum-likelihood-estimation.html#mle-for-mixed-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How does <code>lmer</code> estimate the parameters in our models? <code>lmer</code> uses maximum likelihood estimation (MLE) to estimate the parameters of the model. The likelihood function is based on the assumption that the random effects and the residuals are normally distributed. The MLE approach finds the parameter values that maximize the likelihood of observing the data given the model. In practice, <code>lmer</code> uses two different algorithms for estimating the parameters. The one we will discuss is MLE.</p>
<p>Let’s look at an example.</p>
<div class="sourceCode" id="cb936"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb936-1"><a href="maximum-likelihood-estimation.html#cb936-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.2.0     ✔ readr     2.1.5
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.1.0     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb938"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb938-1"><a href="maximum-likelihood-estimation.html#cb938-1" tabindex="-1"></a>ss <span class="ot">&lt;-</span> lme4<span class="sc">::</span>sleepstudy <span class="sc">|&gt;</span> </span>
<span id="cb938-2"><a href="maximum-likelihood-estimation.html#cb938-2" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">|&gt;</span> </span>
<span id="cb938-3"><a href="maximum-likelihood-estimation.html#cb938-3" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span></code></pre></div>
<p>We estimate the parameters involved with a <strong>random intercepts</strong> model. To set notation, the mathematical formulation of this model is</p>
<p><span class="math display">\[
\text{reaction}_{ij} = \gamma_{00} + \beta_1 \text{days}_{ij} + u_{0i} + \epsilon_{ij}
\]</span></p>
<p>We can start by getting reasonable guesses for the values.</p>
<div class="sourceCode" id="cb939"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb939-1"><a href="maximum-likelihood-estimation.html#cb939-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(reaction <span class="sc">~</span> days <span class="sc">+</span> subject, <span class="at">data =</span> ss)</span>
<span id="cb939-2"><a href="maximum-likelihood-estimation.html#cb939-2" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = reaction ~ days + subject, data = ss)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -100.540  -16.389   -0.341   15.215  131.159 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  295.0310    10.4471  28.240  &lt; 2e-16 ***
## days          10.4673     0.8042  13.015  &lt; 2e-16 ***
## subject309  -126.9008    13.8597  -9.156 2.35e-16 ***
## subject310  -111.1326    13.8597  -8.018 2.07e-13 ***
## subject330   -38.9124    13.8597  -2.808 0.005609 ** 
## subject331   -32.6978    13.8597  -2.359 0.019514 *  
## subject332   -34.8318    13.8597  -2.513 0.012949 *  
## subject333   -25.9755    13.8597  -1.874 0.062718 .  
## subject334   -46.8318    13.8597  -3.379 0.000913 ***
## subject335   -92.0638    13.8597  -6.643 4.51e-10 ***
## subject337    33.5872    13.8597   2.423 0.016486 *  
## subject349   -66.2994    13.8597  -4.784 3.87e-06 ***
## subject350   -28.5312    13.8597  -2.059 0.041147 *  
## subject351   -52.0361    13.8597  -3.754 0.000242 ***
## subject352    -4.7123    13.8597  -0.340 0.734300    
## subject369   -36.0992    13.8597  -2.605 0.010059 *  
## subject370   -50.4321    13.8597  -3.639 0.000369 ***
## subject371   -47.1498    13.8597  -3.402 0.000844 ***
## subject372   -24.2477    13.8597  -1.750 0.082108 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 30.99 on 161 degrees of freedom
## Multiple R-squared:  0.7277, Adjusted R-squared:  0.6973 
## F-statistic: 23.91 on 18 and 161 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We can guess that <span class="math inline">\(\gamma_{00} \approx 295\)</span> and <span class="math inline">\(\beta_1 \approx 10.5\)</span>. The variance of the residuals is approximately <span class="math inline">\(31^2\)</span> (it will likely be less, depending on how much variance is explained by the random intercept). Now we need to estimate the variance of the random intercepts. We can get a rough estimate of this by looking at the variance of the subject means.</p>
<div class="sourceCode" id="cb941"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb941-1"><a href="maximum-likelihood-estimation.html#cb941-1" tabindex="-1"></a><span class="dv">295</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">coef</span>(mod)[<span class="dv">3</span><span class="sc">:</span><span class="dv">19</span>]) <span class="co">#these are the intercepts</span></span></code></pre></div>
<pre><code>##            subject309 subject310 subject330 subject331 subject332 subject333 
##   295.0000   168.0992   183.8674   256.0876   262.3022   260.1682   269.0245 
## subject334 subject335 subject337 subject349 subject350 subject351 subject352 
##   248.1682   202.9362   328.5872   228.7006   266.4688   242.9639   290.2877 
## subject369 subject370 subject371 subject372 
##   258.9008   244.5679   247.8502   270.7523</code></pre>
<div class="sourceCode" id="cb943"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb943-1"><a href="maximum-likelihood-estimation.html#cb943-1" tabindex="-1"></a><span class="fu">var</span>(<span class="dv">295</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">coef</span>(mod)[<span class="dv">3</span><span class="sc">:</span><span class="dv">19</span>]))</span></code></pre></div>
<pre><code>## [1] 1474.224</code></pre>
<p>The variance of the intercepts is about <span class="math inline">\(1474\)</span>. The final estimated value will likely be smaller than this.</p>
<p>Let’s see what <code>lmer</code> gives.</p>
<div class="sourceCode" id="cb945"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb945-1"><a href="maximum-likelihood-estimation.html#cb945-1" tabindex="-1"></a>mod_lmer <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(reaction <span class="sc">~</span> days <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>subject), <span class="at">data =</span> ss)</span>
<span id="cb945-2"><a href="maximum-likelihood-estimation.html#cb945-2" tabindex="-1"></a><span class="fu">summary</span>(mod_lmer)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: reaction ~ days + (1 | subject)
##    Data: ss
## 
## REML criterion at convergence: 1786.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.2257 -0.5529  0.0109  0.5188  4.2506 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  subject  (Intercept) 1378.2   37.12   
##  Residual              960.5   30.99   
## Number of obs: 180, groups:  subject, 18
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept) 251.4051     9.7467   25.79
## days         10.4673     0.8042   13.02
## 
## Correlation of Fixed Effects:
##      (Intr)
## days -0.371</code></pre>
<p>Our values are pretty close.</p>
<p>We can use these values as starting points for the optimization algorithm that <code>lmer</code> uses to find the MLE estimates. Using our mathematical model of <code>reaction</code>, we can see that each response is a function of the fixed effects, the random effects, and the residuals. The distribution of a single response is</p>
<p><span class="math display">\[
y_{ij} \sim N(\gamma_{00} + \beta_1 x_{ij}, \tau^2 + \sigma^2)
\]</span></p>
<p>where here we use the assumption that <span class="math inline">\(u_{0i} \sim N(0, \tau^2)\)</span> and <span class="math inline">\(\epsilon_{ij} \sim N(0, \sigma^2)\)</span> are independent. The likelihood function is the product of the probability density functions for each response, which is a function of the parameters <span class="math inline">\(\gamma_{00}\)</span>, <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\tau^2\)</span>, and <span class="math inline">\(\sigma^2\)</span>. The MLE estimates are the values of these parameters that maximize the likelihood function.</p>
<p>When we do this, we will maximize the <strong>log</strong> of the likelihood function, in order to keep values reasonably sized.</p>
<div class="sourceCode" id="cb947"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb947-1"><a href="maximum-likelihood-estimation.html#cb947-1" tabindex="-1"></a><span class="co">#This isn&#39;t correct</span></span>
<span id="cb947-2"><a href="maximum-likelihood-estimation.html#cb947-2" tabindex="-1"></a>like <span class="ot">&lt;-</span> <span class="cf">function</span>(par) {</span>
<span id="cb947-3"><a href="maximum-likelihood-estimation.html#cb947-3" tabindex="-1"></a>  gamma <span class="ot">&lt;-</span> par[<span class="dv">1</span>]</span>
<span id="cb947-4"><a href="maximum-likelihood-estimation.html#cb947-4" tabindex="-1"></a>  beta <span class="ot">&lt;-</span> par[<span class="dv">2</span>]</span>
<span id="cb947-5"><a href="maximum-likelihood-estimation.html#cb947-5" tabindex="-1"></a>  tau2 <span class="ot">&lt;-</span> par[<span class="dv">3</span>]</span>
<span id="cb947-6"><a href="maximum-likelihood-estimation.html#cb947-6" tabindex="-1"></a>  sigma2 <span class="ot">&lt;-</span> par[<span class="dv">4</span>]</span>
<span id="cb947-7"><a href="maximum-likelihood-estimation.html#cb947-7" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> gamma <span class="sc">+</span> beta <span class="sc">*</span> ss<span class="sc">$</span>days</span>
<span id="cb947-8"><a href="maximum-likelihood-estimation.html#cb947-8" tabindex="-1"></a>  var <span class="ot">&lt;-</span> tau2 <span class="sc">+</span> sigma2</span>
<span id="cb947-9"><a href="maximum-likelihood-estimation.html#cb947-9" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dnorm</span>(ss<span class="sc">$</span>reaction, <span class="at">mean =</span> mu, <span class="at">sd =</span> <span class="fu">sqrt</span>(var), <span class="at">log =</span> <span class="cn">TRUE</span>))</span>
<span id="cb947-10"><a href="maximum-likelihood-estimation.html#cb947-10" tabindex="-1"></a>}</span>
<span id="cb947-11"><a href="maximum-likelihood-estimation.html#cb947-11" tabindex="-1"></a></span>
<span id="cb947-12"><a href="maximum-likelihood-estimation.html#cb947-12" tabindex="-1"></a><span class="fu">like</span>(<span class="fu">c</span>(<span class="dv">295</span>, <span class="fl">10.5</span>, <span class="dv">1474</span>, <span class="dv">961</span>))</span></code></pre></div>
<pre><code>## [1] 1021.136</code></pre>
<div class="sourceCode" id="cb949"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb949-1"><a href="maximum-likelihood-estimation.html#cb949-1" tabindex="-1"></a>oo <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">295</span>, <span class="fl">10.5</span>, <span class="dv">1474</span>, <span class="dv">961</span>), <span class="at">fn =</span> like, <span class="at">method =</span> <span class="st">&quot;L-BFGS-B&quot;</span>, <span class="at">lower =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code></pre></div>
<div class="sourceCode" id="cb950"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb950-1"><a href="maximum-likelihood-estimation.html#cb950-1" tabindex="-1"></a><span class="fu">like</span>(oo<span class="sc">$</span>par)</span></code></pre></div>
<pre><code>## [1] 950.1465</code></pre>
<div class="sourceCode" id="cb952"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb952-1"><a href="maximum-likelihood-estimation.html#cb952-1" tabindex="-1"></a>tidy_modlmer <span class="ot">&lt;-</span> broom.mixed<span class="sc">::</span><span class="fu">tidy</span>(mod_lmer)</span>
<span id="cb952-2"><a href="maximum-likelihood-estimation.html#cb952-2" tabindex="-1"></a><span class="fu">like</span>(<span class="fu">c</span>(tidy_modlmer<span class="sc">$</span>estimate[<span class="dv">1</span>], tidy_modlmer<span class="sc">$</span>estimate[<span class="dv">2</span>], tidy_modlmer<span class="sc">$</span>estimate[<span class="dv">3</span>]<span class="sc">^</span><span class="dv">2</span>, tidy_modlmer<span class="sc">$</span>estimate[<span class="dv">4</span>]<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<pre><code>## [1] 950.2107</code></pre>
<p>We can see that we don’t quite get the fully correct answer. This is because we haven’t correctly described the likelihood function for a mixed effect model. The likelihood function for a mixed effect model is more complicated than the one we wrote down above, because it allows correlation within subjects. The likelihood function for a mixed effect model is based on the joint distribution of the responses for each subject, which is a multivariate normal distribution with mean vector and covariance matrix that depend on the fixed effects and the random effects. While the <strong>marginal</strong> distribution of each response is normal, the <strong>joint</strong> distribution of the responses for each subject is multivariate normal with correlation between responses from the same subject. This is fundamentally different than what we were doing in the previous section, because now we have to compute the <strong>joint likelihood</strong> of the entire sample directly, rather than multiplying the likelihood of the samples together.</p>
<p><strong>How would that work for linear regression</strong></p>
<p>Let’s return to the same example we did earlier with running speed. We have to understand multivariate normal distributions to some extent, so here we go. The multivariate normal distribution is a generalization of the univariate normal distribution to multiple dimensions. Its parameters are a <em>mean vector</em> and a <em>covariance matrix</em>. The mean vector gives the expected value of each variable, while the covariance matrix gives the variance of each variable and the covariance between each pair of variables. In the following example, we will look at the <strong>joint</strong> distribution of <span class="math inline">\((X_1, X_2)\)</span>, so the length of the mean vector will be 2 and the covariance matrix will be <span class="math inline">\(2 \times 2\)</span>.</p>
<div class="sourceCode" id="cb954"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb954-1"><a href="maximum-likelihood-estimation.html#cb954-1" tabindex="-1"></a>Sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">5</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb954-2"><a href="maximum-likelihood-estimation.html#cb954-2" tabindex="-1"></a><span class="fu">eigen</span>(Sigma) <span class="co">#this is a positive definite matrix, so it is a valid covariance matrix</span></span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 6.236068 1.763932
## 
## $vectors
##           [,1]       [,2]
## [1,] 0.5257311 -0.8506508
## [2,] 0.8506508  0.5257311</code></pre>
<div class="sourceCode" id="cb956"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb956-1"><a href="maximum-likelihood-estimation.html#cb956-1" tabindex="-1"></a><span class="fu">library</span>(mvtnorm)</span>
<span id="cb956-2"><a href="maximum-likelihood-estimation.html#cb956-2" tabindex="-1"></a>dat <span class="ot">&lt;-</span> mvtnorm<span class="sc">::</span><span class="fu">rmvnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>), <span class="at">sigma =</span> Sigma)</span>
<span id="cb956-3"><a href="maximum-likelihood-estimation.html#cb956-3" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(dat)</span>
<span id="cb956-4"><a href="maximum-likelihood-estimation.html#cb956-4" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb956-5"><a href="maximum-likelihood-estimation.html#cb956-5" tabindex="-1"></a><span class="fu">ggplot</span>(dd, <span class="fu">aes</span>(<span class="at">x =</span> X1, <span class="at">y =</span> X2)) <span class="sc">+</span> </span>
<span id="cb956-6"><a href="maximum-likelihood-estimation.html#cb956-6" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb956-7"><a href="maximum-likelihood-estimation.html#cb956-7" tabindex="-1"></a>  <span class="fu">coord_equal</span>() </span></code></pre></div>
<p><img src="11-mle_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>To force independence of the coordinates, we set the covariances equal to zero. Note that for general rvs, uncorrelated does not imply independent, but for multivariate normal rvs, uncorrelated does imply independent.</p>
<p>We can also re-estimate the mean vector and the covariance matrix using MLE as follows:</p>
<div class="sourceCode" id="cb957"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb957-1"><a href="maximum-likelihood-estimation.html#cb957-1" tabindex="-1"></a>like_fun <span class="ot">&lt;-</span> <span class="cf">function</span>(par) {</span>
<span id="cb957-2"><a href="maximum-likelihood-estimation.html#cb957-2" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> <span class="fu">c</span>(par[<span class="dv">1</span>], par[<span class="dv">2</span>])</span>
<span id="cb957-3"><a href="maximum-likelihood-estimation.html#cb957-3" tabindex="-1"></a>  sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(par[<span class="dv">3</span>], par[<span class="dv">4</span>], par[<span class="dv">4</span>], par[<span class="dv">5</span>]), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb957-4"><a href="maximum-likelihood-estimation.html#cb957-4" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dmvnorm</span>(dat, <span class="at">mean =</span> mu, <span class="at">sigma =</span> sigma, <span class="at">log =</span> T))</span>
<span id="cb957-5"><a href="maximum-likelihood-estimation.html#cb957-5" tabindex="-1"></a>}</span>
<span id="cb957-6"><a href="maximum-likelihood-estimation.html#cb957-6" tabindex="-1"></a>purrr<span class="sc">::</span><span class="fu">safely</span>(<span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">5</span>), <span class="at">fn =</span> like_fun, <span class="at">lower =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>), <span class="at">method =</span> <span class="st">&quot;L-BFGS-B&quot;</span>))</span></code></pre></div>
<pre><code>## function (...) 
## capture_error(.f(...), otherwise, quiet)
## &lt;bytecode: 0x7f8c0bcd3248&gt;
## &lt;environment: 0x7f8c0bcd36e0&gt;</code></pre>
<div class="sourceCode" id="cb959"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb959-1"><a href="maximum-likelihood-estimation.html#cb959-1" tabindex="-1"></a><span class="co">#if the matrix created isn&#39;t positive definite, then this will break</span></span></code></pre></div>
<p>Let’s see how it works.</p>
<div class="sourceCode" id="cb960"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb960-1"><a href="maximum-likelihood-estimation.html#cb960-1" tabindex="-1"></a>par <span class="ot">&lt;-</span> oo<span class="sc">$</span>par</span>
<span id="cb960-2"><a href="maximum-likelihood-estimation.html#cb960-2" tabindex="-1"></a><span class="fu">library</span>(mvtnorm)</span>
<span id="cb960-3"><a href="maximum-likelihood-estimation.html#cb960-3" tabindex="-1"></a>nll <span class="ot">&lt;-</span> <span class="cf">function</span>(par) {</span>
<span id="cb960-4"><a href="maximum-likelihood-estimation.html#cb960-4" tabindex="-1"></a>  gamma  <span class="ot">&lt;-</span> par[<span class="dv">1</span>]</span>
<span id="cb960-5"><a href="maximum-likelihood-estimation.html#cb960-5" tabindex="-1"></a>  beta   <span class="ot">&lt;-</span> par[<span class="dv">2</span>]</span>
<span id="cb960-6"><a href="maximum-likelihood-estimation.html#cb960-6" tabindex="-1"></a>  tau2   <span class="ot">&lt;-</span> par[<span class="dv">3</span>]</span>
<span id="cb960-7"><a href="maximum-likelihood-estimation.html#cb960-7" tabindex="-1"></a>  sigma2 <span class="ot">&lt;-</span> par[<span class="dv">4</span>]</span>
<span id="cb960-8"><a href="maximum-likelihood-estimation.html#cb960-8" tabindex="-1"></a></span>
<span id="cb960-9"><a href="maximum-likelihood-estimation.html#cb960-9" tabindex="-1"></a>  <span class="cf">if</span> (tau2 <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">||</span> sigma2 <span class="sc">&lt;=</span> <span class="dv">0</span>) <span class="fu">return</span>(<span class="cn">Inf</span>)</span>
<span id="cb960-10"><a href="maximum-likelihood-estimation.html#cb960-10" tabindex="-1"></a></span>
<span id="cb960-11"><a href="maximum-likelihood-estimation.html#cb960-11" tabindex="-1"></a>  response <span class="ot">&lt;-</span> ss<span class="sc">$</span>reaction</span>
<span id="cb960-12"><a href="maximum-likelihood-estimation.html#cb960-12" tabindex="-1"></a>  pred_fixed_effect <span class="ot">&lt;-</span> gamma <span class="sc">+</span> beta <span class="sc">*</span> ss<span class="sc">$</span>days <span class="co">#this is the same as mu, which is a good check</span></span>
<span id="cb960-13"><a href="maximum-likelihood-estimation.html#cb960-13" tabindex="-1"></a>    </span>
<span id="cb960-14"><a href="maximum-likelihood-estimation.html#cb960-14" tabindex="-1"></a>  g <span class="ot">&lt;-</span> <span class="fu">factor</span>(ss<span class="sc">$</span>subject) <span class="co">#this is the grouping variable for the random intercepts)</span></span>
<span id="cb960-15"><a href="maximum-likelihood-estimation.html#cb960-15" tabindex="-1"></a>  Z <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> g)   <span class="co"># columns correspond to groups (levels of g)</span></span>
<span id="cb960-16"><a href="maximum-likelihood-estimation.html#cb960-16" tabindex="-1"></a></span>
<span id="cb960-17"><a href="maximum-likelihood-estimation.html#cb960-17" tabindex="-1"></a>  N <span class="ot">&lt;-</span> <span class="fu">length</span>(response)</span>
<span id="cb960-18"><a href="maximum-likelihood-estimation.html#cb960-18" tabindex="-1"></a>  V <span class="ot">&lt;-</span> tau2 <span class="sc">*</span> (Z <span class="sc">%*%</span> <span class="fu">t</span>(Z)) <span class="sc">+</span> sigma2 <span class="sc">*</span> <span class="fu">diag</span>(N)  <span class="co"># Marginal covariance: V = tau2 * Z Z&#39; + sigma2 * I_N</span></span>
<span id="cb960-19"><a href="maximum-likelihood-estimation.html#cb960-19" tabindex="-1"></a></span>
<span id="cb960-20"><a href="maximum-likelihood-estimation.html#cb960-20" tabindex="-1"></a>  </span>
<span id="cb960-21"><a href="maximum-likelihood-estimation.html#cb960-21" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">dmvnorm</span>(response, <span class="at">mean =</span> pred_fixed_effect, <span class="at">sigma =</span> V, <span class="at">log =</span> <span class="cn">TRUE</span>)</span>
<span id="cb960-22"><a href="maximum-likelihood-estimation.html#cb960-22" tabindex="-1"></a>}</span>
<span id="cb960-23"><a href="maximum-likelihood-estimation.html#cb960-23" tabindex="-1"></a><span class="fu">nll</span>(par)</span></code></pre></div>
<pre><code>## [1] 897.4195</code></pre>
<div class="sourceCode" id="cb962"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb962-1"><a href="maximum-likelihood-estimation.html#cb962-1" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> par, <span class="at">fn =</span> nll, <span class="at">method =</span> <span class="st">&quot;L-BFGS-B&quot;</span>, <span class="at">lower =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code></pre></div>
<pre><code>## $par
## [1]  251.40703   10.46715 1379.07124  954.27973
## 
## $value
## [1] 897.0538
## 
## $counts
## function gradient 
##       15       15 
## 
## $convergence
## [1] 0
## 
## $message
## [1] &quot;CONVERGENCE: REL_REDUCTION_OF_F &lt;= FACTR*EPSMCH&quot;</code></pre>
<div class="sourceCode" id="cb964"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb964-1"><a href="maximum-likelihood-estimation.html#cb964-1" tabindex="-1"></a><span class="fu">summary</span>(mod_lmer)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: reaction ~ days + (1 | subject)
##    Data: ss
## 
## REML criterion at convergence: 1786.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.2257 -0.5529  0.0109  0.5188  4.2506 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  subject  (Intercept) 1378.2   37.12   
##  Residual              960.5   30.99   
## Number of obs: 180, groups:  subject, 18
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept) 251.4051     9.7467   25.79
## days         10.4673     0.8042   13.02
## 
## Correlation of Fixed Effects:
##      (Intr)
## days -0.371</code></pre>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p>citation needed<a href="maximum-likelihood-estimation.html#fnref5" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lecture-notes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="solutions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
