<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Non-Linear Regression Models | Applied Regression with R</title>
  <meta name="description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Non-Linear Regression Models | Applied Regression with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Non-Linear Regression Models | Applied Regression with R" />
  
  <meta name="twitter:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

<meta name="author" content="Darrin Speegle" />


<meta name="date" content="2026-02-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
<link rel="prev" href="variable-selection.html"/>
<link rel="next" href="tree-regression-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Regression with R<br />&nbsp; Notes From STAT 4870/5087</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="classicaltheory.html"><a href="classicaltheory.html"><i class="fa fa-check"></i><b>2</b> Classical Theory of Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="classicaltheory.html"><a href="classicaltheory.html#review"><i class="fa fa-check"></i><b>2.1</b> Review</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-means-and-standard-deviations"><i class="fa fa-check"></i><b>2.1.1</b> Estimating Means and standard deviations</a></li>
<li class="chapter" data-level="2.1.2" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-the-density-of-an-rv"><i class="fa fa-check"></i><b>2.1.2</b> Estimating the density of an rv</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-overview"><i class="fa fa-check"></i><b>2.2</b> Linear Regression Overview</a></li>
<li class="chapter" data-level="2.3" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-with-no-intercept"><i class="fa fa-check"></i><b>2.3</b> Linear Regression with no intercept</a></li>
<li class="chapter" data-level="2.4" data-path="classicaltheory.html"><a href="classicaltheory.html#the-full-model"><i class="fa fa-check"></i><b>2.4</b> The full model</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="classicaltheory.html"><a href="classicaltheory.html#hypothesis-test-interlude"><i class="fa fa-check"></i><b>2.4.1</b> Hypothesis Test Interlude</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="classicaltheory.html"><a href="classicaltheory.html#using-different-loss-functions"><i class="fa fa-check"></i><b>2.5</b> Using different loss functions</a></li>
<li class="chapter" data-level="" data-path="classicaltheory.html"><a href="classicaltheory.html#vignette-a-dplyr-primer"><i class="fa fa-check"></i>Vignette: A dplyr primer</a></li>
<li class="chapter" data-level="2.6" data-path="classicaltheory.html"><a href="classicaltheory.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#anova"><i class="fa fa-check"></i><b>3.0.1</b> Aside on multiple R squared and ANOVA</a></li>
<li class="chapter" data-level="3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-variable-selection-anova"><i class="fa fa-check"></i><b>3.1</b> More Variable Selection: ANOVA</a></li>
<li class="chapter" data-level="3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#predictions"><i class="fa fa-check"></i><b>3.2</b> Predictions</a></li>
<li class="chapter" data-level="3.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#using-aic"><i class="fa fa-check"></i><b>3.3</b> Using AIC</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#likelihood-functions"><i class="fa fa-check"></i><b>3.3.1</b> Likelihood functions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercises-1"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html"><i class="fa fa-check"></i><b>4</b> Intro to Predictive Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#comparingtwomodels"><i class="fa fa-check"></i><b>4.1</b> Comparing Two Models</a></li>
<li class="chapter" data-level="4.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#a-brief-return-to-inference"><i class="fa fa-check"></i><b>4.2</b> A Brief Return to Inference</a></li>
<li class="chapter" data-level="4.3" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#simulations-of-expected-mse"><i class="fa fa-check"></i><b>4.3</b> Simulations of Expected MSE</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-and-bias-variance-tradeoff"><i class="fa fa-check"></i><b>4.3.1</b> Estimating MSE and Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-for-new-predictors-uniformly-sampled"><i class="fa fa-check"></i><b>4.3.2</b> Estimating MSE for new predictors uniformly sampled</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>4.4</b> Bias Variance Trade-off</a></li>
<li class="chapter" data-level="4.5" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#exercises-2"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html"><i class="fa fa-check"></i><b>5</b> Regression Predictive Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#preprocessing"><i class="fa fa-check"></i><b>5.1</b> Preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#missing-data"><i class="fa fa-check"></i><b>5.2</b> Missing Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#predicting-when-a-level-is-missing-from-the-training-set"><i class="fa fa-check"></i><b>5.2.1</b> Predicting when a level is missing from the training set</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#correlated-predictors"><i class="fa fa-check"></i><b>5.3</b> Correlated Predictors</a></li>
<li class="chapter" data-level="5.4" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#aside-on-pca"><i class="fa fa-check"></i><b>5.4</b> Aside on PCA</a></li>
<li class="chapter" data-level="5.5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#johnson-lindenstrauss-dimension-reduction"><i class="fa fa-check"></i><b>5.5</b> Johnson-Lindenstrauss Dimension Reduction</a></li>
<li class="chapter" data-level="5.6" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#exercises-3"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variable-selection.html"><a href="variable-selection.html"><i class="fa fa-check"></i><b>6</b> Variable Selection</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variable-selection.html"><a href="variable-selection.html#partial-least-squares"><i class="fa fa-check"></i><b>6.1</b> Partial Least Squares</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="variable-selection.html"><a href="variable-selection.html#optional-pls-stuff"><i class="fa fa-check"></i><b>6.1.1</b> Optional PLS Stuff</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variable-selection.html"><a href="variable-selection.html#ridgelasso-and-elastic-net"><i class="fa fa-check"></i><b>6.2</b> Ridge/Lasso and Elastic Net</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="variable-selection.html"><a href="variable-selection.html#ridge-regression"><i class="fa fa-check"></i><b>6.2.1</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.2.2" data-path="variable-selection.html"><a href="variable-selection.html#lasso"><i class="fa fa-check"></i><b>6.2.2</b> LASSO</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variable-selection.html"><a href="variable-selection.html#step-aic"><i class="fa fa-check"></i><b>6.3</b> Step AIC</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="variable-selection.html"><a href="variable-selection.html#doing-lgocv-with-preprocessing"><i class="fa fa-check"></i><b>6.3.1</b> Doing LGOCV with preprocessing</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variable-selection.html"><a href="variable-selection.html#interactions"><i class="fa fa-check"></i><b>6.4</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html"><i class="fa fa-check"></i><b>7</b> Non-Linear Regression Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#support-vector-regression"><i class="fa fa-check"></i><b>7.1</b> Support Vector Regression</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#plot-twist"><i class="fa fa-check"></i><b>7.1.1</b> PLOT TWIST</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>7.2</b> K Nearest Neighbors</a></li>
<li class="chapter" data-level="7.3" data-path="non-linear-regression-models.html"><a href="non-linear-regression-models.html#exercises-4"><i class="fa fa-check"></i><b>7.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tree-regression-models.html"><a href="tree-regression-models.html"><i class="fa fa-check"></i><b>8</b> Tree Regression Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="tree-regression-models.html"><a href="tree-regression-models.html#basic-regression-trees"><i class="fa fa-check"></i><b>8.1</b> Basic Regression Trees</a></li>
<li class="chapter" data-level="8.2" data-path="tree-regression-models.html"><a href="tree-regression-models.html#regression-model-trees"><i class="fa fa-check"></i><b>8.2</b> Regression Model Trees</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="tree-regression-models.html"><a href="tree-regression-models.html#choosing-variable-to-split"><i class="fa fa-check"></i><b>8.2.1</b> Choosing Variable to Split</a></li>
<li class="chapter" data-level="8.2.2" data-path="tree-regression-models.html"><a href="tree-regression-models.html#choosing-split-value"><i class="fa fa-check"></i><b>8.2.2</b> Choosing Split Value</a></li>
<li class="chapter" data-level="8.2.3" data-path="tree-regression-models.html"><a href="tree-regression-models.html#predicting-values-smoothing"><i class="fa fa-check"></i><b>8.2.3</b> Predicting values (Smoothing)</a></li>
<li class="chapter" data-level="8.2.4" data-path="tree-regression-models.html"><a href="tree-regression-models.html#using-r-functions"><i class="fa fa-check"></i><b>8.2.4</b> Using R functions</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="tree-regression-models.html"><a href="tree-regression-models.html#bagging"><i class="fa fa-check"></i><b>8.3</b> Bagging</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="lecture-notes.html"><a href="lecture-notes.html"><i class="fa fa-check"></i><b>9</b> Lecture Notes</a>
<ul>
<li class="chapter" data-level="9.1" data-path="lecture-notes.html"><a href="lecture-notes.html#january-27"><i class="fa fa-check"></i><b>9.1</b> January 27</a></li>
<li class="chapter" data-level="9.2" data-path="lecture-notes.html"><a href="lecture-notes.html#february-3"><i class="fa fa-check"></i><b>9.2</b> February 3</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="lecture-notes.html"><a href="lecture-notes.html#simulating-data"><i class="fa fa-check"></i><b>9.2.1</b> Simulating Data</a></li>
<li class="chapter" data-level="9.2.2" data-path="lecture-notes.html"><a href="lecture-notes.html#building-models"><i class="fa fa-check"></i><b>9.2.2</b> Building Models</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="lecture-notes.html"><a href="lecture-notes.html#february-5"><i class="fa fa-check"></i><b>9.3</b> February 5</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="lecture-notes.html"><a href="lecture-notes.html#using-broomaugment"><i class="fa fa-check"></i><b>9.3.1</b> Using <code>broom::augment</code></a></li>
<li class="chapter" data-level="9.3.2" data-path="lecture-notes.html"><a href="lecture-notes.html#multicollinearity"><i class="fa fa-check"></i><b>9.3.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="lecture-notes.html"><a href="lecture-notes.html#february-10"><i class="fa fa-check"></i><b>9.4</b> February 10</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="lecture-notes.html"><a href="lecture-notes.html#anova-models"><i class="fa fa-check"></i><b>9.4.1</b> ANOVA Models</a></li>
<li class="chapter" data-level="9.4.2" data-path="lecture-notes.html"><a href="lecture-notes.html#penguins"><i class="fa fa-check"></i><b>9.4.2</b> Penguins</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="lecture-notes.html"><a href="lecture-notes.html#february-12"><i class="fa fa-check"></i><b>9.5</b> February 12</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="lecture-notes.html"><a href="lecture-notes.html#an-example"><i class="fa fa-check"></i><b>9.5.1</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="lecture-notes.html"><a href="lecture-notes.html#february-17"><i class="fa fa-check"></i><b>9.6</b> February 17</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-speaker-and-sentence-effects"><i class="fa fa-check"></i><b>9.6.1</b> Adding random speaker and sentence effects</a></li>
<li class="chapter" data-level="9.6.2" data-path="lecture-notes.html"><a href="lecture-notes.html#random-intercepts-with-continuous-predictor"><i class="fa fa-check"></i><b>9.6.2</b> Random intercepts with continuous predictor</a></li>
<li class="chapter" data-level="9.6.3" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-slopes"><i class="fa fa-check"></i><b>9.6.3</b> Adding random slopes</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="lecture-notes.html"><a href="lecture-notes.html#february-19"><i class="fa fa-check"></i><b>9.7</b> February 19</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="lecture-notes.html"><a href="lecture-notes.html#random-slopes"><i class="fa fa-check"></i><b>9.7.1</b> Random Slopes</a></li>
<li class="chapter" data-level="9.7.2" data-path="lecture-notes.html"><a href="lecture-notes.html#comparing-models"><i class="fa fa-check"></i><b>9.7.2</b> Comparing models</a></li>
<li class="chapter" data-level="9.7.3" data-path="lecture-notes.html"><a href="lecture-notes.html#some-theory"><i class="fa fa-check"></i><b>9.7.3</b> Some Theory</a></li>
<li class="chapter" data-level="9.7.4" data-path="lecture-notes.html"><a href="lecture-notes.html#intro-to-random-effects-and-mixed-effect-models---terminology-and-first-examples"><i class="fa fa-check"></i><b>9.7.4</b> Intro to Random Effects and Mixed Effect Models - Terminology and First Examples</a></li>
<li class="chapter" data-level="9.7.5" data-path="lecture-notes.html"><a href="lecture-notes.html#comparison-of-models"><i class="fa fa-check"></i><b>9.7.5</b> Comparison of Models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>10</b> Solutions</a>
<ul>
<li class="chapter" data-level="10.1" data-path="solutions.html"><a href="solutions.html#chapter-2-solutions"><i class="fa fa-check"></i><b>10.1</b> Chapter 2 Solutions</a></li>
<li class="chapter" data-level="10.2" data-path="solutions.html"><a href="solutions.html#chapter-3-solutions"><i class="fa fa-check"></i><b>10.2</b> Chapter 3 Solutions</a></li>
<li class="chapter" data-level="10.3" data-path="solutions.html"><a href="solutions.html#chapter-5"><i class="fa fa-check"></i><b>10.3</b> Chapter 5</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Regression with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="non-linear-regression-models" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Non-Linear Regression Models<a href="non-linear-regression-models.html#non-linear-regression-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This short chapter will cover two techniques: Support Vector Machines and <span class="math inline">\(k\)</span> nearest neighbors.</p>
<p>Support vector machines are more commonly used in classification problems, but we are focusing on a numeric response for now. We will motivate SVM’s via an appeal to <em>robust regression</em>, much like using Huber or another error function.</p>
<p><span class="math inline">\(k\)</span> Nearest Neighbors is a useful technique in many contexts. We will only give a brief overview of this technique.</p>
<div id="support-vector-regression" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Support Vector Regression<a href="non-linear-regression-models.html#support-vector-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall once again that OLS using <code>lm</code> minimizes the SSE given by</p>
<p><span class="math display">\[
SSE = \sum_{i = 1}^n\bigl(y_i - (\beta_0 + \beta_1 x_{1i} + \cdots \beta_{Pi})\bigr)^2
\]</span></p>
<p>In other words, if <span class="math inline">\(g(x) = x^2\)</span>, then the SSE is given by</p>
<p><span class="math display">\[
SSE = \sum_{i = 1}^n g(y_i - \hat y_i)
\]</span></p>
<p>We have seen before that picking different functions <span class="math inline">\(g\)</span> can lead to better results in some instances. For example, chosing <span class="math inline">\(g\)</span> to be given in the following plot limits the influence of outliers.</p>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb657-1"><a href="non-linear-regression-models.html#cb657-1" tabindex="-1"></a><span class="fu">curve</span>(robustbase<span class="sc">::</span><span class="fu">Mchi</span>(x, <span class="at">cc =</span> <span class="fl">1.6</span>, <span class="at">psi =</span> <span class="st">&quot;bisquare&quot;</span>), <span class="at">from =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">to =</span> <span class="dv">2</span>,</span>
<span id="cb657-2"><a href="non-linear-regression-models.html#cb657-2" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">&quot;g(x)&quot;</span>)</span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Support vector machines give another choice of <span class="math inline">\(g\)</span>, which is shown below:</p>
<div class="sourceCode" id="cb658"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb658-1"><a href="non-linear-regression-models.html#cb658-1" tabindex="-1"></a>svm <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">epsilon =</span> <span class="dv">1</span>) {</span>
<span id="cb658-2"><a href="non-linear-regression-models.html#cb658-2" tabindex="-1"></a>  <span class="fu">pmax</span>(<span class="dv">0</span>, <span class="fu">abs</span>(x) <span class="sc">-</span> epsilon)</span>
<span id="cb658-3"><a href="non-linear-regression-models.html#cb658-3" tabindex="-1"></a>}</span>
<span id="cb658-4"><a href="non-linear-regression-models.html#cb658-4" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">svm</span>(x, .<span class="dv">2</span>), <span class="at">from =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">to =</span> <span class="dv">2</span>)</span>
<span id="cb658-5"><a href="non-linear-regression-models.html#cb658-5" tabindex="-1"></a><span class="fu">curve</span>(robustbase<span class="sc">::</span><span class="fu">Mchi</span>(x, <span class="at">psi =</span> <span class="st">&quot;huber&quot;</span>, <span class="at">cc =</span> <span class="dv">1</span>), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>The loss function for SVM is similar to the Huber loss function and to <span class="math inline">\(g(x) = |x|\)</span>, because it behaves linearly outside of some interval around 0. However, a key difference is that small errors are set to exactly 0, rather than some small number. Another way to describe the loss function is that it is the absolute loss function <span class="math inline">\(g(x) = |x|\)</span>, which has been <em>soft thresholded</em> at some value of <span class="math inline">\(\epsilon\)</span>. Don’t worry if that doesn’t help you understand that last sentence; you can definitely understand the loss function straight from the graph.</p>
<p>Let’s call the SVM loss function <span class="math inline">\(g_S\)</span> for this chapter, just to have notation. SVM regression minimizes</p>
<p><span class="math display">\[
\lambda \sum_{i = 1}^n g_S(y_i - \hat y_i) + \sum_{i = 1}^P \beta_i^2
\]</span></p>
<p>Note that there is a penalty attached to the coefficients. This will force the coefficients to be small within the range of errors for which <span class="math inline">\(g_S = 0\)</span>. You can think of it as; an error less than <span class="math inline">\(\epsilon\)</span> isn’t really an error, it is essentially correct. So, there is no point in fitting the curve further once we are within <span class="math inline">\(\epsilon\)</span>, we should work on other priorities. The two priorities chosen are fitting points outside of the <span class="math inline">\(\epsilon\)</span> error band, and making the coefficients small. We could have chosen other priorities and put those in the thing we are trying to minimize.</p>
<p>Note also that there is a parameter associated with the fit error. This parameter will determine how much weight is given to data points that fall outside of the <span class="math inline">\(\epsilon\)</span> band relative to how much weight is given to the penalty term of the coefficients. The textbook recommends that you fix a value of <span class="math inline">\(\epsilon\)</span> and tune the <span class="math inline">\(\lambda\)</span> parameter via cross-validation.</p>
<p>Let’s look at an example, using simulated data.</p>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb659-1"><a href="non-linear-regression-models.html#cb659-1" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(<span class="dv">9</span>), <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb659-2"><a href="non-linear-regression-models.html#cb659-2" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">t</span>(sigma) <span class="sc">%*%</span> sigma</span>
<span id="cb659-3"><a href="non-linear-regression-models.html#cb659-3" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">matrix</span>(MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="dv">3</span>, <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">Sigma =</span> sigma), <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb659-4"><a href="non-linear-regression-models.html#cb659-4" tabindex="-1"></a><span class="fu">cor</span>(dd)</span></code></pre></div>
<pre><code>##            [,1]       [,2]      [,3]
## [1,]  1.0000000 -0.3245328 0.1180751
## [2,] -0.3245328  1.0000000 0.1019505
## [3,]  0.1180751  0.1019505 1.0000000</code></pre>
<div class="sourceCode" id="cb661"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb661-1"><a href="non-linear-regression-models.html#cb661-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(dd)</span>
<span id="cb661-2"><a href="non-linear-regression-models.html#cb661-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb661-3"><a href="non-linear-regression-models.html#cb661-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">response =</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> X1 <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> X2 <span class="sc">+</span> <span class="dv">4</span> <span class="sc">*</span> X3 <span class="sc">+</span> <span class="dv">8</span> <span class="sc">*</span> <span class="fu">rt</span>(<span class="dv">100</span>, <span class="dv">4</span>))</span>
<span id="cb661-4"><a href="non-linear-regression-models.html#cb661-4" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(response <span class="sc">~</span> ., <span class="at">data =</span>df))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = response ~ ., data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -24.018  -6.817  -0.835   4.677  62.534 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.3024     0.6707   3.433 0.000682 ***
## X1            2.3362     0.5994   3.897 0.000120 ***
## X2            2.4941     0.7237   3.446 0.000651 ***
## X3            4.4056     0.4927   8.942  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.47 on 296 degrees of freedom
## Multiple R-squared:  0.2881, Adjusted R-squared:  0.2809 
## F-statistic: 39.93 on 3 and 296 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb663-1"><a href="non-linear-regression-models.html#cb663-1" tabindex="-1"></a>svm_error <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) {</span>
<span id="cb663-2"><a href="non-linear-regression-models.html#cb663-2" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> beta[<span class="dv">1</span>] <span class="sc">+</span> dd <span class="sc">%*%</span> beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb663-3"><a href="non-linear-regression-models.html#cb663-3" tabindex="-1"></a>  lambda <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">svm</span>(df<span class="sc">$</span>response <span class="sc">-</span> yhat, <span class="at">epsilon =</span> <span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">sum</span>(beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb663-4"><a href="non-linear-regression-models.html#cb663-4" tabindex="-1"></a>}</span>
<span id="cb663-5"><a href="non-linear-regression-models.html#cb663-5" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb663-6"><a href="non-linear-regression-models.html#cb663-6" tabindex="-1"></a><span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">fn =</span> svm_error)</span></code></pre></div>
<pre><code>## $par
## [1] 1.455720 1.367466 2.871621 3.904552
## 
## $value
## [1] 2093.236
## 
## $counts
## function gradient 
##      321       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL</code></pre>
<p>We definitely get quite different values for the parameters than we got when we used <code>lm</code>. Let’s do CV to see what the estimate RMSE is. In the past, we have been forcing our functions passed to optim to only have one parameter; namely, the one of interest. Here we see that we can have more arguments, and we just can add them to the end of <code>optim</code> and they get passed right along to the function we are optimizing.</p>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb665-1"><a href="non-linear-regression-models.html#cb665-1" tabindex="-1"></a>svm_error <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, lambda, dd_train, df_train) {</span>
<span id="cb665-2"><a href="non-linear-regression-models.html#cb665-2" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> beta[<span class="dv">1</span>] <span class="sc">+</span> dd_train <span class="sc">%*%</span> beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb665-3"><a href="non-linear-regression-models.html#cb665-3" tabindex="-1"></a>  lambda <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">svm</span>(df_train<span class="sc">$</span>response <span class="sc">-</span> yhat, <span class="at">epsilon =</span> .<span class="dv">5</span>)) <span class="sc">+</span> <span class="fu">sum</span>(beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb665-4"><a href="non-linear-regression-models.html#cb665-4" tabindex="-1"></a>}</span>
<span id="cb665-5"><a href="non-linear-regression-models.html#cb665-5" tabindex="-1"></a>svm_rmse <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, {</span>
<span id="cb665-6"><a href="non-linear-regression-models.html#cb665-6" tabindex="-1"></a>  train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">100</span>, <span class="dv">75</span>)</span>
<span id="cb665-7"><a href="non-linear-regression-models.html#cb665-7" tabindex="-1"></a>  test_indices <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)[<span class="sc">-</span>train_indices]</span>
<span id="cb665-8"><a href="non-linear-regression-models.html#cb665-8" tabindex="-1"></a>  dd_train <span class="ot">&lt;-</span> dd[train_indices,]</span>
<span id="cb665-9"><a href="non-linear-regression-models.html#cb665-9" tabindex="-1"></a>  df_train <span class="ot">&lt;-</span> df[train_indices,]</span>
<span id="cb665-10"><a href="non-linear-regression-models.html#cb665-10" tabindex="-1"></a>  dd_test <span class="ot">&lt;-</span> dd[test_indices,]</span>
<span id="cb665-11"><a href="non-linear-regression-models.html#cb665-11" tabindex="-1"></a>  beta <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">fn =</span> svm_error, </span>
<span id="cb665-12"><a href="non-linear-regression-models.html#cb665-12" tabindex="-1"></a>                  <span class="at">lambda =</span> lambda, </span>
<span id="cb665-13"><a href="non-linear-regression-models.html#cb665-13" tabindex="-1"></a>                  <span class="at">dd_train =</span> dd_train,</span>
<span id="cb665-14"><a href="non-linear-regression-models.html#cb665-14" tabindex="-1"></a>                  <span class="at">df_train =</span> df_train)<span class="sc">$</span>par</span>
<span id="cb665-15"><a href="non-linear-regression-models.html#cb665-15" tabindex="-1"></a>  yhats <span class="ot">&lt;-</span> beta[<span class="dv">1</span>] <span class="sc">+</span> dd_test <span class="sc">%*%</span> beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb665-16"><a href="non-linear-regression-models.html#cb665-16" tabindex="-1"></a>  errors <span class="ot">&lt;-</span> df<span class="sc">$</span>response[test_indices] <span class="sc">-</span> yhats</span>
<span id="cb665-17"><a href="non-linear-regression-models.html#cb665-17" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">mean</span>(errors<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb665-18"><a href="non-linear-regression-models.html#cb665-18" tabindex="-1"></a>})</span>
<span id="cb665-19"><a href="non-linear-regression-models.html#cb665-19" tabindex="-1"></a><span class="fu">mean</span>(svm_rmse)</span></code></pre></div>
<pre><code>## [1] 11.18908</code></pre>
<p>Now, let’s tune over several different values of <span class="math inline">\(\lambda\)</span>.</p>
<div class="sourceCode" id="cb667"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb667-1"><a href="non-linear-regression-models.html#cb667-1" tabindex="-1"></a>svm_error <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, lambda, dd_train, df_train) {</span>
<span id="cb667-2"><a href="non-linear-regression-models.html#cb667-2" tabindex="-1"></a>  yhat <span class="ot">&lt;-</span> beta[<span class="dv">1</span>] <span class="sc">+</span> dd_train <span class="sc">%*%</span> beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb667-3"><a href="non-linear-regression-models.html#cb667-3" tabindex="-1"></a>  lambda <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">svm</span>(df_train<span class="sc">$</span>response <span class="sc">-</span> yhat, <span class="at">epsilon =</span> .<span class="dv">5</span>)) <span class="sc">+</span> <span class="fu">sum</span>(beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb667-4"><a href="non-linear-regression-models.html#cb667-4" tabindex="-1"></a>}</span>
<span id="cb667-5"><a href="non-linear-regression-models.html#cb667-5" tabindex="-1"></a><span class="fu">sapply</span>((<span class="dv">2</span>)<span class="sc">^</span>((<span class="sc">-</span><span class="dv">6</span>)<span class="sc">:</span><span class="dv">14</span>), <span class="cf">function</span>(lambda) {</span>
<span id="cb667-6"><a href="non-linear-regression-models.html#cb667-6" tabindex="-1"></a></span>
<span id="cb667-7"><a href="non-linear-regression-models.html#cb667-7" tabindex="-1"></a>  svm_rmse <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, {</span>
<span id="cb667-8"><a href="non-linear-regression-models.html#cb667-8" tabindex="-1"></a>    train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">100</span>, <span class="dv">75</span>)</span>
<span id="cb667-9"><a href="non-linear-regression-models.html#cb667-9" tabindex="-1"></a>    test_indices <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)[<span class="sc">-</span>train_indices]</span>
<span id="cb667-10"><a href="non-linear-regression-models.html#cb667-10" tabindex="-1"></a>    dd_train <span class="ot">&lt;-</span> dd[train_indices,]</span>
<span id="cb667-11"><a href="non-linear-regression-models.html#cb667-11" tabindex="-1"></a>    df_train <span class="ot">&lt;-</span> df[train_indices,]</span>
<span id="cb667-12"><a href="non-linear-regression-models.html#cb667-12" tabindex="-1"></a>    dd_test <span class="ot">&lt;-</span> dd[test_indices,]</span>
<span id="cb667-13"><a href="non-linear-regression-models.html#cb667-13" tabindex="-1"></a>    beta <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">fn =</span> svm_error, </span>
<span id="cb667-14"><a href="non-linear-regression-models.html#cb667-14" tabindex="-1"></a>                  <span class="at">lambda =</span> lambda, </span>
<span id="cb667-15"><a href="non-linear-regression-models.html#cb667-15" tabindex="-1"></a>                  <span class="at">dd_train =</span> dd_train,</span>
<span id="cb667-16"><a href="non-linear-regression-models.html#cb667-16" tabindex="-1"></a>                  <span class="at">df_train =</span> df_train)<span class="sc">$</span>par</span>
<span id="cb667-17"><a href="non-linear-regression-models.html#cb667-17" tabindex="-1"></a>    yhats <span class="ot">&lt;-</span> beta[<span class="dv">1</span>] <span class="sc">+</span> dd_test <span class="sc">%*%</span> beta[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb667-18"><a href="non-linear-regression-models.html#cb667-18" tabindex="-1"></a>    errors <span class="ot">&lt;-</span> df<span class="sc">$</span>response[test_indices] <span class="sc">-</span> yhats</span>
<span id="cb667-19"><a href="non-linear-regression-models.html#cb667-19" tabindex="-1"></a>    <span class="fu">sqrt</span>(<span class="fu">mean</span>(errors<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb667-20"><a href="non-linear-regression-models.html#cb667-20" tabindex="-1"></a>  })</span>
<span id="cb667-21"><a href="non-linear-regression-models.html#cb667-21" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">lambda =</span> lambda, <span class="at">mu =</span> <span class="fu">mean</span>(svm_rmse), <span class="at">sdev =</span> <span class="fu">sd</span>(svm_rmse))</span>
<span id="cb667-22"><a href="non-linear-regression-models.html#cb667-22" tabindex="-1"></a>})</span></code></pre></div>
<pre><code>##             [,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
## lambda  0.015625  0.031250  0.062500  0.125000  0.250000  0.500000  1.000000
## mu     12.770140 12.851859 12.304318 11.766305 11.262668 11.367910 11.109200
## sdev    3.165466  2.981116  3.068947  3.236702  2.941832  3.123076  3.103451
##             [,8]      [,9]     [,10]     [,11]     [,12]     [,13]      [,14]
## lambda  2.000000  4.000000  8.000000 16.000000 32.000000 64.000000 128.000000
## mu     11.318648 11.261377 11.401634 11.235324 11.361837 11.559575  10.976781
## sdev    3.044137  2.882519  3.065034  2.874574  3.186897  3.233528   2.912531
##             [,15]      [,16]       [,17]       [,18]      [,19]       [,20]
## lambda 256.000000 512.000000 1024.000000 2048.000000 4096.00000 8192.000000
## mu      11.054994  10.791886   11.480855   10.908943   11.45509   11.784265
## sdev     2.885535   2.970352    2.712785    2.675327    3.12303    3.305523
##               [,21]
## lambda 16384.000000
## mu        11.033548
## sdev       3.046968</code></pre>
<p>We see that once we get to a <span class="math inline">\(\lambda\)</span> of about 1/8, the RMSE is about as small as it is going to get.</p>
<p>And now we compare that to <code>lm</code>.</p>
<div class="sourceCode" id="cb669"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb669-1"><a href="non-linear-regression-models.html#cb669-1" tabindex="-1"></a>lm_rmse <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, {</span>
<span id="cb669-2"><a href="non-linear-regression-models.html#cb669-2" tabindex="-1"></a>  train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">100</span>, <span class="dv">75</span>)</span>
<span id="cb669-3"><a href="non-linear-regression-models.html#cb669-3" tabindex="-1"></a>  test_indices <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)[<span class="sc">-</span>train_indices]</span>
<span id="cb669-4"><a href="non-linear-regression-models.html#cb669-4" tabindex="-1"></a>  dd_train <span class="ot">&lt;-</span> dd[train_indices,]</span>
<span id="cb669-5"><a href="non-linear-regression-models.html#cb669-5" tabindex="-1"></a>  df_train <span class="ot">&lt;-</span> df[train_indices,]</span>
<span id="cb669-6"><a href="non-linear-regression-models.html#cb669-6" tabindex="-1"></a>  dd_test <span class="ot">&lt;-</span> dd[test_indices,]</span>
<span id="cb669-7"><a href="non-linear-regression-models.html#cb669-7" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(response <span class="sc">~</span> ., <span class="at">data =</span> df_train)</span>
<span id="cb669-8"><a href="non-linear-regression-models.html#cb669-8" tabindex="-1"></a>  yhats <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod, <span class="at">newdata =</span> df[test_indices,])</span>
<span id="cb669-9"><a href="non-linear-regression-models.html#cb669-9" tabindex="-1"></a>  errors <span class="ot">&lt;-</span> df<span class="sc">$</span>response[test_indices] <span class="sc">-</span> yhats</span>
<span id="cb669-10"><a href="non-linear-regression-models.html#cb669-10" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">mean</span>(errors<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb669-11"><a href="non-linear-regression-models.html#cb669-11" tabindex="-1"></a>})</span>
<span id="cb669-12"><a href="non-linear-regression-models.html#cb669-12" tabindex="-1"></a><span class="fu">mean</span>(lm_rmse)</span></code></pre></div>
<pre><code>## [1] 11.24577</code></pre>
<p>Seems to be working about the same as <code>lm</code> on this data set. Up to this point, you could fairly ask why this section is in the non-linear regression chapter of the book. It seems completely in line with the things we were doing earlier. However, we can do a switcheroo called the “kernel trick.” Let’s do this.</p>
<p>Let’s suppose that we have new data <span class="math inline">\((u_1, \ldots, u_P)\)</span> that we want to predict the response for. We find values <span class="math inline">\((\alpha_i)\)</span> such that</p>
<p><span class="math display">\[
\beta_j = \sum_{i = 1}^n \alpha_i x_{ij}
\]</span></p>
<p>Then, plugging into the regression equation, we have</p>
<p><span class="math display">\[
\begin{aligned*}
\hat y &amp;= \beta_0 + \sum_{j = 1}^P \beta_j u_j \\
&amp;= \beta_0 + \sum_{j = 1}^P \sum_{i = 1}^n \alpha_i x_{ij} u_j\\
&amp;= \beta_0 + \sum_{i = 1}^n \alpha_i \bigl(\sum_{j = 1}^P x_{ij} u_j\bigr)
\end{aligned*}
\]</span></p>
<p>Now we have more parameters in our model than we have observations! That is normally not a good idea, but we can add penalties to having <span class="math inline">\(|\alpha_i| &gt; 0\)</span> which make many of them zero. We want to minimize the following function:</p>
<p><span class="math display">\[
\sum_{i = 1}^n\sum_{j = 1}^n \alpha_i \alpha_j \langle x[i,], x[j,]\rangle + \epsilon \sum_{i = 1}^n |\alpha_i| - \sum_{i = 1}^n \alpha_i y_i
\]</span>
subject to the constraints <span class="math inline">\(\sum_{i = 1}^n \alpha_i = 0\)</span> and <span class="math inline">\(|\alpha_i| \le C\)</span>. I will be the first to admit that it is not obvious how to get to these conditions from where we started, but it follows from considering the <a href="https://en.wikipedia.org/wiki/Karush%E2%80%93Kuhn%E2%80%93Tucker_conditions">Karush-Kuhn-Tucker Conditions</a> for transforming one optimization problem into its dual formulation. See this <a href="https://alex.smola.org/papers/2003/SmoSch03b.pdf">paper</a> for details. But, notice that there is an <span class="math inline">\(\ell_1\)</span> penalty on the <span class="math inline">\(\alpha_i\)</span> coefficients, which we have seen in the LASSO tends to force some/many of them to be zero. I am not going to try to solve that minimization problem directly, let’s use packages that do SVR and see what we get.</p>
<div class="sourceCode" id="cb671"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb671-1"><a href="non-linear-regression-models.html#cb671-1" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb671-2"><a href="non-linear-regression-models.html#cb671-2" tabindex="-1"></a>ys <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> xs <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, .<span class="dv">5</span>)</span>
<span id="cb671-3"><a href="non-linear-regression-models.html#cb671-3" tabindex="-1"></a><span class="fu">plot</span>(xs, ys)</span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb672"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb672-1"><a href="non-linear-regression-models.html#cb672-1" tabindex="-1"></a><span class="fu">library</span>(kernlab)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;kernlab&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     cross</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     alpha</code></pre>
<div class="sourceCode" id="cb676"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb676-1"><a href="non-linear-regression-models.html#cb676-1" tabindex="-1"></a>tuneGrid <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">C =</span> <span class="dv">2</span><span class="sc">^</span>((<span class="sc">-</span><span class="dv">4</span>)<span class="sc">:</span><span class="dv">4</span>))</span>
<span id="cb676-2"><a href="non-linear-regression-models.html#cb676-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> xs, <span class="at">y =</span> ys)</span>
<span id="cb676-3"><a href="non-linear-regression-models.html#cb676-3" tabindex="-1"></a>tuneGrid <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">C =</span> <span class="dv">2</span><span class="sc">^</span>((<span class="sc">-</span><span class="dv">4</span>)<span class="sc">:</span><span class="dv">4</span>))</span>
<span id="cb676-4"><a href="non-linear-regression-models.html#cb676-4" tabindex="-1"></a>caret<span class="sc">::</span><span class="fu">train</span>(y <span class="sc">~</span> x,</span>
<span id="cb676-5"><a href="non-linear-regression-models.html#cb676-5" tabindex="-1"></a>             <span class="at">data =</span> df,</span>
<span id="cb676-6"><a href="non-linear-regression-models.html#cb676-6" tabindex="-1"></a>             <span class="at">method =</span> <span class="st">&quot;svmLinear&quot;</span>,</span>
<span id="cb676-7"><a href="non-linear-regression-models.html#cb676-7" tabindex="-1"></a>             <span class="at">tuneGrid =</span> tuneGrid,</span>
<span id="cb676-8"><a href="non-linear-regression-models.html#cb676-8" tabindex="-1"></a>             <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;scale&quot;</span>)</span>
<span id="cb676-9"><a href="non-linear-regression-models.html#cb676-9" tabindex="-1"></a>              )</span></code></pre></div>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<pre><code>## Support Vector Machines with Linear Kernel 
## 
## 100 samples
##   1 predictor
## 
## Pre-processing: centered (1), scaled (1) 
## Resampling: Bootstrapped (25 reps) 
## Summary of sample sizes: 100, 100, 100, 100, 100, 100, ... 
## Resampling results across tuning parameters:
## 
##   C        RMSE       Rsquared   MAE      
##    0.0625  0.4244596  0.8617257  0.3452688
##    0.1250  0.4177273  0.8617257  0.3395679
##    0.2500  0.4160328  0.8617257  0.3383377
##    0.5000  0.4172620  0.8617257  0.3389625
##    1.0000  0.4174206  0.8617257  0.3388128
##    2.0000  0.4175769  0.8617257  0.3389441
##    4.0000  0.4175593  0.8617257  0.3389334
##    8.0000  0.4176696  0.8617257  0.3389961
##   16.0000  0.4176812  0.8617257  0.3390239
## 
## RMSE was used to select the optimal model using the smallest value.
## The final value used for the model was C = 0.25.</code></pre>
<p>There doesn’t seem to be much difference between the tuning parameters, so let’s just do the default <span class="math inline">\(C = 1\)</span>.</p>
<div class="sourceCode" id="cb681"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb681-1"><a href="non-linear-regression-models.html#cb681-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> kernlab<span class="sc">::</span><span class="fu">ksvm</span>(<span class="at">x =</span> xs, </span>
<span id="cb681-2"><a href="non-linear-regression-models.html#cb681-2" tabindex="-1"></a>                     <span class="at">y =</span> ys, </span>
<span id="cb681-3"><a href="non-linear-regression-models.html#cb681-3" tabindex="-1"></a>                     <span class="at">kernel =</span> <span class="st">&quot;vanilladot&quot;</span>, <span class="co">#linear regression</span></span>
<span id="cb681-4"><a href="non-linear-regression-models.html#cb681-4" tabindex="-1"></a>                     <span class="at">scaled =</span> <span class="cn">FALSE</span>, <span class="co">#for illustration purposes</span></span>
<span id="cb681-5"><a href="non-linear-regression-models.html#cb681-5" tabindex="-1"></a>                     <span class="at">C =</span> <span class="dv">1</span>,</span>
<span id="cb681-6"><a href="non-linear-regression-models.html#cb681-6" tabindex="-1"></a>                     <span class="at">epsilon =</span> .<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##  Setting default kernel parameters</code></pre>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="non-linear-regression-models.html#cb683-1" tabindex="-1"></a>kernlab<span class="sc">::</span><span class="fu">alpha</span>(mod)</span></code></pre></div>
<pre><code>##  [1] -1.0000000 -1.0000000  1.0000000  1.0000000  1.0000000  1.0000000
##  [7] -1.0000000  1.0000000  1.0000000  1.0000000 -1.0000000 -1.0000000
## [13]  1.0000000 -1.0000000  1.0000000 -1.0000000  1.0000000 -1.0000000
## [19]  1.0000000 -1.0000000 -1.0000000 -1.0000000  1.0000000 -1.0000000
## [25]  1.0000000 -1.0000000  1.0000000  1.0000000 -1.0000000 -1.0000000
## [31]  1.0000000 -1.0000000 -1.0000000  1.0000000 -1.0000000  1.0000000
## [37]  1.0000000 -1.0000000  1.0000000 -1.0000000 -1.0000000 -1.0000000
## [43]  1.0000000  1.0000000  1.0000000 -1.0000000  1.0000000  1.0000000
## [49] -1.0000000 -0.4760304  1.0000000 -1.0000000  1.0000000 -1.0000000
## [55]  1.0000000  1.0000000  1.0000000 -1.0000000  1.0000000 -1.0000000
## [61] -1.0000000  1.0000000 -0.5239696 -1.0000000 -1.0000000  1.0000000
## [67] -1.0000000  1.0000000  1.0000000 -1.0000000 -1.0000000  1.0000000
## [73]  1.0000000  1.0000000 -1.0000000 -1.0000000 -1.0000000 -1.0000000
## [79] -1.0000000  1.0000000  1.0000000</code></pre>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="non-linear-regression-models.html#cb685-1" tabindex="-1"></a>kernlab<span class="sc">::</span><span class="fu">alphaindex</span>(mod)</span></code></pre></div>
<pre><code>##  [1]  1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
## [26] 27 29 30 31 32 33 34 35 36 37 38 40 42 43 44 45 46 48 49 51 54 55 56 58 60
## [51] 62 64 65 67 68 69 71 72 73 75 76 77 78 79 81 82 84 85 87 88 89 90 91 92 93
## [76] 94 95 96 97 98 99</code></pre>
<p>The observations for which the corresponding <span class="math inline">\(\alpha_i\)</span> are not zero are called <strong>support vectors</strong>. In this case, we see that we have a surprisingly (perhaps) large number of support vectors for the model, considering the model can be described by two numbers; a slope and an intercept. We had the math up above, but I don’t know whether I emphasized it enough. Let’s see how we could predict a new value of the response given <span class="math inline">\(x = 1.5\)</span>. What we would do is compute</p>
<p><span class="math display">\[
\beta_0 + \sum_{i = 1}^n \alpha_i \langle x_[i,], x\rangle
\]</span>
where here the inner product is just the multiplication of the two numbers. In order to do this with the results from <code>ksvm</code>, we would need to extract the <span class="math inline">\(\alpha\)</span> values and the corresponding <span class="math inline">\(x\)</span> values, multiply them together with the new x value, which in this case is <span class="math inline">\(x = 1.5\)</span>.</p>
<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb687-1"><a href="non-linear-regression-models.html#cb687-1" tabindex="-1"></a>(<span class="sc">-</span><span class="fu">b</span>(mod) <span class="sc">+</span> <span class="fu">sum</span>(<span class="fu">alpha</span>(mod) <span class="sc">*</span> xs[<span class="fu">alphaindex</span>(mod)] <span class="sc">*</span> <span class="fl">1.5</span>)) </span></code></pre></div>
<pre><code>## [1] 3.999581</code></pre>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="non-linear-regression-models.html#cb689-1" tabindex="-1"></a><span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fl">1.5</span>)</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 3.999581</code></pre>
<p>In the above, I set <code>scaled = FALSE</code> to simplify this process, but in general we will not make that change. Let’s see what happens if we change <span class="math inline">\(\epsilon\)</span>.</p>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb691-1"><a href="non-linear-regression-models.html#cb691-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> kernlab<span class="sc">::</span><span class="fu">ksvm</span>(<span class="at">x =</span> xs, </span>
<span id="cb691-2"><a href="non-linear-regression-models.html#cb691-2" tabindex="-1"></a>                     <span class="at">y =</span> ys, </span>
<span id="cb691-3"><a href="non-linear-regression-models.html#cb691-3" tabindex="-1"></a>                     <span class="at">kernel =</span> <span class="st">&quot;vanilladot&quot;</span>, <span class="co">#linear regression</span></span>
<span id="cb691-4"><a href="non-linear-regression-models.html#cb691-4" tabindex="-1"></a>                     <span class="at">C =</span> <span class="dv">1</span>,</span>
<span id="cb691-5"><a href="non-linear-regression-models.html#cb691-5" tabindex="-1"></a>                     <span class="at">epsilon =</span> .<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##  Setting default kernel parameters</code></pre>
<div class="sourceCode" id="cb693"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb693-1"><a href="non-linear-regression-models.html#cb693-1" tabindex="-1"></a><span class="fu">alphaindex</span>(mod)</span></code></pre></div>
<pre><code>##  [1]  3  4 17 21 24 27 32 36 42 43 48 51 55 56 58 76 77 79 90 95 96 98</code></pre>
<p>We see that we get quite a bit fewer support vectors. Let’s see which observations are showing up as support vectors in this model.</p>
<div class="sourceCode" id="cb695"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb695-1"><a href="non-linear-regression-models.html#cb695-1" tabindex="-1"></a>df<span class="sc">$</span>support <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb695-2"><a href="non-linear-regression-models.html#cb695-2" tabindex="-1"></a>df<span class="sc">$</span>support[kernlab<span class="sc">::</span><span class="fu">alphaindex</span>(mod)] <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb695-3"><a href="non-linear-regression-models.html#cb695-3" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">abs</span>(<span class="fu">predict</span>(mod, <span class="at">newdata =</span> xs) <span class="sc">-</span> ys) <span class="sc">&gt;</span> .<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##  [1]  3  4 17 21 24 27 32 33 34 36 42 43 48 51 55 56 58 76 77 79 82 87 90 95 96
## [26] 98</code></pre>
<div class="sourceCode" id="cb697"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb697-1"><a href="non-linear-regression-models.html#cb697-1" tabindex="-1"></a>m <span class="ot">&lt;-</span> (<span class="fu">diff</span>(<span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))))[<span class="dv">1</span>,<span class="dv">1</span>]</span>
<span id="cb697-2"><a href="non-linear-regression-models.html#cb697-2" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="dv">0</span>)[<span class="dv">1</span>,<span class="dv">1</span>]</span>
<span id="cb697-3"><a href="non-linear-regression-models.html#cb697-3" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">color =</span> support)) <span class="sc">+</span> </span>
<span id="cb697-4"><a href="non-linear-regression-models.html#cb697-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb697-5"><a href="non-linear-regression-models.html#cb697-5" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> m, <span class="at">intercept =</span> b)</span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-14-1.png" width="672" />
Note that the support vectors for the model correspond to the observations which are further away than <span class="math inline">\(\epsilon = 0.5\)</span> from the line of best fit (as determined by SVR). Suggestion: repeat the above plot, adding in lines that are <span class="math inline">\(\pm \epsilon\)</span> of the line of best fit, and coloring the points that are associated with <span class="math inline">\(\alpha = C\)</span> (=1, in this case).</p>
<p>Now let’s look at another simulated example, but with multiple predictors.</p>
<div class="sourceCode" id="cb698"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb698-1"><a href="non-linear-regression-models.html#cb698-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">342020</span>)</span>
<span id="cb698-2"><a href="non-linear-regression-models.html#cb698-2" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(<span class="dv">9</span>), <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb698-3"><a href="non-linear-regression-models.html#cb698-3" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">t</span>(sigma) <span class="sc">%*%</span> sigma</span>
<span id="cb698-4"><a href="non-linear-regression-models.html#cb698-4" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">matrix</span>(MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="dv">50</span>, <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">Sigma =</span> sigma), <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb698-5"><a href="non-linear-regression-models.html#cb698-5" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(dd)</span>
<span id="cb698-6"><a href="non-linear-regression-models.html#cb698-6" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">response =</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> X1 <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> X2 <span class="sc">+</span> <span class="dv">4</span> <span class="sc">*</span> X3 <span class="sc">+</span> <span class="dv">8</span> <span class="sc">*</span> <span class="fu">rt</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb698-7"><a href="non-linear-regression-models.html#cb698-7" tabindex="-1"></a></span>
<span id="cb698-8"><a href="non-linear-regression-models.html#cb698-8" tabindex="-1"></a></span>
<span id="cb698-9"><a href="non-linear-regression-models.html#cb698-9" tabindex="-1"></a><span class="fu">library</span>(kernlab)</span>
<span id="cb698-10"><a href="non-linear-regression-models.html#cb698-10" tabindex="-1"></a>tuneGrid <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">C =</span> <span class="dv">2</span><span class="sc">^</span>((<span class="sc">-</span><span class="dv">4</span>)<span class="sc">:</span><span class="dv">4</span>))</span>
<span id="cb698-11"><a href="non-linear-regression-models.html#cb698-11" tabindex="-1"></a>caret<span class="sc">::</span><span class="fu">train</span>(response <span class="sc">~</span> ., </span>
<span id="cb698-12"><a href="non-linear-regression-models.html#cb698-12" tabindex="-1"></a>             <span class="at">data =</span> df,</span>
<span id="cb698-13"><a href="non-linear-regression-models.html#cb698-13" tabindex="-1"></a>             <span class="at">method =</span> <span class="st">&quot;svmLinear&quot;</span>,</span>
<span id="cb698-14"><a href="non-linear-regression-models.html#cb698-14" tabindex="-1"></a>             <span class="at">tuneGrid =</span> tuneGrid,</span>
<span id="cb698-15"><a href="non-linear-regression-models.html#cb698-15" tabindex="-1"></a>             <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;scale&quot;</span>)</span>
<span id="cb698-16"><a href="non-linear-regression-models.html#cb698-16" tabindex="-1"></a>              )</span></code></pre></div>
<pre><code>## Support Vector Machines with Linear Kernel 
## 
## 50 samples
##  3 predictor
## 
## Pre-processing: centered (3), scaled (3) 
## Resampling: Bootstrapped (25 reps) 
## Summary of sample sizes: 50, 50, 50, 50, 50, 50, ... 
## Resampling results across tuning parameters:
## 
##   C        RMSE       Rsquared   MAE     
##    0.0625  10.040449  0.6590511  7.161621
##    0.1250   9.984610  0.6601772  7.154352
##    0.2500   9.919240  0.6622761  7.204765
##    0.5000   9.927216  0.6610119  7.222924
##    1.0000   9.942027  0.6588586  7.265434
##    2.0000   9.959372  0.6563532  7.309928
##    4.0000   9.995107  0.6528606  7.358029
##    8.0000  10.032467  0.6486597  7.407044
##   16.0000  10.092680  0.6423048  7.471047
## 
## RMSE was used to select the optimal model using the smallest value.
## The final value used for the model was C = 0.25.</code></pre>
<p>Not much to choose from here; looks like the tuning parameter doesn’t matter much, but we’ll take it to be <span class="math inline">\(C = 0.25\)</span>, which is the smallest RMSE.</p>
<div class="sourceCode" id="cb700"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb700-1"><a href="non-linear-regression-models.html#cb700-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> kernlab<span class="sc">::</span><span class="fu">ksvm</span>(<span class="at">x =</span> dd, </span>
<span id="cb700-2"><a href="non-linear-regression-models.html#cb700-2" tabindex="-1"></a>                     <span class="at">y =</span> df<span class="sc">$</span>response, </span>
<span id="cb700-3"><a href="non-linear-regression-models.html#cb700-3" tabindex="-1"></a>                     <span class="at">kernel =</span> <span class="st">&quot;vanilladot&quot;</span>, </span>
<span id="cb700-4"><a href="non-linear-regression-models.html#cb700-4" tabindex="-1"></a>                     <span class="at">C =</span> <span class="fl">0.25</span>,</span>
<span id="cb700-5"><a href="non-linear-regression-models.html#cb700-5" tabindex="-1"></a>                     <span class="at">scaled =</span> <span class="cn">FALSE</span>) <span class="co">#for illustrative purposes</span></span></code></pre></div>
<pre><code>##  Setting default kernel parameters</code></pre>
<div class="sourceCode" id="cb702"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb702-1"><a href="non-linear-regression-models.html#cb702-1" tabindex="-1"></a>kernlab<span class="sc">::</span><span class="fu">alpha</span>(mod)</span></code></pre></div>
<pre><code>##  [1]  0.0190795 -0.2500000 -0.2500000  0.2500000  0.2500000 -0.2500000
##  [7]  0.2500000 -0.2500000  0.2500000 -0.2500000  0.2500000 -0.2500000
## [13] -0.2500000  0.2500000  0.2500000 -0.2500000  0.2500000 -0.2500000
## [19]  0.2500000 -0.2500000  0.2500000 -0.2500000 -0.2500000  0.2500000
## [25]  0.2500000 -0.2500000  0.2500000 -0.2500000  0.2500000 -0.2500000
## [31]  0.2500000 -0.2500000 -0.0190795  0.2500000  0.2500000 -0.2500000
## [37]  0.2500000 -0.2500000  0.2500000 -0.2500000  0.2500000 -0.2500000
## [43] -0.2500000  0.2500000  0.2500000 -0.2500000  0.2500000 -0.2500000
## [49]  0.2500000 -0.2500000</code></pre>
<div class="sourceCode" id="cb704"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb704-1"><a href="non-linear-regression-models.html#cb704-1" tabindex="-1"></a>kernlab<span class="sc">::</span><span class="fu">alphaindex</span>(mod)</span></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
## [26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50</code></pre>
<p>Let’s again see how to predict a new value. Recall that if the new predictors are <span class="math inline">\(x = (V1, V2, V3)\)</span>, then we compute the estimate of <span class="math inline">\(\hat y\)</span> via:</p>
<p><span class="math display">\[
\beta_0 + \sum_{i = 1}^n \alpha_i \langle x[i,], x\rangle
\]</span></p>
<div class="sourceCode" id="cb706"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb706-1"><a href="non-linear-regression-models.html#cb706-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)</span>
<span id="cb706-2"><a href="non-linear-regression-models.html#cb706-2" tabindex="-1"></a>ip <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y) {</span>
<span id="cb706-3"><a href="non-linear-regression-models.html#cb706-3" tabindex="-1"></a>  <span class="fu">sum</span>(x <span class="sc">*</span> y)</span>
<span id="cb706-4"><a href="non-linear-regression-models.html#cb706-4" tabindex="-1"></a>}</span>
<span id="cb706-5"><a href="non-linear-regression-models.html#cb706-5" tabindex="-1"></a>ips <span class="ot">&lt;-</span> <span class="fu">apply</span>(dd[<span class="fu">alphaindex</span>(mod),], <span class="dv">1</span>, <span class="cf">function</span>(y) <span class="fu">ip</span>(y,x))</span>
<span id="cb706-6"><a href="non-linear-regression-models.html#cb706-6" tabindex="-1"></a><span class="sc">-</span><span class="fu">b</span>(mod) <span class="sc">+</span> <span class="fu">sum</span>(<span class="fu">alpha</span>(mod) <span class="sc">*</span> ips)</span></code></pre></div>
<pre><code>## [1] 3.962655</code></pre>
<div class="sourceCode" id="cb708"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb708-1"><a href="non-linear-regression-models.html#cb708-1" tabindex="-1"></a><span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">nrow =</span> <span class="dv">1</span>))</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 3.962655</code></pre>
<p>Again, when doing problems that are not for illustrative purposes, we will typically use <code>scaled = TRUE</code>, which is the default.</p>
<div id="plot-twist" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> PLOT TWIST<a href="non-linear-regression-models.html#plot-twist" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s recast what we have done. We have data that is stored in a tall, skinny matrix <span class="math inline">\(X\)</span>, which has <span class="math inline">\(n\)</span> row and <span class="math inline">\(p\)</span> columns. We get predictions of responses given new predictors <span class="math inline">\(u = (u_1, \ldots, u_p)\)</span> by finding <span class="math inline">\(\{\alpha\}_{i = 1}^n\)</span> and <span class="math inline">\(\beta_0\)</span> and computing
<span class="math display">\[
\hat y = \beta_0 + \sum_{i = 1}^n \alpha_i \langle X[i,], u\rangle
\]</span>
So, the predictions depend <strong>only on the data through their inner products with the new predictors</strong>. Of course, the <span class="math inline">\(\alpha_i\)</span> and <span class="math inline">\(\beta_0\)</span> will depend on the training responses. So, we take the inner product of each row with the new vector <span class="math inline">\(u\)</span>, and use that as weights in our weighted sum prediction of <span class="math inline">\(\hat y\)</span>.</p>
<p>What if, instead, we used a different function of each row and the new vector <span class="math inline">\(u\)</span>? Formally, if we write <span class="math inline">\(K(x, y) = \langle x, y \rangle\)</span>, then
<span class="math display">\[
\hat y = \beta_0 + \sum_{i = 1}^n \alpha_i K(X[i,], u)
\]</span>
This is called a <em>kernel method</em> and the function <span class="math inline">\(K\)</span> is a <em>kernel</em>. We can define other functions <span class="math inline">\(K\)</span> that we can use as kernels in the above equation. A commonly used one is the <em>radial basis function</em> <span class="math inline">\(K(x, y) = e^{-\sigma\|x - y\|^2}\)</span>, which leads to predictions of the form
<span class="math display">\[
\hat y = \beta_0 + \sum_{i = 1}^n \alpha_i e^{-\sigma\|X[i,] - u\|^2}
\]</span>
Of course, we would have to re-evaluate the best way of choosing the <span class="math inline">\(\alpha_i\)</span> and <span class="math inline">\(\beta_0\)</span> in this context. The paramter <span class="math inline">\(\sigma\)</span> is a tuning parameter that can be chosen by cross-validation. Let’s think about what this would do. The data in the training set <span class="math inline">\(X\)</span> that is closest to the new data is given the most weight, with the weight accorded to data that is further away from <span class="math inline">\(u\)</span> decreasing exponentially with the distance from <span class="math inline">\(u\)</span>. So, predictions will be a weighted average of the distances to the new data, where the weights are determined in such a way as to make the predictions close to the training data responses. Now, let’s spice things up. Here is a new data set that is a <span class="math inline">\(\sin\)</span> curve.</p>
<div class="sourceCode" id="cb710"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb710-1"><a href="non-linear-regression-models.html#cb710-1" tabindex="-1"></a>sincurve <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">2</span> <span class="sc">*</span> pi))</span>
<span id="cb710-2"><a href="non-linear-regression-models.html#cb710-2" tabindex="-1"></a>sincurve<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">sin</span>(sincurve<span class="sc">$</span>x) <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, .<span class="dv">1</span>)</span>
<span id="cb710-3"><a href="non-linear-regression-models.html#cb710-3" tabindex="-1"></a><span class="fu">plot</span>(sincurve) </span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Now, let’s throw in some outliers.</p>
<div class="sourceCode" id="cb711"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb711-1"><a href="non-linear-regression-models.html#cb711-1" tabindex="-1"></a>sincurve <span class="ot">&lt;-</span> <span class="fu">rbind</span>(sincurve, <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">5</span>), <span class="at">y =</span> <span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb711-2"><a href="non-linear-regression-models.html#cb711-2" tabindex="-1"></a><span class="fu">plot</span>(sincurve)</span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<div class="sourceCode" id="cb712"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb712-1"><a href="non-linear-regression-models.html#cb712-1" tabindex="-1"></a>c_mod <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(y <span class="sc">~</span> x, </span>
<span id="cb712-2"><a href="non-linear-regression-models.html#cb712-2" tabindex="-1"></a>             <span class="at">data =</span> sincurve,</span>
<span id="cb712-3"><a href="non-linear-regression-models.html#cb712-3" tabindex="-1"></a>             <span class="at">method =</span> <span class="st">&quot;svmRadial&quot;</span></span>
<span id="cb712-4"><a href="non-linear-regression-models.html#cb712-4" tabindex="-1"></a>             )</span>
<span id="cb712-5"><a href="non-linear-regression-models.html#cb712-5" tabindex="-1"></a>c_mod<span class="sc">$</span>bestTune</span></code></pre></div>
<pre><code>##      sigma    C
## 1 13.25457 0.25</code></pre>
<div class="sourceCode" id="cb714"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb714-1"><a href="non-linear-regression-models.html#cb714-1" tabindex="-1"></a>svm_mod <span class="ot">&lt;-</span> <span class="fu">ksvm</span>(<span class="at">x =</span> sincurve<span class="sc">$</span>x, <span class="at">y =</span> sincurve<span class="sc">$</span>y,</span>
<span id="cb714-2"><a href="non-linear-regression-models.html#cb714-2" tabindex="-1"></a>                <span class="at">C =</span> c_mod<span class="sc">$</span>bestTune<span class="sc">$</span>C, </span>
<span id="cb714-3"><a href="non-linear-regression-models.html#cb714-3" tabindex="-1"></a>                <span class="at">epsilon =</span> .<span class="dv">1</span>, </span>
<span id="cb714-4"><a href="non-linear-regression-models.html#cb714-4" tabindex="-1"></a>                <span class="at">sigma =</span> c_mod<span class="sc">$</span>bestTune<span class="sc">$</span>sigma</span>
<span id="cb714-5"><a href="non-linear-regression-models.html#cb714-5" tabindex="-1"></a>                )</span>
<span id="cb714-6"><a href="non-linear-regression-models.html#cb714-6" tabindex="-1"></a>new_x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">2</span><span class="sc">*</span>pi, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb714-7"><a href="non-linear-regression-models.html#cb714-7" tabindex="-1"></a>new_y <span class="ot">&lt;-</span> <span class="fu">predict</span>(svm_mod, <span class="at">newdata =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">2</span> <span class="sc">*</span> pi, <span class="at">length.out =</span> <span class="dv">100</span>))</span>
<span id="cb714-8"><a href="non-linear-regression-models.html#cb714-8" tabindex="-1"></a><span class="fu">plot</span>(sincurve)</span>
<span id="cb714-9"><a href="non-linear-regression-models.html#cb714-9" tabindex="-1"></a><span class="fu">points</span>(new_x, new_y, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span>
<span id="cb714-10"><a href="non-linear-regression-models.html#cb714-10" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">sin</span>(x), <span class="at">add =</span> T, <span class="at">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>This technique isn’t perfect, but that it looks like a pretty good match for this particular example, doesn’t it!</p>
</div>
</div>
<div id="k-nearest-neighbors" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> K Nearest Neighbors<a href="non-linear-regression-models.html#k-nearest-neighbors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the version of support vector regression with the radial basis function presented above, we estimated the response by taking a weighted sum of the responses in the training data. The weight was chosen so that observations which are close to the new data are weighted much more heavily than observations that are far away from the new data. <span class="math inline">\(K\)</span>-Nearest Neighbors (KNN) is another method of doing a similar thing.</p>
<p>The basic version is that, when we are given new data that we want to predict on, we choose the <span class="math inline">\(K\)</span> observations that are <strong>closest</strong> to the new data, and compute the mean of the corresponding responses. Let’s look at the sine curve example from the previous section.</p>
<div class="sourceCode" id="cb715"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb715-1"><a href="non-linear-regression-models.html#cb715-1" tabindex="-1"></a><span class="fu">plot</span>(sincurve)</span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Suppose that we want to predict the value of the response when <span class="math inline">\(x = 3\)</span> using KNN with <span class="math inline">\(K = 2\)</span>. The first thing that we need to do is find the two observations that are closest to <span class="math inline">\(x = 3\)</span>. To do that, we will compute the distance between <span class="math inline">\(x = 3\)</span> and each observation.</p>
<div class="sourceCode" id="cb716"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb716-1"><a href="non-linear-regression-models.html#cb716-1" tabindex="-1"></a>distances <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="dv">3</span> <span class="sc">-</span> sincurve<span class="sc">$</span>x)</span></code></pre></div>
<p>Now, we need to find the two that have the smallest distances to <span class="math inline">\(x = 3\)</span>. There are lots of ways to do this. Let’s append the distances to the sincurve data frame, and use <code>arrange</code>.</p>
<div class="sourceCode" id="cb717"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb717-1"><a href="non-linear-regression-models.html#cb717-1" tabindex="-1"></a>sincurve <span class="ot">&lt;-</span> <span class="fu">mutate</span>(sincurve, <span class="at">d3 =</span> <span class="fu">abs</span>( <span class="dv">3</span> <span class="sc">-</span> x))</span>
<span id="cb717-2"><a href="non-linear-regression-models.html#cb717-2" tabindex="-1"></a><span class="fu">arrange</span>(sincurve, d3) <span class="sc">%&gt;%</span> </span>
<span id="cb717-3"><a href="non-linear-regression-models.html#cb717-3" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">2</span>, <span class="at">wt =</span> <span class="sc">-</span>d3) </span></code></pre></div>
<pre><code>##          x          y        d3
## 1 2.945620  0.3762654 0.0543801
## 2 3.111168 -0.1364121 0.1111682</code></pre>
<p>We see that the two observations that are closest to <span class="math inline">\(x = 3\)</span> are when <span class="math inline">\(x = 2.95\)</span> and when <span class="math inline">\(x = 3.11\)</span>. Our <strong>prediction</strong> for <span class="math inline">\(y\)</span> would then just be the average of the two <span class="math inline">\(y\)</span> values, 0.12.</p>
<p>Let’s see what the predictions would look like for a variety of <span class="math inline">\(x\)</span> values.</p>
<div class="sourceCode" id="cb719"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb719-1"><a href="non-linear-regression-models.html#cb719-1" tabindex="-1"></a>new_xs <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">2</span> <span class="sc">*</span> pi, <span class="at">length.out =</span> <span class="dv">500</span>)</span>
<span id="cb719-2"><a href="non-linear-regression-models.html#cb719-2" tabindex="-1"></a>new_ys <span class="ot">&lt;-</span> <span class="fu">sapply</span>(new_xs, <span class="cf">function</span>(z) {</span>
<span id="cb719-3"><a href="non-linear-regression-models.html#cb719-3" tabindex="-1"></a>  sincurve <span class="ot">&lt;-</span> <span class="fu">mutate</span>(sincurve, <span class="at">d3 =</span> <span class="fu">abs</span>(z <span class="sc">-</span> x))</span>
<span id="cb719-4"><a href="non-linear-regression-models.html#cb719-4" tabindex="-1"></a>  <span class="fu">arrange</span>(sincurve, d3) <span class="sc">%&gt;%</span> </span>
<span id="cb719-5"><a href="non-linear-regression-models.html#cb719-5" tabindex="-1"></a>    <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">2</span>, <span class="at">wt =</span> <span class="sc">-</span>d3) <span class="sc">%&gt;%</span> </span>
<span id="cb719-6"><a href="non-linear-regression-models.html#cb719-6" tabindex="-1"></a>    <span class="fu">pull</span>(y) <span class="sc">%&gt;%</span> </span>
<span id="cb719-7"><a href="non-linear-regression-models.html#cb719-7" tabindex="-1"></a>    <span class="fu">mean</span>()</span>
<span id="cb719-8"><a href="non-linear-regression-models.html#cb719-8" tabindex="-1"></a>})</span>
<span id="cb719-9"><a href="non-linear-regression-models.html#cb719-9" tabindex="-1"></a><span class="fu">plot</span>(sincurve<span class="sc">$</span>x, sincurve<span class="sc">$</span>y)</span>
<span id="cb719-10"><a href="non-linear-regression-models.html#cb719-10" tabindex="-1"></a><span class="fu">lines</span>(new_xs, new_ys, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="06-nonlinear-regression_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>We see that the base KNN method does not work well with outliers. We also see that the predictions are <strong>piecewise constant</strong>, and it also seems to be <strong>overfitting</strong>. We can use the <code>median</code> of the responses rather than the mean in order to help the outliers somewhat. We can also do cross-validation on <span class="math inline">\(K\)</span>, the number of nearest neighbors that we are choosing.</p>
<div class="exercise">
<span class="divhead-definition exercise-before"> 7.1</span>
<p><span id="exr:knn-median" class="exercise"><strong>Exercise 7.1  </strong></span>Consider the sine curve data created above. Do KNN estimation of the response using the <strong>median</strong> of the <strong>5</strong> nearest neighbors, and provide a plot of the predictions.</p>
</div>
<p>When we have more than one predictor, it becomes necessary to make a choice for what <strong>distance</strong> function we are going to use. A couple of common ones are the <span class="math inline">\(\ell_2\)</span> distance and the <span class="math inline">\(\ell_1\)</span> distance, given by</p>
<p><span class="math display">\[
\sqrt{\sum_{i  = 1}^P (x_i - y_i)^2}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\sum_{i = 1}^P |x_i - y_i|
\]</span>
respectively. We will stick with the <span class="math inline">\(\ell_2\)</span> distance in this section.</p>
<p>Let’s see how to do KNN prediction and cross validation using packages. The <code>caret</code> package has a function <code>knnreg</code> that does KNN regression. Note that we get the same answer below as we got when doing it above by hand.</p>
<div class="sourceCode" id="cb720"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb720-1"><a href="non-linear-regression-models.html#cb720-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">knnreg</span>(y <span class="sc">~</span> x, <span class="at">data =</span> sincurve, <span class="at">k =</span> <span class="dv">2</span>)</span>
<span id="cb720-2"><a href="non-linear-regression-models.html#cb720-2" tabindex="-1"></a><span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="dv">3</span>))</span></code></pre></div>
<pre><code>## [1] 0.1199267</code></pre>
<p>In order to do cross validation, we can use the <code>train</code> function in <code>caret</code> as below. <strong>Note</strong>: since the predictions we make are means of the actual responses, we probably want to use folded cross validation, rather than the default which is bootstrapping.</p>
<div class="sourceCode" id="cb722"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb722-1"><a href="non-linear-regression-models.html#cb722-1" tabindex="-1"></a>tune_k <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">k =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)</span>
<span id="cb722-2"><a href="non-linear-regression-models.html#cb722-2" tabindex="-1"></a>knn_train <span class="ot">&lt;-</span> <span class="fu">train</span>(y <span class="sc">~</span> x, </span>
<span id="cb722-3"><a href="non-linear-regression-models.html#cb722-3" tabindex="-1"></a>                   <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">&quot;repeatedcv&quot;</span>, <span class="at">repeats =</span> <span class="dv">5</span>),</span>
<span id="cb722-4"><a href="non-linear-regression-models.html#cb722-4" tabindex="-1"></a>      <span class="at">data =</span> sincurve, </span>
<span id="cb722-5"><a href="non-linear-regression-models.html#cb722-5" tabindex="-1"></a>      <span class="at">method =</span> <span class="st">&quot;knn&quot;</span>,</span>
<span id="cb722-6"><a href="non-linear-regression-models.html#cb722-6" tabindex="-1"></a>      <span class="at">tuneGrid =</span> tune_k)</span>
<span id="cb722-7"><a href="non-linear-regression-models.html#cb722-7" tabindex="-1"></a>knn_train<span class="sc">$</span>results</span></code></pre></div>
<pre><code>##     k      RMSE  Rsquared       MAE    RMSESD RsquaredSD      MAESD
## 1   1 0.3838788 0.7170167 0.2276043 0.2586968  0.2886250 0.12792148
## 2   2 0.3362237 0.7800469 0.1970388 0.2058597  0.2117669 0.10299997
## 3   3 0.3399026 0.7868182 0.2072089 0.1886640  0.2009687 0.09307557
## 4   4 0.3290409 0.8042437 0.1979214 0.1770419  0.1861005 0.08898719
## 5   5 0.2979963 0.8408409 0.1869965 0.1546552  0.1519875 0.07981688
## 6   6 0.3047243 0.8363890 0.1903598 0.1464807  0.1466539 0.07870518
## 7   7 0.3035879 0.8357667 0.1895394 0.1475990  0.1464507 0.08000583
## 8   8 0.3026958 0.8352688 0.1899724 0.1504518  0.1518960 0.08243188
## 9   9 0.2987045 0.8387690 0.1889080 0.1514698  0.1510139 0.08272786
## 10 10 0.2992286 0.8369184 0.1877063 0.1562651  0.1569141 0.08484843
## 11 11 0.3001848 0.8354555 0.1863867 0.1600516  0.1582971 0.08715876
## 12 12 0.3009612 0.8336326 0.1857216 0.1634831  0.1640991 0.08890183
## 13 13 0.2993238 0.8316823 0.1842788 0.1710689  0.1727768 0.09450845
## 14 14 0.2994149 0.8297009 0.1841082 0.1763259  0.1759472 0.09761913
## 15 15 0.3013161 0.8264298 0.1867235 0.1799269  0.1806064 0.10120519
## 16 16 0.3051031 0.8215116 0.1897412 0.1833183  0.1847234 0.10415262
## 17 17 0.3122916 0.8155246 0.1930653 0.1837068  0.1887951 0.10416938
## 18 18 0.3160359 0.8114759 0.1965241 0.1868663  0.1934326 0.10518028
## 19 19 0.3191308 0.8078853 0.1985402 0.1896941  0.1964903 0.10439126
## 20 20 0.3226328 0.8044391 0.1996434 0.1928524  0.1999880 0.10488994</code></pre>
<p>Next, we find the smallest RMSE and choose the simplest model that is within one sd of the smallest RMSE.</p>
<div class="sourceCode" id="cb724"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb724-1"><a href="non-linear-regression-models.html#cb724-1" tabindex="-1"></a>best_k <span class="ot">&lt;-</span> <span class="fu">which.min</span>(knn_train<span class="sc">$</span>results<span class="sc">$</span>RMSE)</span>
<span id="cb724-2"><a href="non-linear-regression-models.html#cb724-2" tabindex="-1"></a>one_sd <span class="ot">&lt;-</span> knn_train<span class="sc">$</span>results<span class="sc">$</span>RMSE[best_k] <span class="sc">+</span> knn_train<span class="sc">$</span>results<span class="sc">$</span>RMSESD[best_k]</span>
<span id="cb724-3"><a href="non-linear-regression-models.html#cb724-3" tabindex="-1"></a><span class="fu">filter</span>(knn_train<span class="sc">$</span>results, RMSE <span class="sc">&lt;</span> one_sd) <span class="sc">%&gt;%</span> </span>
<span id="cb724-4"><a href="non-linear-regression-models.html#cb724-4" tabindex="-1"></a>  <span class="fu">pull</span>(k)</span></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20</code></pre>
<p>We would choose k = 1 based on the one sd rule, or we could also choose the minimum RMSE, which was 5.</p>
<p>Finally, we offer some practical advice. We recommend <strong>centering</strong> and <strong>scaling</strong> your predictors before using KNN. Including predictors that have little predictive value for the response can cause KNN to have poor results, as just by chance the “wrong” observations are going to be close to the new data.</p>
<div class="exercise">
<span class="divhead-definition exercise-before"> 7.2</span>
<p><span id="exr:larger-example" class="exercise"><strong>Exercise 7.2  </strong></span>Consider the tecator data set that is contained in the <code>caret</code> library. Recall that you can access this data via <code>data(tecator)</code>. Model the first response variable in <code>endpoints</code> on the <code>absorp</code> data using knn3</p>
<ol style="list-style-type: decimal">
<li>How many neighbors give the lowest RMSE?</li>
<li>How many neighbors is the simplest model that is within one sd of the lowest RMSE?</li>
<li>Use your model to predict the response for the <strong>first</strong> observation in the data frame</li>
<li>What is the error when you predict the response for the first observation in the data set?</li>
</ol>
</div>
</div>
<div id="exercises-4" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Exercises<a href="non-linear-regression-models.html#exercises-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Exercise <a href="non-linear-regression-models.html#exr:knn-median">7.1</a></p></li>
<li><p>Exercise <a href="non-linear-regression-models.html#exr:larger-example">7.2</a></p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="variable-selection.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tree-regression-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
