<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 The retrofit study | Applied Regression with R</title>
  <meta name="description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 The retrofit study | Applied Regression with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 The retrofit study | Applied Regression with R" />
  
  <meta name="twitter:description" content="Applied Regression With R by Darrin Speegle. This book is based on the notes for my Applied Regression course taught at Saint Louis University. We cover the basics of descriptive modeling, predictive modeling and causal inference." />
  

<meta name="author" content="Darrin Speegle" />


<meta name="date" content="2026-04-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
<link rel="prev" href="causal-inference.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Regression with R<br />&nbsp; Notes From STAT 4870/5087</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="classicaltheory.html"><a href="classicaltheory.html"><i class="fa fa-check"></i><b>2</b> Classical Theory of Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="classicaltheory.html"><a href="classicaltheory.html#review"><i class="fa fa-check"></i><b>2.1</b> Review</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-means-and-standard-deviations"><i class="fa fa-check"></i><b>2.1.1</b> Estimating Means and standard deviations</a></li>
<li class="chapter" data-level="2.1.2" data-path="classicaltheory.html"><a href="classicaltheory.html#estimating-the-density-of-an-rv"><i class="fa fa-check"></i><b>2.1.2</b> Estimating the density of an rv</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-overview"><i class="fa fa-check"></i><b>2.2</b> Linear Regression Overview</a></li>
<li class="chapter" data-level="2.3" data-path="classicaltheory.html"><a href="classicaltheory.html#linear-regression-with-no-intercept"><i class="fa fa-check"></i><b>2.3</b> Linear Regression with no intercept</a></li>
<li class="chapter" data-level="2.4" data-path="classicaltheory.html"><a href="classicaltheory.html#the-full-model"><i class="fa fa-check"></i><b>2.4</b> The full model</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="classicaltheory.html"><a href="classicaltheory.html#hypothesis-test-interlude"><i class="fa fa-check"></i><b>2.4.1</b> Hypothesis Test Interlude</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="classicaltheory.html"><a href="classicaltheory.html#using-different-loss-functions"><i class="fa fa-check"></i><b>2.5</b> Using different loss functions</a></li>
<li class="chapter" data-level="" data-path="classicaltheory.html"><a href="classicaltheory.html#vignette-a-dplyr-primer"><i class="fa fa-check"></i>Vignette: A dplyr primer</a></li>
<li class="chapter" data-level="2.6" data-path="classicaltheory.html"><a href="classicaltheory.html#exercises"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#anova"><i class="fa fa-check"></i><b>3.0.1</b> Aside on multiple R squared and ANOVA</a></li>
<li class="chapter" data-level="3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-variable-selection-anova"><i class="fa fa-check"></i><b>3.1</b> More Variable Selection: ANOVA</a></li>
<li class="chapter" data-level="3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#predictions"><i class="fa fa-check"></i><b>3.2</b> Predictions</a></li>
<li class="chapter" data-level="3.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#using-aic"><i class="fa fa-check"></i><b>3.3</b> Using AIC</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#likelihood-functions"><i class="fa fa-check"></i><b>3.3.1</b> Likelihood functions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercises-1"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html"><i class="fa fa-check"></i><b>4</b> Intro to Predictive Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#comparingtwomodels"><i class="fa fa-check"></i><b>4.1</b> Comparing Two Models</a></li>
<li class="chapter" data-level="4.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#a-brief-return-to-inference"><i class="fa fa-check"></i><b>4.2</b> A Brief Return to Inference</a></li>
<li class="chapter" data-level="4.3" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#simulations-of-expected-mse"><i class="fa fa-check"></i><b>4.3</b> Simulations of Expected MSE</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-and-bias-variance-tradeoff"><i class="fa fa-check"></i><b>4.3.1</b> Estimating MSE and Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#estimating-mse-for-new-predictors-uniformly-sampled"><i class="fa fa-check"></i><b>4.3.2</b> Estimating MSE for new predictors uniformly sampled</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>4.4</b> Bias Variance Trade-off</a></li>
<li class="chapter" data-level="4.5" data-path="intro-to-predictive-modeling.html"><a href="intro-to-predictive-modeling.html#exercises-2"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html"><i class="fa fa-check"></i><b>5</b> Regression Predictive Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#preprocessing"><i class="fa fa-check"></i><b>5.1</b> Preprocessing</a></li>
<li class="chapter" data-level="5.2" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#missing-data"><i class="fa fa-check"></i><b>5.2</b> Missing Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#predicting-when-a-level-is-missing-from-the-training-set"><i class="fa fa-check"></i><b>5.2.1</b> Predicting when a level is missing from the training set</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#correlated-predictors"><i class="fa fa-check"></i><b>5.3</b> Correlated Predictors</a></li>
<li class="chapter" data-level="5.4" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#aside-on-pca"><i class="fa fa-check"></i><b>5.4</b> Aside on PCA</a></li>
<li class="chapter" data-level="5.5" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#johnson-lindenstrauss-dimension-reduction"><i class="fa fa-check"></i><b>5.5</b> Johnson-Lindenstrauss Dimension Reduction</a></li>
<li class="chapter" data-level="5.6" data-path="regression-predictive-models.html"><a href="regression-predictive-models.html#exercises-3"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variable-selection.html"><a href="variable-selection.html"><i class="fa fa-check"></i><b>6</b> Variable Selection</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variable-selection.html"><a href="variable-selection.html#partial-least-squares"><i class="fa fa-check"></i><b>6.1</b> Partial Least Squares</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="variable-selection.html"><a href="variable-selection.html#optional-pls-stuff"><i class="fa fa-check"></i><b>6.1.1</b> Optional PLS Stuff</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variable-selection.html"><a href="variable-selection.html#ridgelasso-and-elastic-net"><i class="fa fa-check"></i><b>6.2</b> Ridge/Lasso and Elastic Net</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="variable-selection.html"><a href="variable-selection.html#ridge-regression"><i class="fa fa-check"></i><b>6.2.1</b> Ridge Regression</a></li>
<li class="chapter" data-level="6.2.2" data-path="variable-selection.html"><a href="variable-selection.html#lasso"><i class="fa fa-check"></i><b>6.2.2</b> LASSO</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variable-selection.html"><a href="variable-selection.html#step-aic"><i class="fa fa-check"></i><b>6.3</b> Step AIC</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="variable-selection.html"><a href="variable-selection.html#doing-lgocv-with-preprocessing"><i class="fa fa-check"></i><b>6.3.1</b> Doing LGOCV with preprocessing</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variable-selection.html"><a href="variable-selection.html#interactions"><i class="fa fa-check"></i><b>6.4</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>7</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#logistic-regression"><i class="fa fa-check"></i><b>7.1</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#malaria-example-intro"><i class="fa fa-check"></i><b>7.1.1</b> Malaria Example (Intro)</a></li>
<li class="chapter" data-level="7.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#the-model-theory"><i class="fa fa-check"></i><b>7.1.2</b> The model (theory)</a></li>
<li class="chapter" data-level="7.1.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#estimating-parameters-using-mle"><i class="fa fa-check"></i><b>7.1.3</b> Estimating parameters using MLE</a></li>
<li class="chapter" data-level="7.1.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#estimating-parameters-via-loss-function"><i class="fa fa-check"></i><b>7.1.4</b> Estimating parameters via loss function</a></li>
<li class="chapter" data-level="7.1.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#interpreting-summary"><i class="fa fa-check"></i><b>7.1.5</b> Interpreting summary</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#mixed-effects-logistic-regression"><i class="fa fa-check"></i><b>7.2</b> Mixed Effects Logistic Regression</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#nested-random-effects"><i class="fa fa-check"></i><b>7.2.1</b> Nested random effects</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#count-regression"><i class="fa fa-check"></i><b>7.3</b> Count Regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#mixed-effects-model"><i class="fa fa-check"></i><b>7.3.1</b> Mixed Effects Model</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#offsets"><i class="fa fa-check"></i><b>7.4</b> Offsets</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="lecture-notes.html"><a href="lecture-notes.html"><i class="fa fa-check"></i><b>8</b> Lecture Notes</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lecture-notes.html"><a href="lecture-notes.html#january-27"><i class="fa fa-check"></i><b>8.1</b> January 27</a></li>
<li class="chapter" data-level="8.2" data-path="lecture-notes.html"><a href="lecture-notes.html#february-3"><i class="fa fa-check"></i><b>8.2</b> February 3</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="lecture-notes.html"><a href="lecture-notes.html#simulating-data"><i class="fa fa-check"></i><b>8.2.1</b> Simulating Data</a></li>
<li class="chapter" data-level="8.2.2" data-path="lecture-notes.html"><a href="lecture-notes.html#building-models"><i class="fa fa-check"></i><b>8.2.2</b> Building Models</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="lecture-notes.html"><a href="lecture-notes.html#february-5"><i class="fa fa-check"></i><b>8.3</b> February 5</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="lecture-notes.html"><a href="lecture-notes.html#using-broomaugment"><i class="fa fa-check"></i><b>8.3.1</b> Using <code>broom::augment</code></a></li>
<li class="chapter" data-level="8.3.2" data-path="lecture-notes.html"><a href="lecture-notes.html#multicollinearity"><i class="fa fa-check"></i><b>8.3.2</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="lecture-notes.html"><a href="lecture-notes.html#february-10"><i class="fa fa-check"></i><b>8.4</b> February 10</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="lecture-notes.html"><a href="lecture-notes.html#anova-models"><i class="fa fa-check"></i><b>8.4.1</b> ANOVA Models</a></li>
<li class="chapter" data-level="8.4.2" data-path="lecture-notes.html"><a href="lecture-notes.html#penguins"><i class="fa fa-check"></i><b>8.4.2</b> Penguins</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="lecture-notes.html"><a href="lecture-notes.html#february-12"><i class="fa fa-check"></i><b>8.5</b> February 12</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="lecture-notes.html"><a href="lecture-notes.html#an-example"><i class="fa fa-check"></i><b>8.5.1</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="lecture-notes.html"><a href="lecture-notes.html#february-17"><i class="fa fa-check"></i><b>8.6</b> February 17</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-speaker-and-sentence-effects"><i class="fa fa-check"></i><b>8.6.1</b> Adding random speaker and sentence effects</a></li>
<li class="chapter" data-level="8.6.2" data-path="lecture-notes.html"><a href="lecture-notes.html#random-intercepts-with-continuous-predictor"><i class="fa fa-check"></i><b>8.6.2</b> Random intercepts with continuous predictor</a></li>
<li class="chapter" data-level="8.6.3" data-path="lecture-notes.html"><a href="lecture-notes.html#adding-random-slopes"><i class="fa fa-check"></i><b>8.6.3</b> Adding random slopes</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="lecture-notes.html"><a href="lecture-notes.html#february-19"><i class="fa fa-check"></i><b>8.7</b> February 19</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="lecture-notes.html"><a href="lecture-notes.html#random-slopes"><i class="fa fa-check"></i><b>8.7.1</b> Random Slopes</a></li>
<li class="chapter" data-level="8.7.2" data-path="lecture-notes.html"><a href="lecture-notes.html#comparing-models"><i class="fa fa-check"></i><b>8.7.2</b> Comparing models</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="lecture-notes.html"><a href="lecture-notes.html#february-24"><i class="fa fa-check"></i><b>8.8</b> February 24</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="lecture-notes.html"><a href="lecture-notes.html#beethoven-tempo-example"><i class="fa fa-check"></i><b>8.8.1</b> Beethoven Tempo Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html"><i class="fa fa-check"></i><b>9</b> Maximum Likelihood Estimation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#mle-for-mixed-models"><i class="fa fa-check"></i><b>9.1</b> MLE for mixed models</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-z-tz-do"><i class="fa fa-check"></i><b>9.1.1</b> What does <code>Z %*% t(Z)</code> do?</a></li>
<li class="chapter" data-level="9.1.2" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-multiplying-by-tau2-do"><i class="fa fa-check"></i><b>9.1.2</b> What does multiplying by <code>tau2</code> do?</a></li>
<li class="chapter" data-level="9.1.3" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-sigma2-diagn-do"><i class="fa fa-check"></i><b>9.1.3</b> What does <code>sigma2 * diag(N)</code> do?</a></li>
<li class="chapter" data-level="9.1.4" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#what-does-the-final-matrix-represent"><i class="fa fa-check"></i><b>9.1.4</b> What does the final matrix represent?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="missing-data-1.html"><a href="missing-data-1.html"><i class="fa fa-check"></i><b>10</b> Missing Data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="missing-data-1.html"><a href="missing-data-1.html#technical-details"><i class="fa fa-check"></i><b>10.1</b> Technical Details</a></li>
<li class="chapter" data-level="10.2" data-path="missing-data-1.html"><a href="missing-data-1.html#diagnostics"><i class="fa fa-check"></i><b>10.2</b> Diagnostics</a></li>
<li class="chapter" data-level="10.3" data-path="missing-data-1.html"><a href="missing-data-1.html#pooling"><i class="fa fa-check"></i><b>10.3</b> Pooling</a></li>
<li class="chapter" data-level="10.4" data-path="missing-data-1.html"><a href="missing-data-1.html#simulations"><i class="fa fa-check"></i><b>10.4</b> Simulations</a></li>
<li class="chapter" data-level="10.5" data-path="missing-data-1.html"><a href="missing-data-1.html#sensitivity-analysis"><i class="fa fa-check"></i><b>10.5</b> Sensitivity Analysis</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="causal-inference.html"><a href="causal-inference.html"><i class="fa fa-check"></i><b>11</b> Causal Inference</a>
<ul>
<li class="chapter" data-level="11.0.1" data-path="causal-inference.html"><a href="causal-inference.html#baseline-differences-between-the-groups"><i class="fa fa-check"></i><b>11.0.1</b> Baseline Differences Between the Groups</a></li>
<li class="chapter" data-level="11.0.2" data-path="causal-inference.html"><a href="causal-inference.html#summary"><i class="fa fa-check"></i><b>11.0.2</b> Summary</a></li>
<li class="chapter" data-level="11.1" data-path="causal-inference.html"><a href="causal-inference.html#identification-assumptions-for-causal-adjustment"><i class="fa fa-check"></i><b>11.1</b> Identification Assumptions for Causal Adjustment</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="causal-inference.html"><a href="causal-inference.html#assumptions-for-causal-adjustment"><i class="fa fa-check"></i><b>11.1.1</b> Assumptions for Causal Adjustment</a></li>
<li class="chapter" data-level="11.1.2" data-path="causal-inference.html"><a href="causal-inference.html#the-lalonde-data-revisited"><i class="fa fa-check"></i><b>11.1.2</b> The Lalonde Data Revisited</a></li>
<li class="chapter" data-level="11.1.3" data-path="causal-inference.html"><a href="causal-inference.html#vocabulary-and-an-example"><i class="fa fa-check"></i><b>11.1.3</b> Vocabulary and an Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html"><i class="fa fa-check"></i><b>12</b> The <code>retrofit</code> study</a>
<ul>
<li class="chapter" data-level="12.0.1" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#worksheet"><i class="fa fa-check"></i><b>12.0.1</b> Worksheet</a></li>
<li class="chapter" data-level="12.0.2" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#solutions"><i class="fa fa-check"></i><b>12.0.2</b> Solutions</a></li>
<li class="chapter" data-level="12.1" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#collid3rs"><i class="fa fa-check"></i><b>12.1</b> Collid3rs</a></li>
<li class="chapter" data-level="12.2" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#post-treatment-variables-do-not-always-fit-neatly-into-one-box"><i class="fa fa-check"></i><b>12.2</b> Post-treatment variables do not always fit neatly into one box</a></li>
<li class="chapter" data-level="12.3" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#variables-measured-after-treatment-are-not-automatically-bad-controls"><i class="fa fa-check"></i><b>12.3</b> Variables measured after treatment are not automatically bad controls</a></li>
<li class="chapter" data-level="12.4" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#why-insulation_added-and-thermostat_setting_2025-play-different-roles"><i class="fa fa-check"></i><b>12.4</b> Why <code>insulation_added</code> and <code>thermostat_setting_2025</code> play different roles</a></li>
<li class="chapter" data-level="12.5" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#why-finalist_pool-or-special_review-can-be-problematic-in-more-than-one-way"><i class="fa fa-check"></i><b>12.5</b> Why <code>finalist_pool</code> or <code>special_review</code> can be problematic in more than one way</a></li>
<li class="chapter" data-level="12.6" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#a-compact-summary"><i class="fa fa-check"></i><b>12.6</b> A compact summary</a></li>
<li class="chapter" data-level="12.7" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#directed-acyclic-graphs-dags"><i class="fa fa-check"></i><b>12.7</b> Directed Acyclic Graphs (DAGs)</a></li>
<li class="chapter" data-level="12.8" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#matching"><i class="fa fa-check"></i><b>12.8</b> Matching</a></li>
<li class="chapter" data-level="12.9" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#propensity-scores-and-matching-in-the-lalonde-data"><i class="fa fa-check"></i><b>12.9</b> Propensity scores and matching in the Lalonde data</a></li>
<li class="chapter" data-level="12.10" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#bernoulli-outcomes"><i class="fa fa-check"></i><b>12.10</b> Bernoulli outcomes</a>
<ul>
<li class="chapter" data-level="12.10.1" data-path="the-retrofit-study.html"><a href="the-retrofit-study.html#rhc"><i class="fa fa-check"></i><b>12.10.1</b> <code>rhc</code></a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Regression with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-retrofit-study" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Chapter 12</span> The <code>retrofit</code> study<a href="the-retrofit-study.html#the-retrofit-study" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The <code>retrofit</code> study is a hypothetical observational study of a city-run home weatherization program. The city offers subsidies for attic and wall insulation, air sealing, duct repair, and minor furnace improvements to households with high energy burdens. Some households apply directly, while others are identified through neighborhood outreach or energy audits. Some households receive the retrofit before the winter heating season, and some do not. There is no random assignment. Participation depends on a mixture of household choice, city targeting, contractor availability, and administrative prioritization.</p>
<p>The treatment variable is <code>retrofit</code>, equal to 1 if the household received the weatherization package before winter 2024–25 and 0 otherwise. The outcome is <code>gas_use_2025</code>, the household’s total natural-gas use during winter 2024–25. Lower values are better. Because treatment is not randomized, treated and untreated households are likely to differ in many ways before treatment begins. Some live in older homes, some have larger families, some have higher energy burdens, and some have homes that are much less energy efficient than others. Those pre-treatment differences are exactly what make causal adjustment necessary.</p>
<p>It is useful to imagine what <code>?retrofit</code> might look like in R.</p>
<pre class="text"><code>retrofit {causalexamples} R Documentation

Home Weatherization Program Study

Description
Observational study of a city-run home weatherization program. The dataset follows
5,000 owner-occupied households over two winters. Treated households received a
subsidized weatherization package before winter 2024--25. The main outcome is
natural-gas use during winter 2024--25. The data were assembled from utility bills,
program records, property records, and a follow-up survey.

Usage
retrofit

Format
A data frame with 5000 rows and 27 variables:

retrofit
    Treatment indicator equal to 1 if the household received the retrofit package
    before winter 2024--25 and 0 otherwise.

gas_use_2025
    Outcome: total natural-gas use during winter 2024--25, measured in therms.

gas_use_2024
    Baseline variable measured before treatment: total natural-gas use during
    winter 2023--24, measured in therms.

electric_use_2024
    Baseline variable measured before treatment: total electricity use during
    calendar year 2024 before retrofit work began, measured in kWh.

sqft
    Baseline variable measured before treatment: interior square footage of the
    home from property records.

home_age
    Baseline variable measured before treatment: age of the home in years at the
    start of winter 2024--25.

building_type
    Baseline variable measured before treatment: detached, duplex, rowhouse, or
    small multifamily.

insulation_baseline
    Baseline variable measured before treatment: insulation score from the
    pre-treatment energy audit.

furnace_age
    Baseline variable measured before treatment: age of the primary heating system
    in years at intake.

income
    Baseline variable measured before treatment: household income in thousands of
    dollars, recorded at intake.

arrears_balance
    Baseline variable measured before treatment: amount owed on utility bills at
    intake or referral.

credit_score
    Baseline variable measured before treatment: household credit-score category
    at intake, before any retrofit work begins.

owner_occupied
    Baseline variable measured before treatment: indicator for owner occupancy at
    intake.

years_in_home
    Baseline variable measured before treatment: number of years the household had
    lived in the home at intake.

occupants
    Baseline variable measured before treatment: number of people living in the
    home at intake.

children
    Baseline variable measured before treatment: number of children in the
    household at intake.

elderly_resident
    Baseline variable measured before treatment: indicator for whether at least
    one resident was age 65 or older at intake.

work_from_home_days
    Baseline variable measured before treatment: average number of days per week
    at least one adult worked from home at intake.

energy_audit_score
    Baseline variable measured before treatment: audit score summarizing energy
    inefficiency before treatment.

energy_burden
    Baseline variable measured before treatment: share of household income spent
    on home energy before treatment.

neighborhood
    Baseline variable measured before treatment: neighborhood identifier from the
    city&#39;s administrative records.

application_month
    Baseline variable measured before treatment: month in 2024 when the household
    applied or was referred to the program.

insulation_added
    Post-treatment variable: amount of new insulation installed after treatment
    assignment as part of the retrofit intervention.

contractor_visits
    Post-treatment variable: number of contractor visits after treatment began.

coaching_sessions
    Post-treatment variable: number of energy coaching sessions completed after
    treatment began.

thermostat_setting_2025
    Post-treatment variable: average winter thermostat setting during 2024--25.

inspection_passed
    Post-treatment variable: indicator for whether the household passed the
    post-installation inspection.

followup_survey_response
    Post-treatment variable: indicator for whether the household completed the
    spring 2025 follow-up survey.</code></pre>
<div id="worksheet" class="section level3 hasAnchor" number="12.0.1">
<h3><span class="header-section-number">12.0.1</span> Worksheet<a href="the-retrofit-study.html#worksheet" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>After you read the vocabulary and the <code>retrofit</code> description, switch to the worksheet. The goal is not to produce the one perfect answer. The goal is to practice naming the roles variables can play in an observational causal study and to justify those choices in words.</p>
<p>Consult the reference handout while you work. First answer the questions on your own. Then compare answers with a partner or small group.</p>
<div id="part-a-core-roles" class="section level4 hasAnchor" number="12.0.1.1">
<h4><span class="header-section-number">12.0.1.1</span> Part A: Core roles<a href="the-retrofit-study.html#part-a-core-roles" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li><p>What is the treatment variable?</p></li>
<li><p>What is the outcome variable?</p></li>
</ol>
</div>
<div id="part-b-variable-classification" class="section level4 hasAnchor" number="12.0.1.2">
<h4><span class="header-section-number">12.0.1.2</span> Part B: Variable classification<a href="the-retrofit-study.html#part-b-variable-classification" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Fill in each line with several variable names (unless otherwise instructed) from the <code>retrofit</code> study.</p>
<ul>
<li><p><strong>Strong pre-treatment confounders:</strong></p></li>
<li><p><strong>Other useful pre-treatment covariates:</strong></p></li>
<li><p><strong>One post-treatment mediator (best choice):</strong></p></li>
<li><p><strong>One possible collider (best choice):</strong></p></li>
<li><p><strong>Other bad controls (not including your mediator or collider choice):</strong></p></li>
<li><p><strong>Variables or combinations of variables that raise an overlap concern:</strong></p></li>
<li><p><strong>Variables that raise a consistency concern:</strong></p></li>
</ul>
</div>
<div id="part-c-one-step-back" class="section level4 hasAnchor" number="12.0.1.3">
<h4><span class="header-section-number">12.0.1.3</span> Part C: One step back<a href="the-retrofit-study.html#part-c-one-step-back" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In two or three sentences, explain the difference between these two problems:</p>
<ul>
<li>unmeasured confounding</li>
<li>limited overlap</li>
</ul>
<p>Your answer should make clear why one is something we try to reduce through adjustment, while the other is a limitation of the data themselves.</p>
</div>
</div>
<div id="solutions" class="section level3 hasAnchor" number="12.0.2">
<h3><span class="header-section-number">12.0.2</span> Solutions<a href="the-retrofit-study.html#solutions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This key is not completely unique. Several answers are defensible if the explanation is good. The main goal is that students classify variables according to their causal role and justify the harder cases clearly.</p>
<div id="part-a-core-roles-1" class="section level4 hasAnchor" number="12.0.2.1">
<h4><span class="header-section-number">12.0.2.1</span> Part A: Core roles<a href="the-retrofit-study.html#part-a-core-roles-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li><p><strong>Treatment variable:</strong> <code>retrofit</code></p></li>
<li><p><strong>Outcome variable:</strong> <code>gas_use_2025</code></p></li>
</ol>
</div>
<div id="part-b-variable-classification-1" class="section level4 hasAnchor" number="12.0.2.2">
<h4><span class="header-section-number">12.0.2.2</span> Part B: Variable classification<a href="the-retrofit-study.html#part-b-variable-classification-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p><strong>Strong pre-treatment confounders:</strong><br />
<code>gas_use_2024</code>, <code>sqft</code>, <code>home_age</code>, <code>insulation_baseline</code>, <code>furnace_age</code>, <code>income</code>, <code>arrears_balance</code>, <code>energy_burden</code>, <code>energy_audit_score</code>, <code>neighborhood</code></p></li>
<li><p><strong>Other useful pre-treatment covariates:</strong><br />
<code>electric_use_2024</code>, <code>building_type</code>, <code>owner_occupied</code>, <code>years_in_home</code>, <code>occupants</code>, <code>children</code>, <code>elderly_resident</code>, <code>work_from_home_days</code>, <code>credit_score</code>, <code>application_month</code></p></li>
<li><p><strong>One post-treatment mediator (best choice):</strong><br />
<code>thermostat_setting_2025</code></p></li>
<li><p><strong>One possible collider (best choice):</strong><br />
<code>followup_survey_response</code></p></li>
<li><p><strong>Other bad controls (not including your mediator or collider choice):</strong><br />
<code>coaching_sessions</code>, <code>contractor_visits</code><br />
A reasonable additional answer is <code>inspection_passed</code> if students explain that conditioning on it may induce selection bias or open a noncausal path. I would usually not count <code>insulation_added</code> here if the goal is to keep the roles clean, since it is more useful for the consistency discussion.</p></li>
<li><p><strong>Variables or combinations of variables that raise an overlap concern:</strong><br />
Extreme combinations are the main idea here. Good answers include things like:</p>
<ul>
<li>very high <code>income</code> together with low <code>energy_burden</code></li>
<li>very new homes with strong <code>insulation_baseline</code></li>
<li>very old homes with high <code>gas_use_2024</code>, poor <code>insulation_baseline</code>, and high <code>energy_burden</code></li>
<li>combinations of <code>neighborhood</code>, <code>income</code>, and <code>home_age</code></li>
</ul>
<p>The point is that some treated and untreated households may be scarce in these parts of the covariate space.</p></li>
<li><p><strong>Variables that raise a consistency concern:</strong><br />
<code>insulation_added</code> is the best single answer. Stronger answers may note that <code>insulation_added</code> together with <code>contractor_visits</code> or <code>coaching_sessions</code> suggests that <code>retrofit = 1</code> may bundle together substantially different interventions.</p></li>
</ul>
</div>
<div id="part-c-one-step-back-1" class="section level4 hasAnchor" number="12.0.2.3">
<h4><span class="header-section-number">12.0.2.3</span> Part C: One step back<a href="the-retrofit-study.html#part-c-one-step-back-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A good answer would say something like this:</p>
<blockquote>
<p>Unmeasured confounding means that there may still be variables affecting both treatment assignment and the outcome that are not included in the data, so adjustment may fail to make treated and control units truly comparable. Limited overlap is different: it means that even after choosing the covariates, there may be parts of the covariate space where treated and control units are too different to compare directly. Adjustment is meant to reduce confounding by observed variables, but it cannot repair a lack of overlap, which is a limitation of the data themselves.</p>
</blockquote>
</div>
</div>
<div id="collid3rs" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> Collid3rs<a href="the-retrofit-study.html#collid3rs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A variable can be a <strong>collider</strong> without automatically being a bad control for the causal effect of interest. A collider is simply a variable with two arrows pointing into it on some path. For example, if both <code>home_age</code> and <code>furnace_age</code> affect <code>energy_burden</code>, then <code>energy_burden</code> is a collider relative to those two variables. That fact alone does <strong>not</strong> imply that controlling for <code>energy_burden</code> will bias the estimated effect of <code>retrofit</code> on <code>gas_use_2025</code>.</p>
<p>What matters for causal inference is whether conditioning on the collider opens a <strong>noncausal path between treatment and outcome</strong>. This is the key distinction. A variable may be locally a collider, yet still be harmless for the treatment effect if conditioning on it does not create a new path from <code>retrofit</code> to <code>gas_use_2025</code>. In that case the variable might still cause ordinary modeling problems such as redundancy, multicollinearity, or interpretability issues, but not collider bias in the treatment effect.</p>
<p>A collider is <strong>not</strong> automatically a bad control. It becomes a bad control when conditioning on it opens a spurious path from treatment to outcome.</p>
<p>A good way to separate the ideas is to compare two cases.</p>
<p>In a relatively harmless case, suppose</p>
<p><span class="math display">\[
\text{home\_age} \rightarrow \text{energy\_burden} \leftarrow \text{furnace\_age}.
\]</span></p>
<p>Here <code>energy_burden</code> is indeed a collider of <code>home_age</code> and <code>furnace_age</code>. But unless conditioning on <code>energy_burden</code> opens some new route from <code>retrofit</code> to <code>gas_use_2025</code>, this local collider structure does not itself create causal bias in the treatment effect. The issue is mostly statistical rather than causal.</p>
<p>In a harmful case, suppose a pre-treatment variable such as <code>finalist_pool</code> behaves like this:</p>
<p><span class="math display">\[
\text{retrofit} \leftarrow U_1 \rightarrow \text{finalist\_pool} \leftarrow U_2 \rightarrow \text{gas\_use\_2025},
\]</span></p>
<p>where <code>U_1</code> is an unmeasured factor such as household persistence in the application process, and <code>U_2</code> is an unmeasured factor such as hidden housing damage. If we condition on <code>finalist_pool</code>, then treatment can become associated with hidden housing damage through the opened path. Since hidden housing damage affects later gas use, the estimated treatment effect becomes biased. This is the classic collider problem.</p>
<p>One important intuition is that before conditioning on the collider, <code>U_2</code> is not associated with treatment along that path because the path is blocked. After conditioning on the collider, <code>U_2</code> may become associated with treatment. That is why conditioning on a collider can create a confounding-like problem that was not there before.</p>
</div>
<div id="post-treatment-variables-do-not-always-fit-neatly-into-one-box" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Post-treatment variables do not always fit neatly into one box<a href="the-retrofit-study.html#post-treatment-variables-do-not-always-fit-neatly-into-one-box" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Some bad controls do not fit neatly into the simple mediator-versus-collider classification. A good example is <code>sqft</code> measured <strong>after</strong> treatment. Baseline square footage is a sensible pre-treatment covariate. But if post-treatment <code>sqft</code> reflects later additions to the home, then it is no longer just a baseline housing characteristic. Instead, it may reflect changes that happened after treatment or later household decisions influenced by treatment.</p>
<p>That means post-treatment <code>sqft</code> is usually best described as a <strong>messy post-treatment bad control</strong>. It is not the cleanest flagship example of a mediator, and it is not naturally a collider either. The main problem is simply that it is measured after treatment and may itself reflect downstream changes. A useful sentence is: not every bad control falls neatly into the mediator/collider taxonomy; some are problematic simply because they reflect post-treatment developments.</p>
</div>
<div id="variables-measured-after-treatment-are-not-automatically-bad-controls" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Variables measured after treatment are not automatically bad controls<a href="the-retrofit-study.html#variables-measured-after-treatment-are-not-automatically-bad-controls" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The crucial issue is not just whether a variable is measured after treatment in calendar time. The real question is whether the variable is <strong>downstream of the treatment variable in the causal question of interest</strong>. This is why <code>heating_degree_days</code> is different from post-treatment square footage.</p>
<p>If <code>heating_degree_days</code> measures how cold the winter was, then it is not caused by the retrofit. Even if it is recorded during the same winter as the outcome, it is not downstream of treatment. For that reason, it is not a bad control in the same way a post-treatment mediator would be. It may still or may not be useful, depending on whether households face different weather conditions, but it is not problematic merely because of timing.</p>
<p>So the better rule is this: be very careful with variables measured after treatment, but the real danger comes from variables that are affected by treatment or otherwise lie on the treatment pathway.</p>
</div>
<div id="why-insulation_added-and-thermostat_setting_2025-play-different-roles" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Why <code>insulation_added</code> and <code>thermostat_setting_2025</code> play different roles<a href="the-retrofit-study.html#why-insulation_added-and-thermostat_setting_2025-play-different-roles" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The variable <code>insulation_added</code> is best used in the retrofit example to illustrate a <strong>consistency</strong> concern. If treated households receive very different amounts of insulation or very different bundles of work, then the label <code>retrofit</code> may hide important versions of treatment. In that case the treated potential outcome is less clearly defined, and consistency becomes less plausible unless treatment is described more precisely.</p>
<p>The variable <code>thermostat_setting_2025</code> is a cleaner example of a <strong>mediator</strong>. If the retrofit makes the home easier or cheaper to heat, households may change how warm they keep the house, and that changed thermostat behavior may affect <code>gas_use_2025</code>. Then</p>
<p><span class="math display">\[
\text{retrofit} \rightarrow \text{thermostat\_setting\_2025} \rightarrow \text{gas\_use\_2025}
\]</span></p>
<p>is a plausible part of the causal story. If the goal is to estimate the <strong>total effect</strong> of retrofit on gas use, then controlling for <code>thermostat_setting_2025</code> would be a mistake because it would block part of the treatment effect.</p>
</div>
<div id="why-finalist_pool-or-special_review-can-be-problematic-in-more-than-one-way" class="section level2 hasAnchor" number="12.5">
<h2><span class="header-section-number">12.5</span> Why <code>finalist_pool</code> or <code>special_review</code> can be problematic in more than one way<a href="the-retrofit-study.html#why-finalist_pool-or-special_review-can-be-problematic-in-more-than-one-way" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Variables such as <code>finalist_pool</code> or <code>special_review</code> are not only potential colliders. They can also cause trouble because they often function as <strong>selection variables</strong>. If the analysis is restricted to households in the finalist pool, then the study is no longer describing the original applicant population. Even apart from collider bias, this restriction changes the population being studied.</p>
<p>These variables may also be poor modeling choices because they are often <strong>opaque composite variables</strong>. A status such as <code>finalist_pool</code> may bundle together income, energy burden, application quality, housing problems, and city rules into one summary indicator. Even if it were not creating collider bias, it could still be unhelpful because it hides the underlying sources of variation rather than representing a clean pre-treatment characteristic.</p>
<p>So there are three distinct concerns worth separating:</p>
<ul>
<li><strong>Collider problem:</strong> conditioning on the variable may open a false treatment–outcome path.</li>
<li><strong>Selection problem:</strong> restricting the sample using the variable may change the target population.</li>
<li><strong>Modeling problem:</strong> the variable may bundle together several processes and be hard to interpret causally.</li>
</ul>
</div>
<div id="a-compact-summary" class="section level2 hasAnchor" number="12.6">
<h2><span class="header-section-number">12.6</span> A compact summary<a href="the-retrofit-study.html#a-compact-summary" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The retrofit discussion suggests four practical lessons.</p>
<ol style="list-style-type: decimal">
<li>A variable can be a collider somewhere in the graph without being a bad control for the treatment effect.</li>
<li>A collider becomes a causal problem when conditioning on it opens a noncausal path from treatment to outcome.</li>
<li>Not every bad control is a clean mediator or collider; some post-treatment variables are simply messy because they reflect downstream changes.</li>
<li>Variables such as <code>finalist_pool</code> can be problematic for more than one reason: collider bias, selection bias, and opacity in the adjustment set.</li>
</ol>
<p>These distinctions are worth making slowly, because people often hear “collider” or “post-treatment variable” as if those labels automatically settle the matter. The more careful rule is always the same: ask whether conditioning on the variable helps or harms the treatment–outcome comparison that the causal question actually requires.</p>
</div>
<div id="directed-acyclic-graphs-dags" class="section level2 hasAnchor" number="12.7">
<h2><span class="header-section-number">12.7</span> Directed Acyclic Graphs (DAGs)<a href="the-retrofit-study.html#directed-acyclic-graphs-dags" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>DAGs can be used to help understand the relationship between variables in a causal analysis. In its simplest form, we put an arrow bewteen two variables if there is or could be (we believe) a causal effect between the two variables. As a basic example, if <span class="math inline">\(D\)</span> is the 0/1 treatment variable and <span class="math inline">\(R\)</span> is the response variable, then we would normally put an arrow between <span class="math inline">\(D\)</span> and <span class="math inline">\(R\)</span>. In the context of the <code>lalonde</code> data, we believe that there is or could be a causal effect between <code>treat</code> and <code>re78</code>, so we would write</p>
<p><span class="math display">\[
\text{treat} \to \text{re78}
\]</span></p>
<p>We also believe that <code>re75</code> has a causal effect on <code>re78</code>, so we would write</p>
<p><span class="math display">\[
\text{re75}\to \text{re78}
\]</span></p>
<p>At this point, <code>re75</code> is not yet identified as a confounder, merely a variable that could have a causal effect on <code>re78</code>. However, we also believe that income in 1975 could have a causal effect on whether a candidate participates in the job training program, so we would have:</p>
<p><span class="math display">\[
\text{treat} \leftarrow \text{re75}\rightarrow \text{re78}
\]</span>
This is the classic DAG for a confounder. It is a variable that has a causal effect on both treatment and the response variable. This creates a <strong>backdoor path</strong> so that if we do not adjust for income in 1975, then we could have non-causal correlation between treatment and income in 1978. In other words, <code>re75</code> is a good control because it helps block a noncausal association between <code>treat</code> and <code>re78</code>.</p>
<p>Now let’s look at <strong>mediators</strong>. Suppose we also had the variable <code>jobsearcheffort</code>. This would be a mediator. The reason is that we can imagine that the training could have a causal effect on the job search effort. Job search effort also has a causal effect on income. So we get the DAG</p>
<p><span class="math display">\[
\text{treat} \rightarrow \text{jobsearch} \rightarrow \text{re78}
\]</span></p>
<p>This is the traditional mediator DAG. If we control on <code>jobsearch</code>, then part of the effect of <code>treat</code> will be swallowed up by the <code>jobsearch</code> estimate, when in fact the <code>jobsearch</code> usage was <strong>caused</strong> by the <code>treat</code>. Note that the difference between a confounder and a mediator is whether the variable is caused by the treatment (mediator) or causes the treatment (confounder).</p>
<p>Finally, let’s look at <strong>colliders</strong>. We claim that <code>followupresponse</code> is a collider. The causal story is that the training can affect whether someone completes the follow-up, and organizational skill (which is unmeasured) can also affect whether someone follows up. Organizational skill may also affect later income. This gives the DAG</p>
<p><span class="math display">\[
\text{treat} \rightarrow \text{followupresponse} \leftarrow \text{organization} \rightarrow \text{re78}.
\]</span></p>
<p>By itself, this path isn’t a problem. But if we condition on <code>followupresponse</code> for example, by controlling for it in a regression or by restricting attention to those who respond, we open a noncausal path between treatment and income. Treatment does not affect real income along this path, but conditioning on the collider can still induce a correlation between treatment and income.</p>
<p>Although many colliders which are bad controls are downstream of treatment, that is not always the case. Here is a slightly more complicated collider example in which the collider is <strong>not</strong> downstream of treatment. Suppose <code>retrofit</code> is our treatment and <code>gas\_use\_2025</code> is the outcome. Now imagine two unmeasured variables. The first is household persistence: some households are better at completing paperwork, meeting deadlines, and following through with the application process. That can increase the chance that they ultimately receive the retrofit. The second is hidden housing damage: some homes have serious but partly unrecorded problems, such as leaky ducts or damaged window seals, and those problems can increase later gas use. Suppose also that a household enters the city’s <code>finalist\_pool</code> either because it has a very persistent application or because the home appears complicated enough to merit special attention. Then we have the DAG</p>
<p><span class="math display">\[
\text{retrofit} \leftarrow \text{persistence} \rightarrow \text{finalist\_pool} \leftarrow \text{hidden damage} \rightarrow \text{gas\_use\_2025}.
\]</span></p>
<p>The key point is that <code>finalist_pool</code> is a collider, but it is <strong>not</strong> downstream of treatment. By itself, this path is not a problem. However, if we condition on <code>finalist_pool</code>, for example, by controlling for it in a regression or by restricting the analysis only to households in the finalist pool, we open a noncausal path between treatment and outcome. Intuitively, once we hold finalist status fixed, treatment begins to carry information about hidden housing damage through the induced association created at the collider. That means <code>finalist_pool</code> is a bad control even though it is not caused by treatment.</p>
<p>We contrast that with the following collider which is not a bad control. This is different from the earlier <code>energy_burden</code> example. There, the idea was that <code>energy_burden</code> might be a collider relative to two other baseline housing variables, such as <code>home_age</code> and <code>furnace_age</code>, if both of those affect energy burden. But that fact alone does not make <code>energy_burden</code> a bad control for estimating the effect of <code>retrofit</code> on <code>gas_use_2025</code>. The reason is that conditioning on <code>energy_burden</code> does not necessarily open any important new noncausal path from treatment to outcome. In that case, the main concerns are more ordinary modeling issues, such as redundancy with other baseline controls or difficulty interpreting coefficients, rather than collider bias in the treatment effect. However, if you could come up with a different story about how <code>energy_burden</code> collides with variables to create a noncausal path between treatment and response, then it could be a bad control.</p>
</div>
<div id="matching" class="section level2 hasAnchor" number="12.8">
<h2><span class="header-section-number">12.8</span> Matching<a href="the-retrofit-study.html#matching" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="propensity-scores-and-matching-in-the-lalonde-data" class="section level2 hasAnchor" number="12.9">
<h2><span class="header-section-number">12.9</span> Propensity scores and matching in the Lalonde data<a href="the-retrofit-study.html#propensity-scores-and-matching-in-the-lalonde-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We now use propensity scores and nearest-neighbor matching to estimate the effect of participation in the training program on <code>re78</code>, real earnings in 1978. The goal is to compare treated and untreated individuals who look similar on the observed pre-treatment covariates. This is useful because the training and control groups differ in important baseline ways, so a raw comparison of 1978 earnings is not automatically credible as a causal estimate.</p>
<p>The basic idea is simple. First, we estimate each individual’s <strong>propensity score</strong>, which is the probability of treatment given the observed baseline covariates. Then we use those scores to match treated and control individuals with similar covariate profiles. This does not solve the problem of unmeasured confounding, but it can improve comparability on the observed covariates and reduce reliance on extrapolation.</p>
<div class="sourceCode" id="cb1271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1271-1"><a href="the-retrofit-study.html#cb1271-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1271-2"><a href="the-retrofit-study.html#cb1271-2" tabindex="-1"></a><span class="fu">library</span>(MatchIt)</span>
<span id="cb1271-3"><a href="the-retrofit-study.html#cb1271-3" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1271-4"><a href="the-retrofit-study.html#cb1271-4" tabindex="-1"></a></span>
<span id="cb1271-5"><a href="the-retrofit-study.html#cb1271-5" tabindex="-1"></a>aa <span class="ot">&lt;-</span> MatchIt<span class="sc">::</span>lalonde <span class="sc">|&gt;</span></span>
<span id="cb1271-6"><a href="the-retrofit-study.html#cb1271-6" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb1271-7"><a href="the-retrofit-study.html#cb1271-7" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1271-8"><a href="the-retrofit-study.html#cb1271-8" tabindex="-1"></a>    <span class="at">treat =</span> <span class="fu">factor</span>(treat, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Control&quot;</span>, <span class="st">&quot;Treated&quot;</span>)),</span>
<span id="cb1271-9"><a href="the-retrofit-study.html#cb1271-9" tabindex="-1"></a>    <span class="at">race =</span> <span class="fu">factor</span>(race),</span>
<span id="cb1271-10"><a href="the-retrofit-study.html#cb1271-10" tabindex="-1"></a>    <span class="at">married =</span> <span class="fu">factor</span>(married, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>)),</span>
<span id="cb1271-11"><a href="the-retrofit-study.html#cb1271-11" tabindex="-1"></a>    <span class="at">nodegree =</span> <span class="fu">factor</span>(nodegree, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span>
<span id="cb1271-12"><a href="the-retrofit-study.html#cb1271-12" tabindex="-1"></a>  )</span></code></pre></div>
<p>We begin by estimating propensity scores using a logistic regression for treatment assignment. The covariates here are all measured before treatment and are plausible common causes of treatment and later earnings.</p>
<div class="sourceCode" id="cb1272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1272-1"><a href="the-retrofit-study.html#cb1272-1" tabindex="-1"></a>ps_mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb1272-2"><a href="the-retrofit-study.html#cb1272-2" tabindex="-1"></a>  treat <span class="sc">~</span> age <span class="sc">+</span> educ <span class="sc">+</span> race <span class="sc">+</span> married <span class="sc">+</span> nodegree <span class="sc">+</span> re74 <span class="sc">+</span> re75,</span>
<span id="cb1272-3"><a href="the-retrofit-study.html#cb1272-3" tabindex="-1"></a>  <span class="at">data =</span> aa,</span>
<span id="cb1272-4"><a href="the-retrofit-study.html#cb1272-4" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>()</span>
<span id="cb1272-5"><a href="the-retrofit-study.html#cb1272-5" tabindex="-1"></a>)</span>
<span id="cb1272-6"><a href="the-retrofit-study.html#cb1272-6" tabindex="-1"></a></span>
<span id="cb1272-7"><a href="the-retrofit-study.html#cb1272-7" tabindex="-1"></a>aa_ps <span class="ot">&lt;-</span> ps_mod <span class="sc">|&gt;</span></span>
<span id="cb1272-8"><a href="the-retrofit-study.html#cb1272-8" tabindex="-1"></a>  <span class="fu">augment</span>(<span class="at">data =</span> aa, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb1272-9"><a href="the-retrofit-study.html#cb1272-9" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps =</span> .fitted) <span class="sc">|&gt;</span></span>
<span id="cb1272-10"><a href="the-retrofit-study.html#cb1272-10" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>.fitted)</span></code></pre></div>
<p>We can now inspect the estimated propensity scores. The main issue is <strong>overlap</strong>. Where the treated and control groups overlap, there are plausible treated-versus-control comparisons. Where they do not overlap, the analysis becomes more dependent on extrapolation.</p>
<div class="sourceCode" id="cb1273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1273-1"><a href="the-retrofit-study.html#cb1273-1" tabindex="-1"></a>aa_ps <span class="sc">|&gt;</span></span>
<span id="cb1273-2"><a href="the-retrofit-study.html#cb1273-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ps, <span class="at">fill =</span> treat)) <span class="sc">+</span></span>
<span id="cb1273-3"><a href="the-retrofit-study.html#cb1273-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb1273-4"><a href="the-retrofit-study.html#cb1273-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1273-5"><a href="the-retrofit-study.html#cb1273-5" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Estimated propensity score&quot;</span>,</span>
<span id="cb1273-6"><a href="the-retrofit-study.html#cb1273-6" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>,</span>
<span id="cb1273-7"><a href="the-retrofit-study.html#cb1273-7" tabindex="-1"></a>    <span class="at">fill =</span> <span class="cn">NULL</span></span>
<span id="cb1273-8"><a href="the-retrofit-study.html#cb1273-8" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="13-causal-inference_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>If the treated group tends to have much higher propensity scores than the control group, that tells us treatment assignment is strongly related to the observed baseline covariates. That is exactly why a naive comparison can be misleading. At the same time, if there is at least some substantial overlap, then matching may allow us to compare treated and control individuals who were similarly likely to receive treatment.</p>
<p>Next, we use nearest-neighbor matching based on the estimated propensity scores. The basic algorithm for this is that we pick a treated unit and find the control that has the nearest propensity score. We then remove the treated and control unit from the data and put them into a new data set. We go to the next treated unit and repeat until either there are no more controls or no more treated units.</p>
<div class="sourceCode" id="cb1274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1274-1"><a href="the-retrofit-study.html#cb1274-1" tabindex="-1"></a>m_out <span class="ot">&lt;-</span> <span class="fu">matchit</span>(</span>
<span id="cb1274-2"><a href="the-retrofit-study.html#cb1274-2" tabindex="-1"></a>  treat <span class="sc">~</span> age <span class="sc">+</span> educ <span class="sc">+</span> race <span class="sc">+</span> married <span class="sc">+</span> nodegree <span class="sc">+</span> re74 <span class="sc">+</span> re75,</span>
<span id="cb1274-3"><a href="the-retrofit-study.html#cb1274-3" tabindex="-1"></a>  <span class="at">data =</span> aa,</span>
<span id="cb1274-4"><a href="the-retrofit-study.html#cb1274-4" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">&quot;nearest&quot;</span>,</span>
<span id="cb1274-5"><a href="the-retrofit-study.html#cb1274-5" tabindex="-1"></a>  <span class="at">distance =</span> <span class="st">&quot;glm&quot;</span></span>
<span id="cb1274-6"><a href="the-retrofit-study.html#cb1274-6" tabindex="-1"></a>)</span>
<span id="cb1274-7"><a href="the-retrofit-study.html#cb1274-7" tabindex="-1"></a></span>
<span id="cb1274-8"><a href="the-retrofit-study.html#cb1274-8" tabindex="-1"></a><span class="fu">summary</span>(m_out)</span></code></pre></div>
<pre><code>## 
## Call:
## matchit(formula = treat ~ age + educ + race + married + nodegree + 
##     re74 + re75, data = aa, method = &quot;nearest&quot;, distance = &quot;glm&quot;)
## 
## Summary of Balance for All Data:
##             Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance           0.5774        0.1822          1.7941     0.9211    0.3774
## age               25.8162       28.0303         -0.3094     0.4400    0.0813
## educ              10.3459       10.2354          0.0550     0.4959    0.0347
## raceblack          0.8432        0.2028          1.7615          .    0.6404
## racehispan         0.0595        0.1422         -0.3498          .    0.0827
## racewhite          0.0973        0.6550         -1.8819          .    0.5577
## marriedNo          0.8108        0.4872          0.8263          .    0.3236
## marriedYes         0.1892        0.5128         -0.8263          .    0.3236
## nodegreeNo         0.2919        0.4033         -0.2450          .    0.1114
## nodegreeYes        0.7081        0.5967          0.2450          .    0.1114
## re74            2095.5737     5619.2365         -0.7211     0.5181    0.2248
## re75            1532.0553     2466.4844         -0.2903     0.9563    0.1342
##             eCDF Max
## distance      0.6444
## age           0.1577
## educ          0.1114
## raceblack     0.6404
## racehispan    0.0827
## racewhite     0.5577
## marriedNo     0.3236
## marriedYes    0.3236
## nodegreeNo    0.1114
## nodegreeYes   0.1114
## re74          0.4470
## re75          0.2876
## 
## Summary of Balance for Matched Data:
##             Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance           0.5774        0.3629          0.9739     0.7566    0.1321
## age               25.8162       25.3027          0.0718     0.4568    0.0847
## educ              10.3459       10.6054         -0.1290     0.5721    0.0239
## raceblack          0.8432        0.4703          1.0259          .    0.3730
## racehispan         0.0595        0.2162         -0.6629          .    0.1568
## racewhite          0.0973        0.3135         -0.7296          .    0.2162
## marriedNo          0.8108        0.7892          0.0552          .    0.0216
## marriedYes         0.1892        0.2108         -0.0552          .    0.0216
## nodegreeNo         0.2919        0.3622         -0.1546          .    0.0703
## nodegreeYes        0.7081        0.6378          0.1546          .    0.0703
## re74            2095.5737     2342.1076         -0.0505     1.3289    0.0469
## re75            1532.0553     1614.7451         -0.0257     1.4956    0.0452
##             eCDF Max Std. Pair Dist.
## distance      0.4216          0.9740
## age           0.2541          1.3938
## educ          0.0757          1.2474
## raceblack     0.3730          1.0259
## racehispan    0.1568          1.0743
## racewhite     0.2162          0.8390
## marriedNo     0.0216          0.8281
## marriedYes    0.0216          0.8281
## nodegreeNo    0.0703          1.0106
## nodegreeYes   0.0703          1.0106
## re74          0.2757          0.7965
## re75          0.2054          0.7381
## 
## Sample Sizes:
##           Control Treated
## All           429     185
## Matched       185     185
## Unmatched     244       0
## Discarded       0       0</code></pre>
<p>The matching summary is useful because it reports balance before and after matching. The main question is whether the treated and control groups become more similar on the observed covariates after matching. In a good matching analysis, we care more about improved balance than about how well the treatment model predicts treatment. Here, we can see that several variables are not well balanced even after matching. We focus only on the first three colums and we see that while the mean of <code>age</code> (for example) is well balanced with 25.8 for treatment and 25.3 for control, the racial balance is poor with 84% of the treated population is black while only 47% of the matched control population is black. For each variable, we want the standardized mean difference to be less than, say 0.2, in absolute value to be well-balanced. Here, we see that the race variables are not well matched, nor is distance, which is the raw propensity score.</p>
<p>Despite these warning signs, we now extract the matched data and estimate the treatment effect in the matched sample.</p>
<div class="sourceCode" id="cb1276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1276-1"><a href="the-retrofit-study.html#cb1276-1" tabindex="-1"></a>aa_match <span class="ot">&lt;-</span> <span class="fu">match.data</span>(m_out)</span>
<span id="cb1276-2"><a href="the-retrofit-study.html#cb1276-2" tabindex="-1"></a></span>
<span id="cb1276-3"><a href="the-retrofit-study.html#cb1276-3" tabindex="-1"></a>mod_match <span class="ot">&lt;-</span> <span class="fu">lm</span>(re78 <span class="sc">~</span> treat, <span class="at">data =</span> aa_match, <span class="at">weights =</span> weights) <span class="co">#not recommended</span></span>
<span id="cb1276-4"><a href="the-retrofit-study.html#cb1276-4" tabindex="-1"></a></span>
<span id="cb1276-5"><a href="the-retrofit-study.html#cb1276-5" tabindex="-1"></a><span class="fu">tidy</span>(mod_match, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   term         estimate std.error statistic  p.value conf.low conf.high
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)     5455.      516.     10.6  5.88e-23    4439.     6470.
## 2 treatTreated     894.      730.      1.22 2.21e- 1    -542.     2330.</code></pre>
<p>This matched regression is much simpler than the earlier adjusted regression because the covariate adjustment has largely been moved into the design stage. After matching, we estimate the effect of treatment by comparing outcomes in the matched sample, where treated and control individuals are intended to be more comparable on the observed baseline covariates. Note that the matched data is now paired, which introduces some dependence structure on the data and puts the usage of <code>lm</code> on the paired observations into question. We would want to analyze the matched data set taking into account the paired nature of the data. You already know one way of doing that - paired <span class="math inline">\(t\)</span>-tests. These are not central to modern causal inference, but for the sake of time, we use them here.</p>
<div class="sourceCode" id="cb1278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1278-1"><a href="the-retrofit-study.html#cb1278-1" tabindex="-1"></a>aa_wide <span class="ot">&lt;-</span> aa_match <span class="sc">|&gt;</span> </span>
<span id="cb1278-2"><a href="the-retrofit-study.html#cb1278-2" tabindex="-1"></a>  <span class="fu">select</span>(treat, re78, subclass) <span class="sc">|&gt;</span> </span>
<span id="cb1278-3"><a href="the-retrofit-study.html#cb1278-3" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> treat, <span class="at">values_from =</span> re78) </span>
<span id="cb1278-4"><a href="the-retrofit-study.html#cb1278-4" tabindex="-1"></a>  </span>
<span id="cb1278-5"><a href="the-retrofit-study.html#cb1278-5" tabindex="-1"></a>aa_wide <span class="sc">|&gt;</span> </span>
<span id="cb1278-6"><a href="the-retrofit-study.html#cb1278-6" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mu_treated =</span> <span class="fu">mean</span>(Treated),</span>
<span id="cb1278-7"><a href="the-retrofit-study.html#cb1278-7" tabindex="-1"></a>            <span class="at">mu_control =</span> <span class="fu">mean</span>(Control))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   mu_treated mu_control
##        &lt;dbl&gt;      &lt;dbl&gt;
## 1      6349.      5455.</code></pre>
<div class="sourceCode" id="cb1280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1280-1"><a href="the-retrofit-study.html#cb1280-1" tabindex="-1"></a><span class="fu">t.test</span>(aa_wide<span class="sc">$</span>Treated, aa_wide<span class="sc">$</span>Control, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  aa_wide$Treated and aa_wide$Control
## t = 1.2699, df = 184, p-value = 0.2057
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -495.1223 2283.8573
## sample estimates:
## mean difference 
##        894.3675</code></pre>
<p>We see that we have an estimate of 894 dollars higher salary based on the paired data, with a confidence interval of <span class="math inline">\([-495, 2284]\)</span>. This is not statistically significant (<span class="math inline">\(p = .2057\)</span>).</p>
<p>Note that our matching was not very good - in particular the racial profile of the treated and untreated groups are different. We can try to fix that by forcing an exact match on race, rather than allowing a dubious close enough match to someone of a different race. However, doint so causes other variables to become poorly balanced.</p>
<div class="sourceCode" id="cb1282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1282-1"><a href="the-retrofit-study.html#cb1282-1" tabindex="-1"></a>m_out2 <span class="ot">&lt;-</span> <span class="fu">matchit</span>(treat <span class="sc">~</span> age <span class="sc">+</span> educ <span class="sc">+</span> race <span class="sc">+</span> married <span class="sc">+</span> nodegree <span class="sc">+</span> re74 <span class="sc">+</span> re75, <span class="at">data =</span> aa, <span class="at">method =</span> <span class="st">&quot;nearest&quot;</span>, <span class="at">distance =</span> <span class="st">&quot;glm&quot;</span>, <span class="at">exact =</span> <span class="sc">~</span>race)</span>
<span id="cb1282-2"><a href="the-retrofit-study.html#cb1282-2" tabindex="-1"></a></span>
<span id="cb1282-3"><a href="the-retrofit-study.html#cb1282-3" tabindex="-1"></a><span class="fu">summary</span>(m_out2)</span></code></pre></div>
<pre><code>## 
## Call:
## matchit(formula = treat ~ age + educ + race + married + nodegree + 
##     re74 + re75, data = aa, method = &quot;nearest&quot;, distance = &quot;glm&quot;, 
##     exact = ~race)
## 
## Summary of Balance for All Data:
##             Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance           0.5774        0.1822          1.7941     0.9211    0.3774
## age               25.8162       28.0303         -0.3094     0.4400    0.0813
## educ              10.3459       10.2354          0.0550     0.4959    0.0347
## raceblack          0.8432        0.2028          1.7615          .    0.6404
## racehispan         0.0595        0.1422         -0.3498          .    0.0827
## racewhite          0.0973        0.6550         -1.8819          .    0.5577
## marriedNo          0.8108        0.4872          0.8263          .    0.3236
## marriedYes         0.1892        0.5128         -0.8263          .    0.3236
## nodegreeNo         0.2919        0.4033         -0.2450          .    0.1114
## nodegreeYes        0.7081        0.5967          0.2450          .    0.1114
## re74            2095.5737     5619.2365         -0.7211     0.5181    0.2248
## re75            1532.0553     2466.4844         -0.2903     0.9563    0.1342
##             eCDF Max
## distance      0.6444
## age           0.1577
## educ          0.1114
## raceblack     0.6404
## racehispan    0.0827
## racewhite     0.5577
## marriedNo     0.3236
## marriedYes    0.3236
## nodegreeNo    0.1114
## nodegreeYes   0.1114
## re74          0.4470
## re75          0.2876
## 
## Summary of Balance for Matched Data:
##             Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance           0.5851        0.4899          0.4319     1.2527    0.0902
## age               25.5517       26.4397         -0.1241     0.4439    0.0804
## educ              10.4914       10.3879          0.0515     0.3517    0.0417
## raceblack          0.7500        0.7500          0.0000          .    0.0000
## racehispan         0.0948        0.0948          0.0000          .    0.0000
## racewhite          0.1552        0.1552          0.0000          .    0.0000
## marriedNo          0.9397        0.7241          0.5503          .    0.2155
## marriedYes         0.0603        0.2759         -0.5503          .    0.2155
## nodegreeNo         0.2155        0.3879         -0.3792          .    0.1724
## nodegreeYes        0.7845        0.6121          0.3792          .    0.1724
## re74             887.7150     3090.7096         -0.4508     0.2353    0.1553
## re75            1293.6827     1924.4269         -0.1959     1.0263    0.0941
##             eCDF Max Std. Pair Dist.
## distance      0.4224          0.4338
## age           0.1724          1.4085
## educ          0.1724          1.1405
## raceblack     0.0000          0.0000
## racehispan    0.0000          0.0000
## racewhite     0.0000          0.0000
## marriedNo     0.2155          0.5943
## marriedYes    0.2155          0.5943
## nodegreeNo    0.1724          0.8722
## nodegreeYes   0.1724          0.8722
## re74          0.3879          0.7036
## re75          0.2155          0.7532
## 
## Sample Sizes:
##           Control Treated
## All           429     185
## Matched       116     116
## Unmatched     313      69
## Discarded       0       0</code></pre>
<p>This matching is arguably better (based on the distance score), but still does not pass the rule of thumb that standardized differences should be between -0.2 and 0.2. Realistically, it doesn’t make a lot of sense to keep trying to get a good match here, when we already know of unmeasured confounders (<code>sex</code> for example). As an exercise, compute the estimated effect of treatment among the treated based on this new matching, and see whether it is significant.</p>
</div>
<div id="bernoulli-outcomes" class="section level2 hasAnchor" number="12.10">
<h2><span class="header-section-number">12.10</span> Bernoulli outcomes<a href="the-retrofit-study.html#bernoulli-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we consider Bernoulli outcomes. We will use the data set <code>rhc</code> in the <code>causaldef</code> package. Let’s start by examining it.</p>
<div class="sourceCode" id="cb1284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1284-1"><a href="the-retrofit-study.html#cb1284-1" tabindex="-1"></a>aa <span class="ot">&lt;-</span> causaldef<span class="sc">::</span>rhc <span class="sc">|&gt;</span> </span>
<span id="cb1284-2"><a href="the-retrofit-study.html#cb1284-2" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span></code></pre></div>
<p>The help page doesn’t provide a whole lot of information about the variables. Note that for causal inference, understanding exactly what the variables are measuring (and when) is essential. We cannot proceed without a better understanding of the variables. I downloaded the original paper and asked ChatGPT to provide more information on the variables based on the descriptions in the paper. Here is what it gave:</p>
<div id="rhc" class="section level3 hasAnchor" number="12.10.1">
<h3><span class="header-section-number">12.10.1</span> <code>rhc</code><a href="the-retrofit-study.html#rhc" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A dataset containing 5,735 critically ill adult patients from the SUPPORT study. The treatment variable is <code>swang1</code>, indicating whether the patient received right heart catheterization (RHC, Swan-Ganz catheterization) within the first 24 hours of ICU care. Common outcome variables include <code>dth30</code> (30-day mortality), <code>death</code> (longer-term mortality indicator), and <code>t3d30</code> (survival time up to 30 days).</p>
<div id="format" class="section level4 hasAnchor" number="12.10.1.1">
<h4><span class="header-section-number">12.10.1.1</span> Format<a href="the-retrofit-study.html#format" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A tibble with 5,735 rows and 63 variables.</p>
</div>
<div id="variables" class="section level4 hasAnchor" number="12.10.1.2">
<h4><span class="header-section-number">12.10.1.2</span> Variables<a href="the-retrofit-study.html#variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><code>X</code>: row index carried over from the imported data set.</li>
<li><code>cat1</code>: primary disease category used by the study.</li>
<li><code>cat2</code>: secondary disease category, when applicable.</li>
<li><code>ca</code>: cancer status, typically coded as no cancer, localized cancer, or metastatic cancer.</li>
<li><code>sadmdte</code>: study admission date, stored as an integer date code.</li>
<li><code>dschdte</code>: hospital discharge date, stored as an integer date code.</li>
<li><code>dthdte</code>: date of death, stored as an integer date code.</li>
<li><code>lstctdte</code>: date of last contact, stored as an integer date code.</li>
<li><code>death</code>: indicator for death by the longer-term follow-up window.</li>
<li><code>cardiohx</code>: indicator for prior cardiovascular disease history.</li>
<li><code>chfhx</code>: indicator for prior congestive heart failure history.</li>
<li><code>dementhx</code>: indicator for prior dementia or related neurologic functional impairment.</li>
<li><code>psychhx</code>: indicator for prior psychiatric history.</li>
<li><code>chrpulhx</code>: indicator for prior chronic pulmonary disease history.</li>
<li><code>renalhx</code>: indicator for prior chronic renal disease history.</li>
<li><code>liverhx</code>: indicator for prior liver disease history.</li>
<li><code>gibledhx</code>: indicator for prior gastrointestinal bleeding history.</li>
<li><code>malighx</code>: indicator for prior malignancy history.</li>
<li><code>immunhx</code>: indicator for prior immunocompromised status.</li>
<li><code>transhx</code>: indicator for prior transfer from another hospital or prior major transfer history.</li>
<li><code>amihx</code>: indicator for prior acute myocardial infarction history.</li>
<li><code>age</code>: age in years.</li>
<li><code>sex</code>: sex.</li>
<li><code>edu</code>: years of education.</li>
<li><code>surv2md1</code>: model-based estimate of the probability of surviving 2 months, computed at day 1.</li>
<li><code>das2d3pc</code>: Duke Activity Status Index or a closely related baseline functional-status measure.</li>
<li><code>t3d30</code>: survival time up to 30 days.</li>
<li><code>dth30</code>: indicator for death within 30 days.</li>
<li><code>aps1</code>: APACHE III severity score on day 1.</li>
<li><code>scoma1</code>: Glasgow Coma Score on day 1.</li>
<li><code>meanbp1</code>: mean blood pressure on day 1.</li>
<li><code>wblc1</code>: white blood cell count on day 1.</li>
<li><code>hrt1</code>: heart rate on day 1.</li>
<li><code>resp1</code>: respiratory rate on day 1.</li>
<li><code>temp1</code>: body temperature on day 1.</li>
<li><code>pafi1</code>: ratio of arterial oxygen pressure to fraction of inspired oxygen (PaO2/FiO2) on day 1.</li>
<li><code>alb1</code>: albumin on day 1.</li>
<li><code>hema1</code>: hematocrit on day 1.</li>
<li><code>bili1</code>: bilirubin on day 1.</li>
<li><code>crea1</code>: creatinine on day 1.</li>
<li><code>sod1</code>: sodium on day 1.</li>
<li><code>pot1</code>: potassium on day 1.</li>
<li><code>paco21</code>: arterial PaCO2 on day 1.</li>
<li><code>ph1</code>: arterial pH on day 1.</li>
<li><code>swang1</code>: treatment indicator for receipt of right heart catheterization within the first 24 hours.</li>
<li><code>wtkilo1</code>: weight in kilograms on day 1.</li>
<li><code>dnr1</code>: do-not-resuscitate status on day 1.</li>
<li><code>ninsclas</code>: insurance class.</li>
<li><code>resp</code>: indicator for a respiratory admission diagnosis.</li>
<li><code>card</code>: indicator for a cardiovascular admission diagnosis.</li>
<li><code>neuro</code>: indicator for a neurologic admission diagnosis.</li>
<li><code>gastr</code>: indicator for a gastrointestinal admission diagnosis.</li>
<li><code>renal</code>: indicator for a renal admission diagnosis.</li>
<li><code>meta</code>: indicator for a metabolic admission diagnosis.</li>
<li><code>hema</code>: indicator for a hematologic admission diagnosis.</li>
<li><code>seps</code>: indicator for sepsis.</li>
<li><code>trauma</code>: indicator for trauma.</li>
<li><code>ortho</code>: indicator for an orthopedic diagnosis.</li>
<li><code>adld3p</code>: activities-of-daily-living measure recorded later in the study period, typically around day 3.</li>
<li><code>urin1</code>: urine output on day 1.</li>
<li><code>race</code>: race category.</li>
<li><code>income</code>: income category.</li>
<li><code>ptid</code>: patient identifier.</li>
</ul>
</div>
<div id="details" class="section level4 hasAnchor" number="12.10.1.3">
<h4><span class="header-section-number">12.10.1.3</span> Details<a href="the-retrofit-study.html#details" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For causal inference, it is useful to think of these variables in broad groups. The treatment is <code>swang1</code>. The most common binary outcome is <code>dth30</code>, though <code>death</code> and <code>t3d30</code> are also used. Variables such as <code>age</code>, <code>sex</code>, <code>race</code>, <code>income</code>, <code>cat1</code>, <code>cat2</code>, and the <code>*hx</code> variables are the clearest baseline covariates. The day-1 physiology variables, such as <code>aps1</code>, <code>meanbp1</code>, <code>hrt1</code>, <code>resp1</code>, and the laboratory measures, are clinically important but raise timing questions because treatment also occurs within the first 24 hours. Variables such as <code>dth30</code>, <code>death</code>, <code>t3d30</code>, and <code>adld3p</code> should be treated as outcomes or downstream variables rather than ordinary baseline controls.</p>
</div>
<div id="source" class="section level4 hasAnchor" number="12.10.1.4">
<h4><span class="header-section-number">12.10.1.4</span> Source<a href="the-retrofit-study.html#source" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>SUPPORT (Study to Understand Prognoses and Preferences for Outcomes and Risks of Treatments), as used in observational analyses of right heart catheterization in critically ill ICU patients.</p>
<p>OK, let’s modify the data a little bit to make sure things are working correctly, then we’ll start with propensity scores.</p>
<div class="sourceCode" id="cb1285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1285-1"><a href="the-retrofit-study.html#cb1285-1" tabindex="-1"></a>aa <span class="ot">&lt;-</span> aa <span class="sc">|&gt;</span></span>
<span id="cb1285-2"><a href="the-retrofit-study.html#cb1285-2" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb1285-3"><a href="the-retrofit-study.html#cb1285-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1285-4"><a href="the-retrofit-study.html#cb1285-4" tabindex="-1"></a>    <span class="fu">across</span>(</span>
<span id="cb1285-5"><a href="the-retrofit-study.html#cb1285-5" tabindex="-1"></a>      <span class="fu">c</span>(cardiohx, chfhx, dementhx, psychhx, chrpulhx, renalhx,</span>
<span id="cb1285-6"><a href="the-retrofit-study.html#cb1285-6" tabindex="-1"></a>        liverhx, gibledhx, malighx, immunhx, transhx, amihx),</span>
<span id="cb1285-7"><a href="the-retrofit-study.html#cb1285-7" tabindex="-1"></a>      <span class="sc">~</span> <span class="fu">factor</span>(.x, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>))</span>
<span id="cb1285-8"><a href="the-retrofit-study.html#cb1285-8" tabindex="-1"></a>    )</span>
<span id="cb1285-9"><a href="the-retrofit-study.html#cb1285-9" tabindex="-1"></a>  )</span></code></pre></div>
<p>We now perform a logistic regression and estimate the overlap. We choose controls of the following type:</p>
<ol style="list-style-type: decimal">
<li>General demographics: <code>age</code>, <code>sex</code>, <code>race</code>, <code>edu</code>, <code>income</code>, and <code>ninsclas</code></li>
<li>General health history before treatment: <code>cat1</code>, <code>ca</code>, <code>cardiohx</code>, <code>chfhx</code>, <code>dementhx</code>, <code>psychhx</code>, <code>chrpulhx</code>, <code>renalhx</code>, <code>liverhx</code>, <code>gibledhx</code>, <code>malighx</code>, <code>immunhx</code>, <code>transhx</code>, <code>amihx</code></li>
<li>Day of treatment health indicator that cannot reasonably be influenced by choice of treatment: <code>dnr1</code></li>
</ol>
<p>It would be helpful if we knew which of the day of treatment variables were <strong>before</strong> the treatment and which were <strong>after</strong> the treatment, but absent that information we leave out these potential bad controls. We do not include <code>cat2</code> because it contains many missing values. If we knew that these were missing becuase that meant there <strong>isn’t</strong> a second disease category, then we could replace it with “None” and add it.</p>
<div class="sourceCode" id="cb1286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1286-1"><a href="the-retrofit-study.html#cb1286-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(swang1 <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> race <span class="sc">+</span> edu <span class="sc">+</span> income <span class="sc">+</span> ninsclas <span class="sc">+</span> cat1 <span class="sc">+</span> ca <span class="sc">+</span></span>
<span id="cb1286-2"><a href="the-retrofit-study.html#cb1286-2" tabindex="-1"></a>    cardiohx <span class="sc">+</span> chfhx <span class="sc">+</span> dementhx <span class="sc">+</span> psychhx <span class="sc">+</span> chrpulhx <span class="sc">+</span> renalhx <span class="sc">+</span></span>
<span id="cb1286-3"><a href="the-retrofit-study.html#cb1286-3" tabindex="-1"></a>    liverhx <span class="sc">+</span> gibledhx <span class="sc">+</span> malighx <span class="sc">+</span> immunhx <span class="sc">+</span> transhx <span class="sc">+</span> amihx <span class="sc">+</span> dnr1, <span class="at">data =</span> aa, <span class="at">family =</span> binomial)</span>
<span id="cb1286-4"><a href="the-retrofit-study.html#cb1286-4" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = swang1 ~ age + sex + race + edu + income + ninsclas + 
##     cat1 + ca + cardiohx + chfhx + dementhx + psychhx + chrpulhx + 
##     renalhx + liverhx + gibledhx + malighx + immunhx + transhx + 
##     amihx + dnr1, family = binomial, data = aa)
## 
## Coefficients:
##                              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                 -1.731890   0.471998  -3.669 0.000243 ***
## age                          0.002777   0.002380   1.167 0.243387    
## sexMale                      0.169146   0.059511   2.842 0.004479 ** 
## raceother                    0.040291   0.136778   0.295 0.768320    
## racewhite                    0.058324   0.083989   0.694 0.487418    
## edu                          0.019977   0.010588   1.887 0.059207 .  
## income$11-$25k              -0.051560   0.124638  -0.414 0.679108    
## income$25-$50k               0.060185   0.124556   0.483 0.628955    
## incomeUnder $11k             0.013798   0.123752   0.111 0.911225    
## ninsclasMedicare             0.188941   0.122550   1.542 0.123135    
## ninsclasMedicare &amp; Medicaid  0.209621   0.153686   1.364 0.172582    
## ninsclasNo insurance         0.413173   0.150452   2.746 0.006029 ** 
## ninsclasPrivate              0.378736   0.112462   3.368 0.000758 ***
## ninsclasPrivate &amp; Medicare   0.323499   0.126064   2.566 0.010283 *  
## cat1CHF                      0.103493   0.130686   0.792 0.428406    
## cat1Cirrhosis               -0.942597   0.218943  -4.305 1.67e-05 ***
## cat1Colon Cancer            -0.927949   1.094764  -0.848 0.396647    
## cat1Coma                    -0.665925   0.126532  -5.263 1.42e-07 ***
## cat1COPD                    -1.285997   0.165518  -7.770 7.88e-15 ***
## cat1Lung Cancer             -1.207561   0.502498  -2.403 0.016256 *  
## cat1MOSF w/Malignancy        0.363687   0.136515   2.664 0.007720 ** 
## cat1MOSF w/Sepsis            0.849876   0.073744  11.525  &lt; 2e-16 ***
## caNo                         0.435257   0.398095   1.093 0.274240    
## caYes                       -0.050606   0.143720  -0.352 0.724753    
## cardiohxYes                  0.133110   0.086428   1.540 0.123529    
## chfhxYes                     0.140010   0.093593   1.496 0.134671    
## dementhxYes                 -0.534149   0.107611  -4.964 6.92e-07 ***
## psychhxYes                  -0.504803   0.126850  -3.980 6.91e-05 ***
## chrpulhxYes                 -0.103179   0.090695  -1.138 0.255265    
## renalhxYes                  -0.122353   0.141512  -0.865 0.387252    
## liverhxYes                   0.233900   0.162963   1.435 0.151203    
## gibledhxYes                 -0.220111   0.213684  -1.030 0.302972    
## malighxYes                   0.187896   0.357715   0.525 0.599396    
## immunhxYes                   0.072910   0.066425   1.098 0.272366    
## transhxYes                   0.451930   0.089002   5.078 3.82e-07 ***
## amihxYes                     0.503990   0.155191   3.248 0.001164 ** 
## dnr1Yes                     -0.591689   0.104392  -5.668 1.45e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 7621.4  on 5734  degrees of freedom
## Residual deviance: 6974.7  on 5698  degrees of freedom
## AIC: 7048.7
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb1288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1288-1"><a href="the-retrofit-study.html#cb1288-1" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(mod) <span class="sc">|&gt;</span> </span>
<span id="cb1288-2"><a href="the-retrofit-study.html#cb1288-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">propensity =</span> <span class="fu">plogis</span>(.fitted)) <span class="sc">|&gt;</span> </span>
<span id="cb1288-3"><a href="the-retrofit-study.html#cb1288-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> propensity, <span class="at">fill =</span> swang1)) <span class="sc">+</span> </span>
<span id="cb1288-4"><a href="the-retrofit-study.html#cb1288-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">bins =</span> <span class="dv">20</span>) </span></code></pre></div>
<p><img src="13-causal-inference_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Let’s also count the number of treated and untreated.</p>
<div class="sourceCode" id="cb1289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1289-1"><a href="the-retrofit-study.html#cb1289-1" tabindex="-1"></a><span class="fu">summary</span>(aa<span class="sc">$</span>swang1)</span></code></pre></div>
<pre><code>## No RHC    RHC 
##   3551   2184</code></pre>
<p>Since we considering RHC as the treatment and we will do 1:1 matching of the treated, this looks pretty good. We don’t need there to be many RHC treated people on the lower tail, but we do like to see no RHC people in the upper tail, and we do for the most part.</p>
<div class="sourceCode" id="cb1291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1291-1"><a href="the-retrofit-study.html#cb1291-1" tabindex="-1"></a>match_mod <span class="ot">&lt;-</span> <span class="fu">matchit</span>(swang1 <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> race <span class="sc">+</span> edu <span class="sc">+</span> income <span class="sc">+</span> ninsclas <span class="sc">+</span> cat1 <span class="sc">+</span> ca <span class="sc">+</span></span>
<span id="cb1291-2"><a href="the-retrofit-study.html#cb1291-2" tabindex="-1"></a>    cardiohx <span class="sc">+</span> chfhx <span class="sc">+</span> dementhx <span class="sc">+</span> psychhx <span class="sc">+</span> chrpulhx <span class="sc">+</span> renalhx <span class="sc">+</span></span>
<span id="cb1291-3"><a href="the-retrofit-study.html#cb1291-3" tabindex="-1"></a>    liverhx <span class="sc">+</span> gibledhx <span class="sc">+</span> malighx <span class="sc">+</span> immunhx <span class="sc">+</span> transhx <span class="sc">+</span> amihx <span class="sc">+</span> dnr1, </span>
<span id="cb1291-4"><a href="the-retrofit-study.html#cb1291-4" tabindex="-1"></a>    <span class="at">data =</span> aa,</span>
<span id="cb1291-5"><a href="the-retrofit-study.html#cb1291-5" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;nearest&quot;</span>,</span>
<span id="cb1291-6"><a href="the-retrofit-study.html#cb1291-6" tabindex="-1"></a>    <span class="at">distance =</span> <span class="st">&quot;glm&quot;</span>)</span>
<span id="cb1291-7"><a href="the-retrofit-study.html#cb1291-7" tabindex="-1"></a></span>
<span id="cb1291-8"><a href="the-retrofit-study.html#cb1291-8" tabindex="-1"></a>aa_dat <span class="ot">&lt;-</span> <span class="fu">match.data</span>(match_mod)</span>
<span id="cb1291-9"><a href="the-retrofit-study.html#cb1291-9" tabindex="-1"></a></span>
<span id="cb1291-10"><a href="the-retrofit-study.html#cb1291-10" tabindex="-1"></a><span class="fu">summary</span>(match_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## matchit(formula = swang1 ~ age + sex + race + edu + income + 
##     ninsclas + cat1 + ca + cardiohx + chfhx + dementhx + psychhx + 
##     chrpulhx + renalhx + liverhx + gibledhx + malighx + immunhx + 
##     transhx + amihx + dnr1, data = aa, method = &quot;nearest&quot;, distance = &quot;glm&quot;)
## 
## Summary of Balance for All Data:
##                             Means Treated Means Control Std. Mean Diff.
## distance                           0.4466        0.3404          0.7284
## age                               60.7498       61.7609         -0.0647
## sexFemale                          0.4148        0.4610         -0.0937
## sexMale                            0.5852        0.5390          0.0937
## raceblack                          0.1534        0.1647         -0.0315
## raceother                          0.0650        0.0600          0.0204
## racewhite                          0.7816        0.7753          0.0153
## edu                               11.8564       11.5690          0.0910
## income&gt; $50k                       0.0888        0.0724          0.0578
## income$11-$25k                     0.2070        0.2008          0.0152
## income$25-$50k                     0.1799        0.1408          0.1019
## incomeUnder $11k                   0.5243        0.5860         -0.1237
## ninsclasMedicaid                   0.0884        0.1279         -0.1391
## ninsclasMedicare                   0.2340        0.2667         -0.0773
## ninsclasMedicare &amp; Medicaid        0.0563        0.0707         -0.0623
## ninsclasNo insurance               0.0623        0.0524          0.0409
## ninsclasPrivate                    0.3347        0.2723          0.1322
## ninsclasPrivate &amp; Medicare         0.2244        0.2101          0.0342
## cat1ARF                            0.4162        0.4452         -0.0589
## cat1CHF                            0.0957        0.0696          0.0889
## cat1Cirrhosis                      0.0224        0.0493         -0.1813
## cat1Colon Cancer                   0.0005        0.0017         -0.0576
## cat1Coma                           0.0435        0.0960         -0.2575
## cat1COPD                           0.0266        0.1124         -0.5337
## cat1Lung Cancer                    0.0023        0.0096         -0.1524
## cat1MOSF w/Malignancy              0.0723        0.0679          0.0173
## cat1MOSF w/Sepsis                  0.3205        0.1484          0.3688
## caMetastatic                       0.0563        0.0735         -0.0745
## caNo                               0.7908        0.7468          0.1080
## caYes                              0.1529        0.1797         -0.0743
## cardiohxNo                         0.7958        0.8403         -0.1105
## cardiohxYes                        0.2042        0.1597          0.1105
## chfhxNo                            0.8054        0.8322         -0.0676
## chfhxYes                           0.1946        0.1678          0.0676
## dementhxNo                         0.9309        0.8837          0.1859
## dementhxYes                        0.0691        0.1163         -0.1859
## psychhxNo                          0.9542        0.9195          0.1663
## psychhxYes                         0.0458        0.0805         -0.1663
## chrpulhxNo                         0.8558        0.7820          0.2099
## chrpulhxYes                        0.1442        0.2180         -0.2099
## renalhxNo                          0.9515        0.9580         -0.0306
## renalhxYes                         0.0485        0.0420          0.0306
## liverhxNo                          0.9377        0.9254          0.0511
## liverhxYes                         0.0623        0.0746         -0.0511
## gibledhxNo                         0.9753        0.9631          0.0783
## gibledhxYes                        0.0247        0.0369         -0.0783
## malighxNo                          0.7967        0.7544          0.1050
## malighxYes                         0.2033        0.2456         -0.1050
## immunhxNo                          0.7088        0.7446         -0.0788
## immunhxYes                         0.2912        0.2554          0.0788
## transhxNo                          0.8503        0.9057         -0.1552
## transhxYes                         0.1497        0.0943          0.1552
## amihxNo                            0.9565        0.9704         -0.0683
## amihxYes                           0.0435        0.0296          0.0683
## dnr1No                             0.9290        0.8595          0.2709
## dnr1Yes                            0.0710        0.1405         -0.2709
##                             Var. Ratio eCDF Mean eCDF Max
## distance                        0.9173    0.1917   0.2749
## age                             0.8175    0.0285   0.0703
## sexFemale                            .    0.0462   0.0462
## sexMale                              .    0.0462   0.0462
## raceblack                            .    0.0114   0.0114
## raceother                            .    0.0050   0.0050
## racewhite                            .    0.0063   0.0063
## edu                             1.0147    0.0181   0.0511
## income&gt; $50k                         .    0.0165   0.0165
## income$11-$25k                       .    0.0062   0.0062
## income$25-$50k                       .    0.0391   0.0391
## incomeUnder $11k                     .    0.0618   0.0618
## ninsclasMedicaid                     .    0.0395   0.0395
## ninsclasMedicare                     .    0.0327   0.0327
## ninsclasMedicare &amp; Medicaid          .    0.0144   0.0144
## ninsclasNo insurance                 .    0.0099   0.0099
## ninsclasPrivate                      .    0.0624   0.0624
## ninsclasPrivate &amp; Medicare           .    0.0143   0.0143
## cat1ARF                              .    0.0290   0.0290
## cat1CHF                              .    0.0261   0.0261
## cat1Cirrhosis                        .    0.0268   0.0268
## cat1Colon Cancer                     .    0.0012   0.0012
## cat1Coma                             .    0.0525   0.0525
## cat1COPD                             .    0.0858   0.0858
## cat1Lung Cancer                      .    0.0073   0.0073
## cat1MOSF w/Malignancy                .    0.0045   0.0045
## cat1MOSF w/Sepsis                    .    0.1721   0.1721
## caMetastatic                         .    0.0172   0.0172
## caNo                                 .    0.0439   0.0439
## caYes                                .    0.0267   0.0267
## cardiohxNo                           .    0.0445   0.0445
## cardiohxYes                          .    0.0445   0.0445
## chfhxNo                              .    0.0268   0.0268
## chfhxYes                             .    0.0268   0.0268
## dementhxNo                           .    0.0472   0.0472
## dementhxYes                          .    0.0472   0.0472
## psychhxNo                            .    0.0348   0.0348
## psychhxYes                           .    0.0348   0.0348
## chrpulhxNo                           .    0.0737   0.0737
## chrpulhxYes                          .    0.0737   0.0737
## renalhxNo                            .    0.0066   0.0066
## renalhxYes                           .    0.0066   0.0066
## liverhxNo                            .    0.0124   0.0124
## liverhxYes                           .    0.0124   0.0124
## gibledhxNo                           .    0.0122   0.0122
## gibledhxYes                          .    0.0122   0.0122
## malighxNo                            .    0.0423   0.0423
## malighxYes                           .    0.0423   0.0423
## immunhxNo                            .    0.0358   0.0358
## immunhxYes                           .    0.0358   0.0358
## transhxNo                            .    0.0554   0.0554
## transhxYes                           .    0.0554   0.0554
## amihxNo                              .    0.0139   0.0139
## amihxYes                             .    0.0139   0.0139
## dnr1No                               .    0.0696   0.0696
## dnr1Yes                              .    0.0696   0.0696
## 
## Summary of Balance for Matched Data:
##                             Means Treated Means Control Std. Mean Diff.
## distance                           0.4466        0.4201          0.1817
## age                               60.7498       61.0777         -0.0210
## sexFemale                          0.4148        0.4295         -0.0297
## sexMale                            0.5852        0.5705          0.0297
## raceblack                          0.1534        0.1621         -0.0241
## raceother                          0.0650        0.0600          0.0204
## racewhite                          0.7816        0.7779          0.0089
## edu                               11.8564       11.8039          0.0166
## income&gt; $50k                       0.0888        0.0824          0.0225
## income$11-$25k                     0.2070        0.2111         -0.0102
## income$25-$50k                     0.1799        0.1712          0.0226
## incomeUnder $11k                   0.5243        0.5353         -0.0220
## ninsclasMedicaid                   0.0884        0.0920         -0.0129
## ninsclasMedicare                   0.2340        0.2477         -0.0324
## ninsclasMedicare &amp; Medicaid        0.0563        0.0623         -0.0258
## ninsclasNo insurance               0.0623        0.0595          0.0114
## ninsclasPrivate                    0.3347        0.3164          0.0388
## ninsclasPrivate &amp; Medicare         0.2244        0.2221          0.0055
## cat1ARF                            0.4162        0.4904         -0.1505
## cat1CHF                            0.0957        0.0962         -0.0016
## cat1Cirrhosis                      0.0224        0.0201          0.0155
## cat1Colon Cancer                   0.0005        0.0000          0.0214
## cat1Coma                           0.0435        0.0412          0.0112
## cat1COPD                           0.0266        0.0261          0.0028
## cat1Lung Cancer                    0.0023        0.0018          0.0096
## cat1MOSF w/Malignancy              0.0723        0.0907         -0.0707
## cat1MOSF w/Sepsis                  0.3205        0.2335          0.1864
## caMetastatic                       0.0563        0.0641         -0.0338
## caNo                               0.7908        0.7633          0.0675
## caYes                              0.1529        0.1726         -0.0547
## cardiohxNo                         0.7958        0.7981         -0.0057
## cardiohxYes                        0.2042        0.2019          0.0057
## chfhxNo                            0.8054        0.8059         -0.0012
## chfhxYes                           0.1946        0.1941          0.0012
## dementhxNo                         0.9309        0.9240          0.0271
## dementhxYes                        0.0691        0.0760         -0.0271
## psychhxNo                          0.9542        0.9473          0.0329
## psychhxYes                         0.0458        0.0527         -0.0329
## chrpulhxNo                         0.8558        0.8512          0.0130
## chrpulhxYes                        0.1442        0.1488         -0.0130
## renalhxNo                          0.9515        0.9496          0.0085
## renalhxYes                         0.0485        0.0504         -0.0085
## liverhxNo                          0.9377        0.9437         -0.0246
## liverhxYes                         0.0623        0.0563          0.0246
## gibledhxNo                         0.9753        0.9753          0.0000
## gibledhxYes                        0.0247        0.0247          0.0000
## malighxNo                          0.7967        0.7711          0.0637
## malighxYes                         0.2033        0.2289         -0.0637
## immunhxNo                          0.7088        0.7106         -0.0040
## immunhxYes                         0.2912        0.2894          0.0040
## transhxNo                          0.8503        0.8796         -0.0821
## transhxYes                         0.1497        0.1204          0.0821
## amihxNo                            0.9565        0.9643         -0.0382
## amihxYes                           0.0435        0.0357          0.0382
## dnr1No                             0.9290        0.9226          0.0250
## dnr1Yes                            0.0710        0.0774         -0.0250
##                             Var. Ratio eCDF Mean eCDF Max Std. Pair Dist.
## distance                        1.3098    0.0424   0.1282          0.1818
## age                             0.7847    0.0283   0.0632          1.1822
## sexFemale                            .    0.0147   0.0147          0.9702
## sexMale                              .    0.0147   0.0147          0.9702
## raceblack                            .    0.0087   0.0087          0.7306
## raceother                            .    0.0050   0.0050          0.4661
## racewhite                            .    0.0037   0.0037          0.8090
## edu                             1.0232    0.0058   0.0169          1.0730
## income&gt; $50k                         .    0.0064   0.0064          0.5376
## income$11-$25k                       .    0.0041   0.0041          0.7991
## income$25-$50k                       .    0.0087   0.0087          0.7330
## incomeUnder $11k                     .    0.0110   0.0110          0.9865
## ninsclasMedicaid                     .    0.0037   0.0037          0.5356
## ninsclasMedicare                     .    0.0137   0.0137          0.8371
## ninsclasMedicare &amp; Medicaid          .    0.0060   0.0060          0.4826
## ninsclasNo insurance                 .    0.0027   0.0027          0.4699
## ninsclasPrivate                      .    0.0183   0.0183          0.8869
## ninsclasPrivate &amp; Medicare           .    0.0023   0.0023          0.8331
## cat1ARF                              .    0.0742   0.0742          0.7450
## cat1CHF                              .    0.0005   0.0005          0.5837
## cat1Cirrhosis                        .    0.0023   0.0023          0.2813
## cat1Colon Cancer                     .    0.0005   0.0005          0.0214
## cat1Coma                             .    0.0023   0.0023          0.3165
## cat1COPD                             .    0.0005   0.0005          0.1737
## cat1Lung Cancer                      .    0.0005   0.0005          0.0862
## cat1MOSF w/Malignancy                .    0.0183   0.0183          0.5373
## cat1MOSF w/Sepsis                    .    0.0870   0.0870          0.4710
## caMetastatic                         .    0.0078   0.0078          0.4826
## caNo                                 .    0.0275   0.0275          0.7947
## caYes                                .    0.0197   0.0197          0.7162
## cardiohxNo                           .    0.0023   0.0023          0.7394
## cardiohxYes                          .    0.0023   0.0023          0.7394
## chfhxNo                              .    0.0005   0.0005          0.7529
## chfhxYes                             .    0.0005   0.0005          0.7529
## dementhxNo                           .    0.0069   0.0069          0.4927
## dementhxYes                          .    0.0069   0.0069          0.4927
## psychhxNo                            .    0.0069   0.0069          0.4272
## psychhxYes                           .    0.0069   0.0069          0.4272
## chrpulhxNo                           .    0.0046   0.0046          0.6595
## chrpulhxYes                          .    0.0046   0.0046          0.6595
## renalhxNo                            .    0.0018   0.0018          0.4432
## renalhxYes                           .    0.0018   0.0018          0.4432
## liverhxNo                            .    0.0060   0.0060          0.4718
## liverhxYes                           .    0.0060   0.0060          0.4718
## gibledhxNo                           .    0.0000   0.0000          0.0458
## gibledhxYes                          .    0.0000   0.0000          0.0458
## malighxNo                            .    0.0256   0.0256          0.7919
## malighxYes                           .    0.0256   0.0256          0.7919
## immunhxNo                            .    0.0018   0.0018          0.8929
## immunhxYes                           .    0.0018   0.0018          0.8929
## transhxNo                            .    0.0293   0.0293          0.5775
## transhxYes                           .    0.0293   0.0293          0.5775
## amihxNo                              .    0.0078   0.0078          0.3704
## amihxYes                             .    0.0078   0.0078          0.3704
## dnr1No                               .    0.0064   0.0064          0.4743
## dnr1Yes                              .    0.0064   0.0064          0.4743
## 
## Sample Sizes:
##           Control Treated
## All          3551    2184
## Matched      2184    2184
## Unmatched    1367       0
## Discarded       0       0</code></pre>
<p>We can see that the balance between treated and untreated is better after matching. Now, we want to examine the outcome for the two groups. We consider the <code>dth30</code> as our outcome. We note that we have two balanced, paired groups; one corresponding to RHC and one corresponding to no RHC. To analyze this, we first compute the number of concordant and discordant pairs in the paired sample. Let’s start by computing the percentage of patients that survived in each treatment.</p>
<div class="sourceCode" id="cb1293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1293-1"><a href="the-retrofit-study.html#cb1293-1" tabindex="-1"></a>aa_dat <span class="sc">|&gt;</span> </span>
<span id="cb1293-2"><a href="the-retrofit-study.html#cb1293-2" tabindex="-1"></a>  <span class="fu">group_by</span>(swang1) <span class="sc">|&gt;</span> </span>
<span id="cb1293-3"><a href="the-retrofit-study.html#cb1293-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">surv =</span> <span class="fu">mean</span>(dth30<span class="sc">==</span><span class="st">&quot;No&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   swang1  surv
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 No RHC 0.723
## 2 RHC    0.620</code></pre>
<p>Since we have paired data, the natural test is McNemar’s test, which is really just a special version of a chi-squared test. We start by counting the discordant and concordant pairs. Pairs are discordant if the outcomes are different and they are concordant if the outcomes are the same.</p>
<div class="sourceCode" id="cb1295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1295-1"><a href="the-retrofit-study.html#cb1295-1" tabindex="-1"></a>aa_dat <span class="sc">|&gt;</span> </span>
<span id="cb1295-2"><a href="the-retrofit-study.html#cb1295-2" tabindex="-1"></a>  <span class="fu">select</span>(subclass, swang1, dth30) <span class="sc">|&gt;</span> </span>
<span id="cb1295-3"><a href="the-retrofit-study.html#cb1295-3" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> swang1, <span class="at">values_from =</span> dth30) <span class="sc">|&gt;</span> </span>
<span id="cb1295-4"><a href="the-retrofit-study.html#cb1295-4" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1295-5"><a href="the-retrofit-study.html#cb1295-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">d30_success =</span> <span class="fu">case_when</span>(</span>
<span id="cb1295-6"><a href="the-retrofit-study.html#cb1295-6" tabindex="-1"></a>    rhc <span class="sc">==</span> <span class="st">&quot;No&quot;</span> <span class="sc">&amp;</span> no_rhc <span class="sc">==</span> <span class="st">&quot;No&quot;</span> <span class="sc">~</span> <span class="st">&quot;both&quot;</span>,</span>
<span id="cb1295-7"><a href="the-retrofit-study.html#cb1295-7" tabindex="-1"></a>    rhc <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">&amp;</span> no_rhc <span class="sc">==</span> <span class="st">&quot;No&quot;</span> <span class="sc">~</span> <span class="st">&quot;no_rhc&quot;</span>,</span>
<span id="cb1295-8"><a href="the-retrofit-study.html#cb1295-8" tabindex="-1"></a>    rhc <span class="sc">==</span> <span class="st">&quot;No&quot;</span> <span class="sc">&amp;</span> no_rhc <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;rhc&quot;</span>,</span>
<span id="cb1295-9"><a href="the-retrofit-study.html#cb1295-9" tabindex="-1"></a>    rhc <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">&amp;</span> no_rhc <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;neither&quot;</span>,</span>
<span id="cb1295-10"><a href="the-retrofit-study.html#cb1295-10" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;uhoh&quot;</span></span>
<span id="cb1295-11"><a href="the-retrofit-study.html#cb1295-11" tabindex="-1"></a>  )) <span class="sc">|&gt;</span> </span>
<span id="cb1295-12"><a href="the-retrofit-study.html#cb1295-12" tabindex="-1"></a>  <span class="fu">pull</span>(d30_success) <span class="sc">|&gt;</span> </span>
<span id="cb1295-13"><a href="the-retrofit-study.html#cb1295-13" tabindex="-1"></a>  <span class="fu">table</span>()</span></code></pre></div>
<pre><code>## 
##    both neither  no_rhc     rhc 
##     987     239     591     367</code></pre>
<p>We see that 987 paired patients were both successes, in 591 of the pairs only the no RHC was successful, in 367 of the pairs only RHC was successful, and 239 of the pairs neither was successful. McNemar’s test does a chi-squared test on the items that are <strong>different</strong>, so in other words:</p>
<div class="sourceCode" id="cb1297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1297-1"><a href="the-retrofit-study.html#cb1297-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">c</span>(<span class="dv">591</span>, <span class="dv">367</span>), <span class="at">correct =</span> T)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(591, 367)
## X-squared = 52.376, df = 1, p-value = 4.583e-13</code></pre>
<p>There is also a built in R function for this test, which works for more general things:</p>
<div class="sourceCode" id="cb1299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1299-1"><a href="the-retrofit-study.html#cb1299-1" tabindex="-1"></a><span class="fu">mcnemar.test</span>(<span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">987</span>, <span class="dv">591</span>, <span class="dv">367</span>, <span class="dv">239</span>), <span class="at">nrow =</span> <span class="dv">2</span>))</span></code></pre></div>
<pre><code>## 
##  McNemar&#39;s Chi-squared test with continuity correction
## 
## data:  matrix(c(987, 591, 367, 239), nrow = 2)
## McNemar&#39;s chi-squared = 51.909, df = 1, p-value = 5.813e-13</code></pre>
<p>It is a good idea to provide an effect size and confidence interval where possible, in order to make the difference between RHC and no RHC more clear. For this case, we recommend the <em>paired risk difference</em>, which is computed by</p>
<div class="sourceCode" id="cb1301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1301-1"><a href="the-retrofit-study.html#cb1301-1" tabindex="-1"></a>(<span class="dv">591</span> <span class="sc">-</span> <span class="dv">367</span>)<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">c</span>(<span class="dv">987</span>, <span class="dv">591</span>, <span class="dv">367</span>, <span class="dv">239</span>))</span></code></pre></div>
<pre><code>## [1] 0.1025641</code></pre>
<p>This says that there is about a 10 percentage point better chance of success overall using the no RHC technique than the RHC technique. In order to get a simple CI, we can use <code>t.test</code> on the raw data:</p>
<div class="sourceCode" id="cb1303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1303-1"><a href="the-retrofit-study.html#cb1303-1" tabindex="-1"></a>aa_dat <span class="sc">|&gt;</span> </span>
<span id="cb1303-2"><a href="the-retrofit-study.html#cb1303-2" tabindex="-1"></a>  <span class="fu">select</span>(subclass, swang1, dth30) <span class="sc">|&gt;</span> </span>
<span id="cb1303-3"><a href="the-retrofit-study.html#cb1303-3" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> swang1, <span class="at">values_from =</span> dth30) <span class="sc">|&gt;</span> </span>
<span id="cb1303-4"><a href="the-retrofit-study.html#cb1303-4" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1303-5"><a href="the-retrofit-study.html#cb1303-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rhc =</span> <span class="fu">as.integer</span>(rhc) <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb1303-6"><a href="the-retrofit-study.html#cb1303-6" tabindex="-1"></a>         <span class="at">no_rhc =</span> <span class="fu">as.integer</span>(no_rhc) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1303-7"><a href="the-retrofit-study.html#cb1303-7" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">t.test</span>(rhc, no_rhc, <span class="at">paired =</span> T))</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  rhc and no_rhc
## t = 7.3238, df = 2183, p-value = 3.374e-13
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.07510113 0.13002707
## sample estimates:
## mean difference 
##       0.1025641</code></pre>
<p>We see that we have a 95 percent CI of 0.075 to 0.13. Let’s compare our results to those of the paper. I asked ChatGPT to read the original paper and compare its results to ours, and this is what it said:</p>
<p>Our basic matched analysis and the original paper point in the same direction, but our estimated effect is much larger. In our analysis, after 1:1 nearest-neighbor matching, the estimated 30-day survival rate was 72.3% for the No RHC group and 62.0% for the RHC group. Equivalently, this corresponds to about a 10.3 percentage point higher 30-day mortality rate in the RHC group, with a paired risk difference of 0.103 and a 95% confidence interval from about 0.075 to 0.130. McNemar’s test also gave a very small p-value, suggesting a strong difference between the matched groups.</p>
<p>The paper’s matched analysis was less dramatic. Connors et al. reported 1008 matched pairs, with 30-day survival of 67.2% in the No RHC group and 62.5% in the RHC group. That is still worse for RHC, but the absolute difference is only about 4.7 percentage points rather than the roughly 10 percentage points we found. They reported a matched-pair odds ratio of 1.24 with a 95% confidence interval from 1.03 to 1.49 and a p-value of .03. So the qualitative conclusion is the same—RHC is associated with worse short-term outcomes—but the paper’s estimated effect is smaller and much less statistically overwhelming than the effect from our simplified analysis.</p>
<p>There are several reasons for this difference. First, our propensity score model is much simpler than the one in the paper. We used a conservative set of baseline demographic, diagnostic, comorbidity, and DNR variables, while the paper used a much richer adjustment set that included many additional measures of illness severity and prognosis. In particular, the paper incorporated variables such as APACHE-based severity information, physiologic measurements, laboratory values, functional status, and a model-based estimate of 2-month survival. The point of including those variables was to make the RHC and No RHC patients more comparable in how sick they were at baseline. Since sicker patients were more likely to receive RHC and also more likely to die, leaving out some of those severity variables can make RHC look more harmful than it really is.</p>
<p>Second, the matching strategy in the paper was more selective than the one we used. Our analysis used the default greedy nearest-neighbor matching and kept all 2184 treated patients, pairing each with a control. The paper instead matched patients within disease category and required propensity scores to be very close. As a result, they ended up with only 1008 matched pairs rather than using all treated patients. In other words, the paper was willing to discard many patients in order to create a cleaner comparison. Our analysis uses more data, but it also allows weaker matches, and that can make the estimated treatment effect look larger if the remaining imbalance still favors the No RHC group.</p>
<p>Third, the paper did not rely only on one matched-pair comparison. The authors also fit multivariable outcome models after propensity-score adjustment, looked at survival over multiple time horizons, examined subgroups, and carried out sensitivity analyses asking how large an omitted confounder would have to be to explain away the observed association. These extra analyses do not prove causality, but they do make the overall argument more careful. Our analysis is a good first pass because it shows the basic logic of propensity scores, matching, and paired outcome analysis. The paper’s analysis is more sophisticated because it tries harder to address the possibility that the RHC patients were simply sicker in ways not fully captured by a simpler model.</p>
<p>So the right takeaway is not that one analysis is “correct” and the other is “wrong.” Rather, the simpler analysis is useful for illustrating the method, while the paper shows what a more serious observational analysis looks like. The fact that both analyses point in the same direction is reassuring. The fact that the paper’s estimated effect is smaller is also informative: it suggests that some of the very large difference we saw in the simplified analysis was probably due to the fact that our matching model did not control as fully for severity of illness as the original study did.</p>

</div>
</div>
</div>
</div>










            </section>

          </div>
        </div>
      </div>
<a href="causal-inference.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
